= Command-line reference
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:toc:
:toc: right
:toc-title: COMMAND REFERENCE
:toclevels: 1
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)

The DFINITY command-line execution environment (`+dfx+`) is the primary tool for creating, deploying, and managing the applications you develop for the {platform}.

== dfx

Use the `+dfx+` parent command with flags and subcommands to specify the operations you want to perform with or without optional arguments.

=== Basic usage

[source,bash]
----
dfx [option] [subcommand] [flag]
----

=== Flags

You can use the following optional flags with the `+dfx+` parent command or with any of the `+dfx+` subcommands.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-q+``, `+--quiet+` |Suppresses informational messages.
|`+-v+`, `+--verbose+` |Displays detailed information about operations.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Options

You can use the following options with the `+dfx+` command.

[width="100%",cols="<32%,<68%",options="header",]
|===
|Option |Description

|`+--identity <identity>+` |Specifies the user identity to use when running a command.

|`+--logfile <logfile>+` |Writes log file messages to the specified log file name if you use the `+--log file+` logging option.

|`+--log <logmode>+` |Specifies the logging mode to use.
+
You can set the log mode to one of the following:

- `+stderr+` to log messages to the standard error facility.

- `+tee+` to write messages to both standard output and to a specified file name.

- `+file+` to write messages to a specified file name.

The default logging mode is `+stderr+`.
|===

=== Subcommands

Use the following subcommands to specify the operation you want to perform or to view usage information for a specific command.

[width="100%",cols="<32%,<68%",options="header",]
|===
|Command |Description
|`+bootstrap+` |Starts the bootstrap server you want to use to serve front-end assets for your project.

|`+build+` |Builds canister output from the source code in your project.

|`+cache+` |Manages the `+dfx+` cache on the local computer.

|`+canister+` |Manages canisters deployed on a network replica.

|`+config+` |Sets or changes configuration options for your current project.

|`+help+` |Displays usage information for a specified subcommand.

|`+identity+` |Enables you to create and manage the identities used to communicate with the Internet Computer network.

|`+new+` |Creates a new project.

|`+ping+` |Sends a response request to a specified {IC} network to determine network connectivity.
If the connection is successful, the {IC} replies with its status.

|`+replica+` |Starts a local network replica process.

|`+start+` |Starts the local network replica and a web server for the current project.

|`+stop+` |Stops the local network replica.

|`+upgrade+` |Upgrades the version of `+dfx+` installed on the local computer to the latest version available.
|===

=== Examples

You can use the `+dfx+` parent command to display usage information or version information.
For example, to display information about the version of `+dfx+` you currently have installed, you can run the following command:

[source,bash]
----
dfx --version
----

To view usage information for a specific subcommand, specify the subcommand and the `+--help+` flag.
For example, to see usage information for `+dfx build+`, you can run the following command:

[source,bash]
----
dfx build --help
----

==== Using logging options

You can use the `+--verbose+` and `+--quiet+` flags to increment or decrement the logging level.
If you don't specify any logging level, CRITICAL, ERROR, WARNING, and INFO messages are logged by default.
Specifying one verbose flag (`+-v+`) increases the log level to include DEBUG messages.
Specifying two verbose flags (`+-vv+`)increases the logging level to include both DEBUG and TRACE messages.

Adding a `+--quiet+` flag decreases the logging level.
For example, to remove all messages, you can run a command similar the following:

[source,bash]
----
dfx -qqqq build
----

Keep in mind that using TRACE level logging (`+--vv+`) generates a lot of log messages that can affect performance and should only be used when required for troubleshooting or analysis.

To output log messages to a file named `newlog.txt` and display the messages on your terminal when creating a new project, you can run a command similar to the following:

[source,bash]
----
dfx --log tee --logfile newlog.txt new hello_world
----

==== Specifying a user identity

If you create user identities with the `+dfx identity new+` command, you can then use the `+--identity+` comment-line option to change the user context when running other `+dfx+` commands.

In the most common use case, you use the `+--identity+` option to call specific canister functions to test access controls for specific operations.

For example, you might want to test whether the `+devops+` user identity can call the `+modify_profile+` function for the `+accounts+` canister by running the following command:

....
dfx --identity devops canister call accounts modify_profile '("Kris Smith")'
....

== dfx bootstrap

Use the `+dfx bootstrap+` command to start the bootstrap web server defined in the `+dfx.json+` configuration file or specified using command-line options.

The bootstrap web server you specify is used to serve the front-end static assets for your project.

=== Basic usage

[source,bash]
----
dfx bootstrap [option]
----

=== Flags

You can use the following optional flags with the `+dfx bootstrap+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Options

You can specify the following options for the `+dfx bootstrap+` command.

[width="100%",cols="<36%,<64%",options="header"]
|===
|Option |Description
|`+ip+` <ip_address> |Specifies the IP address that the bootstrap server listens on.
If you don’t specify an IP address, the `address` setting you have configured in the `+dfx.json+` configuration file is used.
By default, the server address is 127.0.0.1.

|--network <network> |Specifies the network to connect to if you want to override the default local network endpoint (`+http://127.0.0.1:8080/api+`).

|--port <port> |Specifies the port number that the bootstrap server listens on.
By default, port number 8081 is used.

|--root <root> |Specifies the directory containing static assets served by the bootstrap server.
By default, the path to static assets is:
`+$HOME/.cache/dfinity/versions/$DFX_VERSION/js-user-library/dist/bootstrap+`.

|--timeout <timeout> | Specifies the maximum amount of time, in seconds, the bootstrap server will wait for upstream requests to complete.
By default, the bootstrap server waits for a maximum of 30 seconds.
|===

=== Examples

You can use the `+dfx bootstrap+` command to start a web server for your application using custom settings, including a specific server address, port number, and static asset location.

For example, to start the bootstrap server using a specific IP address and port number, you would run a command similar to the following:

[source,bash]
----
dfx bootstrap --ip 192.168.47.1 --port 5353
----

The command displays output similar to the following:

[source,bash]
----
binding to: V4(192.168.47.1:5353)
replica(s): \http://127.0.0.1:8080/api
Webserver started...
----

To use the default server address and port number but specify a custom location for static assets and longer timeout period, you might run a command similar to the following:

[source,bash]
----
dfx bootstrap --root $HOME/ic-projects/assets --timeout 60
----

You can use CTRL-C to stop the bootstrap server.

== dfx build

Use the `+dfx build+` command to compile your program into a WebAssembly module that can be deployed on the {IC}.
You can use this command to compile all of the programs that are defined for a project in the project's `+dfx.json+` configuration file or a specific canister.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

The `+dfx build+` command looks for the source code to compile using the information you have configured under the `+canisters+` section in the `+dfx.json+` configuration file.

=== Basic usage

[source,bash]
----
dfx build [flag] [option] [--all | canister_name]
----

=== Flags

You can use the following optional flags with the `+dfx build+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description

|`+--check+` |Builds canisters using a temporary, hard-coded, locally-defined canister identifier for testing that your program compiles without connecting to the {IC} network.

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Options

You can specify the following option for the `+dfx build+` command.

[width="100%",cols="<36%,<64%",options="header"]
|===

|Option |Description

|`+--network <network>+` |Specifies the {IC} network you want to connect to. You can use this option to override the network specified in the `+dfx.json+` configuration file.

|===

=== Arguments

You can specify the following arguments for the `+dfx build+` command.

[width="100%",cols="<36%,<64%",options="header"]
|===

|Argument |Description

|`+--all+` |Builds all of the canisters configured in the project's `+dfx.json+` file.

|`+canister_name+` |Specifies the name of the canister you want to build.
If you are not using the `+--all+` option, you can continue to use `+dfx build+` or provide a canister name as an argument (the canister name must match at least one name that you have configured in the `+canisters+` section of the `+dfx.json+` configuration file for your project.)

|===

=== Examples

You can use the `+dfx build+` command to build one or more WebAssembly modules from the programs specified in the `+dfx.json+` configuration file under the `+canisters+` key.
For example, if your `+dfx.json+` configuration file defines one `+hello_world+` canister and one `+hello_world_assets+` canister, then running `+dfx build+` compiles two WebAssembly modules:

[source,json]
----
include::example$sample-dfx.json[]
----

Note that the file name and path to the programs on your file system must match the information specified in the `+dfx.json+` configuration file.

In this example, the `+hello_world+` canister contains the main program code and the `+hello_world_assets+` canister store front-end code and assets.
If you want to keep the `+hello_world_assets+` canister defined in the `+dfx.json+` file, but only build the back-end program, you could run the following command:

[source,bash]
----
dfx build hello_world
----

Building a specific canister is useful when you have multiple canisters defined in the dfx.json file, but want to test and debug operations for canisters independently.

To test whether a canister compiles without connecting to any {IC} network, you would run the following command:

[source,bash]
----
dfx build --check
----

== dfx cache

Use the `+dfx cache+` command with flags and subcommands to manage the `+dfx+` version cache.

=== Basic usage

[source,bash]
----
dfx cache [subcommand] [flag]
----

=== Flags

You can use the following optional flags with the `+dfx cache+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Subcommands

Use the following subcommands to specify the operation you want to perform or to view usage information for a specific command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description
|`+delete+` |Deletes the specified version of `+dfx+` from the local cache.

|`+help+` |Displays usage information message for a specified subcommand.

|`+install+` |Installs the specified version of `+dfx+` from the local cache.

|`+list+` |Lists the versions of `+dfx+` currently installed and used in current projects.

|`+show+` |Show the path of the cache used by this version of the `+dfx+` executable.
|===

=== Examples

You can use the `+dfx cache+` command to display usage information for its subcommands.
To view usage information for a specific subcommand, specify the subcommand and the `+--help+` flag.
For example, to see usage information for `+dfx cache delete+`, you can run the following command:

[source,bash]
----
dfx cache delete --help
----

== dfx cache delete

Use the `+dfx cache delete+` command to delete a specified version of `+dfx+` from the version cache on the local computer.

=== Basic usage

[source,bash]
----
dfx cache delete [version] [flag]
----

=== Flags

You can use the following optional flags with the `+dfx cache delete+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx cache delete+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description
|`+version+` |Specifies the version of `+dfx+` you to delete from the local cache.
|===

=== Examples

You can use the `+dfx cache delete+` command to permanently delete versions of `+dfx+`  that you no longer want to use.
For example, you can run the following command to delete `+dfx+` version `+0.5.2+`:

[source,bash]
----
dfx cache delete 0.5.2
----

== dfx cache install

Use the `+dfx cache install+` command to install `+dfx+` using the version currently found in the `+dfx+` cache.

=== Basic usage

[source,bash]
----
dfx cache install [flag]
----

=== Flags

You can use the following optional flags with the `+dfx cache install+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Examples

You can use the `+dfx cache install+` command to force the installation of `+dfx+` from the version in the cache.
For example, you can run the following command to install `+dfx+`:
+
[source,bash]
----
dfx cache install
----

== dfx cache list

Use the `+dfx cache list+` command to list the `+dfx+` versions you have currently installed and used in projects.

If you have multiple versions of `+dfx+` installed, the cache list displays an asterisk (*) to indicate the currently active version.

=== Basic usage

[source,bash]
----
dfx cache list [flag]
----

=== Flags

You can use the following optional flags with the `+dfx cache list+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Examples

You can use the `+dfx cache list+` command to list the `+dfx+` versions you have currently installed and used in projects.
For example, you can run the following command to list versions of `+dfx+` found in te cache:

[source,bash]
----
dfx cache list
----

This command displays the list of `+dfx+` versions found similar to the following:

[source,bash]
----
0.5.4 *
0.5.3
0.5.0
----

== dfx cache show

Use the `+dfx cache show+` command to display the full path to the cache used by the `+dfx+` version you are currently using.

=== Basic usage

[source,bash]
----
dfx cache show [flag]
----

=== Flags

You can use the following optional flags with the `+dfx cache show+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Examples

You can use the `+dfx cache show+` command to display the path to the cache used by the `+dfx+` version you are currently using:

[source,bash]
----
dfx cache show
----

This command displays the path to the cache used by the `+dfx+` version you are currently using:

[source,bash]
----
/Users/pubs/.cache/dfinity/versions/0.5.4
----

== dfx canister

Use the `+dfx canister+` command with flags and subcommands to manage canister operations and interaction with the {platform}.

=== Basic usage

[source,bash]
----
dfx canister [subcommand] [flag]
----

=== Flags

You can use the following optional flags with the `+dfx canister+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===

|Flag |Description

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.

|===

=== Options

You can specify the following option for the `+dfx canister+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===

|Option |Description

|`+--network <network>+` |Specifies the {IC} network you want to connect to.
You can use this option to override the network specified in the `+dfx.json+` configuration file.

|===

=== Subcommands

Use the following subcommands to specify the operation you want to perform or to view usage information for a specific command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description
|`+call+` |Calls a specified method on a deployed canister.

|`+create+` |Creates a new "empty" canister by registering a canister identifier on an {IC} network.

|`+help+` |Displays usage information message for a specified subcommand.

|`+id+` |Displays the identifier for a canister.

|`+install+` |Installs compiled code as a canister on the replica.

|`+request-status+` |Request the status of a call to a canister.
|===

=== Examples

In most cases, you use `+dfx canister+` subcommands after you compile a program to manage the canister lifecycle and perform key tasks such as calling program functions.

To view usage information for a specific `+dfx canister+` subcommand, specify the subcommand and the `+--help+` flag.
For example, to see usage information for `+dfx canister call+`, you can run the following command:

[source,bash]
----
dfx canister call --help
----

==== Registering a canister identifier

To register unique canister identifiers for a project, you can run the following command:

[source,bash]
----
dfx canister create --all
----

==== Overriding the default network

If you want to send a `+dfx canister+` subcommand to a specific network provider address and port number without changing the settings in your `+dfx.json+` configuration file, you can explicitly specify the network using the `+--network+` option.

For example, you can specify a remote {IC} network by running a command similar to the following:

[source,bash]
----
dfx canister --network \http://192.168.3.1:5678 call counter get
----

Note that you must specify the network parameter before the canister operation (`+call+`), canister name (`+counter+`), and function (`+get+`).

== dfx canister call

Use the `+dfx canister call+` command to call a specified method on a deployed canister.

=== Basic usage

[source,bash]
----
dfx canister call [option] canister_name method_name [argument] [flag]
----

=== Flags

You can use the following optional flags with the `+dfx canister call+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Flag |Description
|`+–async+` |Enables you to continue without waiting for the result of the call to be returned by polling the replica.

|`+-h+`, `+–help+` |Displays usage information.

|`+–query+` |Enables you to send a query request to a deployed canister.
For best performance and network efficiency, you should use this flag when you explicitly want to use the query method to retrieve information.
For information about the difference between query and update calls, see link:introduction-key-concepts{outfilesuffix}#query-calls[Canisters include both program and state].

|`+–update+` |Enables you to send an update request to a deployed canister.
By default, canister calls use the update method.

|`+-V+`, `+–version+` |Displays version information.
|===

=== Options

You can use the following options with the `+dfx canister call+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Option |Description

|`+--output <output>+` |Specifies the output format to use when displaying a method's return result.
The valid values are `+idl+` and `+raw+`.

|`+--type <type>+` |Specifies the data type for the argument when making the call using an argument.
The valid values are `+idl+` and `+raw+`.
|===

=== Arguments

You can specify the following arguments for the `+dfx canister call+` command.

[width="100%",cols="<31%,<69%",options="header",]
|===
|Argument |Description
|`+canister_name+` |Specifies the name of the canister to call. The canister name is a required argument and should match the name you have configured for a project in the `+canisters+` section of the `+dfx.json+` configuration file.

|`+method_name+` |Specifies the method name to call on the canister.
The canister method is a required argument.

|`+argument+` |Specifies the argument to pass to the method.
Depending on your program logic, the argument can be a required or optional argument.
You can specify a type using the `+--type+` option if you pass an argument to the canister.
The default type is `+idl+`. For information about the interface description types that you can use for arguments, see <<Interface description syntax for arguments>>.
You can use `+raw+` as the argument type if you want to pass raw bytes to a canister.
|===

=== Interface description syntax for arguments [[idl-syntax]]

The `+--type idl+` option specifies a special syntax, which is different from {proglang}, for representing argument values.
The syntax provides a language-agnostic way to communicate with canisters using different languages and tools.
Specifically, the Candid interface description language (IDL) enables you to use the same syntax to specify input argument values and display return values from canister methods, regardless of whether you are using the `+dfx+` command-line interface, JavaScript, {proglang}, or another supported language or tool.

The IDL format accepts multiple argument values separated by commas (`+,+`) and wrapped inside parentheses.
For example, specifying `+(42, true)+` represents two argument values, where the first argument is the number `+42+` and the second argument is a boolean value of `+true+`.

The IDL supports the following value forms:

* Unit value (`+null+`).
* Boolean values (`true`, `false`).
* Integers (..., `-2`, `-1`, `0`, `+1`, `+2`, ...).
* Natural numbers (`0`, `1`, `2`, ...) or (`0x0`, `0x01`, ..., `0xfff`, ...)
* Text values `"string of unicode characters"`.
* Optional values (`none`, `opt 42`, `opt opt "optional text"`, ...).
* Vector of values (`vec { 1; 2; 3; }`, ...).
* Record/struct with named labels and values (`record { label = opt 42; 3 = "numbered label" }`, ...).
* Variant/enum with a single named label and value (`variant { ok = "ok result value" }`, `variant { Err = null }`, ...).
* Values with type annotations (`42 : nat`, `42 : int`, ...).

The IDL interprets numbers with plus signs—for example. `+42`—as integers and numbers without plus signs—for example, `42`—as natural numbers.
However, since `Nat` is a subtype of `Int` in {proglang}, you can always write `42` without the plus sign for functions that expect integers.

For compound types, such as `+record+` and `+variant+`, labels can be either natural numbers or strings.
However, the string label is only present for better readability.
Behind the scenes, the string label is converted into a natural number using a fixed hash function.
If the canister method returns a `+record+` or `+variant+` type, the field labels will always be natural numbers.

For a more detailed discussion of the interface description language, see the link:../candid-spec:IDL{outfilesuffix}[Candid specification] and link:https://docs.rs/candid/[Candid Rust crate] documentation.

=== Examples

You can use the `+dfx canister call+` command to invoke specific methods—with or without arguments—after you have deployed the canister on the network using the `+dfx canister install+` command.
For example, to invoke the `+get+` method for a canister with a `+canister_name+` of `+counter+`, you can run the following command:

[source,bash]
----
dfx canister call counter get --async
----

In this example, the command includes the `+--async+` option to indicate that you want to make a separate `+request-status+` call rather than waiting to poll the replica for the result.
The `+--async+` option is useful when processing an operation might take some time to complete.
The option enables you to continue performing other operations then check for the result using a separate `+dfx canister request-status+` command.
The returned result will be displayed as the IDL textual format.

==== Using the IDL syntax

You can explicitly specify that you are passing arguments using the IDL syntax by running commands similar to the following for a Text data type:

[source,bash]
----
dfx canister call hello greet --type idl '("Lisa")'
("Hello, Lisa!")

dfx canister call hello greet '("Lisa")' --type idl
("Hello, Lisa!")
----

You can also implicitly use the IDL by running a command similar to the following:

[source,bash]
----
dfx canister call hello greet '("Lisa")'
("Hello, Lisa!")
----

To specify multiple arguments using the IDL syntax, use commas between the arguments.
For example:

[source,bash]
----
dfx canister call contacts insert '("Amy Lu","01 916-335-2042")'

dfx canister call hotel guestroom '("Deluxe Suite",42,true)'
----

You can pass raw data in bytes by running a command similar to the following:

[source,bash]
----
dfx canister call hello greet --type raw '4449444c00017103e29883'
----

This example uses the raw data type to pass a hexadecimal to the `+greet+` function of the `+hello+` canister.

== dfx canister create

Use the `+dfx canister create+` command to register one or more canister identifiers without compiled code on the {IC} network.
You must be connected to an {IC} network running locally or on a sub-network that you can access to run this command.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

The first time you run the `+dfx canister create+` command to register an identifier, your public/private key pair credentials are used to create a `+default+` user identity.
The credentials for the `+default+` user are migrated from `+$HOME/.dfinity/identity/creds.pem+` to `+$HOME/.config/dfx/identity/default/identity.pem+`.

=== Basic usage

[source,bash]
----
dfx canister create [flag] [--all | canister_name]
----

=== Flags

You can use the following optional flags with the `+dfx canister create+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Flag |Description

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can use the following argument with the `+dfx canister create+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Argument |Description
|`+--all+` |Enables you to create multiple canister identifiers at once if you have a project `+dfx.json+` file that defines multiple canisters.
Note that you must specify `+--all+` or an individual canister name.
|`+canister_name+` |Specifies the name of the canister for which you want to register an identifier.
If you are not using the `+--all+` option, the canister name is a required argument and must match at least one name that you have configured in the `+canisters+` section of the `+dfx.json+` configuration file for your project.
|===

=== Examples

You can use the `+dfx canister create+` command to register canister identifiers without first compiling any code.
For example, if you want to create the canister identifier for the project `+my_counter+` before writing the program, you can run the following command:

[source,bash]
----
dfx canister create my_counter
----

== dfx canister delete

Use the `+dfx canister delete+` command to delete a stopped canister from the local Internet Computer network or on a remote Internet Computer network.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

=== Basic usage

[source,bash]
----
dfx canister delete [flag] [--all | canister_name]
----

=== Flags

You can use the following optional flags with the `+dfx canister delete+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Flag |Description

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can use the following arguments with the `+dfx canister delete+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Argument |Description

|`+--all+` |Deletes all of the canisters configured in the `+dfx.json+` file. Note that you must specify `+--all+` or an individual canister name.

|`+canister_name+` |Specifies the name of the canister you want to delete.
Note that you must specify either a canister name or the `+--all+` option.
|===

=== Examples

You can use the `+dfx canister delete+` command to delete a specific canister or all canisters.

To delete the `+hello_world+` canister, you can run the following command:

[source,bash]
----
dfx canister delete hello_world
----

To delete all of the canisters you have deployed on the `+tungsten+` Internet Computer network, you can run the following command:

[source,bash]
----
dfx canister --network=tungsten delete --all
----

== dfx canister id

Use the `+dfx canister id+` command to output the canister identifier for a specific canister name.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

=== Basic usage

[source,bash]
----
dfx canister id [flag] canister_name
----

=== Flags

You can use the following optional flags with the `+dfx canister id+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Flag |Description

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can use the following argument with the `+dfx canister id+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Argument |Description

|`+canister_name+` |Specifies the name of the canister for which you want to display an identifier.

|===

=== Examples

You can use the `+dfx canister id+` command to display the canister identifier for a specific canister name.

To display the canister identifier for the `+hello_world+` canister, you can run the following command:

[source,bash]
----
dfx canister id hello_world
----

The command displays output similar to the following:

[source,bash]
----
75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
----

== dfx canister install

Use the `+dfx canister install+` command to install compiled code as a canister on the {IC} network running locally or on a sub-network that you can access.

=== Basic usage

[source,bash]
----
dfx canister install [flag] [option] [--all | canister_name]
----

=== Flags

You can use the following optional flags with the `+dfx canister install+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Flag |Description

|`+--async+` |Enables you to continue without waiting for the result of the installation to be returned by polling the replica.

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Options

You can use the following options with the `+dfx canister install+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Option |Description
|`+-c+`, `+--compute-allocation <compute-allocation>+` |Defines a compute allocation—essentially the equivalent of setting a CPU allocation—for  canister execution.
You can set this value as a percentage in the range of 0 to 100.

|`+--memory-allocation <memory-allocation>+` |Specifies how much memory the canister is allowed to use in total.
You can set this value in the range of 0 to 256 TB.
The default is 8GB.

|`+-m+`, `+--mode <mode>+` |Specifies whether you want to `+install+`, `+reinstall+`, or `+upgrade+` canisters.
For more information about installation modes and canister management, see link:working-with-canisters{outfilesuffix}[Managing canisters].

|===

=== Arguments

You can use the following arguments with the `+dfx canister install+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Argument |Description

|`+--all+` |Enables you to install multiple canisters at once if you have a project `dfx.json` file that includes multiple canisters.
Note that you must specify `--all` or an individual canister name.

|`+canister_name+` |Specifies the name of the canister to deploy.
If you are not using the `+--all+` option, the canister name is a required argument and should match the name you have configured for a project in the `+canisters+` section of the `+dfx.json+` configuration file.
|===

=== Examples

You can use the `+dfx canister install+` command to deploy WebAssembly you have compiled using the `+dfx build+` command as a canister on the network.
The most common use case is to install all of the canisters by running the following command:

[source,bash]
----
dfx canister install --all
----

==== Installing a specific canister

You can also use the `+dfx canister install+` command to deploy a specific canister instead of all of the canisters in your project.
For example, if you have a project with a `+hello_world+` canister and a `+hello_world_assets+` canister but only want to deploy the `+hello_world+` canister, you can deploy just that the canister by running the following command:

[source,bash]
----
dfx canister install hello_world
----

==== Sending an asynchronous request

If you want to submit a request to install the canister and return a request identifier to check on the status of your request later instead of waiting for the command to complete, you can run a command similar to the following:
[source,bash]
----
dfx canister install hello_world --async
----

This command submits a request to install the canister and returns a request identifier similar to the following:
[source,bash]
----
0x58d08e785445dcab4ff090463b9e8b12565a67bf436251d13e308b32b5058608
----

You can then use the request identifier to check the status of the request at a later time, much like a tracking number if you were shipping a package.

==== Overriding the default network provider

If you want to deploy a canister on a specific {IC} network without changing the settings in your `+dfx.json+` configuration file, you can explicitly specify the network you want to connect to by using the `+--network` option.

For example, you can specify a remote network by running a command similar to the following:

[source,bash]
----
dfx canister --network \http://192.168.3.1:5678 install --all
----

Note that you must specify the network parameter before the canister operation (`+install+`) and before the canister name or `+--all+` flag.

==== Allocating message processing

The `+--compute-allocation+` options allows you to allocate computing resources as a percentage in the range of 0 to 100 to indicate how often your canister should be scheduled for execution.

For example, assume you run the following command:

[source,bash]
----
dfx canister install --all --compute-allocation 50
----

With this setting, all of the canisters in the current projects are assigned a 50% allocation. When canisters in the project receive input messages to process, the messages are scheduled for execution.
Over 100 execution cycles, each canister's messages will be scheduled for processing at least 50 times.

The default value for this option is 0—indicating that no specific allocation or scheduling is in effect.
If all of your canisters use the default setting, processing occurs in a round-robin fashion.

== dfx canister request-status

Use the `+dfx canister request-status+` to request the status of a specified call to a canister.
This command requires you to specify the request identifier you received after invoking a method on the canister.
The request identifier is an hexadecimal string starting with `+0x+`.

=== Basic usage

[source,bash,subs="quotes"]
----
dfx canister request-status _request_id_
----

=== Flags

You can use the following optional flags with the `+dfx canister request-status+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx canister request-status+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description
|`+request_id+` |Specifies the hexadecimal string returned in response to a `+dfx canister call+` or `+dfx canister install+` command.
This identifier is an hexadecimal string starting with 0x.
|===

=== Examples

You can use the `+dfx canister request-status+` command to check on the status of a canister state change or to verify that a call was not rejected by running a command similar to the following:

[source,bash]
----
dfx canister request-status 0x58d08e785445dcab4ff090463b9e8b12565a67bf436251d13e308b32b5058608
----

This command displays an error message if the request identifier is invalid or refused by the canister.

== dfx canister start

Use the `+dfx canister start+` command to restart a stopped canister on the local Internet Computer network or on a remote Internet Computer network.

In most cases, you run this command after you have stopped a canister to properly terminate any pending requests as a prerequisite to upgrading the canister.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

=== Basic usage

[source,bash]
----
dfx canister start [flag] [--all | canister_name]
----

=== Flags

You can use the following optional flags with the `+dfx canister start+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Flag |Description

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can use the following arguments with the `+dfx canister start+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Argument |Description

|`+--all+` |Starts all of the canisters configured in the `+dfx.json+` file. Note that you must specify `+--all+` or an individual canister name.

|`+canister_name+` |Specifies the name of the canister you want to start.
Note that you must specify either a canister name or the `+--all+` option.
|===

=== Examples

You can use the `+dfx canister start+` command to start a specific canister or all canisters.

To start the `+hello_world+` canister, you can run the following command:

[source,bash]
----
dfx canister start hello_world
----

To start all of the canisters you have deployed on the `+tungsten+` Internet Computer network, you can run the following command:

[source,bash]
----
dfx canister --network=tungsten start --all
----

== dfx canister status

Use the `+dfx canister status+` command to check whether a canister is currently running, in the process of stopping, or currently stopped on the local Internet Computer network or on a remote Internet Computer network.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

=== Basic usage

[source,bash]
----
dfx canister status [flag] [--all | canister_name]
----

=== Flags

You can use the following optional flags with the `+dfx canister status+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Flag |Description

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can use the following arguments with the `+dfx canister status+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Argument |Description

|`+--all+` |Returns status information for all of the canisters configured in the `+dfx.json+` file. Note that you must specify `+--all+` or an individual canister name.

|`+canister_name+` |Specifies the name of the canister you want to return information for.
Note that you must specify either a canister name or the `+--all+` option.
|===

=== Examples

You can use the `+dfx canister status+` command to check the status of a specific canister or all canisters.

To check the status of the `+hello_world+` canister, you can run the following command:

[source,bash]
----
dfx canister status hello_world
----

To check the status for all of the canisters you have deployed on the `+tungsten+` Internet Computer network, you can run the following command:

[source,bash]
----
dfx canister --network=tungsten status --all
----

== dfx canister stop

Use the `+dfx canister stop+` command to stop a canister that is currently running on the local Internet Computer network or on a remote Internet Computer network.

In most cases, you run this command to properly terminate any pending requests as a prerequisite to upgrading the canister.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

=== Basic usage

[source,bash]
----
dfx canister stop [flag] [--all | canister_name]
----

=== Flags

You can use the following optional flags with the `+dfx canister stop+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Flag |Description

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can use the following arguments with the `+dfx canister stop+` command.

[width="100%",cols="<31%,<69%",options="header"]
|===
|Argument |Description

|`+--all+` |Stops all of the canisters configured in the `+dfx.json+` file. Note that you must specify `+--all+` or an individual canister name.

|`+canister_name+` |Specifies the name of the canister you want to stop.
Note that you must specify either a canister name or the `+--all+` option.
|===

=== Examples

You can use the `+dfx canister stop+` command to start a specific canister or all canisters.

To stop the `+hello_world+` canister, you can run the following command:

[source,bash]
----
dfx canister stop hello_world
----

To stop all of the canisters you have deployed on the `+tungsten+` Internet Computer network, you can run the following command:

[source,bash]
----
dfx canister --network=tungsten stop --all
----

== dfx config

Use the `+dfx config+` command to view or configure settings in the configuration file for a current project.
Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

=== Basic usage

[source,bash]
----
dfx config [config_path] [value] [flag]
----

=== Flags

You can use the following optional flags with the `+dfx config+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Options

You can use the following option with the `+dfx config+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Option |Description
|`+--format+` |Specifies the format of the configuration file output.
By default, the file is displayed using JSON format.
The valid values are `+json+` and `+text+`.
|===

=== Arguments

You can specify the following arguments for the `+dfx config+` command.

[width="100%",cols="<34%,<66%",options="header"]
|===
|Argument |Description
|`+config_path+` |Specifies the name of the configuration option that you want to set or read.
You must specify the configuration file option using its period-delineated path to set or read the specific option you want to change or view.
If you don't specify the path to a specific configuration option, the command displays the full configuration file.

|`+value+` |Specifies the new value for the option you are changing.
If you don’t specify a value, the command returns the current value for the option from the configuration file.
|===

=== Examples

You can use the `+dfx config+` command to change configuration settings such as the location of the default output directory or the name of your main program file.

For example, to change the default build output directory from `+canisters+` to `+staging+`, you can run the following command:

[source,bash]
----
dfx config defaults.build.output "staging/"
----

To view the current value for a configuration setting, you can specify the path to the setting in the configuration file without specifying a value.
For example:

[source,bash]
----
dfx config defaults.build.output
----

The command returns the current value for the configuration option:

[source,bash]
----
"staging/"
----

Similarly, you can change the name of the main source file or the port number for the local network replica by running commands similar to the following:

[source,bash]
----
dfx config canisters.hello.main "src/hello_world/hello-main.mo"
dfx config networks.local.bind 127.0.0.1:5050
----

You can also verify your configuration changes by viewing the `+dfx.json+` configuration file after running the `+dfx config+` command.

== dfx help

Use this command to view usage information for the `+dfx+` parent command or for any specified subcommand.

=== Basic usage

[source,bash]
----
dfx help [subcommand]
----

=== Arguments

You can specify any `+dfx+` subcommand as an argument to view usage information for that subcommand using the `+dfx help+` command.

[width="100%",cols="<34%,<66%",options="header"]
|===
|Argument |Description
|`+subcommand+` |Specifies the subcommand usage information you want to display.
|===

### Examples

To display the usage information for `+dfx+`, run the following command:

[source,bash]
----
dfx help
----

To display the usage information for `+dfx bew+`, run the following command:

[source,bash]
----
dfx help new
----

== dfx identity

Use the `+dfx identity+` command to manage the identities used to communicate with the Internet Computer network. 
Creating multiple user identities enables you to test user-based access controls.

=== Basic usage

[source,bash]
----
dfx identity [subcommand] [flag]
----

=== Flag

You can use the following optional flags with the `+dfx identity+` command:

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Subcommands

Use the following subcommands to specify the operation you want to perform or to view usage information for a specific command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description

| `+help+` |Displays this usage message or the help of the given subcommand(s).

|`+list+` |Lists existing identities.

|`+new <identity_name>+` |Creates a new identity.

|`+remove <identity_name>+` |Removes an existing identity.

|`+rename <from_name> <to_name>+` |Renames an existing identity.

|`+use <identity_name>+` |Specifies the identity to use.

|`+whoami+` |Displays the name of the current identity user context.
|===

=== Examples

The first time you run the `+dfx canister create+` command to register an identifier, your public/private key pair credentials are used to create a `+default+` user identity.
The credentials for the `+default+` user are migrated from `+$HOME/.dfinity/identity/creds.pem+` to `+$HOME/.config/dfx/identity/default/identity.pem+`.

You can then use `+dfx identity new+` to create new user identities and store credentials for those identities in `+$HOME/.config/dfx/identity/<identity_name>/identity.pem+` files.
For example, you can create an identity named `+ic_admin+` by running the following command:

....
dfx identity new ic_admin
....

This command adds a private key for the `+ic_admin+` user identity in the `+~/.config/dfx/identity/ic_admin/identity.pem+` file.

You can rename the default user or any identity you have previously created using the `+dfx identity rename+` command.
For example, if you want to rename a `+test_admin+` identity that you previously created, you would specify the current identity name you want to change **from** and the new name you want to change **to** by running a command similar to the following:

....
dfx identity rename test_admin ops
....

If you want to run multiple commands with the same user identity context, you can run the following command:

....
dfx identity use ops
....

== dfx new

Use the `+dfx new+` command to create a new project for the {platform}.
This command creates a default project structure with template files that you can modify to suit your application.
You must specify the name of the project to you want to create.

You can use the `+--dry-run+` option to preview the directories and files to be created without adding them to the file system.

=== Basic usage

[source,bash]
----
dfx new _project_name_ [flag]
----

=== Flag

You can use the following optional flags with the `+dfx new+` command:

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+--dry-run+` |Generates a preview the directories and files to be created for a new project without adding them to the file system.

| `+--frontend+` |Installs the template frontend code for the default project canister.
The default value for the flag is `+true+` if `+node.js+` is currently installed on your local computer.
If `+node.js+` is not currently installed, you can set this flag to `+true+` to attempt to install `+node.js+` and the template file when creating the project or you can set the flag to `+false+` to skip the installation of template frontend code entirely.

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx new+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description
|`+project_name+` |Specifies the name of the project to create.
This argument is required. |
|===

=== Examples

You can use `+dfx new+` to create a new project named `+my_social_network+` by running the following command:

[source,bash]
----
dfx new my_social_network
----

The command creates a new project, including a default project directory structure under the new project name and a Git repository for your project.

If you want to preview the directories and files to be created without adding them to the file system, you can run the following command:

[source,bash]
----
dfx new my_social_network --dry-run
----

== dfx ping

Use the `+dfx ping+` command to check connectivity between a local computer and an {IC} network provider.
This command enables you to verify that you can connect to a specific {IC} network and that the remote network services are running.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

=== Basic usage

[source,bash]
----
dfx ping [provider] [flag]
----

=== Flags

You can use the following optional flags with the `+dfx ping+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx ping+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description

|provider |Specifies the network provider URL that you want to use.
|===

=== Examples

You can use the `+dfx ping+` command to check whether the {IC} is currently available at a specific network address by running a command similar to the following:

[source,bash]
----
dfx ping https://testgw.dfinity.network
----

If the {IC} is running on the specified network provider address, the command returns output similar to the following:

....
{
  "ic_api_version": "0.8"
}
....

== dfx replica

Use the `+dfx replica+` command to start a {IC} replica process (without a web server) locally.
This command enables you to deploy canisters locally to simulate network deployment and to test your programs during development.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

=== Basic usage

[source,bash]
----
dfx replica [option] [flag]
----

=== Flags

You can use the following optional flags with the `+dfx replica+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Options

You can use the following option with the `+dfx replica+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Option |Description
|`+--port port+` |Specifies the port the local replica should listen to.
|===

////
|`+--message-gas-limit maximum-gas-limit+` |Specifies the maximum resources that a single message can consume. Computational resources such as CPU, memory, and storage are measured in tokens that are converted in "gas" available to be consumed by applications.
|`+--round-gas-limit round-gas-limit+` |Specifies the maximum resources that a single round of messages can consume in the "gas" available to be consumed by applications.
////

=== Examples

You can start the {IC} replica by running the following command:

[source,bash]
----
dfx replica
----
////
If you want to set an upper limit on the resources a single message can consume, you might run a command similar to the following:

[source,bash]
----
dfx replica --maximum-gas-limit 1000
----
////

== dfx start

Use the `+dfx start+` command to start a local {IC} replica process and web server processes for the current project.
This command enables you to deploy canisters to the local {IC} network to test your programs during development.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

=== Basic usage

[source,bash]
----
dfx start [option] [flag]
----

=== Flags

You can use the following optional flags with the `+dfx start+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+--background+` |Starts the {IC} replica and web server processes in the background and waits for a reply before returning to the shell.

|`+--clean+` |Starts the {IC} replica and web server processes in a clean state by removing checkpoints from your project cache.
You can use this flag to set your project cache to a new state when troubleshooting or debugging.

|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Options

You can use the following option with the `+dfx start+` command.

[width="100%",cols="<32%,<68%",options="header",]
|===
|Option |Description
|`+--host host+` |Specifies the host name and port number to bind the frontend to.
|===

=== Examples

You can start the {IC} replica and web server processes in the current shell by running the following command:

[source,bash]
----
dfx start
----

If you start the {IC} in the current shell, you need to open a new terminal shell to run additional commands.
Alternatively, you can start the {IC} in the background by running the following command:

[source,bash]
----
dfx start --background
----

If you run the {IC} in the background, however, be sure to stop the network before uninstalling or reinstalling the `+dfx+` execution environment by running the following command:

[source,bash]
----
dfx stop
----

You can view the current process identifier (`+pid+`) for the {IC} process started by `+dfx+`  by running the following command:
[source,bash]
----
more .dfx/pid
----

== dfx stop

Use the `+dfx stop+` command to stop the {IC} processes that you currently have running on your local computer.
In most cases, you run the {IC} locally so that you can deploy canisters and test your programs during development.
To simulate an external {IC} connection, these processes run continuously either in a terminal shell where you started them or the in the background until you stop or kill them.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

=== Basic usage

[source,bash]
----
dfx stop [flag]
----

=== Flags

You can use the following optional flags with the `+dfx stop+` command.

[width="100%",cols="<32%,<68%",options="header",]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Examples

You can stop the {IC} network processes that are running in the background by changing to a project directory then running the following command:

[source,bash]
----
dfx stop
----

If the local {IC} network is running in a current shell rather than in the background, open a new terminal shell, change to a project directory, then run the `+dfx stop+` command.

The current process identifier (`+pid+`) for the {IC} process started by `+dfx+` is recorded in the `+.dfx/pid+` file.
You can view the process identifier before running the `+dfx stop+` command by running the following command:
[source,bash]
----
more .dfx/pid
----
This command displays a process identifier similar to the following:
[source,bash]
----
1896
----

== dfx upgrade

Use the `+dfx upgrade+` command to upgrade the {sdk-short-name} components running on your local computer.
This command checks the version of the {sdk-short-name} that you have currently installed, then upgrades to the latest version available if an older version is detected.

=== Basic usage

[source,bash]
----
dfx upgrade [flag]
----

=== Flags

You can use the following optional flags with the `+dfx upgrade+` command.

[width="100%",cols="<32%,<68%",options="header",]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

=== Examples

You can upgrade the version of the {sdk-short-name} that you have currently installed by running the following command:

[source,bash]
----
dfx upgrade
----

This command checks the version of `+dfx+` you have currently installed and the latest version available published on the {sdk-short-name} website in a manifest file.
If a newer version of `+dfx+` is available, the command automatically downloads and installs the latest version.

[source,bash]
----
Current version: 0.5.7
Fetching manifest \https://sdk.dfinity.org/manifest.json
Already up to date
----
