= Use the default cycles wallet
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)

As discussed in link:concepts/tokens-cycles{outfilesuffix}[Tokens and cycles], ICP tokens can be converted into *cycles* to power canister operations. 
Cycles provide a largely stable value proposition and represent the operational cost of communication, computation, and storage that applications consume. 
For example, cycles reflect the actual cost of physical hardware, rack space, energy, storage devices, and network bandwidth required by applications running on the {IC}.

Unlike ICP tokens, cycles are only associated with canisters and not user or developer principals. 
Because only canisters require and consume cycles—to perform operations and to pay for the resources they use—users and developers manage the distribution and ownership of cycles through a special type of canister called a *cycles wallet*. Because the cycles wallet holds the cycles required to perform operations such as creating new canisters, these operations are executed by default using the canister identifier for the cycles wallet instead of your user principal.

For the purposes of local development, the {sdk-short-name} automatically creates a default cycles wallet for you in every project and most of the operations performed using the cycles wallet happen behind the scenes.
For example, the cycles wallet acts on your behalf to register canister identifiers and deploy canisters on the local network.

In a production environment, however, you often need to explicitly register and transfer cycles to new canisters, specify the principals that can act as custodians, and manage the principals with ownership rights.
You can perform some of these tasks using the default cycles wallet application running in a web browser. 
Depending on the specific action you want to take, you can also perform these cycle and canister management tasks by running `+dfx wallet+` commands in a terminal or by calling methods in the default cycles wallet canister.

You should keep in mind, however, that calls to the cycles wallet canister are executed using the cycles wallet identifier associated with the currently-selected user identity.
Depending on your currently-selected identity and whether the principal associated with that identity has been added as a controller or a custodian for a wallet, you might see different results or be denied access to a specific method.

To check the identity you are currently using, run the following command:

[source,bash]
----
dfx identity whoami
----

== Controller and custodian roles

A user principal or canister identifier can be assigned to a *controller* or *custodian* role.

A *controller* is the most privileged role and a principal assigned to the controller role can perform privileged tasks including the following:

* Add and remove other principals as controllers.
* Authorize and deauthorize other principals as custodians.
* Add entries to the cycles wallet address book.
* Access the cycles wallet balance and all other information.
* Send cycles to other canisters.
* Act as the message calling principal in calls to other canisters.
* Create canisters and additional cycles wallets.
* Rename the wallet.

A principal assigned to the *custodian* role can only perform a subset of cycles wallet management tasks, including the following:

* Access the wallet information.
* Send cycles to other canisters.
* Act as the message calling principal in calls to other canisters.
* Create canisters.

[[wallet-check-balance]]
== Check the cycle balance

If you are doing local development, your cycles wallet is created when you register a new canister identifier using `+dfx canister create+` or when you register, build, and deploy a canister with `+dfx deploy+`.

If you are deploying on the {IC}, you typically create your cycles wallet by converting ICP tokens to cycles, transferring the cycles to a new canister identifier, and updating the canister with the default cycles wallet WebAssembly module.

After you have a cycles wallet on the local or remote network, you can use the  `+dfx wallet balance+` command or the `+wallet_balance+` method to check the current cycle balance.

To check the cycles balance in a local project:

. Open a terminal and navigate to the root directory of the project.
. Start the {IC} locally by running the following command:
+
[source,bash]
----
dfx start --background
----
. Display the cycle balance from the cycles wallet associated with the currently-selected identity by running the following command:
+
[source,bash]
----
dfx wallet balance
----
+
The command displays output similar to the following:
+
....
78000000000000 cycles.
....


For example, if your principal is a controller for the `h5aet-waaaa-aaaab-qaamq-cai` cycles wallet, you check check the current cycle balance by running the following command:

....
dfx canister --network ic call h5aet-waaaa-aaaab-qaamq-cai wallet_balance
....

The command returns the balance using Candid format as a record with an amount field (represented by the hash 3_573_748_184) and a balance of
6,895,656,625,450 cycles like this:

....
(record { 3_573_748_184 = 6_895_656_625_450 })
....

[[wallet-create-wallets]]
== Create a new cycles wallet

Use the `wallet_create_wallet` method to create a new cycles wallet canister with an initial cycle balance and, optionally, with a specific principal as its controller.
If you don't specify a controlling principal, the cycles wallet you use to create the new wallet will be the new wallet's controller.

For example, you can run a command similar to the following to create a new wallet and assign a principal as a controller:

....
dfx canister --network  call f3yw6-7qaaa-aaaab-qaabq-cai wallet_create_wallet '(record { cycles = 5000000000000 : nat64; controller = principal "vpqee-nujda-46rtu-4noo7-qnxmb-zqs7g-5gvqf-4gy7t-vuprx-u2urx-gqe"})'
....

The command returns the principal for the new wallet:

....
(record { 1_313_628_723 = principal "dcxxq-jqaaa-aaaab-qaavq-cai" })
....

[[wallet-create-canister]]
== Register a new canister identifier

Use the `wallet_create_canister` method to register a new canister identifier on the {IC}. 
This method creates a new "empty" canister placeholder with an initial cycle balance and, optionally, with a specific principal as its controller.
After you have registered the canister identifier, you can install code for your application as a separate step.

For example, you can run a command similar to the following to create a new wallet and assign a principal as a controller:

....
dfx canister --network  call f3yw6-7qaaa-aaaab-qaabq-cai wallet_create_canister '(record { cycles = 5000000000000 : nat64; controller = principal "vpqee-nujda-46rtu-4noo7-qnxmb-zqs7g-5gvqf-4gy7t-vuprx-u2urx-gqe"})'
....

The command returns the principal for the new canister you created:

....
(record { 1_313_628_723 = principal "dxqg5-iyaaa-aaaab-qaawa-cai" })
....

[[wallet-add-controller]]
== Add a controller

Use the `add_controllers` method to add a principal as a controller of the cycles wallet.

For example:

....
dfx canister --network ic --no-wallet call f3yw6-7qaaa-aaaab-qaabq-cai add_controller '(principal "vpqee-nujda-46rtu-4noo7-qnxmb-zqs7g-5gvqf-4gy7t-vuprx-u2urx-gqe")'
....

In this example, the principal for the currently-active identity is a controller of the `f3yw6-7qaaa-aaaab-qaabq-cai` cycles wallet. The `--no-wallet` option enables the call to the add_controller method to use the principal for the currently-active identity (a controller) and not the cycles wallet (which is not a controller).

To make the cycles wallet a controller of itself, you would run a command similar to the following:

....
dfx canister --network ic --no-wallet call f3yw6-7qaaa-aaaab-qaabq-cai add_controller '(principal "f3yw6-7qaaa-aaaab-qaabq-cai")'
....

[[wallet-get-controllers]]
== List the current controllers

If you are doing local development, your cycles wallet is created when you register a new canister identifier using `+dfx canister create+` or when you register, build, and deploy a canister with `+dfx deploy+`.

If you are deploying on the {IC}, you typically create your cycles wallet by converting ICP tokens to cycles and transferring the cycles to a new canister identifier.

After you have a cycles wallet on the local or remote network, you can use the  `+dfx wallet controllers+` command or the `get_controllers` method to list the principals that have full control over a specified cycles wallet canister.

To list the controllers for a cycles wallet in a local project:

. Open a terminal and navigate to the root directory of the project.
. Start the {IC} locally by running the following command:
+
[source,bash]
----
dfx start --background
----
. List the principal identifiers that have full control over the cycles wallet for the current project by running the following command:
+
[source,bash]
----
dfx wallet controllers
----
+
The command displays the textual representation of the principals that have control over the cycles wallet with output similar to the following:
+
....
tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe
....

For example:

....
dfx canister --network  call f3yw6-7qaaa-aaaab-qaabq-cai get_controllers
....

The command returns a list of principals similar to the following:

....
(
  vec {
    principal "zen7w-sjxmx-jcslx-ey4hf-rfxdq-l4soz-7ie3o-hti3o-nyoma-nrkwa-cqe";
    principal "vpqee-nujda-46rtu-4noo7-qnxmb-zqs7g-5gvqf-4gy7t-vuprx-u2urx-gqe";
  },
)
....


[[wallet-remove-controller]]
== Remove a controller

Use the `remove_controller` method to remove a principal as a controller.

For example:

....
dfx canister --network ic call f3yw6-7qaaa-aaaab-qaabq-cai remove_controller '(principal "zdm3q-uxmkz-lsghp-r737v-dgwav-rinn2-hs3zf-fnib3-2rylb-3kuek-hae")'
....

[[wallet-authorize]]
== Authorize a custodian

Use the `authorize` method to authorize a principal as a custodian of a cycles wallet.

For example:

....
dfx canister --network ic call f3yw6-7qaaa-aaaab-qaabq-cai authorize '(principal "zdm3q-uxmkz-lsghp-r737v-dgwav-rinn2-hs3zf-fnib3-2rylb-3kuek-hae")'
....

[[wallet-get-custodian]]
== List current custodians

Use the `get_custodians` method to return the list of principals that are currently defined as custodians for the cycles wallet.

....
dfx canister --network ic call f3yw6-7qaaa-aaaab-qaabq-cai get_custodians
....

The command returns a list of principals similar to the following:

....
(
  vec {
    principal "zen7w-sjxmx-jcslx-ey4hf-rfxdq-l4soz-7ie3o-hti3o-nyoma-nrkwa-cqe";
    principal "uymke-5ldqg-w6g7u-qjvng-efsfp-t45m2-tekqj-xvjel-57yv2-hpsdl-zqe";
    principal "vpqee-nujda-46rtu-4noo7-qnxmb-zqs7g-5gvqf-4gy7t-vuprx-u2urx-gqe";
  },
)
....

[[wallet-deauthorize]]
== Remove authorization for a custodian

Use the `deauthorize` method to remove a principal as a custodian for a cycles wallet.

For example:

....
dfx canister --network ic call f3yw6-7qaaa-aaaab-qaabq-cai deauthorize '(principal "zdm3q-uxmkz-lsghp-r737v-dgwav-rinn2-hs3zf-fnib3-2rylb-3kuek-hae")'
....


[[wallet-send]]
== Send cycles to a canister

Use the `wallet_send` method to send a specific number of cycles to a specific canister.
Keep in mind that the canister you specify must have a wallet_receive method to accept the cycles.

For example, if you attempt to send cycles to the hello canister (`hbe6c-baaaa-aaaab-qaaoq-cai`) using a command like this:

....
dfx canister --network ic call f3yw6-7qaaa-aaaab-qaabq-cai wallet_send '(record { canister = principal "hbe6c-baaaa-aaaab-qaaoq-cai";amount=2000000000000:nat64;})'
....

You'll see an error message similar to this:

....
Canister hbe6c-baaaa-aaaab-qaaoq-cai has no update method 'wallet_receive'
....

If you call the method to send the cycles to a cycles wallet, however, the command succeeds:

....
dfx canister --network ic call f3yw6-7qaaa-aaaab-qaabq-cai wallet_send '(record { canister = principal "h5aet-waaaa-aaaab-qaamq-cai";amount=2000000000000:nat64;})'
....

[[wallet-receive]]
== Receive cycles from a canister

Use the `wallet_receive` method as an endpoint to receive cycles.


[[wallet-call]]
== Forward calls from a wallet

Use the `wallet_call` method to forward calls using the cycles wallet identifier.

[[wallet-addresses]]
== Manage addresses

Use the following methods to manage address book entries:

* `add_address`: (address: AddressEntry) -> ();
* `list_addresses`: () -> (vec AddressEntry) query;
* `remove_address`: (address: principal) -> ();


[[events]]
== Manage events

Use the following methods to retrieve event and chart information.

* `get_events`: (opt record { from: opt nat32; to: opt nat32; }) -> (vec Event) query;
* `get_chart`: (opt record { count: opt nat32; precision: opt nat64; } ) -> (vec record { nat64; nat64; }) query;
