= Use the default cycles wallet
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)

As discussed in link:concepts/tokens-cycles{outfilesuffix}[Tokens and cycles], ICP tokens can be converted into *cycles* to power canister operations. 
Cycles provide a largely stable value proposition and represent the operational cost of communication, computation, and storage that applications consume. 
For example, cycles reflect the actual cost of physical hardware, rack space, energy, storage devices, and network bandwidth required by applications running on the {IC}.

Unlike ICP tokens, cycles are only associated with canisters and not user or developer principals. 
Instead, users and developes manage the distribution and ownership of cycles through a special type of canister called a *cycles wallet*.

For the purposes of local development, the {sdk-short-name} automatically creates a default cycles wallet for you in every project and most of the operations performed using the cycles wallet happen behind the scenes.
For example, the cycles wallet acts on your behalf to register canister identifiers and deploy canisters on the local network.

In a production environment, however, you often need to explicitly register and transfer cycles to new canisters, specify the principals that can act as custodians, and manage the principals with ownership rights. 

[[wallet-create-wallets]]
== Create a new cycles wallet

Use the `wallet_create_wallet` method to

[[wallet-create-canister]]
== Register a new canister identifier

Use the `wallet_create_canister` method to

[[wallet-get-controllers]]
== List the current controllers

Use the `get_controllers` method to

....
dfx canister --network=alpha call f3yw6-7qaaa-aaaab-qaabq-cai get_controllers
....

....
(
  vec {
    principal "zen7w-sjxmx-jcslx-ey4hf-rfxdq-l4soz-7ie3o-hti3o-nyoma-nrkwa-cqe";
    principal "uymke-5ldqg-w6g7u-qjvng-efsfp-t45m2-tekqj-xvjel-57yv2-hpsdl-zqe";
    principal "vpqee-nujda-46rtu-4noo7-qnxmb-zqs7g-5gvqf-4gy7t-vuprx-u2urx-gqe";
  },
)
....

[[wallet-add-controller]]
== Add a controller

Use the `add_controllers` method to 

....
dfx canister --network=alpha --no-wallet call f3yw6-7qaaa-aaaab-qaabq-cai add_controller '(principal "vpqee-nujda-46rtu-4noo7-qnxmb-zqs7g-5gvqf-4gy7t-vuprx-u2urx-gqe")'
....

[[wallet-remove-controller]]
== Remove a controller

Use the `remove_controller` method to 

[[wallet-authorize]]
== Authorize a custodian

Use the `authorize` method to 

[[wallet-get-custodian]]
== List current custodians

Use the `get_custodians` method to return the list of principals that are currently defined as custodians for the cycles wallet.

....
dfx canister --network=alpha call f3yw6-7qaaa-aaaab-qaabq-cai get_custodians
....

The command returns a list of principals similar to the following:

....
(
  vec {
    principal "zen7w-sjxmx-jcslx-ey4hf-rfxdq-l4soz-7ie3o-hti3o-nyoma-nrkwa-cqe";
    principal "uymke-5ldqg-w6g7u-qjvng-efsfp-t45m2-tekqj-xvjel-57yv2-hpsdl-zqe";
    principal "vpqee-nujda-46rtu-4noo7-qnxmb-zqs7g-5gvqf-4gy7t-vuprx-u2urx-gqe";
  },
)
....

[[wallet-deauthorize]]
== Remove authorization for a custodian

Use the `deauthorize` method to 


[[wallet-check-balance]]
== Check the cycle balance

Use the `wallet_balance` method to 

[[wallet-send]]
== Send cycles to a canister

Use the wallet_send method to 

[[wallet-receive]]
== Receive cycles from a canister

Use the `wallet_receive` method to

[[wallet-call]]
== Forward calls from a wallet

Use the `wallet_call` method to

[[wallet-addresses]]
== Manage addresses

Use the following methods to manage address book entries:

add_address: (address: AddressEntry) -> ();

list_addresses: () -> (vec AddressEntry) query;

remove_address: (address: principal) -> ();


[[events]]
== Manage events

Use the following methods to retrieve event and chart information.

get_events: (opt record { from: opt nat32; to: opt nat32; }) -> (vec Event) query;

get_chart: (opt record { count: opt nat32; precision: opt nat64; } ) -> (vec record { nat64; nat64; }) query;