:title:  Developer's Guide
= DFINITY Canister SDK Developer's Guide
December 2019 (Alpha)
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:ext: .mo
:company-id: DFINITY
:page-layout: default
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

Are you ready to write code that runs directly on the internet? 
Dive in right away with the link:../quickstart/quickstart-intro{outfilesuffix}[Quick start].

The Alpha release of the DFINITY Canister SDK is available for download now. The contents of this release are built directly from the production source code repository and are ready for you to start exploring a new frontier—the next generation of the open internet.

The {platform} is poised to help you start a revolution with a new way to design, build, and release software with superpowers.

Select a topic to explore the {sdk-long-name}.

++++
<div id="content-section">
  <div class="container">
    <div class="home-card"><a href="introduction-key-concepts.html">
        <p class="service-name">Concepts</p></a>
      </div>
      <div class="box2"><a href="getting-started.html">
        <p class="center"></p>
        <p class="service-name">Get started</p></a>
      </div>
      <div class="box3"><a href="tutorials-intro.html">
        <p class="center"></p>
        <p class="service-name">Tutorials</p></a>
      </div>
    </div>

    <div class="three-columns">
      <div class="box1"><a href="customize-projects.html">
        <p class="center"></p>
        <p class="service-name">Projects</p>
        <!--<p class="tagline">Customize your project using the configuration file.</p>--></a>
      </div>
      <div class="box2"><a href="basic-syntax-rules.html">
        <p class="center"></p>
        <p class="service-name">Basic Motoko</p>
        <!--<p class="tagline">Review the basic syntax requirements for writing Motoko code.</p>--></a>
      </div>
      <div class="box3"><a href="cli-reference.html">
        <p class="center"></p>
        <p class="service-name">CLI</p>
        <!--<p class="tagline">Go beyond basic usage information in the command-line reference.</p>--></a>
      </div>
    </div>

    <div class="three-columns">
      <div class="box1"><a href="https://github.com/dfinity">
        <p class="center"></p>
        <p class="service-name">Samples</p></a>
      </div>
      <div class="box2"><a href="https://dfinity.org/community">
        <p class="center"></p>
        <p class="service-name">Videos</p></a>
      </div>
      <div class="box3"><a href="https://dfinity.org">
        <p class="center"></p>
        <p class="service-name">Sandbox</p></a>
      </div>
    </div>
  </div>
</div>
</main>
</div>
++++
