= 用語集
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

[[g-actor]]
Actor::
  Actor とは、モダンプログラミング言語における特殊な種類のオブジェクトで、メッセージ（Actor 間の関数呼び出しのやり取り）を隔離されたステートとして処理し、リモートで非同期に処理することを可能にします。

[[g-canister]]
Canister スマートコントラクト::
  Canister スマートコントラクト（あるいは、単に Canister と呼ばれることもあります）は、スマートコントラクトを拡張したものです。
  Canister スマートコントラクトが画期的なのは、決定論的に並列実行できるからです。
  これは、Actor モデルと決定論的メッセージパッシングによって可能になります。
  Canister のスマートコントラクトは、普遍的にユニークな識別子と、特定の Dapp の境界を定義する Owner を持っています。
  Canister は、プログラムのロジック、公開された関数の呼び出し方法、メッセージの型に対するインターフェース記述、および Canister によって表される Dapp のステート情報のすべてをカプセル化します。

[[g-principal]]
プリンシパル::
  プリンシパルとは、{IC} ブロックチェーンによって認証可能なエンティティです。
  {IC} ブロックチェーンとやりとりするプリンシパルは、多くの場合、ID を介して行います。
  例えば、{sdk-short-name} を初めて使用するとき、`+dfx+` というコマンドラインツールは、PEM ファイル内の公開鍵と秘密鍵のペアを使って、`+デフォルトの+` 開発者 ID を生成します。（訳者注：`default` という名前のディレクトリが生成され、その中に PEM ファイルが生成されます。）
  この開発者 ID が、**プリンシパル**を決定づけます。
  プリンシパルにはテキスト表現があり、これはしばしば **プリンシパル ID **と呼ばれます。
  開発者 ID は、ICP トークンを ID に代わって Ledger に保持するための**アカウント ID **（BitcoinやEthereumのアドレスに似ています）を導くためにも使用できます。

[[g-controller]]
コントローラ::
  コントローラとは、Canister スマートコントラクトを管理する特別な権利を持つプリンシパルのことです。
  たとえば、コントローラであるプリンシパルのみが、その制御下にある Canister のインストール、アップグレード、または削除を行うことができます。
  コントローラは、ユーザーまたは Canister に関連付けられたプリンシパルのテキスト表現（プリンシパル ID）を用いて指定することができます。

[[g-ledger]]
Ledger::
  {IC} ブロックチェーンは、ICP トークンを含むすべての取引を、**Ledger Canister** と呼ばれる専用の管理 Canister スマートコントラクトに記録します。
  Ledger Canister は、**アカウント**と**残高**を管理し、アカウントと残高に影響を与える *トランザクション* の履歴を残すスマートコントラクトを実装しています。トランザクションは、以下の特定のイベントを追跡するために記録されます:
  
  * アカウントに対して **ICPトークンをミント** する。
  * あるアカウントから別のアカウントに **ICP トークン**を転送する。
  * **ICP トークンをバーン**して消滅させる。

[[g-wallet]]
Wallet::
  Wallet とは、Cycle を保管・管理するための専用の Dapp で、Canister スマートコントラクトとして実装されています。
  Cycle は {IC} ブロックチェーンでの計算やリソース消費の支払いに使用されます。
  Cycle は {IC} ブロックチェーンのネイティブユーティリティートークンである ICP から変換することで入手できます。

[[g-node]]
ノード::
  {IC} ブロックチェーンに参加するために必要なすべてのハードウェア、レプリカソフトウェア、および構成設定をホストする物理的または仮想的なマシンです。

[[g-replica]]
レプリカ:: 
  {IC} ブロックチェーンの文脈では、レプリカとはノード上で実行されている {IC} プロトコルのプロセスを指します。

[[g-wasm]]
WebAssembly::
  https://webassembly.org/[WebAssembly] (`+Wasm+`) は、低レベルのコンピュータ命令フォーマットです。
  WebAssemblyは、ほとんどのモダンなコンピュータハードウェアをきれいに抽象化した、ポータブルでオープンスタンダードなバイナリフォーマットを定義しているため、インターネット上で実行するプログラムに広くサポートされています。
  {proglang} で書かれた Dapps は、{IC} ブロックチェーン上で実行するために WebAssembly コードにコンパイルされます。

////
= Glossary
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

[[g-actor]]
actor::
  An actor is a special kind of object in modern programming languages that processes messages in an isolated state, enabling them to be handled remotely and asynchronously.

[[g-canister]]
Canister smart contract::
  Canister smart contracts, sometimes also simply called canisters, are an extended form of smart contracts. They are revolutionary because they can be run in parallel deterministically. This is enabled by relying on the actor model and deterministic message passing. A canister smart contract has a universally-unique identifier and an owner that defines the boundaries of a specific dapp.
  A canister encapsulates all of the programming logic, public entry methods, the interface description for the provided message types, and state information for the dapp it describes.

[[g-principal]]
principal::
  A principal is an entity that can be authenticated by the {IC} blockchain. Principals that interact with the {IC} blockchain often do so via an identity. For example, the first time you use the {sdk-short-name}, the `+dfx+` command-line tool creates a `+default+` developer identity for you with a public/private key pair in a PEM file. This developer identity determines a **principal**. There is a textual representation of the principal which is often referred to as your **principal identifier**.
  Note that the developer identity can also be used to derive an **account identifier**—similar to a Bitcoin or Ethereum address—to hold ICP tokens on the identity's behalf in the ledger canister.

[[g-controller]]
controller::
  A controller is a principal that has special rights to manage the canister smart contract it controls.
  For example, only a controlling principal can be used to install, upgrade, or delete the canister under its control.
  You can specify the controller principal using the textual representation of a principal—often referred to as the principal identifier—associated with a user or with a canister.

[[g-ledger]]
ledger::
  The {IC} blockchain records all transactions involving ICP tokens in a specialized management canister smart contract, called the **ledger canister**.
  The ledger canister implements a smart contract that maintains **accounts** and **balances** and keeps a history of the *transactions* that affect accounts and balances. The transactions are recorded to track the following specific events:
  
  * **Mint ICP tokens** for accounts.
  * **Transfer ICP tokens** from one account to another.
  * **Burn ICP tokens** to eliminate them from existence.

[[g-wallet]]
wallet::
  A wallet is a specialized dapp (implemented as a canister smart contract) that allows to store and manage cycles. Cycles are used to pay for computation and resource consumption on the {IC} blockchain. Cycles can be obtained by conversion from the {IC} blockchain's native utility token ICP.

[[g-node]]
node::
  A physical or virtual machine that hosts all the hardware, replica software, and configuration settings required to participate in the {IC} blockchain.

[[g-replica]]
replica:: 
  In the context of the {IC} blockchain, a replica refers to the {IC} protocol processes running on a node.

[[g-wasm]]
WebAssembly::
  https://webassembly.org/[WebAssembly] (`+Wasm+`) is a low-level computer instruction format. 
  Because WebAssembly defines a portable, open-standard, binary format that abstracts cleanly over most modern computer hardware, it is broadly supported for programs that run on the internet.
  Dapps written in {proglang} are compiled to WebAssembly code for execution on the {IC} blockchain.
////