= Glossary
December 2019 (Alpha)
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:ext: .mo
:company-id: DFINITY

actor::
  An actor is a special kind of object in modern programming languages that processes messages in an isolated state, enabling them to be handled remotely and asynchronously.
canister::
  A canister is a conceptual object with a universally-unique identifier and an owner that defines the boundaries of a specific application, service, or micro-site. 
  A canister encapsulates all of the programming logic, public entry methods, the interface description for the provided message types, and state information for the application, service, or micro-service it describes.
replica::
  In the context of the {platform}, a replica refers to the {IC} processes (for example, the `+replica+`, `+nodemanager+`, and other lower-level {IC} protocol processes) running on a physical computer node in the network.
  For the {sdk-short-name}, you use the `+dfx start+` and `+dfx stop+` commands to start and stop the `+replica+` process locally to provide a local network for development.
node::
  A physical computer that is a registered member of the {platform} network and running the {IC} replica processes.
WebAssembly::
  https://webassembly.org/[WebAssembly] (`+Wasm+`) is a low-level computer instruction format. 
  Because WebAssembly defines a portable,open-standard, binary format that abstracts cleanly over most modern computer hardware, it is broadly supported for programs that run on the internet. 
  Programs written in {proglang} are compiled to WebAssembly code for execution on {IC} replicas.
