= ソフトウェアのインストール・アップグレード・削除
:experimental:
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

link:../quickstart/quickstart-intro{outfilesuffix}[クイックスタート]で説明したように、ターミナルシェルでコマンドを実行することで、DFINITY Canister スマートコントラクト SDK パッケージの最新バージョンをダウンロードしてインストールすることができます。
このセクションでは、{sdk-short-name} のインストール、アップグレード、および削除に関する追加情報を提供します。

include::ROOT:page$download.adoc[leveloffset=0,tag=install_jp]

== インストールされるもの

{sdk-short-name} のインストールスクリプトは、ローカルコンピュータのデフォルトの場所にいくつかのコンポーネントをインストールします。
次の表では、スクリプトがインストールする開発環境のコンポーネントについて説明します:

[cols="20,55,25",options="header"]
|===
|コンポーネント
|概要
|デフォルトの場所

|dfx
|{company-id} 実行コマンドラインインターフェース (CLI)
|`+/usr/local/bin/dfx+`

|moc
|{proglang} ランタイムコンパイラ
|`~/.cache/dfinity/versions/<VERSION>/moc`

|replica
|{IC} ローカルネットワークバイナリ
|`~/.cache/dfinity/versions/<VERSION>/replica`

|uninstall.sh
|{sdk-short-name} と全てのコンポーネントの削除スクリプト
|`~/.cache/dfinity/uninstall.sh`

|versions
|{sdk-short-name} の各バージョンのサブディレクトリを含むキャッシュディレクトリ。 
|`~/.cache/dfinity/versions`

|===

=== versions ディレクトリに含まれる主要コンポーネント

`~/.cache/dfinity/versions` ディレクトリには、{sdk-short-name} の各バージョンのサブディレクトリが格納されています。
各バージョンのサブディレクトリには、{sdk-short-name} の特定のバージョンに必要な全てのディレクトリとファイルが含まれています。
例えば、`~/.cache/dfinity/versions/0.9.0` ディレクトリの内容をリストアップすると、以下のような主要コンポーネントが表示されます。

....
total 349192
drwxr-xr-x  17 pubs  staff       544 Mar 15 11:55 .
drwxr-xr-x   4 pubs  staff       128 Mar 25 14:36 ..
drwxr-xr-x  49 pubs  staff      1568 Mar 15 11:55 base
drwxr-xr-x  20 pubs  staff       640 Mar 15 11:55 bootstrap
-r-x------   1 pubs  staff  66253292 Mar 15 11:55 dfx
-r-x------   1 pubs  staff  10496256 Dec 31  1969 ic-ref
-r-x------   1 pubs  staff   5663644 Dec 31  1969 ic-starter
-r-x------   1 pubs  staff      9604 Dec 31  1969 libcharset.1.0.0.dylib
-r-x------   1 pubs  staff     38220 Dec 31  1969 libffi.7.dylib
-r-x------   1 pubs  staff    668300 Dec 31  1969 libgmp.10.dylib
-r-x------   1 pubs  staff    958248 Dec 31  1969 libiconv.2.4.0.dylib
-r-x------   1 pubs  staff      4200 Dec 31  1969 libiconv.dylib
-r-x------   1 pubs  staff     96900 Dec 31  1969 libz.1.2.11.dylib
-r-x------   1 pubs  staff  15417684 Dec 31  1969 mo-doc
-r-x------   1 pubs  staff  14634020 Dec 31  1969 mo-ide
-r-x------   1 pubs  staff  15111508 Dec 31  1969 moc
-r-x------   1 pubs  staff  49404128 Dec 31  1969 replica
....

=== {proglang} base ディレクトリ

{sdk-short-name} の各バージョンのサブディレクトリ内にある `+base+` ディレクトリには、そのバージョンの{sdk-short-name} と互換性のある{proglang} のベースライブラリモジュールが含まれています。
{proglang} ベースライブラリは急速に進化しているため、インストールした {sdk-short-name} のバージョンにパッケージされているベースモジュールのみを使用する必要があります。

=== Bootstrap ディレクトリ

`bootstrap` ディレクトリにはすでに非推奨となった Web サーバのコードが含まれています。
バージョン 0.7.0 以降、agent は `bootstrap` コードの代わりに HTTP ミドルウェアサーバを呼び出すことができるようになりました。
この変更により、canister は HTTP リクエストに直接応答できるようになり、従来のウェブベースのアプリケーションのように操作できるようになりました。

== 最新バージョンへのアップグレード

最初のインストール後に {sdk-short-name} の新しいバージョンがダウンロードできるようになった場合、最新の修正や拡張機能をいち早く手にするために、更新されたバージョンをできるだけ早くインストールすることを推奨します。
現在インストールされているバージョンと、ダウンロード可能な最新バージョンを比較するには、`+dfx upgrade+` コマンドを使用します。
より新しいバージョンの `+dfx+` が利用可能な場合、`+dfx upgrade+` コマンドによって自動的に最新バージョンをダウンロードしてインストールすることができます。

なお，新しいバージョンをインストールする前に，既存のソフトウェアをアンインストールする必要はありません。
ただし，アップグレードではなくクリーンインストールを行いたい場合は，xref:remove[ソフトウェアのアンインストール] で説明しているように，まず既存のソフトウェアをアンインストールしてから，ダウンロードおよびインストールコマンドを実行してください。

最新リリースの機能や修正については、xref:release-notes:sdk-release-notes.adoc[リリースノート]をご覧ください。

[[remove]]
== ソフトウェアのアンインストール

{sdk-short-name} をインストールすると、インストールスクリプトが必要なバイナリファイルをローカルディレクトリに置き、キャッシュを作成します。
`.cache` フォルダにある `+uninstall+` スクリプトを実行することで、ローカルコンピュータから SDK のバイナリとキャッシュを削除することができます。

例えば、以下のようにします:
[source,bash]
----
~/.cache/dfinity/uninstall.sh
----

まっさらな状態の `dfx` をすぐに再インストールしたい場合は、以下のコマンドを実行してください:

[source,bash]
----
~/.cache/dfinity/uninstall.sh && sh -ci "$(curl -sSL https://sdk.dfinity.org/install.sh)"
----

////
= Install, upgrade, or remove software
:experimental:
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

As described in the link:../quickstart/quickstart-intro{outfilesuffix}[Quick start], you can download and install the latest version of the DFINITY Canister smart contract SDK package by running a command in a terminal shell.
The topics in this section provide additional information about installing, upgrading, and removing the {sdk-short-name}.

include::ROOT:page$download.adoc[leveloffset=0,tag=install]

== What gets installed

The {sdk-short-name} installation script installs several components in default locations on your local computer.
The following table describes the development environment components that the installation script installs:

[cols="20,55,25",options="header"]
|===
|Component
|Description
|Default location

|dfx
|{company-id} execution command-line interface (CLI)
|`+/usr/local/bin/dfx+`

|moc
|{proglang} runtime compiler
|`~/.cache/dfinity/versions/<VERSION>/moc`

|replica
|{IC} local network binary
|`~/.cache/dfinity/versions/<VERSION>/replica`

|uninstall.sh
|Script to remove the {sdk-short-name} and all of its components
|`~/.cache/dfinity/uninstall.sh`

|versions
|Cache directory that contains a subdirectory for each version of the {sdk-short-name} you install.  
|`~/.cache/dfinity/versions`

|===

=== Core components in a versioned directory

The `~/.cache/dfinity/versions` directory stores one or more versioned subdirectories of the {sdk-short-name}. 
Each versioned subdirectory contains the all of the directories and files required for a specific version of the {sdk-short-name}.
For example, if you list the contents of the `~/.cache/dfinity/versions/0.9.0` directory you would see the following core components:

....
total 349192
drwxr-xr-x  17 pubs  staff       544 Mar 15 11:55 .
drwxr-xr-x   4 pubs  staff       128 Mar 25 14:36 ..
drwxr-xr-x  49 pubs  staff      1568 Mar 15 11:55 base
drwxr-xr-x  20 pubs  staff       640 Mar 15 11:55 bootstrap
-r-x------   1 pubs  staff  66253292 Mar 15 11:55 dfx
-r-x------   1 pubs  staff  10496256 Dec 31  1969 ic-ref
-r-x------   1 pubs  staff   5663644 Dec 31  1969 ic-starter
-r-x------   1 pubs  staff      9604 Dec 31  1969 libcharset.1.0.0.dylib
-r-x------   1 pubs  staff     38220 Dec 31  1969 libffi.7.dylib
-r-x------   1 pubs  staff    668300 Dec 31  1969 libgmp.10.dylib
-r-x------   1 pubs  staff    958248 Dec 31  1969 libiconv.2.4.0.dylib
-r-x------   1 pubs  staff      4200 Dec 31  1969 libiconv.dylib
-r-x------   1 pubs  staff     96900 Dec 31  1969 libz.1.2.11.dylib
-r-x------   1 pubs  staff  15417684 Dec 31  1969 mo-doc
-r-x------   1 pubs  staff  14634020 Dec 31  1969 mo-ide
-r-x------   1 pubs  staff  15111508 Dec 31  1969 moc
-r-x------   1 pubs  staff  49404128 Dec 31  1969 replica
....

=== {proglang} base directory

The `+base+` directory in the versioned subdirectory of the {sdk-short-name} contains the {proglang} base library modules that are compatible with that version of the {sdk-short-name}. 
Because the {proglang} base library is evolving rapidly, you should only use the base modules that are packaged with the version of the {sdk-short-name} that you have installed.

=== Bootstrap directory

The `bootstrap` directory contains web server code that is deprecated. 
Beginning with version 0.7.0, agents can call an HTTP middleware server instead of the `bootstrap` code. 
This change enables canisters to respond to HTTP requests directly and operate more like traditional web-based applications.

== Upgrading to the latest version

If a new version of the {sdk-short-name} is available for download after your initial installation, you should install the updated version at your earliest convenience to get the latest fixes and enhancements as soon as possible.
You can use the `+dfx upgrade+` command to compare the version you have currently installed against the latest version available for download. 
If a newer version of `+dfx+` is available, the `+dfx upgrade+` command automatically downloads and installs the latest version. 

Note that you don't need to uninstall the software before installing the new version.
However, if you want to perform a clean installation rather than an upgrade, you can first uninstall the software as described in xref:remove[Removing the software], then re-run the download and installation command.

For information about the features and fixes in the latest release, see the xref:release-notes:sdk-release-notes.adoc[Release notes].

[[remove]]
== Removing the software

When you install the {sdk-short-name}, the installation script puts the required binary files in a local directory and creates a cache.
You can remove the SDK binaries and cache from your local computer by running the `+uninstall+` script located in the `.cache` folder.

For example:
[source,bash]
----
~/.cache/dfinity/uninstall.sh
----

If you are uninstalling because you want to immediately reinstall a clean version of `dfx`, you can run the following command:

[source,bash]
----
~/.cache/dfinity/uninstall.sh && sh -ci "$(curl -sSL https://sdk.dfinity.org/install.sh)"
----
////