= Sample code, applications, and microservices
May 2020 (Alpha)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:linkedcss:
:toc:
:toc: right
:toc-title: SAMPLE PROJECTS
:toclevels: 1
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:ext: .mo
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)

Sample code, applications, and microservices that have been developed by DFINITY or contributed by the community are available from the link:https://github.com/dfinity/examples[DFINITY public repository].

By accessing the public repository, you can directly download, clone, fork, or share sample projects.
You will also be able to contribute by suggesting updates or reporting issues for the published projects using the standard GitHub work flow. 

Sample projects provide a way for you to experiment and collaborate with other developers.
The projects and sample code are not, however, intended to be used as commercial applications and do not provide any explicit or implied support or warranty of any kind.

This section provides a preliminary look at some sample code for applications and microservices that you can copy and modify to jump-start your own projects.

== C
For examples of projects written in the C programming language for the {IC}, see link:https://github.com/dfinity/examples/tree/master/c[C++ sample projects].

* link:https://github.com/dfinity/examples/tree/master/c/adventure[Adventure game]
* link:https://github.com/dfinity/examples/tree/master/c/qr[QR code generator]
* link:https://github.com/dfinity/examples/tree/master/c/reverse[Reverse game]

== Motoko

For projects that use the {proglang} programming language, see link:https://github.com/dfinity/examples/tree/master/motoko[Motoko sample projects].

* link:https://github.com/dfinity/examples/tree/master/motoko/calc[Calculator - simple functions]
* link:https://github.com/dfinity/examples/tree/master/motoko/counter[Counter]
* link:https://github.com/dfinity/examples/tree/master/motoko/echo[Echo]
* link:https://github.com/dfinity/examples/tree/master/motoko/factorial[Factorial]
* link:https://github.com/dfinity/examples/tree/master/motoko/favorite_cities[Favorite cities]
* link:https://github.com/dfinity/examples/tree/master/motoko/hello-world[Hello, world]
//* link:[Hex encoding and decoding]
* link:https://github.com/dfinity/examples/tree/master/motoko/phone-book[Phone book]
* link:https://github.com/dfinity/examples/tree/master/motoko/pubsub[Publish/subscribe]
// link:[To-do checklist]


== Additional sample application

This section includes sample code from projects that are not currently available in the public repository.

=== To-do checklist

The `+motoko-to-do+` project illustrates how to create a simple to-do checklist application using the {proglang} programming language.

This project is implemented using the following {proglang} source code files. 

==== utils.mo

The `+utils.mo+` file contains the core functions for adding, completing, and removing to-do items. 

[source,motoko]
----
include::example$motoko-to-do/utils.mo[]
----

==== types.mo
The `+types.mo+` file defines the properties for `+ToDo+` items as a custom data type definition.

[source,motoko]
----
include::example$motoko-to-do/types.mo[]
----

==== main.mo

The `+main.mo+` file contains the actor definition and public functions that the compiled canister exposes.

[source,motoko]
----
include::example$motoko-to-do/main.mo[]
----

=== Hex encoding and decoding

The `+mo-hex+` project implements hexadecimal encoding and decoding routines for the {proglang} programming language.

=== Source code

The project includes the following `+hex.mo+` source code.

[source,motoko]
----
include::example$hex/hex.mo[]
----

=== Polynomial long-division in GF(256)

This program performs polynomial long division for a Galois field GF(256) element.

=== Source code

In addition to standard libraries, this project uses two main {proglang} source code files. 
- The `+galois.mo+` file contains the core programming logic. 
- The `+nat.mo+` file contains additional functions that are imported for use in the `+galois.mo+` file.

==== galois.mo

[source,motoko]
----
include::example$galois/galois.mo[]
----

==== nat.mo

[source,motoko]
----
include::example$galois/nat.mo[]
----