= Sample code, applications, and microservices
May 2020 (Alpha)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

Sample code, applications, and microservices that have been developed by DFINITY or contributed by the community are available from the link:https://github.com/dfinity/examples[DFINITY public repository].

By accessing the public repository, you can directly download, clone, fork, or share sample projects.
You will also be able to contribute by suggesting updates or reporting issues for the published projects using the standard GitHub work flow.

Sample projects provide a way for you to experiment and collaborate with other developers.
The projects and sample code are not, however, intended to be used as commercial applications and do not provide any explicit or implied support or warranty of any kind.

This section provides a preliminary look at some sample code for applications and microservices that you can copy and modify to jump-start your own projects.

== C
For examples of projects written in the C programming language for the {IC}, see link:https://github.com/dfinity/examples/tree/master/c[C++ sample projects].

* link:https://github.com/dfinity/examples/tree/master/c/adventure[Adventure game]
* link:https://github.com/dfinity/examples/tree/master/c/qr[QR code generator]
* link:https://github.com/dfinity/examples/tree/master/c/reverse[Reverse game]

== Motoko

For projects that use the {proglang} programming language, see link:https://github.com/dfinity/examples/tree/master/motoko[Motoko sample projects].

* link:https://github.com/dfinity/examples/tree/master/motoko/calc[Calculator - simple functions]
* link:https://github.com/dfinity/examples/tree/master/motoko/counter[Counter]
* link:https://github.com/dfinity/examples/tree/master/motoko/echo[Echo]
* link:https://github.com/dfinity/examples/tree/master/motoko/factorial[Factorial]
//* link:https://github.com/dfinity/examples/tree/master/motoko/favorite_cities[Favorite cities]
* link:https://github.com/dfinity/examples/tree/master/motoko/hello-world[Hello, world]
* link:https://github.com/dfinity/examples/tree/master/motoko/hello_cycles[Hello, cycles]
//* link:[Hex encoding and decoding]
* link:https://github.com/dfinity/examples/tree/master/motoko/life[Game of Life - upgrades]
* link:https://github.com/dfinity/examples/tree/master/motoko/phone-book[Phone book]
* link:https://github.com/dfinity/examples/tree/master/motoko/pub-sub[Publish/subscribe]
* link:https://github.com/dfinity/examples/tree/master/motoko/quicksort[Quicksort]
* link:https://github.com/dfinity/examples/tree/master/motoko/random_maze[Random maze - cryptographic randomness]
* link:https://github.com/dfinity/examples/tree/master/motoko/simple-to-do[To-do checklist]
* link:https://github.com/dfinity/examples/tree/master/motoko/superheroes[Superheroes database]
* link:https://github.com/dfinity/examples/tree/master/motoko/whoami[whoami]


== Additional sample applications

This section includes sample code from projects that are not currently available in the public repository.

=== Hex encoding and decoding

The `+mo-hex+` project implements hexadecimal encoding and decoding routines for the {proglang} programming language.

==== Source code

The project includes the following xref:hex[hex.mo] source code.

[[hex]]
===== hex.mo
[source.copy,motoko,no-repl]
----
include::example$hex/hex.mo[]
----

=== Polynomial long-division in GF(256)

This program performs polynomial long division for a Galois field GF(256) element.

==== Source code

In addition to standard libraries, this project uses two main {proglang} source code files.

- The xref:galois[Galois.mo] file contains the core programming logic.
- The xref:nat[Nat.mo] file contains additional functions that are imported for use in the `+Galois.mo+` file.

[[galois]]
===== Galois.mo

[source.copy,motoko,no-repl]
----
include::example$galois/Galois.mo[]
----

[[nat]]
===== Nat.mo

[source.copy,motoko,no-repl]
----
include::example$galois/Nat.mo[]
----
