:title:  {IC} SDK - Developer Tools
= Developer Center
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
:page-layout: home
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

The {IC} blockchain is poised to help you start a revolution with a new way to design, build, and release dapps.

== Developing dapps

The {IC} is a blockchain that runs canister smart contracts, which are code units bundling together WebAssembly bytecode and the memory pages the bytecode runs in. The {IC} is composed by individual subnet blockchains running in parallel and connected together by the use of Chain Key Cryptography. This means that canisters running on a subnet can seamlessly call canisters hosted in any other subnet of the {IC} blockchain. Moreover, the governance system of the {IC} can dynamically increase the capacity of the {IC} by adding new subnets, allowing dapps to scale out.

Developers can thus build new dapps consisting of multiple canisters running in parallel on different subnets and possibly integrate them with existing canisters already running on the {IC}.

== Developer workflow at-a-glance

At a high-level, there are two main possible workflows for developing dapps that run on the {IC} blockchain.

image:local-remote-path-workflow.svg[Development paths]

//Local development: you start a local instance of the Internet Computer running locally, then write, compile, and install your dapp in the local iteratively in a local development environment.

* *Local development:* you start a local canister deployment environment simulating the {IC} blockchain locally. Then you write, compile, install and iteratively update your canisters in the development environment. This gives you the possibility to test your canisters locally without the need to use cycles to power it.

* *On-chain deployment:* once your dapp is ready you can then deploy it to the {IC} blockchain, making it available for the world to use it. Note that your canisters need have cycles to be able to run on the {IC}, as discussed in link:/concepts/tokens-cycles{outfilesuffix}[Tokens and cycles].

//If you prefer to do all of your development work without connecting to a local or remote network, you can follow the second path and only connect to the network when you are ready to compile and deploy.
//With this option, you only connect to the Internet Computer network and register for a unique identifier after you have a program ready to deploy.

//In the third path, you connect to the Internet Computer running on a remote network, then register for a unique identifier before you have a program ready to compile.
//With this option, you can preregister with the network to receive a unique identifier, then compile and deploy using a known identifier when you are ready to move your application to the network.

Regardless of the development workflow you choose, keep in mind that when you deploy a canister for the first time, either on a canister deployment environment or on the {IC}, a unique link:/glossary{outfilesuffix}#g-principal[principal identifier] is created for your canister smart contract. For example, if you start developing your canister locally and then deploy it to the {IC}, then your canister will generally have a different identifier on the development environment and on the {IC} blockchain. Note that it is also possible for you to register a principal identifier for your new canister before deploying it or even writing any line of code.