= さまざまなプログラミング言語を用いた開発
:cpp: C++

このドキュメントに掲載されている Dapps の例のほとんどは、{proglang} という {IC} で動作するように特別に設計されたプログラミング言語を使用しています。
しかし、{IC} 上に Dapps をデプロイするために、WebAssembly にコンパイル可能な任意のプログラミング言語で Dapps を書くことも可能です。
この章では、様々なプログラミング言語で Dapps を書き、{IC} 上にデプロイするためのハイレベルなガイダンスを用意しています。

== Rust を使用する

Cargo を使用し、Dapp を WebAssembly にコンパイルすることで、{IC} 上で動作する Rust プロジェクトを作成することができます。

この章では、Rust プログラムを Canister スマートコントラクトとして {IC} 上にデプロイする際の主要な手順をまとめています。
ただし、ここで説明している手順は、1 つのアプローチを示しているに過ぎないことに注意してください。
他のアプローチも可能です。

なお、link:https://github.com/dfinity/cdk-rs[Rust canister development kit (Rust CDK)] では、クエリコールやアップデートコールの関数を書きやすくするためのショートカットが用意されており、Rust ベースのプロジェクトを作り始めるためのいくつかの link:https://github.com/dfinity/cdk-rs/tree/next/examples[例] が含まれていますが、Rust CDK を使わなくても {IC} 用の Dapps を開発することができます。

=== プロジェクトの作成

ほとんどの Rust プログラマーは、Cargo を使って Dapp が依存しているライブラリのダウンロードやコンパイルなどのビルドやパッケージ管理のタスクを処理しています。そのため、最初のステップは Cargo のコマンドラインインターフェイスを使って新しい Rust プロジェクトを作成することです。

Cargo の代わりに {sdk-long-name} を使って新しいプロジェクトを作成することもできますが、Cargo を使ってプロジェクトを作成するのが Rust プロジェクト作成の典型的なワークフローです。

新しい Rust プロジェクトを作成するには、以下のようにします：

[arabic]
. ローカル PC でターミナルを開きます。
. 以下のコマンドで Cargo がインストールされているかどうかを確認します：
+
[source,bash]
----
cargo --version
----
. {IC} か Rust サンプルプロジェクトのために使用しているディレクトリに移動してください。
. 以下のコマンドを実行して、新しいプロジェクトを作成します：
+
[source,bash]
----
cargo new my_rust_dapp
----
+
このコマンドは、`+Cargo.toml+` ファイルが入った `+my_rust_dapp+` ディレクトリと、`+main.rs+` ファイルが入った `+src+` ディレクトリを新たに作成します。
. 以下のコマンドを実行してプロジェクトディレクトリに移動します：
+
[source,bash]
----
cd my_rust_dapp
----
+
このディレクトリの中身を表示すると、`+Cargo.toml+` ファイルと `+src+` ディレクトリだけが含まれていることがわかります。
このプロジェクトを {IC} 上で動作するようにコンパイルするには、いくつかの追加ファイルが必要になります。

=== Cargo 設定ファイルの修正

`+Cargo.toml+` ファイルでは、それぞれの Rust パッケージごとに *マニフェスト* を用意しています。
マニフェストには、パッケージの設定の詳細を指定するセクションが含まれています。
Rust プロジェクトを {IC} 上で実行できるようにするために、デフォルトの `+Cargo.toml+` ファイルをコピーして、プロジェクトの設定の詳細をいくつか変更します。

`+Cargo.toml+` ファイルを修正するには、以下のようにします：

. 必要に応じて `pwd` コマンドを使い、自分がプロジェクトのルートディレクトリにいることを確認します。
. デフォルトの `+Cargo.toml+` ファイルを `+src+` ディレクトリに以下のコマンドでコピーします：
+
[source,toml]
----
cp Cargo.toml src/Cargo.toml
----
+
{IC} 上で実行されるプロジェクトでは通常、プロジェクトのルートディレクトリにある `+Cargo.toml+` ファイルを使用してプロジェクトの Canister 群のワークスペースを設定し、ソースコードのディレクトリにある2つ目の `+Cargo.toml+` ファイルを使用して、各 Canister の設定を行います。
. プロジェクトのルートディレクトリにある `+Cargo.toml+` ファイルをテキストエディタで開きます。
+
デフォルトでは、`+[package]+` と `+[dependencies]+` のセクションが含まれています。
. `+[package]+` セクションを、以下のように `+[workspace]+` セクションに置き換えます：
+
[source,toml]
----
[workspace]
members = [
    "src/my_rust_dapp",
]
----
+
`+[workspace]+` のセクションで使用するキーについては、link:https://doc.rust-lang.org/cargo/reference/workspaces.html[Workspaces] を参照してください。
`+Cargo.toml+` ファイルで設定できるその他のセクションやキーについては、link:https://doc.rust-lang.org/cargo/reference/manifest.html[The Manifest Format] を参照してください。

. `+[dependencies]+` セクションを削除します。
. 変更を保存しファイルを閉じて次に進んでください。
. `+src/Cargo.toml+` ファイルをテキストエディタで開きます。
. 以下のように、main のソースコードへのパスを指定する `+[lib]+` セクションを追加します：
+
[source,toml]
----
[lib]
path = "main.rs"
----
. パッケージの依存関係については適宜 `+[dependencies]+` セクションに追加してください。
. 変更を保存しファイルを閉じて次に進んでください。

=== Canister 設定ファイルの追加

{sdk-short-name} を使用して新しいプロジェクトを作成すると、`+dfx new+` コマンドが自動的にデフォルトの設定ファイルである `+dfx.json+` をプロジェクトディレクトリに追加します。
ここでは Cargo を使って Rust プロジェクトを作成したので、`+dfx.json+` をプロジェクトディレクトリに手動で作成する必要があります。

`+dfx.json+` を追加するには、以下のようにします：

. 必要に応じて `pwd` コマンドを使い、自分がプロジェクトのルートディレクトリにいることを確認します。
. `+dfx.json+` 設定ファイルをプロジェクトのルートディレクトリに新しく作成します。
. `+dfx.json+` ファイルをテキストエディタで開きます。
. `+version+` と　`+canisters+` キーを以下のように追加します：
+
[source,json]
----
{
  "version": 1,
  "canisters": {
    "my_rust_dapp": {
      "type": "custom",
      "candid": "src/my_rust_dapp.did",
      "wasm": "target/wasm32-unknown-unknown/debug/my_rust_dapp.wasm",
      "build": "cargo build --target wasm32-unknown-unknown --package my_rust_dapp"
    }
  }
}
----
+
この設定について詳しく見てみましょう。
+
--
* `+version+` の設定は、プロジェクトの作成に使用したソフトウェアのバージョンを確認するために使用されます。
* `+canisters+` セクションでは、プロジェクトの Canister の名前を指定します。
この例では、`+my_rust_dapp+` という名前の Canister が1つ指定されています。
* `+type+` キーが `+custom+` なのは、この Canister が現在認識されているCanister タイプ (`+motoko+` か `+assets+`) ではないからです。
* `+candid+` キーは、このプロジェクトで使用する Candid インターフェース記述ファイルの名前と場所を指定します。
* `+wasm+` キーは、`+cargo build+` コマンドで生成される WebAssembly ファイルのパスを指定します。
* `+build+` キーは、コンパイルに使用する `+cargo+` コマンドを指定します。

--
+
これらは必要最小限の設定です。
より複雑なプログラムを作成する際には、`+Cargo.toml+` ファイル、`+dfx.json+` ファイル、あるいはその両方に、追加の設定情報を含める必要が出る可能性があります。
. 変更を保存し、ファイルを閉じて次に進んでください。

=== Candid インターフェース記述ファイルの作成

設定ファイルである `+dfx.json+` に加えて、Candid インターフェース記述ファイル（例えば、`+my_rust_dapp.did+`）を用意する必要があります。このファイルは、Dapp の引数や返り値のフォーマットを、Candid での言語にとらわれない表現にマッピングするために必要です。

Candid インターフェース記述ファイルを追加するには、以下のようにします：

. 必要に応じて `pwd` コマンドを使い、自分がプロジェクトのルートディレクトリにいることを確認します。
. プロジェクトの `+src+` ディレクトリに、Candid インターフェース記述ファイル（例えば、`+my_rust_dapp.did+`）を新たに作成します。
. Candid インターフェース記述ファイルをテキストエディタで開き、Dapp が定義する各関数に対する記述を追加します。
+
例えば、`+my_rust_dapp+` が `+increment+`、`+read+`、`+write+` 関数を使ってカウンタをインクリメントするシンプルな dapp である場合、`+my_rust_dapp.did+` ファイルは以下のようになります：
+
[source,candid]
----
service : {
  "increment": () -> ();
  "read": () -> (nat) query;
  "write": (nat) -> ();
}
----
. 変更を保存しファイルを閉じて次に進んでください。

=== デフォルトの Dapp の修正

新しいプロジェクトを作成すると、"Hello, World!" プログラムのテンプレートファイルである `+main.rs+` ファイルが `+src+` ディレクトリに作られます。

このテンプレートのソースコードを修正するには以下のようにします：

. `+src/main.rs+` ファイルをテキストエディタで開き、中身を削除します。
. {IC} にデプロイしたいプログラムを書きます。
+
プログラムを書く際には、呼び出しには「アップデートコール」と「クエリコール」の2種類があることと、アップデート関数は非同期メッセージングを行うことに注意してください。
. 変更を保存して、`+main.rs+` ファイルを閉じます。

=== Dapp のデプロイ

Dapp をデプロイしてテストする前に、以下を行う必要があります。

* ローカルの Canister 実行環境、または {IC} ブロックチェーンのメインネットのいずれかに接続します。
* アプリケーションにネットワーク固有の識別子を登録します。
* WebAssembly をターゲット出力として Dapp をコンパイルします。

WebAssembly にコンパイルする `+cargo build+` コマンドを `+dfx.json+` ファイルに設定したので、`+dfx+` コマンドラインインターフェイスと標準的なワークフローによって残りのすべてのステップを実行することができます。

Dapp をローカルでビルドとデプロイするには以下のようにします：

. 必要に応じて `pwd` コマンドを使い、自分がプロジェクトのルートディレクトリにいることを確認します。
. 新しいターミナルの窓あるいはタブを開き、プロジェクトディレクトリへ移動します。
+
例えば、macOS で Terminal を使用している場合は、以下のどちらかを行います：
+
--
* *Shell* をクリックし、*New Tab* を選択して、現在の作業ディレクトリに新しいターミナルを開きます。
* *Shell* をクリックし、 *New Window* を選択して、`+cd ~/ic-projects/location_hello+` を新しいターミナルで実行してください（`+ic-projects+` フォルダの中に `+location_hello+` プロジェクトがある場合）。
--
+
今手元では、プロジェクトディレクトリを作業ディレクトリとした、2つのターミナルが開かれているはずです。
. 以下のコマンドを実行して、ローカルの Canister 実行環境を起動します：
+
[source,bash]
----
dfx start
----
+
使用しているプラットフォームやローカルのセキュリティ設定によっては、警告が表示される場合があります。
受信するネットワーク接続を許可するか拒否するかを選択する操作画面が表示された場合は、*Allow* をクリックしてください。
. ネットワーク操作を表示している端末を開いたまま、プロジェクトを作成した元の端末にフォーカスを切り替えます。
. 以下のコマンドを実行して、アプリケーションに固有の Canister ID を登録します：
+
[source,bash]
----
dfx canister create --all
----
. 以下のコマンドを実行して Dapp をビルドします：
+
[source,bash]
----
dfx build
----
. 以下のコマンドを実行して Dapp をローカルの Canister 実行環境にデプロイします：
+
[source,bash]
----
dfx canister install --all
----
. コマンドライン、あるいはブラウザから、Dapp の関数をテストしてください。

== C 言語の使用

{IC} は標準的な WebAssembly モジュールにコンパイルされた Dapps をサポートしているため、標準的なコンパイラやツールチェーンを使用して、C、{cpp}、Objective-C、Objective-{cpp} などのプログラミング言語や、`+Clang+` コンパイラを用いてアプリケーションを構築することができます。

C 言語で書かれた Dapps を {IC} 上で動作するようにする方法を説明するために、link:https://github.com/dfinity/examples/tree/master/c[examples] リポジトリにあるシンプルな `+reverse.c+` プログラムを見てみましょう。
この `+reverse.c+` プログラムには、文字列の順番を反転させる `+go+` という関数を1つ持っています。

=== 開発環境のセットアップ

`+reverse.c+` プログラムを WebAssembly にコンパイルするためには、`+clang+` コンパイラと標準ライブラリがインストールされている必要があります。
ローカルコンピュータに `+clang+` がインストールされているかどうかは、次のコマンドを実行することで確認することができます：

[source,bash]
----
clang --version
----

`+clang+` がインストールされていれば、以下のような情報が表示されます。

....
clang version 10.0.0 
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
....

コマンドがバージョン情報を返さない場合は、先に `+clang+` をインストールしてください。
`+clang+` をインストールする手順は，使用している OS によって異なります。
例えば、Debian Linux では，以下のコマンドを実行してください：

[source,bash]
----
sudo apt-get install clang lld gcc-multilib
----

macOS では、Developer Command-Line Tools をインストールするか、Homebrew を使って LLVM をインストールすることで、`+clang+` をインストールすることができます。
例えば、`+clang+` がインストールされていない場合は、以下のコマンドを実行してください：

[source,bash]
----
brew install llvm
----

=== プログラムを WebAssembly にコンパイルする

C 言語で書いたプログラムを WebAssembly モジュールとして動作させるには、まず `+clang+` でコンパイルし、次に `+wasm-ld+` でリンクします。
使用している OS や `+clang+` のバージョンによっては、macOS では `+wasm-ld+`、Debianでは `+wasm-ld-8+` など、異なるバージョンの WebAssembly リンカを使用する場合もあります。

macOS で WebAssembly にコンパイルするには以下のようにします：
 
. 以下のコマンドを実行し、プログラムをコンパイルします：
+
[source,bash]
----
clang --target=wasm32 -c -O3 reverse.c
----
. 以下のように `+wasm-ld+` コマンドを用いて、WebAssembly モジュールを作成するリンカを実行します：
+
[source,bash]
----
wasm-ld --no-entry --export-dynamic --allow-undefined reverse.o -o reverse.wasm
----

=== 最小限の設定ファイルの作成

次に、{IC} にインストールできるパッケージとして `+reverse+` の Dapp バイナリを識別させるために、簡単な設定ファイルを準備する必要があります。また、`+dfx+` のコマンドラインインターフェイスを使ってパッケージを Canister としてインストールして実行できるように、`+build+` ディレクトリを用意する必要があります。

設定ファイルと build ディレクトリを用意するには以下のようにします：

. 以下のコマンドを実行し、Canister キーを持たせた `+dfx.json+` を作成します：
+
[source,bash]
----
echo '{"canisters":{"reverse":{"main":"reverse"}}}' > dfx.json
----
. 以下のコマンドを実行し、`+build+` ディレクトリを作成します：
+
[source,bash]
----
mkdir build
----
. 以下のコマンドを実行し、`+reverse+` ディレクトリを作成します：
+
[source,bash]
----
mkdir build/reverse
----
. 以下のコマンドを実行して、WebAssembly モジュールを新しい `+build/reverse+` ディレクトリにコピーします：
+
[source,bash]
----
cp reverse.wasm build/reverse/
----

=== 最小限のインターフェース記述ファイルの作成

標準的な開発ワークフローでは、`+dfx build+` コマンドによって `+Canister+` のアウトプットディレクトリにいくつかのファイルが作成され、その中に、プログラムの関数に関連するデータ型の型合わせを行う Candid インターフェース記述ファイル (`+.did+`) が（1つ、あるいは複数）含まれています。

異なるデータ型に使用する構文の詳細については、link:.../candid-guide/candid-intro{outfilesuffix}[_Candid のガイド_] または link:https://github.com/dfinity/candid/tree/master/spec[Candid の仕様]を参照してください。

現在のプログラムに Candid インターフェース記述ファイルを作成するには以下のようにします：

. `+reverse.c+` ファイルを置くために作成した `+build+` ディレクトリでターミナルを開きます。
. 新しいテキストファイルを `+reverse.did+` という名前で作成します。
. 関数 `+go+` の記述を追加します。
+
例えば、以下のようになります：
+
[source.bash]
----
service : {
  "go": (text) -> (text);
}
----
. 変更を保存しファイルを閉じて次に進んでください。

=== Dapp のデプロイとテスト

Dapp をデプロイしてテストする前に、以下の手順を行う必要があります：

* ローカル Canister 実行環境か、{IC} ブロックチェーンのメインネットのどちらかに接続します。
* アプリケーションにネットワーク固有の識別子を登録します。

ローカルで Dapp のデプロイとテストを行うには以下のようにします：

. ローカルコンピュータで、新しいターミナルのウィンドウかタブを開きます。
+
例えば、macOS で Terminal を起動している場合、*Shell* をクリックし、*New Tab* を選択すると、現在の作業ディレクトリに新しいターミナルが開きます。
. 2つ目のターミナルで以下のコマンドを実行して、ローカルの Canister 実行環境を起動します：

+
[source,bash]
----
dfx start
----
. 以下のコマンドを実行し、`+reverse+` アプリケーションに固有の Canister ID を登録します：
+
[source,bash]
----
dfx canister create --all
----
. 以下のコマンドを実行し、ローカルの Canister 実行環境にデフォルトの Dapp をデプロイします：
+
[source,bash]
----
dfx canister install --all
----
. 以下のコマンドを実行し、Dapp の `go` 関数を呼びます：
+
[source,bash]
----
dfx canister call reverse go reward
("drawer")
----

C 言語の Dapps の例は他にも link:https://github.com/dfinity/examples/tree/master/c[examples] リポジトリにあります。

////
= Develop using different languages
:cpp: C++

Most of the example dapps in this guide use {proglang}—the programming language specifically designed to work with the {IC}. 
Potentially, however, you can write dapps in any language that compiles to WebAssembly to deploy applications that run on the {IC}.
This section provides some high-level guidance for writing dapps in different languages and how to deploy them on the {IC}.

== Using Rust

You can create Rust projects to run on the {IC} by using Cargo and compiling your dapp to use WebAssembly as the target output.

This section provides a summary of the key steps involved in deploying a Rust program as a canister smart contract on the {IC}.
You should note, however, that the steps described here only illustrate one approach. 
Other implementation approaches are also possible. 

Note that the link:https://github.com/dfinity/cdk-rs[Rust canister development kit (Rust CDK)] for provides some shortcuts to make it easier to write functions as query and update calls and includes several link:https://github.com/dfinity/cdk-rs/tree/next/examples[examples] to get you started building Rust-based projects, but you can also develop dapps for the {IC} without using the Rust CDK.

=== Create a project

Because most Rust programmers use Cargo to handle build and package management tasks, such as downloading and compiling the libraries your dapp depends on, your first step is to create a new Rust project using the Cargo command-line interface.

Alternatively, you could create a new project using {sdk-long-name} instead of Cargo, but creating a project using Cargo represents the typical workflow for creating Rust projects.

To create a new Rust project:

[arabic]
. Open a terminal shell on your local computer, if you don’t already
have one open.
. Verify that you have Cargo installed by running the following command:
+
[source,bash]
----
cargo --version
----
. Change to the folder you are using for your {IC} or Rust sample projects.
. Create a new project by running a command similar to the following:
+
[source,bash]
----
cargo new my_rust_dapp
----
+
This command creates a new `+my_rust_dapp+` directory with a default `+Cargo.toml+` file and a `+src+` directory with a default `+main.rs+` file.
. Change to your project directory by running the following command:
+
[source,bash]
----
cd my_rust_dapp
----
+
If you list the contents of this directory, you'll see that it only contains the `+Cargo.toml+` file and `+src+` directory. 
To compile this project to run on the {IC}, you'll need some additional files.

=== Modify the Cargo configuration file

The `+Cargo.toml+` file provides a *manifest* for each Rust package. 
The manifest contains sections that specify configuration details for the package.
To prepare the Rust project to run on the {IC}, we'll copy the default `+Cargo.toml+` file then modify some of the configuration details for the project.

To modify the `+Cargo.toml+` file:

. Check that you are in the root directory for your project by running the `+pwd+` command, if necessary.
. Copy the default `+Cargo.toml+` file to the `+src+` directory by running the following command:
+
[source,toml]
----
cp Cargo.toml src/Cargo.toml
----
+
Projects that run on the {IC} typically use one project-level `+Cargo.toml+` file to set up a workspace for the canister members of the project and a second `+Cargo.toml+` file in the source code directory to configure settings for each canister.
. Open the `+Cargo.toml+` file that is the root directory of your project in a text editor. 
+
By default, the file contains the `+[package]+` and the `+[dependencies]+` sections.
. Replace the `+[package]+` section with a `+[workspace]+` section similar to the following:
+
[source,toml]
----
[workspace]
members = [
    "src/my_rust_dapp",
]
----
+
For information about the `+[workspace]+` section and `+[workspace]+` keys, see link:https://doc.rust-lang.org/cargo/reference/workspaces.html[Workspaces].
For information about the other sections and keys you can configure in the `+Cargo.toml+` file, see link:https://doc.rust-lang.org/cargo/reference/manifest.html[The Manifest Format].
. Remove the `+[dependencies]+` section.
. Save your changes and close the file to continue.
. Open the `+src/Cargo.toml+` file in a text editor.
. Add a `+[lib]+` section with the path to the main source code similar to the following: 
+
[source,toml]
----
[lib]
path = "main.rs"
----
. Update the `+[dependencies]+` section with any package dependencies.
. Save your changes and close the file to continue.

=== Add a canister configuration file

When you create a new project using the {sdk-short-name}, the `+dfx new+` command automatically adds a default `+dfx.json+` configuration file to the project directory.
Because we created the Rust project using Cargo, you need to manually create this file in your project directory.

To add the `+dfx.json+` configuration file:

. Check that you are still in your project directory by running the `+pwd+` command, if necessary.
. Create a new `+dfx.json+` configuration file in the root directory for your project.
. Open the `+dfx.json+` file in a text editor.
. Add the `+version+` and `+canisters+` keys with settings similar to the following to the `+dfx.json+` file:
+
[source,json]
----
{
  "version": 1,
  "canisters": {
    "my_rust_dapp": {
      "type": "custom",
      "candid": "src/my_rust_dapp.did",
      "wasm": "target/wasm32-unknown-unknown/debug/my_rust_dapp.wasm",
      "build": "cargo build --target wasm32-unknown-unknown --package my_rust_dapp"
    }
  }
}
----
+
Let's take a closer look at these settings.
+
--
* The `+version+` setting is used to identify the version of the software used to create the project.
* The `+canisters+` section specifies the name of the project's canisters.
In this case, there's only one canister and it is named `+my_rust_dapp+`.
* The `+type+` key is set to `+custom+` because this canister is not one of the currently recognized (`+motoko+` or `+assets+`) canister types.
* The `+candid+` key specifies the name and location of the Candid interface description file to use for this project.
* The `+wasm+` key specifies the path to the WebAssembly file generated by the `+cargo build+` command.
* The `+build+` key specifies the `+cargo+` command used to compile the output.
--
+
These are the minimum settings required.
As you build more complex programs, you might need to include additional configuration details in the `+Cargo.toml+` file, the `+dfx.json+` file, or both files.
. Save your changes and close the file to continue.

=== Create a Candid interface description file

In addition to the `+dfx.json+` configuration file, you need to have a Candid interface description file—for example, `+my_rust_dapp.did+`—to map your dapp's input parameters and return value formats to their language-agnostic representation in Candid.

To add the Candid interface description file:

. Check that you are still in your project directory by running the `+pwd+` command, if necessary.
. Create a new Candid interface description file—for example, `+my_rust_dapp.did+`—in the `+src+` directory for your project.
. Open the Candid interface description file in a text editor and add a description for each function the dapp defines.
+
For example, if the `+my_rust_dapp+` is a simple dapp that increments a counter using the `+increment+`, `+read+`, and `+write+` functions, the `+my_rust_dapp.did+` file might look like this:
+
[source,candid]
----
service : {
  "increment": () -> ();
  "read": () -> (nat) query;
  "write": (nat) -> ();
}
----
. Save your changes and close the file to continue.

=== Modify the default dapp

When you create a new project, your project `+src+` directory includes a template `+main.rs+` file with the "Hello, World!" program.

To modify the template source code:

. Open the template `+src/main.rs+` file in a text editor and delete the existing content.
. Write the program you want to deploy on the {IC}.
+
As you write your program, keep in mind that there are two types of calls—update calls and query calls—and that update functions use asynchronous messaging.
. Save your changes and close the `+main.rs+` file.

=== Deploy the dapp

Before you can deploy and test your dapp, you need to do the following:

* Connect to either the local canister execution environment, or to the {IC} blockchain mainnet.
* Register a network-specific identifier for the application.
* Compile the dapp with a target output of WebAssembly.

Because you configured the custom `+dfx.json+` file with a `+cargo build+` command that compiles to WebAssembly, you can use the `+dfx+` command-line interface and standard work flow to perform all of the remaining steps.

To build and deploy the dapp locally:

. Check that you are still in your project directory by running the `+pwd+` command, if necessary.
. Open a new terminal window or tab on your local computer and navigate to your project directory.
+
For example, you can do either of the following if running Terminal on macOS:
+
--
* Click *Shell*, then select *New Tab* to open a new terminal in your current working directory.
* Click *Shell* and select *New Window*, then run `+cd ~/ic-projects/location_hello+` in the new terminal if your `+location_hello+` project is in the `+ic-projects+` working folder.
--
+
You should now have two terminals open with your project directory as your current working directory**.
. Start the local canister execution environment by running the following command:
+
[source,bash]
----
dfx start
----
+
Depending on your platform and local security settings, you might see a warning displayed. 
If you are prompted to allow or deny incoming network connections, click *Allow*.
. Leave the terminal that displays network operations open and switch your focus to your original terminal where you created your project.
. Register a unique canister identifier for the application by running the following command:
+
[source,bash]
----
dfx canister create --all
----
. Build the dapp by running the following command:
+
[source,bash]
----
dfx build
----
. Deploy the dapp on the local canister execution environment by running the following command:
+
[source,bash]
----
dfx canister install --all
----
. Test functions in the dapp from the command-line or in a browser.

== Using C

Because the {IC} supports dapps compiled to standard WebAssembly modules, you can use standard compilers and toolchains to build applications in languages such as  C, {cpp}, Objective-C, and Objective-{cpp} programming languages and the `+Clang+` compiler.

To illustrate how to migrate dapps written in C to run on the {IC}, let’s look at the simple `+reverse.c+` program in the link:https://github.com/dfinity/examples/tree/master/c[examples] repository. 
The `+reverse.c+` program contains one function—named `+go+`—that reverses a string in place.

=== Set up the development environment

To compile the `+reverse.c+` program into WebAssembly, you need to have the `+clang+` compiler and standard libraries installed. 
You can check whether you have `+clang+` installed on your local computer by running the following command:

[source,bash]
----
clang --version
----

If `+clang+` is installed, the command displays information similar to the following:

....
clang version 10.0.0 
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
....

If the command doesn’t return version information, install `+clang+` before continuing. 
The steps to install `+clang+` vary depending on the operating system you are using.
On Debian Linux, for example, run the following command:

[source,bash]
----
sudo apt-get install clang lld gcc-multilib
----

On macOS, you can install `+clang+` by installing the Developer Command-Line Tools or by installing LLVM using Homebrew. 
For example, if `+clang+` is not installed, run the following command:

[source,bash]
----
brew install llvm
----

=== Compile the program into WebAssembly

You can compile a C program to run as a WebAssembly module by first compiling using `+clang+`, then linking using `+wasm-ld+`. 
Depending on the operating system and version of `+clang+` you are using, you might use a different version of the WebAssembly linker, such as `+wasm-ld+` on macOS or `+wasm-ld-8+` on Debian. 
 
To compile to WebAssembly on macOS:
 
. Compile the program by running the following clang command:
+
[source,bash]
----
clang --target=wasm32 -c -O3 reverse.c
----
. Run the linker to create the WebAssembly module by running the following `+wasm-ld+` command:
+
[source,bash]
----
wasm-ld --no-entry --export-dynamic --allow-undefined reverse.o -o reverse.wasm
----

=== Create a minimal configuration file

Next, you need to prepare a simple configuration file that identifies the `+reverse+` dapp binary as a package that can be installed on the {IC} and a `+build+` directory so that you can use the `+dfx+` command-line interface to install and run the package as a canister.

To prepare a configuration file and build directory:

. Create a `+dfx.json+` file with a canisters key by running the following command:
+
[source,bash]
----
echo '{"canisters":{"reverse":{"main":"reverse"}}}' > dfx.json
----
. Create a `+build+` directory for the dapp by running the following command:
+
[source,bash]
----
mkdir build
----
. Create a `+reverse+` directory for the dapp by running the following command:
+
[source,bash]
----
mkdir build/reverse
----
. Copy the WebAssembly modules to the new `+build/reverse+` directory by running the following command:
+
[source,bash]
----
cp reverse.wasm build/reverse/
----

=== Create a minimal interface description file

In a standard development workflow, running the `+dfx build+` command creates several files in the `+canisters+` output directory, including one or more Candid interface description (`+.did+`) files that handle type matching for the data types associated with a program’s functions.

For details about the syntax to use for different data types, see the link:../candid-guide/candid-intro{outfilesuffix}[_Candid Guide_] and link:https://github.com/dfinity/candid/tree/master/spec[Candid specification].

To create a Candid interface description file for this program:

. Open a terminal in the `+build+` directory you created for the `+reverse.c+` program source
. Create a new text file named `+reverse.did+`.
. Add a description of the `+go+` function.
+
For example:
+
[source.bash]
----
service : {
  "go": (text) -> (text);
}
----
. Save your changes and close the file to continue.

=== Deploy and test the dapp

Before you can deploy and test your dapp, you need to do the following:

* Connect to either the local canister execution environment, or to the {IC} blockchain mainnet.
* Register a network-specific identifier for the application.

To deploy and test the dapp locally:

. Open a new terminal window or tab on your local computer.
+
For example, if running Terminal on macOS,click *Shell*, then select *New Tab* to open a new terminal in your current working directory.
. Start the local canister execution environment in your second terminal by running the following command:
+
[source,bash]
----
dfx start
----
. Register a unique canister identifier for the `+reverse+` application by running the following command:
+
[source,bash]
----
dfx canister create --all
----
. Deploy the default dapp on the local canister execution environment by running the following command:
+
[source,bash]
----
dfx canister install --all
----
. Call the `+go+` function in the dapp by running the following command:
+
[source,bash]
----
dfx canister call reverse go reward
("drawer")
----

You can find additional examples of C dapps in the link:https://github.com/dfinity/examples/tree/master/c[examples] repository.

////