= Canister スマートコントラクトを管理する
March 2020 (Alpha)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)

link:tutorials-intro{outfilesuffix}[チュートリアル] を行ったり、link:https://github.com/dfinity/examples[examples] リポジトリからサンプルをクローンしたりして、{sdk-long-name} を使って実験したことがある方は、すでにプログラムを構築して**Canister スマートコントラクト**として展開する方法に慣れていることでしょう。
このセクションでは、Canister のライフサイクルと管理方法について追加情報を提供します。

[[create-canister]]
== Canister スマートコントラクトの ID を取得する

ご希望の開発ワークフローに応じて、プログラムをコンパイルする前または後に、Canister スマートコントラクト用の一意の ID を取得することができます。
例えば、コードを書く前にサブネット上の Canister スマートコントラクトの一意な ID を確保したい場合、`+dfx canister create+` コマンドを実行することで可能です。
このコマンドは基本的に空の Canister を確保し、そこに後でコードをインストールすることができます。作成された Canister は一意の ID を取得します。

Canister 用の一意の ID を取得するには、

. 新しいターミナルウィンドウまたはタブを開きます。
. 以下のコマンドを実行して、作成する予定の Canister の新規プロジェクトを作成します。
+
[source,bash]
----
dfx new YOUR-PROJECT-NAME
----
+
プロジェクトに使用する名前は、デフォルトで Canister の名前としても使用されることに注意してください。
. 新しいプロジェクト・ディレクトリに変更します。
.  設定ファイル `+dfx.json+` を開き、使用したい Canister 実行環境（例：{IC} ブロックチェーン）のホストとポートを設定します。
+
ローカル環境を使用している場合は、この手順を省略できます。
+
またコードをコンパイルする前に、必要と思われる追加 Canister の ID を作成したい場合は、オプションで Canister の名前を変更したり、Canister の設定を設定ファイルに追加したりすることができます。
. 必要に応じて、以下のコマンドを実行して、ローカルの Canister 実行環境を起動します。
+
[source,bash]
----
dfx start --background
----
+
ほとんどの場合、このステップはローカルで Canister を動作させる場合にのみ必要です。
+
もし、リモート実行環境、例えば {IC} ブロックチェーン上で実行する Canister を登録する場合、このパラメータで指定された環境上でタスクを実行するために、`+--network+` コマンドラインオプションを含めることになります。
. 以下のコマンドを実行して、`+dfx.json+` で定義された Canister に一意の ID を登録します。
+
[source,bash]
----
dfx canister create --all
----
+
このコマンドは `+.dfx/local+` ディレクトリを作成し、そのディレクトリに `+canister_ids.json+` ファイルを追加します。

[[local-id]]
== ローカル ID を持つ Canister スマートコントラクトをビルドする

プロジェクトのソースコードを記述した後、それを WebAssembly モジュールにコンパイルしてから、Canister としてデプロイする必要があります。

ローカルデバッグのためにのみプロジェクトをコンパイルする場合、プロジェクトのローカル定義 ID を生成することができます。

ローカル定義 ID を生成するには、

. 必要な構成設定とプログラムロジックを持つプロジェクトを作成します。
. 必要に応じて、ローカル Canister の実行環境を起動します。
+
もし、{IC} ブロックチェーンなどのリモート実行環境で実行するために Canister をコンパイルする場合は、`+--network+` コマンドラインオプションを含め、このパラメータで指定した環境上でタスクを実行することになるでしょう。
. 以下のコマンドを実行して、`+dfx.json+` で定義された Canister のためのハードコードされたローカル ID を生成してください。
+
[source,bash]
----
dfx build --check
----
+
{IC} ブロックチェーンにプロジェクトを展開する前に、ローカルで定義した ID を置き換えるために、一意の Canister ID を登録する必要があります。

////
=== Register a unique network-wide identifier

In the most common development workflow, you are assigned network-wide canister identifiers as part of the build process rather than before you have code ready to compile. 

Because this scenario is the most common, it is also the simplest. 

To register canister identifiers as part of the build process:

. Start the {IC} network, if necessary.
+
In most cases, this step is only necessary if you are using the local host as the {IC} network provider and have stopped the network locally.
. Build the WebAssembly executable by running the following command:
+
[source,bash]
----
dfx build
----

== Generate interface bindings for a canister
////

[[deploy-canister]]
== Canister スマートコントラクトをデプロイする

プログラムをコンパイルしたら、コンパイルしたコードを、ローカルの Canister 実行環境または {IC} ブロックチェーン上で動作する Canister スマートコントラクトにインストールできます。

事前またはビルドプロセス中に作成された Canister ID が、デプロイ時にコードがインストールされる場所を決定します。

コードを初めてデプロイするには、

. 新しいターミナルを開き、プロジェクトディレクトリに移動します。
. 必要に応じて、ローカル Canister 実行環境を起動します。
+
ほとんどの場合、このステップはローカルで Canister を動作させる場合にのみ必要です。
+
もし、{IC} ブロックチェーンなどのリモート実行環境で実行する Canister を登録する場合は、`+--network+` コマンドラインオプションを含め、このパラメータで指定した環境上でタスクを実行することになるでしょう。
. デプロイしたいすべての Canister に Canister ID があることを確認します。
. 以下のコマンドを実行して、すべての Canister をデプロイします。
+
[source,bash]
----
dfx canister install --all
----

[[lookup-id]]
== Canister のスマートコントラクト ID を調べる

すべての Canister には一意の ID があります。
Canister と対話するために、これらの ID を使用する必要がある場合がよくあります。
たとえば、Dapp 用のフロントエンド Canister にアクセスしたり、Candid ウェブインターフェースを使用してサービスと対話する場合、適切な Canister ID を指定する必要があります。

ID は Canister が配置されている環境に固有なので、情報を保存するために使用されるファイルは異なるディレクトリにあります。
例えば、ローカルに配置された Canister の ID は、プロジェクトの `+.dfx/local/canister_ids.json+` ファイルに格納されます。

`+dfx canister id+` コマンドを実行することにより、特定の Canister の Canister IDを調べることができます。
例えば、ローカルの Canister 実行環境に配置された `+lookup+` Canister の Canister ID を調べるには、次のコマンドを実行します。

....
dfx canister id lookup
....

また、`+ic+` エイリアスで指定された環境に配置された同じ Canister の Canister ID を調べるには、以下のコマンドを実行します。

....
dfx canister --network=ic id lookup
....

[[add-wallet]]
== 既存の Canister スマートコントラクト用のウォレットを追加

ローカルで開発を行っている場合、新しいプロジェクトを作成すると、そのプロジェクト内の Canister で使用するためのデフォルトのウォレットが自動的に作成されます。もし、以前に作成した Canister のプロジェクトにウォレットを追加したい場合は、いくつかの手動ステップを踏むことで、強制的に `dfx` にウォレットを生成させることができます。

既存の Canister で使用するためにウォレットを追加するには、

. ターミナルを開いて、プロジェクトディレクトリに移動します。
. 必要であれば、以下のコマンドを実行して、ローカルの Canister 実行環境を停止します。
+
[source,bash]
----
dfx stop
----
. `+.dfx+` ディレクトリを削除します。
. 以下のコマンドを実行して、ローカル Canister 実行環境のネットワークを開始します。
+
[source,bash]
----
dfx start --clean
----

[[reinstall-canister]]
== Canister スマートコントラクトを再インストールする

開発サイクルの中で、デバッグや改良をしながらプログラムをインストールし、その後入れ替えたいと思うことがあるかもしれません。

このような場合、登録した Canister ID を保持したいが、Canister のコードや状態は保持したくないと考えるかもしれません。
例えば、Canister には保存したくないテストデータしかない場合や、プログラムを完全に変更することを決定したが、以前のプログラムのインストールに使用した Canister ID の下で再インストールしたい場合などです。

Canister を再インストールするには、

. 新しいターミナルを開き、プロジェクトのディレクトリに移動します。
. 必要であれば、ローカル Canister の実行環境を起動します。
+
ほとんどの場合、このステップはローカルで Canister を実行する場合にのみ必要です。
+
もし、{IC} ブロックチェーンなどのリモート実行環境で実行する Canister を登録する場合は、`+--network+` コマンドラインオプションを含め、このパラメータで指定した環境上でタスクを実行することになるでしょう。
. 再デプロイしたいすべての Canister の Canister ID があることを確認します。
. 次のコマンドを実行して、すべての Canister を再デプロイします。
+
[source,bash]
----
dfx canister install --all --mode reinstall
----

なお、`+reinstall+` モードは、Canister にコードや状態が関連付けられているかどうかに関係なく、任意の Canister を交換するために使用できます。

[[set-owner]]
== Canister スマートコントラクトを所有するための ID を設定する

ほとんどの場合、`+dfx canister create+` コマンドを初めて実行すると、`+default+` というユーザー ID が自動的に作成されます。
このデフォルトの ID は、ローカルのユーザーアカウント用に生成された公開鍵と秘密鍵のペアで構成されています。
通常、この `+default+` ID は、あなたが作成するすべてのプロジェクトと、デプロイするすべての Canister のデフォルトの所有者にもなります。
しかし、`+default+` のユーザー ID が使用されないように、積極的に自分の好きな ID を作成し、使用することができます。

例として、次のシナリオでは `+registered_owner+` という ID を作成し、それを使って `+pubs+` プロジェクトの登録、ビルド、デプロイ、コールを行う例を示しています。

プロジェクトに ID を設定するには、

. 以下のコマンドを実行し、新しいプロジェクトを作成します。
+
[source,bash]
----
dfx new pubs
----
. 以下のコマンドを実行して、プロジェクトディレクトリに移動します。
+
[source,bash]
----
cd pubs
----
. 以下のコマンドを実行して、ローカル Canister 実行環境をバックグラウンドで起動します。
+
[source,bash]
----
dfx start --background
----
. 以下のコマンドを実行して、新しい `+registered_owner+` ID を作成します。
+
[source,bash]
----
dfx identity new registered_owner
----
. 以下のコマンドを実行して、アクティブユーザーコンテキストが `+registered_owner+` の ID を使用するように設定します。
+
[source,bash]
----
dfx identity use registered_owner
----
. 以下のコマンドを実行して、プロジェクトの Canister を登録、ビルド、デプロイします。
+
[source,bash]
----
dfx canister create --all
dfx build --all
dfx canister install --all
----
+
これらのコマンドは `+registered_owner+` という ID で実行され、そのユーザが配備された Canister のオーナーになります。
. 以下のコマンドを実行して `+greet+` 関数を呼び出してデプロイが成功したことを確認します。
+
[source,bash]
---- 
dfx canister call pubs greet '("Sam")'
----

[[running-state]]
== Canister スマートコントラクトの実行状態を管理する

Canister をデプロイすると、ユーザや他の Canister からのリクエストの受信と処理を開始することができるようになります。
リクエストの送信と返信の受信が可能な Canister は、**Running** 状態であるとみなされます。

通常、Canister は既定で実行状態になりますが、Canister を一時的または恒久的に停止したい場合があります。
たとえば、Canister をアップグレードする前に停止したい場合があります。
Canister を停止すると、進行中のメッセージが適切に処理され、完了するまで実行するか、ロールバックする必要があることを確認できます。
また、Canister を停止して、Canister の削除の前提条件として、そのメッセージキューをきれいにクリアしたい場合もあります。

// tag::check-status[]
`+dfx canister status+` コマンドを実行することで、全ての Canister 、または指定した Canister の現在の状態を確認することができます。
例えば、ローカルの Canister 実行環境上で動作している全ての Canister の状態を見るには、以下のコマンドを実行します。

[source,bash]
----
dfx canister status --all
----

このコマンドは、Canister が現在実行されている場合、次のような出力を返します。

....
Canister status_check's status is Running.
Canister status_check_assets's status is Running.
....
// end::check-status[]   

// tag::stop-status[]
`+dfx canister stop+` コマンドを実行することにより、現在実行中のCanister を停止することができます。

[source,bash]
----
dfx canister stop --all
----

このコマンドは、次のような出力を表示します。

....
Stopping code for canister status_check, with canister_id 75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
Stopping code for canister status_check_assets, with canister_id cxeji-wacaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
....

もし、`+dfx canister status+` コマンドを再実行すると、`+Stopped+` というステータスが表示され、処理する必要のある保留中のメッセージはない、または `+Stopping+` というステータスが表示され、処理する必要のあるメッセージがあることがわかるかもしれません。
// end::stop-status[]

// tag::restart-status[]
Canister を再起動するには、例えば Canister のアップグレードに成功した後、`+dfx canister start+` コマンドを実行します。
たとえば、すべての Canister を再起動するには、次のコマンドを実行します。

[source,bash]
----
dfx canister start --all
----

このコマンドは、次のような出力を表示します。

....
Starting code for canister status_check, with canister_id 75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
Starting code for canister status_check_assets, with canister_id cxeji-wacaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
....
// tag::restart-status[]

[[upgrade-canister]]
== Canister スマートコントラクトのアップグレード

Canister の再インストールでは Canister の ID は保持されて、状態は保持されませんが、Canister のアップグレードでは、デプロイされた Canister の状態を保持し、コードを変更することができます。
 
たとえば、履歴書とソーシャル接続を管理する Dapp があるとします。
この Dapp に新しい機能を追加する場合、以前に保存されたデータを失うことなく、Canister のコードを更新できる必要があります。
Canister のアップグレードにより、プログラムの状態を失うことなく、プログラムの変更に伴い既存の Canister ID を更新することができます。

NOTE: {proglang} で書かれた Canister をアップグレードするときに状態を保持するには、必ず `+stable+` キーワードを使用して、保持したい変数を特定します。{proglang} で変数の状態を保持することについての詳しい情報は link:../language-guide/upgrades{outfilesuffix}[Stable variables and upgrade methods] を参照してください。
Rust で書かれた Canister をアップグレードする場合は、link:https://github.com/dfinity/cdk-rs/blob/master/examples/asset_storage/src/asset_storage_rs/lib.rs[Rust CDK asset storage] のサンプルにあるように `+pre_upgrade+` と `+post_upgrade+` 関数を使用して、Canister のアップグレード後にデータが適切に保存されるようにする必要があります。

Canister をアップグレードするには、

. 新しいターミナルを開き、プロジェクトディレクトリに移動します。
. 必要であれば、ローカルの Canister 実行環境を起動します。
+
ほとんどの場合、このステップはローカルで Canister を実行する場合にのみ必要です。
+
もし、{IC} ブロックチェーンなどのリモート実行環境で実行する Canister を登録する場合は、`+--network+` コマンドラインオプションを含め、このパラメータで指定した環境上でタスクを実行することになるでしょう。
. アップグレードしたいすべての Canister の Canister ID があることを確認します。
+
変数宣言で `+stable+` キーワードを使用し、状態を維持する変数を特定する必要があることに注意してください。

+
stable 変数宣言の詳細については、_{proglang} Programming Language Guide_ を参照してください。
. 以下のコマンドを実行して、すべての Canister をアップグレードします。
+
[source,bash]
----
dfx canister install --all --mode upgrade
----

[[delete-canister]]
== Canister のスマートコントラクトを削除する

特定のデプロイ環境（ローカル、リモートのいずれか）上の特定の Canister 、または特定のプロジェクトのすべての Canister を永久に削除したい場合、`+dfx canister delete+` コマンドを実行することで可能です。

Canister を削除すると、Canister の ID、コード、およびステートが削除されます。
ただし、Canister を削除する前に、まず Canister を停止して、保留中のメッセージ要求や返信をクリアする必要があります。

プロジェクトのすべての Canister を削除するには、

. 新しいターミナルを開き、プロジェクトディレクトリに移動します。
. 必要であれば、ローカル Canister 実行環境を起動します。
+
ほとんどの場合、このステップはローカルで Canister を実行する場合にのみ必要です。
+
もし、{IC} ブロックチェーンなどのリモート実行環境で実行する Canister を削除する場合は、`+--network+` コマンドラインオプションを含めて、このパラメータで指定した環境上でタスクを実行することになるでしょう。
. 以下のコマンドを実行して、ローカルの Canister 実行環境上で実行されているプロジェクトの Canister の状態を確認します。
+
[source,bash]
----
dfx canister status --all
----
. 以下のコマンドを実行して、すべてのプロジェクトの Canister を停止します。
+
[source,bash]
----
dfx canister stop --all
----
. 以下のコマンドを実行して、すべてのプロジェクトの Canister を削除します。
+
[source,bash]
----
dfx canister delete --all
----
////
== Canister をフォークする
<TBD - not in this release>

== Canister のコントローラを設定する
<TBD - not in this release>
////
////
= Manage canister smart contracts
March 2020 (Alpha)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

If you have experimented with using the {sdk-long-name} by following the tutorials in the link:tutorials-intro{outfilesuffix}[Tutorials] section or by cloning examples from the link:https://github.com/dfinity/examples[examples] repository, you are already familiar with how to build and deploy programs as **canister smart contracts**.
This section provides additional information about the canister lifecycle and how to manage canisters.

[[create-canister]]
== Obtaining a canister smart contract identifier

Depending on your preferred development workflow, you can obtain a unique identifier for your canister smart contract, before or after you have a program ready to compile.
For example, if you want to reserve a unique identifier for your canister smart contract on a subnet before you have written any code, you can do so by running the `+dfx canister create+` command.
This command essentially creates an empty canister placeholder into which you can later install your code. The resulting canister will obtain a unique identifier.

To obtain a unique identifier for a canister:

. Open a new terminal window or tab on your local computer.
. Create a new project for the canister you plan to create by running a command similar to the following:
+
[source,bash]
----
dfx new YOUR-PROJECT-NAME
----
+
Note that the name you use for the project is also used as the canister name by default. 
. Change to your new project directory.
. Open the `+dfx.json+` configuration file and set the host and port for the canister execution environment you want to use (e.g. the {IC} blockchain).
+
If you are using a local deployment, you can skip this step.
+
You can also optionally change the names of your canisters or add canister settings to the configuration file if you want to create identifiers for any additional canisters you think you will need before compiling code.
. Start the local canister execution environment, if necessary, by running the following command:
+
[source,bash]
----
dfx start --background
----
+
In most cases, this step is only necessary if you are running the canisters locally.
+
If you were registering canisters to run on a remote execution environment, e.g. the {IC} blockchain, you would include the `+--network+` command-line option to perform tasks on the environment specified under this parameter.
. Register unique identifiers for the canisters defined in the `+dfx.json+` by running the following command:
+
[source,bash]
----
dfx canister create --all
----
+
The command creates the `+.dfx/local+` directory and adds the `+canister_ids.json+` file to that directory for the project.

[[local-id]]
== Build a canister smart contract with a local identifier

After you have written source code for your project, you need to compile it into a WebAssembly module before deploying it as a canister.

If you are only compiling your project for local debugging, you can generate a locally-defined identifier for your project.

To generate a locally-defined identifier:

. Create a project with the configuration settings and program logic to suit your needs.
. Start the local canister execution environment, if necessary.
+
If you were compiling canisters to run on a remote execution environment, e.g. the {IC} blockchain, you would include the `+--network+` command-line option to perform tasks on the environment specified under this parameter.
. Generate hard-coded local identifiers for the canisters defined in the `+dfx.json+` by running the following command:
+
[source,bash]
----
dfx build --check
----
+
Note that you must register unique canister identifiers to replace your locally-defined identifier before you can deploy the project on the {IC} blockchain.

////
////
=== Register a unique network-wide identifier

In the most common development workflow, you are assigned network-wide canister identifiers as part of the build process rather than before you have code ready to compile. 

Because this scenario is the most common, it is also the simplest. 

To register canister identifiers as part of the build process:

. Start the {IC} network, if necessary.
+
In most cases, this step is only necessary if you are using the local host as the {IC} network provider and have stopped the network locally.
. Build the WebAssembly executable by running the following command:
+
[source,bash]
----
dfx build
----

== Generate interface bindings for a canister
////
////

[[deploy-canister]]
== Deploy canister smart contracts

After you have compiled a program, you can install the compiled code in a canister smart contract running either on a local canister execution environment or on the {IC} blockchain.

The canister identifier that was created in advance or during the build process determines where your code is installed during deployment.

To deploy the code for the first time:

. Open a new terminal and navigate to your project directory.
. Start the local canister execution environment, if necessary.
+
In most cases, this step is only necessary if you are running the canisters locally.
+
If you were registering canisters to run on a remote execution environment, e.g. the {IC} blockchain, you would include the `+--network+` command-line option to perform tasks on the environment specified under this parameter.
. Verify you have canister identifiers for all of the canisters you want to deploy.
. Deploy all of the canisters by running the following command:
+
[source,bash]
----
dfx canister install --all
----

[[lookup-id]]
== Look up a canister smart contract identifier

All canisters have unique identifiers.
You often need to use these identifiers to interact with the canister.
For example, if you want to access the front-end canister for a dapp or interact with a service using the Candid web interface, you must specify the appropriate canister identifier.

Because the identifiers are specific to the environment where the canisters are deployed, the files used to store the information are in different directories.
For example, identifiers for a canister deployed locally are located in the project's `+.dfx/local/canister_ids.json+` file.

You can look up the canister identifier for any specific canister by running the `+dfx canister id+` command.
For example, to look up the the canister identifier for the `+lookup+` canister deployed on the local canister execution environment, you could run the following command:

....
dfx canister id lookup
....

To look up the canister identifier for the same canister deployed on the environment specified by the `+ic+` alias, you would run the following command:

....
dfx canister --network=ic id lookup
....

[[add-wallet]]
== Add a wallet for existing canister smart contracts

When you are doing local development, creating a new project automatically creates a default wallet for you to use with the canisters in that project. If you want to add a wallet for projects with canisters that you have previously created, you can force `dfx` to generate one by taking a couple of manual steps.

To add a wallet for use with an existing canister:

. Open a terminal and navigate to your project directory.
. Stop the local canister execution environment, if necessary, by running the following command:
+
[source,bash]
----
dfx stop
----
. Delete the `+.dfx+` directory.
. Start the local canister execution environment network by running the following command:
+
[source,bash]
----
dfx start --clean
----

[[reinstall-canister]]
== Reinstall a canister smart contract

During the development cycle, you might want to install, then replace your program as you debug and improve it.

In this scenario, you might want to keep the canister identifier you have registered but without preserving any of the canister code or state.
For example, your canister might only have test data that you don't want to keep or you might have decided to change the program altogether but want to reinstall under a canister identifier you used to install a previous program. 

To reinstall a canister:

. Open a new terminal and navigate to your project directory.
. Start the local canister execution environment, if necessary.
+
In most cases, this step is only necessary if you are running the canisters locally.
+
If you were registering canisters to run on a remote execution environment, e.g. the {IC} blockchain, you would include the `+--network+` command-line option to perform tasks on the environment specified under this parameter.
. Verify you have canister identifiers for all of the canisters you want to re-deploy.
. Re-deploy all of the canisters by running the following command:
+
[source,bash]
----
dfx canister install --all --mode reinstall
----

Note that you can use the `+reinstall+` mode to replace any canister, regardless of whether the canister has code or state associated with it.

[[set-owner]]
== Set an identity to own a canister smart contract

In most cases, a `+default+` user identity is created for you automatically the first time you run the `+dfx canister create+` command.
This default identity consists of the public and private key pair generated for your local user account. 
Typically, this `+default+` identity is also the default owner of all of the projects you create and all of the canisters you deploy.
You can, however, proactively create and use identities of your choice to circumvent the `+default+` user identity from being used.

As an example, the following scenario illustrates creating a `+registered_owner+` identity that is then used to register, build, deploy, and call the `+pubs+` project.

To set an identity for a project:

. Create a new project by running the following command:
+
[source,bash]
----
dfx new pubs
----
. Change to the project directory by running the following command:
+
[source,bash]
----
cd pubs
----
. Start the local canister execution environment in the background by running the following command:
+
[source,bash]
----
dfx start --background
----
. Create a new `+registered_owner+` identity by running the following command:
+
[source,bash]
----
dfx identity new registered_owner
----
. Set the active user context to use the `+registered_owner+` identity by running the following command:
+
[source,bash]
----
dfx identity use registered_owner
----
. Register, build, and deploy canisters for the project by running the following commands:
+
[source,bash]
----
dfx canister create --all
dfx build --all
dfx canister install --all
----
+
These commands run using the `+registered_owner+` identity, making that user the owner of the canisters deployed.
. Call the `+greet+` function to verify a successful deployment by running the following command:
+
[source,bash]
---- 
dfx canister call pubs greet '("Sam")'
----

[[running-state]]
== Managing the running state of a canister smart contract

After you deploy a canister, it can begin receiving and processing requests from users and from other canisters.
Canisters that are available to send requests and receive replies are considered in be in a **Running** state.

Although canisters are normally placed in the Running state by default, there are cases where you might want to temporarily or permanently stop a canister.
For example, you might want to stop a canister before upgrading it. 
Stopping a canister helps to ensure proper handling of any messages that are in progress and need to either run to completion or be rolled back. 
You might also want to stop a canister to clear its message queue cleanly as a prerequisite to deleting the canister.

// tag::check-status[]
You can check the current status of all canisters or a specified canister by running the `+dfx canister status+` command.
For example, to see the status for all canisters running on the local canister execution environment, you would run the following command:

[source,bash]
----
dfx canister status --all
----

This command returns output similar to the following if canisters are currently running:

....
Canister status_check's status is Running.
Canister status_check_assets's status is Running.
....
// end::check-status[]   

// tag::stop-status[]
You can stop canisters that are currently running by running the `+dfx canister stop+` command.

[source,bash]
----
dfx canister stop --all
----

This command displays output similar to the following:

....
Stopping code for canister status_check, with canister_id 75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
Stopping code for canister status_check_assets, with canister_id cxeji-wacaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
....

If you were to rerun the `+dfx canister status+` command, you might see a status of `+Stopped+` indicating that there were no pending messages that needed to processed or a status of `+Stopping+` indicating that there were messages in-flight that needed to be addressed.
// end::stop-status[]

// tag::restart-status[]
To restart a canister-for example, after a successful canister upgrade—you can run the `+dfx canister start+` command.
For example, to restart all of the canisters, you would run the following command:

[source,bash]
----
dfx canister start --all
----

This command displays output similar to the following:

....
Starting code for canister status_check, with canister_id 75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
Starting code for canister status_check_assets, with canister_id cxeji-wacaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
....
// tag::restart-status[]

[[upgrade-canister]]
== Upgrade a canister smart contract

Unlike a canister reinstall that preserves the canister identifier but no state, a canister upgrade enables you to preserve the state of a deployed canister, and change the code.
 
For example, assume you have a dapp that manages professional profiles and social connections.
If you want to add a new feature to the dapp, you need to be able to update the canister code without losing any of the previously-stored data.
A canister upgrade enables you to update existing canister identifiers with program changes without losing the program state.

NOTE: To preserve state when you are upgrading a canister written in {proglang}, be sure to use the `+stable+` keyword to identify the variables you want to preserve. For more information about preserving variable state in {proglang}, see link:../language-guide/upgrades{outfilesuffix}[Stable variables and upgrade methods].
If you are upgrading a canister written in Rust, you should use `+pre_upgrade+` and `+post_upgrade+` functions as illustrated in the link:https://github.com/dfinity/cdk-rs/blob/master/examples/asset_storage/src/asset_storage_rs/lib.rs[Rust CDK asset storage] example to ensure data is properly preserved after a canister upgrade.

To upgrade a canister:

. Open a new terminal and navigate to your project directory.
. Start the local canister execution environment, if necessary.
+
In most cases, this step is only necessary if you are running the canisters locally.
+
If you were registering canisters to run on a remote execution environment, e.g. the {IC} blockchain, you would include the `+--network+` command-line option to perform tasks on the environment specified under this parameter.
. Verify you have canister identifiers for all of the canisters you want to upgrade.
+
Note that your program must identify the variables for which to maintain state by using the `+stable+` keyword in the variable declaration.
+
For more information about declaring stable variables, see the _{proglang} Programming Language Guide_.
. Upgrade all of the canisters by running the following command:
+
[source,bash]
----
dfx canister install --all --mode upgrade
----

[[delete-canister]]
== Delete a canister smart contract

If you want to permanently delete a specific canister or all canisters for a specific project on a given deployment (either local, or remote), you can do so by running the `+dfx canister delete+` command.

Deleting a canister removes the canister identifier, code, and state.
Before you can delete a canister, however, you must first stop the canister to clear any pending message requests or replies.

To delete all canisters for a project:

. Open a new terminal and navigate to your project directory.
. Start the local canister execution environment, if necessary.
+
In most cases, this step is only necessary if you are running the canisters locally.
+
If you were deleting canisters to run on a remote execution environment, e.g. the {IC} blockchain, you would include the `+--network+` command-line option to perform tasks on the environment specified under this parameter.
. Check the status of the project canisters running on the local canister execution environment by running the following command:
+
[source,bash]
----
dfx canister status --all
----
. Stop all of the project canisters by running the following command:
+
[source,bash]
----
dfx canister stop --all
----
. Delete all of the project canisters by running the following command:
+
[source,bash]
----
dfx canister delete --all
----

== Fork a canister
<TBD - not in this release>

== Set the controller for a canister
<TBD - not in this release>
////
