= ダウンロードセンター
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

{sdk-long-name} をローカルコンピュータのターミナルシェル内から直接ダウンロードすることができます。
このインストール方法では、どのユーザーとしてもログオンすることができ、追加のソフトウェアは必要ありません。

// tag::install_jp[] 
[[install-latest]]
== ターミナルから直接最新版をインストールする

ターミナルシェルからダウンロードしてインストールする場合、以下のような手順となります:

. ローカルコンピューターでターミナルシェルを開きます。
+
例えば、macOSの場合、「アプリケーション」フォルダーを開き、「ユーティリティ」を開いて「*Terminal*」をダブルクリックします。
. `curl`コマンドを実行して、SDKパッケージをダウンロードし、インストールします:
+
[source,bash]
----
sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

[[install-version]]
== ターミナルから特定のバージョンをインストールする

以前のバージョンと比較してテストするときなど、特定のバージョンをインストールしたい場合は、バージョン名を含めたインストールコマンドを実行します。

以下のようにして、ターミナルシェルから特定のバージョンをダウンロードしてインストールすることができます:

. ローカルコンピューターでターミナルシェルを開きます。

. 環境変数である `DFX_VERSION` に、`+curl+` コマンドのプレフィックスとしてインストールしたい {sdk-short-name} パッケージのバージョンを設定します。
+
例えば、バージョン 0.9.0 をインストールするには、以下のコマンドを実行します:
+
[source,bash]
----
DFX_VERSION=0.9.0 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

NOTE: 環境変数 DFX_VERSION を使用して、まだ一般に公開されていないバージョンの {sdk-short-name} をインストールしている場合は、変更点の概要についてこの link:http-middleware{outfilesuffix}[記事]を参照してください。

// end::install_jp[]   

== 次のステップ

次のステップのためのさらなる情報については、link:developers-guide/sdk-guide{outfilesuffix}[_SDK Developer Tools_] の link:developers-guide/tutorials-intro{outfilesuffix}[チュートリアル]を参照してください.

コードを書き始める前に {IC} のプログラムを書くことについて詳しく知りたい方は、link:developers-guide/concepts/concepts-intro{outfilesuffix}[概念] をご覧ください。

{proglang} を使って {IC} のプログラムを書く方法については、link:language-guide/motoko{outfilesuffix}[_Motoko Programming Language Guide_] を参照してください。

////
= Download center
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

Currently, you can download the {sdk-long-name} directly from within a terminal shell on your local computer.
With this installation option, you can be logged on as any user and no additional software is required.

// tag::install[] 
[[install-latest]]
== Install the latest directly from a terminal

To download and install from a terminal shell:

. Open a terminal shell on your local computer.
+
For example, on macOS open the Applications folder, then open Utilities and double-click *Terminal*.

. Download and install the SDK package by running the following `curl` command:
+
[source,bash]
----
sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

[[install-version]]
== Install a specific version from a terminal

If you want to install a specific version, for example, to test against a previous version, you can modify the installation command to include a version.

To download and install a specific version from a terminal shell:

. Open a terminal shell on your local computer.

. Set the `DFX_VERSION` environment variable to the version of the {sdk-short-name} package you want to install as a prefix to `+curl+` command.
+
For example, to install version 0.9.0, you would run the following command:
+
[source,bash]
----
DFX_VERSION=0.9.0 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

NOTE: If you are using the DFX_VERSION environment variable to install a version of the {sdk-short-name} not yet publicly available, see this link:http-middleware{outfilesuffix}[article] for an overview of what's changed. 

// end::install[]   

== Next steps

For information about the next steps to take, see link:developers-guide/tutorials-intro{outfilesuffix}[Tutorials] in the link:developers-guide/sdk-guide{outfilesuffix}[_SDK Developer Tools_].

To learn more about writing programs for the {IC} before you start experimenting with code, see link:developers-guide/concepts/concepts-intro{outfilesuffix}[Concepts].

For information about writing programs for the {IC} using {proglang}, see the link:language-guide/motoko{outfilesuffix}[_Motoko Programming Language Guide_].
////

////
== Download a packaged release

[width="100%",cols=3*,"35%,30%,35%",options="header",]
|===
|Version |Tag |Documentation and supported platforms
|SDK 0.5.2 (February 2020) |sdk-0.5.2-RELEASE |Release notes / changelog
+
Supported platforms

|SDK 0.5.4 (March 2020) |sdk-0.5.4-RELEASE |Release notes / changelog
+ Supported platforms
|===

== Use a package manager

[source,bash]
----
npm install dfx
----

[source,bash]
----
brew install dfx
----
////