= Download center
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

Currently, you can download the {sdk-long-name} directly from within a terminal shell on your local computer.
With this installation option, you can be logged on as any user and no additional software is required.

== Install the latest directly from a terminal

To download and install from a terminal shell:

. Open a terminal shell on your local computer.

. Run the following `+curl+` command:
+
[source,bash]
----
sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

== Install a specific version from a terminal

If you want to install a specific version, for example, to test against a previous version, you can modify the installation command to include a version.

To download and install a specific version from a terminal shell:

. Open a terminal shell on your local computer.

. Run the following `+curl+` command:
+
[source,bash]
----
DFX_VERSION=0.5.5 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

== Next steps

For information about the next steps to take, see link:developers-guide/tutorials-intro{outfilesuffix}[Tutorials] in the link:developers-guide/sdk-guide{outfilesuffix}[_SDK Developer Tools_].

To learn more about writing programs for the {IC} before you start experimenting with code, see link:developers-guide/introduction-key-concepts{outfilesuffix}[Introduction and key concepts] in the link:developers-guide/sdk-guide{outfilesuffix}[_SDK Developer Tools_].

For information about writing programs for the {IC} using {proglang}, see the link:language-guide/motoko{outfilesuffix}[_Motoko Programming Language Guide_].

////
== Download a packaged release

[width="100%",cols=3*,"35%,30%,35%",options="header",]
|===
|Version |Tag |Documentation and supported platforms
|SDK 0.5.2 (February 2020) |sdk-0.5.2-RELEASE |Release notes / changelog
+
Supported platforms

|SDK 0.5.4 (March 2020) |sdk-0.5.4-RELEASE |Release notes / changelog
+ Supported platforms
|===

== Use a package manager

[source,bash]
----
npm install dfx
----

[source,bash]
----
brew install dfx
----
////