= Download center
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

Currently, you can download the {sdk-long-name} directly from within a terminal shell on your local computer.
With this installation option, you can be logged on as any user and no additional software is required.

// tag::install[] 
[[install-latest]]
== Install the latest directly from a terminal

To download and install from a terminal shell:

. Open a terminal shell on your local computer.
+
For example, on macOS open the Applications folder, then open Utilities and double-click *Terminal*.

. Download and install the SDK package by running the following `curl` command:
+
[source,bash]
----
sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

[[install-version]]
== Install a specific version from a terminal

If you want to install a specific version, for example, to test against a previous version, you can modify the installation command to include a version.

To download and install a specific version from a terminal shell:

. Open a terminal shell on your local computer.

. Set the `DFX_VERSION` environment variable to the version of the {sdk-short-name} package you want to install as a prefix to `+curl+` command.
+
For example, to install version 0.7.2, you would run the following command:
+
[source,bash]
----
DFX_VERSION=0.7.2 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

NOTE: If you are using the DFX_VERSION environment variable to install a version of the {sdk-short-name} not yet publicly available, see this link:http-middleware{outfilesuffix}[article] for an overview of what's changed. 

// end::install[]   

== Next steps

For information about the next steps to take, see link:developers-guide/tutorials-intro{outfilesuffix}[Tutorials] in the link:developers-guide/sdk-guide{outfilesuffix}[_SDK Developer Tools_].

To learn more about writing programs for the {IC} before you start experimenting with code, see link:developers-guide/concepts/concepts-intro{outfilesuffix}[Concepts].

For information about writing programs for the {IC} using {proglang}, see the link:language-guide/motoko{outfilesuffix}[_Motoko Programming Language Guide_].

////
== Download a packaged release

[width="100%",cols=3*,"35%,30%,35%",options="header",]
|===
|Version |Tag |Documentation and supported platforms
|SDK 0.5.2 (February 2020) |sdk-0.5.2-RELEASE |Release notes / changelog
+
Supported platforms

|SDK 0.5.4 (March 2020) |sdk-0.5.4-RELEASE |Release notes / changelog
+ Supported platforms
|===

== Use a package manager

[source,bash]
----
npm install dfx
----

[source,bash]
----
brew install dfx
----
////