= HTTP リクエストの処理とアセットの提供に関する新しいアプローチの紹介 
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

{sdk-short-name} の 0.7.0（またはそれ以降）のバージョンをインストールしている方は、それらのバージョンで HTTP クエリやフロントエンドのアセットの処理にいくつかの大きな改善が行なわれていることにお気づきかもしれません。
これらの変更が {sdk-short-name} の次のパブリックリリースに正式に組み込まれると、{IC} 上でのアプリケーションのビルドとデプロイの方法が変わるでしょう。

新しいプロジェクトを作成する場合、基盤となるアーキテクチャの変更は、開発ワークフローにほとんど影響を与えません。むしろ、{IC} 上で動作するアプリケーションを構築する上で、新しいアーキテクチャの方が馴染みやすいと感じるかもしれません。

ただし、既存のプロジェクトがある場合は、新アーキテクチャへの移行を考える必要があります。
新アーキテクチャへの移行はすぐに行う必要はありませんが、プロジェクトを更新することで、フロントエンドのアセットのアップロードと管理が圧倒的に容易になった変更の恩恵を受けることができます。

== Bootstrap コードの置き換え： 要約

新しいアーキテクチャを説明する前に、置き換えようとしている従来のアプローチと、これまでのコードがどのように機能していたかについての背景を知っておくとよいでしょう。
以前は、{IC} のフロントエンドを開発するには、フロントエンドのアセット Canister に `retrieve()` という関数を追加する必要がありました。
`retrieve()` 関数は、パスを受け取り、blob を返します。`retrieve()` 関数が返す blob には、`index.js` というファイルがあり、`bootstrap` コードと呼ばれる JavaScript と 静的な HTML が含まれていました。
スマートコントラクトとしてのアプリケーション、すなわち link:developers-guide/glossary{outfilesuffix}#g-canister[Canister] を {IC} にデプロイした後、`<CANISTER_ID>.ic0.app` の URL を用いて Canister にアクセスすると、`bootstrap` コードが実行され、次のようなステップが実行されていました：

* 秘密鍵を格納するセキュアな Web Worker を作成。
* 実行中のアプリケーションが {IC} と通信できる仕組みを提供するため、`window.ic` をポリフィル化。
* Canister の `retrieve()` メソッドから `index.js` をパスとして呼び出し、評価。
* ドキュメントオブジェクトモデル（DOM）とページの制御を Canister の JavaScript コードに渡す。

この `bootstrap` のワークフローは、通常のウェブアプリケーションの構築方法とはかなり異なります。
例えば、このアプローチでは、HTML を直接ロードしたり、PNG ファイルのようなアセットをダウンロードすることをサポートしていませんでした。
アセットを扱うには、別のドメイン（例えば、AWS のバケット）からアセットを読み込むか、JavaScript でアセットを読み込み、データ URI に変換し、`src` 属性を設定する必要がありました。
この方法でアセットを処理すると、ブラウザ上で次のような問題が発生していました：

* ページの再レイアウトを待たない。
* アセットの読み込みが保留される。
* 帯域外で JavaScript を実行する。

`bootstrap` 方式は、セキュリティや分散性の面で利点がありましたが、フロントエンドの開発者やアプリケーションのユーザーが望まない、貧弱な HTTP やアセットの処理によって、そのメリットが相殺されていました。

過去 1 年間に渡って、{sdk-short-name} チームは、開発者コミュニティからのフィードバックを収集し、評価してきました。その結果、同等のセキュリティモデルを提供しつつ、より柔軟な開発環境を提供することを決定しました。

== Canister が HTTP リクエストに応答できるようにする

さまざまな案のメリットとデメリットを検討した結果、開発チームは Canister が HTTP リクエストに直接応答できるようなアーキテクチャを採用することを決定しました。
{sdk-short-name} は、この新しいアプローチによって HTTP ミドルウェアサーバを実装しています。

HTTP ミドルウェアサーバは、HTTP リクエストに対する処理を以下のように行います：

* HTTP リクエストを受信し、そのメソッド、URI、ヘッダ、ボディを Candid 構造に変換する。
* リクエストの Canister ID を解決する。
* Canister と通信するためのエージェントをインスタンス化する。
* `http_request()` のクエリメソッドを呼び出す。

Canister が `http_request()` メソッドを実装している場合、HTTP ミドルウェアはレスポンスをデコードし、ヘッダーとボディを受け取り、HTTP レスポンスを構築します。
Canister が `http_request()` メソッドを実装していない場合、後方互換性のため、ミドルウェアは警告として非推奨を指摘しつつ bootstrap ポリフィルを返します。
処理中にエラーが発生した場合、HTTP ミドルウェアは以下のエラーコードを返します：

* 400 Bad Request：不正なリクエスト（HTTP ミドルウェアが Canister ID を見つけられなかったり、デコードできなかった場合など）。
* 500 Internal Server Error：HTTP　ミドルウェア自身のエラー（例えば、レプリカに接続できなかった場合など）。
* 502 Bad Gateway：レプリカ自身からのエラー（Canister のトラッピングを含む）。

これらのエラーが発生した場合、`dfx` コマンドラインインターフェースは、レスポンスボディに詳細を追加します。

== アセットストレージ Canister の再考

この移行を容易にするために、新しいバージョンの `dfx` でビルドされた新規および既存のプロジェクトには、 `http_request()` メソッドをサポートしている改良されたアセット Canister がデフォルトで含まれています。これは、画像などのバイナリアセットを含むアップロードされたアセットが、その URL を使ってブラウザから直接利用できるようになることを意味します。
例えば、新しいプロジェクトでは、`https://<CANISTER_ID>.raw.ic0.app/sample-asset.txt` というファイルがアップロードされ、{IC} に公開された後に利用できるようになります。

将来的には、アセット Casniter のキャッシュ管理、デフォルトのアセットの取り扱い、HTTP に特化した機能の提供などのサポートも追加していく予定です。

== ルーティング

`/api` （レプリカ用）と `/_` （ツール用）のルートは、HTTP リクエストの仕様で予約されています。
それ以外のルートは、アプリケーション内で必要に応じて使用することができ、別途ハッシュルーターに頼る必要はありません。

== DFX の新規プロジェクトの構成

既存のプロジェクトを移行する方法に入る前に、新しいプロジェクトを見てみましょう。
フロントエンドの変更点は以下の通りです：

* `dfx.json` でアセット Canister 用の `frontend` キーを指定します。アセット Canister は JavaScript のエントリーポイントである `index.js` の代わりに `index.html` ファイルを指すようになりました。
* `package.json` ファイルは、デフォルトで Webpack 5 をサポートするようになりました。
* `webpack.config.js` ファイルは、`frontend` キーを持つ各 Canister に対し、Canister のインポートのリストを生成しますが、その方法が変わりました。
* `src/<プロジェクト名>_assets/src/index.html` ファイルは新しいテンプレートファイルであり、フロントエンド用に作成したご自身の `index.html` ファイルに置き換えることができます。ファイルが見つからない場合には、アセット Canister によってデフォルトで生成されます。
* `index.js` ファイルは、エージェントや Actor の作成をサポートするように変更されました。

== エージェントと Actor の作成

新しいアーキテクチャでは、エージェントのインスタンスを明示的に作成してから、Canister に使用する Actor を作成します。
これは、`index.js` ファイルにおいて、`dfx` で生成されたファイルからの `import` が以前は1つだったのに対し、現在は2つになったことを意味します。

例えば、プロジェクトの新しい `index.js` ファイルは、以下のようなコードとなります：

....
import { Actor, HttpAgent } from '@dfinity/agent';
import { idlFactory as example_idl, canisterId as example_id } from 'dfx-generated/example';
 
const agent = new HttpAgent();
const example = Actor.createActor(example_idl, { agent, canisterId: example_id });
....

以上の例のようにエージェントと Actor を明示的に作成することは、以下のような理由で優れています：

* 第1に、エージェント自体はアプリケーションによって完全に設定可能であり、Actor も同様です。例えば、認証の設定はエージェントのインスタンスが作成されるときにしかできないので、ユーザーの ID を管理したい場合は、エージェントを作成する前に行う必要があります。
* 第2に、エージェントと Actor の作成を明示的に行うことで、これらのオブジェクトをインスタンス化する際に、より多くのコントロールを行うことができます。React フックや Angular のサービスで Actor を作成したい場合、このアプローチにより簡単に実行することができます。

== 既存のプロジェクトを移行する

既存のプロジェクトがある場合、{sdk-short-name} をアップデートしても、シームレスに動作しない可能性があります。
残念ながら、このような場合、直接移行することはできません。
現在のフロントエンドを移行するための最良の方法は、新しいプロジェクトを作成し、コードを新しい構造に合わせて手動で移動させることです。

=== 認証されたフロントエンドアセットと認証されていないアセット

{IC} メインネットのベータ版の開始に伴い、フロントエンドアセットを提供するすべてのプロジェクトは、新しい HTTP クエリアーキテクチャを使用します。
また、{IC} の開始に伴い、フロントエンドアセットを、証明済で安全とみなせるように署名された認証データとしてか、あるいは認証されていない生のデータとして提供する、新たな機能が導入されました。
認証プロセスを経ていないフロントエンドアセットは、`+raw.ic0.app+` という URL サフィックスを使って提供されます。
認証されたフロントエンドアセットは、`+.ic0.app+`というURLサフィックスを使用します。

現在の全てのチュートリアルは、認証されていないフロントエンドアセットを提供するアプリケーションについて説明しています。
認証されたクエリ結果をフロントエンドアセットに使用するアプリケーションを構築する方法については、高度な開発トピックです。
クエリに応答して認証されたデータを返す方法については、link:interface-spec/index{outfilesuffix}[インターフェースの仕様]を参照してください。また、link:https://forum.dfinity.org/[DFINITY Developer Forum]を通じて他の開発者と交流してください。

////
= Introducing a new approach to handling HTTP requests and serving assets 
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

If you are installing any 0.7.0 (or later) version of the {sdk-short-name}, you might have noticed that those versions have introduced some major improvements for handling HTTP queries and front-end assets.
When these changes are officially rolled into the next publicly-available release of the {sdk-short-name}, they will change how you build and deploy applications on the Internet Computer.

If you are creating new projects, the changes to the underlying architecture will have little, if any, effect on your development workflow. In fact, you might find that the new architecture makes building applications that run on the {IC} a more familiar experience. 

If you have any existing projects, however, you’ll need to plan for a one-time migration to the new architecture. 
Migration to the new architecture doesn’t have to be completed immediately, but updating your projects to take advantage of the changes will ultimately make it easier to upload and manage front-end assets.

== Replacing the bootstrap code: a recap

Before we describe the new architecture, it’s useful to have some context about the old approach that we are replacing and how the code has worked up to this point. 
Previously, developing a front-end on the Internet Computer involved adding a front-end assets canister with a `retrieve()` function. 
The `retrieve()` function would take a path and return a blob. The blob returned by the `retrieve()` function would then have an `index.js` file that contained some JavaScript and static HTML called the `bootstrap` code. 
After you deployed an application as smart contract—called a link:developers-guide/glossary{outfilesuffix}#g-canister[canister]—on the Internet Computer, accessing the canister using the `<CANISTER_ID>.ic0.app` URL executed the `bootstrap` code, which in turn, performed the following steps:

* Created a secure worker to contain your private key.
* Polyfilled the `window.ic` to provide some mechanics to the running application so that it can communicate with the Internet Computer.
* Called the canister’s `retrieve()` method with `index.js` as the path, and evaluate it.
* Passed control of the document object model (DOM) and the page to the canister’s JavaScript code.

This `bootstrap` workflow is quite different from how people usually build web applications. 
For example, this approach did not support loading HTML directly or downloading assets like PNG files. 
Asset handling required either loading the assets from another domain (for example, an AWS bucket) or loading the assets in JavaScript, transforming them into data URI, then setting the `src` attribute accordingly.
Handling assets in this way led to problems in the browser, such as:

* Not waiting for re-layout of pages.
* Deferred loading of assets.
* Executing JavaScript out of band.

The `bootstrap` approach provided advantages in terms of security and decentralization, but those advantages were offset by the poor HTTP and asset handling that front-end developers and application users didn't expect to experience.

Over the last year, the {sdk-short-name} team has been gathering and evaluating feedback from the developer community. Based on that feedback, the team has decided to provide a more flexible developer experience while continuing to provide an equivalent security model.

== Enabling canisters to respond to HTTP requests

After considering the advantages and disadvantages of different  proposals, the team decided on an architecture that would allow canisters to answer HTTP requests directly.
With this new approach, the {sdk-short-name} implements an HTTP middleware server.

The HTTP middleware server handles the processing for the HTTP request by doing the following:

* Receiving the HTTP request and converting its method, uri, headers and body into a Candid structure.
* Resolving the canister identifier for the request.
* Instantiating an agent to talk to the canister.
* Calling an `http_request()` query method.

If the canister implements the `http_request()` method, the HTTP middleware decodes the response, takes the headers and body, and constructs an HTTP response.
If the canister does not implement the `http_request()` method, for backward compatibility, the middleware returns a bootstrap polyfill that points out the deprecation as a warning.
For any errors in the process, the HTTP middleware returns the following error codes:

* 400 Bad Request for any invalid requests (for example, if the HTTP middleware could not find or decode a canister ID).
* 500 Internal Server Error for errors from the HTTP middleware itself (for example, if it could not connect to a replica)
* 502 Bad Gateway if an error is coming from the replica itself (including canister trapping).

If any of these errors occur,  the `dfx` command-line interface provides additional details in the response body.

== Revisiting the asset storage canister

To make this transition easier, new and existing projects built with the newer version of `dfx` will include an improved asset canister that supports the `http_request()` method by default. This means that assets you upload—including binary assets like images—will be available directly from your browser using their URL.
For example, in a new project, the `sample-asset.txt` file would be uploaded and available after publishing to the Internet Computer at https://<CANISTER_ID>.raw.ic0.app/sample-asset.txt.

In the future, we will also provide additional support for managing the asset canister cache, handling default assets, and providing HTTP-specific features.

== Routing

Both the `/api` (for replicas) and `/_` (for tool purposes) routes are reserved by the HTTP request specification. 
All other routes are available for you to use as needed within your application, eliminating the need to rely on a separate hash router.

== Structure of a new DFX project

Before going into how to migrate an existing project, let’s take a look at a new project. 
The front-end changes include the following:

* The `dfx.json` includes a `frontend` key for the asset canister that now points to an `index.html` file instead of the `index.js` JavaScript entry point.
* The `package.json` file now supports Webpack 5 by default.
* The `webpack.config.js` file now generates the list of canister imports for for each canister that has a `frontend` key in a different way.
* The `src/<project_name>_assets/src/index.html` file is a new template file that you can replace with your own `index.html` file for your front-end. It is served by default by the asset canister when a file isn’t found.
* The `index.js` file has been modified to support agent and actor creation.

== Agent and actor creation

With the new architecture, we explicitly create an agent instance, then create the actor that we’ll use for our canister.
In the `index.js` file, this means that where before there was only one `import` from files generated by `dfx`, now there are two.

For example, the new `index.js` file in a project provides code similar to this:

....
import { Actor, HttpAgent } from '@dfinity/agent';
import { idlFactory as example_idl, canisterId as example_id } from 'dfx-generated/example';
 
const agent = new HttpAgent();
const example = Actor.createActor(example_idl, { agent, canisterId: example_id });
....

Explicitly creating the agent and actor like this example illustrates is better for a couple reasons:

* First, the agent itself is entirely configurable by the application, and so is the actor. For example, authentication can only be set when the agent is constructed, so if you want to manage a user identity, you’ll need to do it before creating the agent.
* Second, being explicit about creating the agent and actor gives you much more control over when you instantiate those objects. If you want a React hook or an Angular service to create the actor, this approach allows you to do so easily.

== Migrating an existing project

If you have an existing project, chances are it will not work seamlessly after you update the {sdk-short-name}. 
Unfortunately, a direct migration path isn’t possible in this case. 
The best way to migrate your current front-end is to create a new project and move your code manually to the new structure.

=== Certified and uncertified front-end assets

With the launch of the {IC} main network Beta, all projects serve front-end assets use the new HTTP query architecture. 
In addition, the {IC} launch introduces a new capability to serve front-end assets as certified data that has been signed and can be considered authenticated and secure or as raw, uncertified data.
Front-end assets that don't go through the certification process are served using the `+raw.ic0.app+` URL suffix.
Certified front-end assets use the `+.ic0.app+` URL suffix.

All of the current tutorials illustrate applications that serve uncertified front-end assets. 
Learning how to build an application that uses certified query results for front-end assets is an advanced development topic.
For information about how to return certified data in response to queries, see the link:interface-spec/index{outfilesuffix}[Interface specification] and connect with other developers through the link:https://forum.dfinity.org/[DFINITY Developer Forum].
////