= Sample code, applications, and microservices

Sample code, applications, and microservices developed by DFINITY and contributed by the community will soon be available from the DFINITY website and DFINITY public Git repository.
By accessing the website or the public repository, you will be able to directly download, clone, fork, or share sample projects.
You will also be able to contribute your own project or suggest updates to published projects using the standard Git work flow. 

Sample projects provide a way for you to experiment and collaborate with other developers.
The projects and sample code are not, however, intended to be used as commercial applications and do not provide any explicit or implied support or warranty of any kind.

Because updates to the website and public repository are still forthcoming, no sample projects are currently available for direct download access yet. 
In the meantime, this section provides a preliminary look at some sample code for applications and microservices that you can copy and modify to jump-start your own projects.
When the DFINITY website and public repository host these projects, the section will provide direct links to the published sample applications and microservices.
