= ビデオとチュートリアル
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

基礎ビデオシリーズでは、{IC} 用のアプリケーションを構築する方法を紹介しています。

== {IC} で構築する: 基礎

基礎ビデオシリーズは、{IC} 用のアプリケーションを構築する方法を紹介しています。
このシリーズは、10 のビデオで構成されています。
ほとんどのビデオは3分から5分程度ですが、プログラミング言語 {proglang} やフロントエンドの開発、それら全てを組み合わせたサンプルアプリケーションの構築など、より深い技術的な内容も含まれています。

++++
<h1></h1>
<br>
++++

video::jduSMHxdYD8[youtube,width=100%,height=480px]

=== {IC} とは何か。なぜ {IC} でアプリを作るのか？

このビデオでは、{IC} についての基礎入門と、{IC} がオープンインターネットサービスの将来をどのようにサポートするかを説明しています。
このビデオを見た後、さらに詳しく学びたい方は、link:developers-guide/concepts/what-is-IC{outfilesuffix}[Internet Computer とは？]をご覧ください。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::TXf87GTXO78[youtube,width=100%,height=480px]

=== 開発者体験をシンプルに

{IC} は、エコシステムの複雑さを軽減することで、アプリケーションの構築を容易にします。
このビデオを見た後、さらに詳しく学びたい方は link:developers-guide/concepts/what-is-IC{outfilesuffix}#next-gen[次世代のソフトウェアとサービスの構築] をご覧ください。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::60uHQfoA8Dk[youtube,width=100%,height=480px]

=== DFINITY Canister SDK とは？

Canister とはなんだろう、と思っていますか？ 何から始めたらいいかわからないですか？ このビデオでは、{IC} 上で動作するプログラムを開発するための鍵となるツールを紹介します。

始める準備ができたら、link:download{outfilesuffix}[ダウンロードセンター] をご覧ください。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::yqIoiyuGYNA[youtube,width=100%,height=480px]

=== はじめてのアプリケーションをデプロイする

このビデオでは、{IC} をローカル実行して最初のアプリケーションをデプロイする方法を説明します。
自分で挑戦するには、link:quickstart/local-quickstart{outfilesuffix}[クイックスタート] チュートリアルの手順に従ってください。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::QbeP4xuPUp0[youtube,width=100%,height=480px]

=== Motoko の紹介: {IC} のために設計されたプログラミング言語

このビデオでは、プログラミング言語 Motoko の概要と、{IC} 上で動作するアプリケーションの開発に適したいくつかの特徴を紹介します。

{proglang} を使った開発についてさらに詳しく学びたい方は、link:language-guide/motoko{outfilesuffix}[{proglang} プログラミング言語] のガイドをご覧ください。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::jWf1zY6o5xM[youtube,width=100%,height=480px]

=== フロントエンドの統合

このビデオでは、生の JavaScript、React（と TypeScript）を使ってフロントエンドのユーザーインターフェースを統合する方法を紹介しています。

ビデオを見た後、link:developers-guide/tutorials/my-contacts{outfilesuffix}[スタイルシートの追加] の手順に従って手を動かすことで、Reactを使用する際にスタイルシートを追加する方法を学ぶことができます。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::O2KaWRtsqHg[youtube,width=100%,height=480px]

=== アプリケーションインターフェースの共通言語となる Candid  

このビデオでは、{IC} 上で動作するサービスと対話するための共通のインターフェース記述言語（IDL）である Candid について説明しています。

Candid の使い方とより詳細な情報については、link:candid-guide/candid-intro{outfilesuffix}[Candid] のガイドか link:https://crates.io/crates/candid[Candid on crates.io] をご覧ください。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::UAlqO66Tweg[youtube,width=100%,height=480px]

=== 開発者のエコシステムに飛び込む

このビデオでは、{proglang} を使用したプログラムを開発するための追加ツールやリソースを紹介します。

コミュニティへの貢献を開始するには、link:https://github.com/dfinity/motoko-base[Motoko base library] をご覧ください。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::GzkRsbqPaA0[youtube,width=100%,height=480px]

=== マルチプレイヤーゲームの構築

このビデオでは、{IC} 上で動作するマルチプレイヤーのリバーシゲームを紹介し、{IC} 向けのアプリケーションを構築する際に必要な多くのキーコンセプトを示しています。

どのようにゲームが作られたかの詳細は、link:https://ninegua.github.io/reversi/[Building a Multiplayer Reversi Game on the Internet Computer] か、 link:https://github.com/ninegua/reversi[Reversi] リポジトリのソースコードをご覧ください。

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::G6vUrC9lues[youtube,width=100%,height=480px]

=== {IC} の開発者コミュニティに参加する

このビデオでは、利用可能なリソースや参加方法についてまとめています。

さらに詳しく知りたい方は、link:https://github.com/dfinity/examples[examples] のサンプルアプリケーションや、link:https://github.com/dfinity/awesome-dfinity[awesome-dfinity] リポジトリをご覧ください。

議論に参加するには、link:https://forum.dfinity.org/[Developer Forum] に参加するか、ツイッターで link:https://twitter.com/dfinitydev[@dfinitydev] をフォローしてください。

++++
<h1></h1>
<br>
<hr>
<br>
++++

== チュートリアル

link:quickstart/quickstart-intro{outfilesuffix}[クイックスタート] では、プロジェクトディレクトリの内容やサンプルコードを調べずに、新しいプロジェクトを作成してデプロイするための基本的なワークフローを簡単に紹介しています。

{IC} 上で動作するプログラムをハンズオンで作成したい方は、以下のチュートリアルをご覧ください。

* link:developers-guide/tutorials/explore-templates{outfilesuffix}[デフォルトプロジェクトの探索]

* link:developers-guide/tutorials/define-an-actor{outfilesuffix}[Actor を用いたクエリ]

* link:developers-guide/tutorials/hello-location{outfilesuffix}[ターミナルでテキストの引数を渡す]

* link:developers-guide/tutorials/counter-tutorial{outfilesuffix}[自然数をインクリメントする]

* link:developers-guide/tutorials/calculator{outfilesuffix}[計算用関数で整数を使う]

* link:developers-guide/tutorials/phonebook{outfilesuffix}[ライブラリモジュールをインポートする]

* link:developers-guide/tutorials/multiple-actors{outfilesuffix}[複数の Actor を使う]

* link:developers-guide/tutorials/custom-frontend{outfilesuffix}[フロントエンドをカスタマイズする]

* link:developers-guide/tutorials/my-contacts{outfilesuffix}[スタイルシートを追加する]

* link:developers-guide/tutorials/intercanister-calls{outfilesuffix}[インターキャニスターコールを行う]

* link:developers-guide/tutorials/scalability-cancan{outfilesuffix}[スケールするアプリケーションを作る]

* link:developers-guide/tutorials/access-control{outfilesuffix}[ID を用いたアクセス制御を追加する]

////
= Videos and tutorials
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

The Fundamentals video series provides an introduction to building applications for the Internet Computer.

== Building on the {IC}: Fundamentals

The Fundamentals video series provides an introduction to building applications for the Internet Computer.
The series consists of ten video segments. 
Most of the segments have a running time of three to five minutes, but there are also deeper technical dives that explore the {proglang} programming language, front-end development, and how all of the pieces come together in a sample application.

++++
<h1></h1>
<br>
++++

video::jduSMHxdYD8[youtube,width=100%,height=480px]

=== What is the {IC} and why build apps for it?

This segment of the Fundamentals video series provides a basic introduction to the {IC} and how it supports the future of open internet services. 

If you want to learn more after watching the video, check out link:developers-guide/concepts/what-is-IC{outfilesuffix}[What is the Internet Computer?].

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::TXf87GTXO78[youtube,width=100%,height=480px]

=== Simplifying the developer experience

The {IC} makes it easier to build applications by reducing the ecosystem complexity. 

If you want to learn more after watching the video, check out link:developers-guide/concepts/what-is-IC{outfilesuffix}#next-gen[Building the next generation of software and services].

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::60uHQfoA8Dk[youtube,width=100%,height=480px]

=== What is the DFINITY Canister SDK?

Wondering what a "canister" is? Not sure where to start? This video segment introduces the key tools for developing programs that run on the {IC}.

If you are ready to get started, visit the link:download{outfilesuffix}[Download center].

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::yqIoiyuGYNA[youtube,width=100%,height=480px]

=== Deploying your first application

This video segment walks through how to deploy your first application with the {IC} running locally.

To try it yourself, follow the steps in the link:quickstart/local-quickstart{outfilesuffix}[Quick start] tutorial.

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::QbeP4xuPUp0[youtube,width=100%,height=480px]

=== Introducing Motoko: A language designed for the {IC}

This video segment offers an overview of the Motoko programming language and highlights a few key features that make it especially well-suited for writing applications that run on the {IC}.

If you want to learn more about using {proglang}, see the link:language-guide/motoko{outfilesuffix}[{proglang} Programming Language] guide.

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::jWf1zY6o5xM[youtube,width=100%,height=480px]

=== Integrating a front end

This video segment demonstrates how to integrate a front-end user interface using raw JavaScript, React, and React with TypeScript.

After watching the video, you can experiment on your own or follow the steps in link:developers-guide/tutorials/my-contacts{outfilesuffix}[Add a stylesheet] to learn how to add a stylesheet when using React.

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::O2KaWRtsqHg[youtube,width=100%,height=480px]

=== How Candid provides a common language for application interfaces

This video segment describes how Candid provides a common interface description language (IDL) for interacting with services running on the Internet Computer.

For more complete information about what Candid is and how to use it, see the link:candid-guide/candid-intro{outfilesuffix}[Candid] guide or link:https://crates.io/crates/candid[Candid on crates.io].

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::UAlqO66Tweg[youtube,width=100%,height=480px]

=== Diving into the developer ecosystem

This video segment highlights additional tools and resources available for developing programs using {proglang}.

To start contributing to the community, take a look at the link:https://github.com/dfinity/motoko-base[Motoko base library].

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::GzkRsbqPaA0[youtube,width=100%,height=480px]

===  Building a multiplayer game

This video segment showcases a multiple-player Reversi game built to run on the {IC} and demonstrates many key concepts involved in building applications for the {IC}.

For a closer look at how the game was made, see link:https://ninegua.github.io/reversi/[Building a Multiplayer Reversi Game on the Internet Computer] or check out the source code in the link:https://github.com/ninegua/reversi[Reversi] repository.

++++
<h1></h1>
<br>
<hr>
<br>
++++

video::G6vUrC9lues[youtube,width=100%,height=480px]

===  Join the {IC} developer community

This video segment summarizes the resources available and how you can get involved. 

For further inspiration, check out the sample applications in the link:https://github.com/dfinity/examples[examples] or link:https://github.com/dfinity/awesome-dfinity[awesome-dfinity] repositories. 
To be part of the conversation, join the  link:https://forum.dfinity.org/[Developer Forum] or follow link:https://twitter.com/dfinitydev[@dfinitydev] on Twitter.

++++
<h1></h1>
<br>
<hr>
<br>
++++

== Tutorials

The link:quickstart/quickstart-intro{outfilesuffix}[Quick start] provides a simplified introduction to the basic work flow for creating and deploying a new project without exploring the contents of the project directory or sample code.

If you want more hands-on experience creating programs that run on the {IC}, check out these tutorials:

* link:developers-guide/tutorials/explore-templates{outfilesuffix}[Explore the default project]

* link:developers-guide/tutorials/define-an-actor{outfilesuffix}[Query using an actor]

* link:developers-guide/tutorials/hello-location{outfilesuffix}[Pass text arguments in a terminal]

* link:developers-guide/tutorials/counter-tutorial{outfilesuffix}[Increment a natural number]

* link:developers-guide/tutorials/calculator{outfilesuffix}[Use integers in calculator functions]

* link:developers-guide/tutorials/phonebook{outfilesuffix}[Import library modules]

* link:developers-guide/tutorials/multiple-actors{outfilesuffix}[Use multiple actors]

* link:developers-guide/tutorials/custom-frontend{outfilesuffix}[Customize the front-end]

* link:developers-guide/tutorials/my-contacts{outfilesuffix}[Add a stylesheet]

* link:developers-guide/tutorials/intercanister-calls{outfilesuffix}[Make inter-canister calls]

* link:developers-guide/tutorials/scalability-cancan{outfilesuffix}[Create scalable apps]

* link:developers-guide/tutorials/access-control{outfilesuffix}[Add access control with identities]
////