= Decentralized data centers
:keywords: Internet Computer,blockchain,protocol,replica,subnet,data center,canister,developer
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK

* A *network* that runs the protocol to provide computing capacity—for example, the hardware, CPU, and memory required to run programs—through *independent data centers*.
* A *globally-accessible and scalable platform* for running software applications.

The {IC} is not physical hardware that exists in any physical location. 
Instead, the {IC} combines computing resources provided by independent data centers around the world to give users and organizations secure access to applications and transaction processing services. 

Unlike a public or private cloud, the {IC} is not owned and operated by a single private company. 
Instead, the {IC} is a public utility with updates and operations that are managed through a decentralized governance system defined in the protocol.
Its architecture enables multiple computers to operate like one, very powerful, virtual machine.

The computers that make up the virtual machine are organized into sub-networks of data centers around the globe. 
The distributed architecture enables secure communication without firewalls or technologies that are vulnerable to attack.
Independent data centers receive remuneration for contributing computing capacity and hosting services to support applications running on the {platform}.
