= Tokens and cycles
:keywords: Internet Computer,blockchain,ICP tokens,smart contracts,cycles,wallet,canister,developer
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK

In general, all canisters consume resources in the form of CPU cycles for execution, bandwidth for routing messages, and memory for persisted data.
Canisters maintain an account balance to pay for the cost of communication, computation, and storage their applications consume. 
The cost of computation is referred to as *cycles*.

Cycles reflects the real costs of operations including resources such physical hardware, rack space, energy,storage devices, and bandwidth. 
In simple terms, a *unit of cycles* represents the cost of executing a single WebAssembly instruction. 

* Programs must be able to pay for complete execution (all or nothing), but the cost associated with a unit of cycles will make efficient programs cost-effective.
* By setting limits on how many cycles a canister can consume, the platform can prevent malicious code from draining resources

The relative stability of operational costs makes it easier to predict the cycles required to process, for example, a million messages.

NOTE: When you deploy canisters locally or to an {IC} test network, there’s no cost associated with program execution. However, it is possible that in calculating the operations to be performed, executing a program might result in an “out of cycles” exception because the operations would exceed a predefined threshold. 
If you see this exception in testing, you can temporarily configure a higher cycles limit by setting a command-line option.

== Want to learn more?

If you are looking for more information about tokens and cycles, check out the following related resources:

* link:https://www.youtube.com/watch?v=H2p5q0PR2pc[Overview of Token Economics (video)]