= What is the {IC}?
:keywords: Internet Computer,blockchain,protocol,replica,subnet,data center,smart contract,canister,developer
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY

[[ic-overview]]

The *{IC}* is a blockchain that enables developers, organizations, and entrepreneurs to build and deploy secure, autonomous, and tamper-proof *canisters*, an evolution of *smart contracts*.

As a dapp developer, you might find it useful to think of the {IC} as providing the following key features:

* A *globally-accessible, public blockchain* for running smart contracts at web speed, that can serve interactive web content to users.
* A secure cryptographic protocol (*Internet Computer Protocol*) run by nodes machines operated by independent node providers in independent data centers all over the world. This guarantees the secure execution of smart contracts.
* A *network of blockchains* connected using Chain Key cryptography that can scale out its capacity as required.

== An open blockchain

The {IC} is a blockchain hosted on node machines operated by independent parties and located in geographically distributed datacenters. The nodes run the {IC} Protocol, an advanced cryptographic fault-tolerant protocol which ensures that smart contracts running on the blockchain cannot be tampered with or stopped.  The {IC} is composed of individual subnet blockchains running in parallel and connected using chain key cryptography. This means that canisters running on a subnet can seamlessly call canisters hosted in any other subnet of the {IC} blockchain.

Another important feature of the {IC} is that it runs under the control of a decentralized permissionless governance system, called *Network Nervous System* (NNS), which runs completely on-chain. The NNS can make decisions on several topics, including scaling out the {IC} by creating new subnet blockchains, updating the node machines, and configuring parameters used in the {IC} protocol. Anyone can participate in the governance and submit new proposals to the NNS or vote on open proposals. To do so, users have to stake ICP, the {IC} utility tokens, and create a *neuron* with the NNS.

[[next-gen]]
== Building the next generation of software and services

The {IC} protocol reduces platform-based risks and paves the way for innovation by re-imagining how software is built, deployed, and accessed. 

For example, with the {IC}, developers can focus on writing code using canister smart contracts without environment-related distractions such as:

* physical or virtual network configuration requirements
* load balancing services
* firewalls, network topology, or port management
* database configuration and maintenance
* storage volumes and devices

By enabling developers to focus on building applications and delivering value, the {IC} helps simplify the development process, reduce time to market, and foster innovation.

For end-users, the {IC} provides a secure environment for accessing dapps with fewer risks.
Because of the inherent security of the blockchain, programs running on the {IC} cannot be hijacked by malicious code, which also reduces the total cost of ownership for both application end-users or organizations.

In addition, because dapps can be "autonomous" and public, developers can write services that communicate with each other and share functions in ways that increase productivity and efficiency while leaving room to innovate and improve projects with confidence.

The {IC} also enables developers to use cryptographically-secure identities to enforce access controls, reducing the need to rely on usernames and passwords or external identity management plug-ins.

////
== Want to learn more?

If you are looking for more information about the Internet Computer project and how it fits into the natural evolution of blockchain technology and the internet itself, check out the following related resources:

* link:https://www.youtube.com/watch?v=XgsOKP224Zw[Overview of the Internet Computer (video)]
* link:https://www.youtube.com/watch?v=jduSMHxdYD8[Building on the {IC}: Fundamentals (video)]
* link:https://www.youtube.com/watch?v=LKpGuBOXxtQ[Introducing Canisters — An Evolution of Smart Contracts (video)]
* link:https://dfinity.org/faq/[Frequently Asked Questions (video and short articles)]

////