= Errors and optional results
:proglang: Motoko
:company-id: DFINITY

== Type errors and messages

Mathematically, the type system of {proglang} is _declarative_,
meaning that it exists independently of any implementation, as a
concept entirely in formal logic.  Likewise, the other key aspects of
the language definition (e.g., its execution semantics) exist outside
of an implementation.

However, to design this logical definition, to experiment with it, and
to practice making mistakes, we want to interact with this type
system, and to make lots of harmless mistakes along the way.

The error messages of the _type checker_ attempt to help the developer
when they misunderstand or otherwise misapply the logic of the type
system, which is explained indirectly in this book.

These error messages will evolve over time, and for this reason, we
will not include particular error messages in this text.  Instead, we
will attempt to explain each code example in its surrounding prose.

[[overview-traps]]
=== Execution traps stop the program

Each form above is a simple wrapper around the always-fail use of the
<<exp-assert, `assert` primitive>>:

....
assert false
....

Dynamically, we call this program-halting behavior a
_program(-generated) trap_, and we say that the program _traps_ when
it executes this code.  It will cease to progress further.

[[exp-error]]
== Chapter: Errors and optional results

to do:

 - ground the concepts: Errors as return values versus errors via special, exceptional control flow
 - this chapter introduces special uses of `switch` and `try` constructs
 - `switch` supports general pattern-matching;
   point to broader discussion of `switch` and <<chapter-patterns, pattern matching (next chapter)>>
 - handle errors as values with `switch` (not with `try`)
 - design question in an API: When to use which?
 - handle errors as exceptions with `try` --- in a way, these are less general for API design; may only appear in certain (`async`) contexts.  But they can recover from errors that would otherwise be fatal (such as system errors), so they are necessary.
 - discuss programming examples:
 - discuss use of <<stdlib-result,`Result` module>>, with examples
 - discuss use of <<stdlib-option,`Option` module>>, with examples
 - discuss use of <<error-type, `Error` type>>; exceptions versus traps (is there a difference?)



[[chapter-sharing]]
== Chapter: Sharing among distinct actors

CAUTION: Not complete

=== Shared data

=== Shared functions

[[example-notify]]
=== Example: Notification service

CAUTION: Not complete (todo: simple example of a callback-using service)


[[chapter-modules]]
== Chapter: Modules and imports

CAUTION: Not complete

to do:

 - discuss use of `module` keyword
 - discuss use of `import` keyword


[[chapter-imp]]
== Chapter: Imperative control flow

CAUTION: Not complete

to do:

 - discuss `return`
 - discuss labels and labeled gotos
 - discuss use of `for` loops
 - discuss iterators; discuss examples of iterating an array and iterating a text value (`.keys`, `.vals`, `.chars`, `.len`, etc.)
 - discuss use of `while` loops
 - discuss use of `do` loops

[[intro-range]]
=== Using `range` with a `for` loop

The `range` function produces an iterator (of type `Iter`) with the
given lower and upper bound, inclusive.

The following loop example prints the numbers `0` through `10` over
its _eleven_ iterations:

....
var i = 0;
for (j in range(0, 10)) {
 printNat(j);
 assert(j == i);
 i += 1;
};
assert(i == 11);
....


More generally, the function `range` is a `class` that constructs
iterators over sequences of natural numbers.  Each such iterator has type `Iter<Nat>`.

As a constructor function, `range` has a function type:

....
(lower:Nat, upper:Nat) -> Iter<Nat>
....

Where `Iter<Nat>` is an iterator object type with a `next` method that produces optional elements, each of type `?Nat`:

....
type Iter<Nat> = {next : () -> ?Nat};
....

For each invocation, `next` returns an optional element (of type
`?Nat`).

The value `null` indicates that the iteration sequence has terminated.

Until reaching `null`, each non-`null` value,
of the form ``?``__n__ for some number _n_,
contains the next
successive element in the iteration sequence.

[[intro-revrange]]
=== Using `revrange`

Like `range`, the function `revrange` is a `class` that constructs
iterators (each of type `Iter`).  As a constructor function, it has a
function type:

....
(upper:Nat, lower:Nat) -> Iter
....

Unlike `range`, the `revrange` function _descends_ in its iteration
sequence, from an initial _upper_ bound to a final _lower_ bound.


[[chapter-discussion]]
== Chapter: Advanced discussion topics

To do:

- discuss: no race conditions

- discuss: no null-pointer exceptions

- discuss: Subtypes and the `Null` type

- discuss: Types are structural
