= Sharing data and behavior

Recall that in {proglang}, mutable state is always private to an actor.

However, two actors can share message data, and those messages can
refer to actors, including themselves and one another.  Additionally,
messages may refer to individual functions, if those functions are `shared`.

Through these mechanisms, two actors can coordinate their behavior
through asynchronous message passing.

== Publisher-subscriber pattern with actors

To give a simple example, we focus on variations of the link:https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern["publisher-subscriber" pattern],
wherein a "publisher" actor records a list of "subscriber" actors to
notify when something notable occurs in the publisher's state (e.g., a
new "publication" is available).

Below, we use two actors in {proglang} to build variations of the
publisher-subscriber relationship between the actors.

For a complete working project,
see the link:https://github.com/dfinity/examples/tree/master/motoko/pubsub[pubsub example].

Below, we introduce the ideas gradually, showing the most salient pieces in code below.
See the link:https://github.com/dfinity/examples[`examples` repository] for working code.

=== A basic version

We begin the most basic version of the pattern by defining a type of
`Subscriber` actor type, which gives a common interface for the two
actors:

[source,motoko]
----
public type Subscriber = actor {
  notify : () -> ()
};
----

1. The `Publisher` uses this type to define a data structure to store its
subscribers as data.
2. Each `Subscriber` actor exposes an update function
`notify`, as in the `Subscriber` actor type signature above.  Recall that
subtyping permits the subscriber actor to also have additional methods not
listed in this type.

For simplicity, we assume a very simple type for `notify` above.  In
general, this `notify` function would accept relevant notification
data and perhaps return some new status of the subscriber to the
publisher, e.g., changing its subscription settings based on the
notification data.

For simplicity here, we do not consider such data, and let the
subscriber perform further queries of the publisher, if need be
(perhaps less efficient than a more custom protocol).


=== Publisher side

The publisher side of the code stores an array of subscribers, where
we assume (for simplicity) that each subscriber only subscribes
themselves once, via `subscribe`.

[source,motoko]
----
actor Publisher {
    var subscribers: [Subscriber] = [];

    public func subscribe(subscriber: Subscriber) {
        subscribers := Array.append<Subscriber>(subscribers, [subscriber]);
    };

    public func publish(counter: Counter) {
        for (subscriber in subscribers.vals()) {
          subscriber.notify();
        };
    };
};
----

Later, when some unspecified external agent invokes `publish`, all of
the subscreibers receive the `notify` message, as in the `Subscriber`
type given above.

=== Subscriber side

In the simplest case, the subscriber side has three methods:
1. query the accumulated state, in this case just a counter (`get`),
2. subscribe to notifications from the publisher (`init`), and
3. notify the subscribed actors (calling `notify`, as in the `Subscriber` type given above):

[source,motoko]
----
import Publisher "canister:pub";

actor Subscriber {
    var count: Nat = 0;
    public func get() : async Nat {
        count
    };
    public func notify() {
        count += 1;
    };
    public func init() {
        Publisher.subscribe(Subscriber);
    };
}
----

We assume, but do not enforce, that the `init` function is only ever
called once.  With more care, the actor could enforce this.
Alternatively, a more advanced publisher actor could check for
duplicates and ignore them.

== Sharing functions among actors

In {proglang}, a `shared` actor function can be sent in a message to
another actor, and then later called by that actor, or another one.

The code shown above has been simplified for illustrative purposes.
The full version offers additional features to the
publisher-subscriber relationship, and uses shared functions to make
this relationship more flexible.

See the link:https://github.com/dfinity/examples/tree/master/motoko/pubsub[the full example]
for details.

=== The keyword `shared`

To do... explain some snippets from the full version, and the use of the keyword.
