= Integrating with the Network Nervous System (NNS)
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

[[nns-intro]]
This _{doctitle}_ guide introduces the Internet Computer Network Nervous System (NNS).
The Internet Computer Network Nervous System (NNS) is a decentralized, algorithmic governance system that manages many aspects of the Internet Computer on behalf of its stakeholders.

_{doctitle}_ includes an overview of the NNS and its key operations and provides a summary of the application programming interface (API) methods that support staking operations for ICP token holders.

_{doctitle}_ is intended as a high-level overview for organizations and developers who need to understand the terminology and operational management flow for the Internet Computer NNS governance system. 
The document focuses on how participants in the Internet Computer network can create a stake with voting rights by locking up ICP tokens for a given period of time.

NOTE: Currently, _{doctitle}_ only covers the minimal API for neuron custody and staking. 
It does not provide information about how to participate in governance by submitting proposals or voting.

In reviewing this document, keep in mind that additional details about specific operations, components, or interfaces might be available in subsequent documents to supplement the overview provided in this document. For example, information about submitting proposals or voting might be provided in a subsequent document or in a update to this document at a later time.

== Basic terminology to get you started

The Internet Computer is primarily a distributed and decentralized platform for running software. 
When developers write applications that run on the Internet Computer, they deploy their programs in the form of a conceptual computational unit called a **canister**. 
A canister is similar to a “smart contract” in that it consists of both program code and state running, replicated, on a block chain network with security and liveness guarantees.

== NNS overview

As a decentralized platform, all changes to the configuration and behavior of the Internet Computer are controlled by an algorithmic governance system called the Network Nervous System (NNS). 
The NNS controls all aspects of the {IC} network configuration and is responsible for performing many network management operations. For example, the Network Nervous System (NNS) is responsible for:

* Upgrading the protocol and guest operating system software used by the nodes that provide computing capacity to the network.
* Inducting new node operators and machines into the network.
* Creating new subnets to increase network capacity.
* Splitting subnets to balance network load.
* Configuring parameters that control how much must be paid by users for compute capacity.
* Monitoring canister activity and node performance for
malicious behavior and statistical deviations.
* De-activating malicious software or under-performing nodes to protect the network.

The requests for changes and updates to the network are submitted to the NNS in the form of **proposals**.
The NNS decides to adopt or reject proposals based on voting activity by certain network participants.

=== Neurons

For network participants to be able to vote on proposals, they need to lock up a stake of ICP tokens for a given period of time to create a representative called a **neuron**.

Because neurons represent a stake of ICP tokens, they also represent an identity with a **ledger canister account** and a principal that controls the ledger account.

Neurons provide the stability required for responsible governance of the {IC} by ensuring that the ICP tokens they represent cannot be exchanged for a specific period of time sometimes referred to as the **lock-up** period.

=== Governance and voting rewards

When a person or organization has ICP tokens locked up in a neuron, the neuron holder can propose and vote on governance issues.
To encourage participation, neuron holders are also paid for voting in proportion to the number of ICP tokens they have locked up and the length of the lock-up period up to a maximum of eight years.

The incentive paid to neuron holders for voting is called a voting **reward**.

=== Unlocking the stake held by a neuron

After network participants create a neuron, the locked balance of ICP tokens can only be unlocked by fully *dissolving* the neuron.
In its **locked** state, the neuron has a fixed non-zero **dissolve delay** equivalent to the lock-up period.
For example, assume you have a stake of 100 ICP tokens locked up for a period of five years. 
After successfully created the neuron with these settings, your dissolve delay is five years.

Based on the dissolve delay that decreases as time progresses, a **dissolve timer** determines how long it will take to completely dissolve a neuron.

When the dissolve timer reaches zero, the neuron owner—the ICP token holder who created the neuron or an authenticated custodian—can dissolve the neuron and unlock the balance of ICP tokens.

The dissolved neuron ceases to exist and the stake of ICP tokens that the neuron represented is released to the appropriate ledger canister account.

////
=== Proposals

=== Voting
////
=== Basic workflow

The following diagram provides a simplified view of the workflow for creating a neuron and the relationship between the neuron and ledger canisters.

image:create-dissolve-neuron-api.svg[]

////
=== How to ... 

This section summarizes the steps for how to 

=== Requirements and limitations
////

== NNS API reference

This section provides reference information about the NNS interfaces. You can also use this information to help you plan for interacting with the NNS.

The NNS provides the following application programming interface methods.

NOTE: The interfaces described in this document are preliminary and subject to change.

=== create_neuron

Creates a new neuron by locking ICP tokens.

This method transfers the ICP tokens specified for the ‘+locked_icpt+’ parameter from a ledger account controlled by the caller and creates a new neuron with the `+dissolve_period+` specified in seconds.

....
create_neuron: (
locked_icpt: ICPT,
dissolve_period_sec,
) -> Result<NeuronId, String>
....

[width="90%",cols="<15%,<75%",options="header"]
|===
|Parameter |Description
|`+locked_icpt+` |Defines how many ICP tokens should be staked in the neuron.
|`+dissolve_period_sec+` |Specifies the minimum dissolve period for the neuron, in seconds.
|===

The principal who invokes the method is identified as `+caller+`.

This method results in a transfer from the ledger account associated with the `+caller+` principal to a new ledger account corresponding to the neuron. 
If the neuron is created successfully, the transfer is recorded as a transaction in the ledger canister.

This method succeeds only if:

- `+dissolve_period_sec+` is greater than 0 and less than 8 years (252288000 seconds).
- there is at least `+staked_icpt+` available in the `+caller+` account.

The caller for this method can only be authenticated using the key for the controlling principal.
The key associated with the controlling principal is also referred to as the **cold key** for an account.

=== add_hotkey

Adds a hot key to the list of authorized hot keys for the neuron.
Hot keys can be used to participate in governance—for example, to submit and vote on proposals—and to obtain information about the neuron.

....
add_hot_key: (
neuron_id: NeuronId,
key: PrincipalId,
) -> Result<(), String>
....

[width="90%",cols="<15%,<75%",options="header"]
|===
|Parameter |Description
|`+neuron_id+`|Specifies the neuron to add the hot key to.
|`+key+` |Specifies the key to add to the list of hot keys that can be used for the neuron.
|===

The principal who invokes the method is identified as `+caller+`.

This method succeeds only if:

- `+caller+` is equal the `+controller+` of the neuron.

After this call succeeds, the key corresponding to the `+key+` parameter can be used to sign governance messages
like voting on proposals or to retrieve information about the current state of the neuron.

=== remove_hotkey

Removes a hot key from the list of authorized hot keys for the neuron. 
Hot keys can be used to participate in governance—for example, to submit and vote on proposals—and to obtain information about the neuron.

....
remove_hot_key: (
neuron_id: NeuronId,
key: PrincipalId,
) -> Result<(), String>
....

[width="90%",cols="<15%,<75%",options="header"]
|===
|Parameter |Description
|`+neuron_id+`|Specifies the neuron to remove the hot key from.
|`+key+` |Specifies the key to remove to the list of hot keys that can be used for the neuron.
|===

The principal who invokes the method is identified as `+caller+`.

This method succeeds only if:

- `+caller+` is equal the `+controller+` of the neuron.
- `+key+` is in the list of hot keys for the neuron.

After this call succeeds, the key corresponding to `+key+` cannot be used to sign governance messages like voting on proposals or to retrieve information about the current state of the neuron.

=== get_neuron_info

Returns the current state of the neuron, including its voting history.

....
get_neuron_info: (
neuron_id: NeuronId,
) -> Result<(), Neuron>
....

[width="90%",cols="<15%,<75%",options="header"]
|===
|Parameter |Description
|`+neuron_id+`|Specifies the neuron for which you want to return information.
|===

The principal who invokes the method is identified as the `+caller+`.

At a minimum, the information returned for a neuron includes the following:

....
Neuron {
 id: NeuronId,
 account: LedgerAccount,
 dissolve_delay: u64,
 dissolving: boolean,
}
....

[width="90%",cols="<15%,<75%",options="header"]
|===
|Fields |Description
|`+id+`|Specifies the unique identifier of the neuron.
|`+account+`|Specifies the ledger account that holds the stake controlled by the neuron.
|`+dissolve_delay+`|Specifies the time, in seconds, it will take to unlock the ICP token balance by "dissolving" the neuron.
|`+dissolving+`|Specifies whether the neuron is currently dissolving.
|===

The method succeeds only if:

- `+caller+` is either the `+controller+` of the neuron or one of the hot keys.

=== start_dissolving

Starts the dissolve timer.

This method starts the timer for dissolving a locked neuron. 
With this method, the dissolve delay for the neuron begins counting down towards dissolution, starting with either the period set when the neuron was created or from the last time the timer was stopped.

The neuron might lose any accumulated bonuses related to aging. When this timer becomes less that 6 months (15552000 seconds), the neuron will no longer be able to participate in governance (either by voting or submitting proposals).

....
start_dissolving: (
neuron_id: NeuronId,
) -> Result<(), String>
....

[width="90%",cols="<15%,<75%",options="header"]
|===
|Parameter |Description
|`+neuron_id+`|Specifies the neuron to start dissolving.
|===

The principal who invokes the method is identified as the `+caller+`.

The method succeeds only if:

- `+caller+` is equal the `+controller+` of the neuron.
- `+dissolve_delay+` is greater than 0.

=== stop_dissolving

Stop the dissolve timer.

This method stops the neuron from progressing towards dissolution. 
The neuron might start accumulating bonuses related to aging, if it's still able to participate in governance.

....
stop_dissolving: (
neuron_id: NeuronId,
) -> Result<(), String>
....

[width="90%",cols="<15%,<75%",options="header"]
|===
|Parameter |Description
|`+neuron_id+`|Specifies the neuron to stop dissolving.
|===

The principal who invokes the method is identified as the `+caller+`.

The method succeeds only if:

- `+caller+` is equal the `+controller+` of the neuron.
- `+dissolve_delay+` is greater than 0.

=== increase_dissolve_delay

Increases the dissolve delay of the neuron.

This method enables you to add time, in seconds, for dissolving a neuron by increasing the dissolve delay by the provided amount.
If this increase brings the total `+dissolve_delay+` above 6 months (15552000 seconds), the neuron will be once more able to participate in governance. 
This has no effect on whether the neuron is dissolving or not. The dissolve timer can only be increased to a maximum of 8 years.

....
increase_dissolve_delay: (
neuron_id: NeuronId,
dissolve_delay_to_add: u64,
) -> Result<(), String>
....

[width="90%",cols="<15%,<75%",options="header"]
|===
|Parameter |Description
|`+neuron_id+`|Specifies the neuron for which to increase the dissolve delay.
|`+dissolve_delay_to_add+`|Specifies the number of seconds to add to the current dissolve delay timer.
|===

The principal who invokes the method is identified as the `+caller+`.

The method succeeds only if:

- `+caller+` is equal the `+controller+` of the neuron.

=== dissolve_neuron

Dissolves the neuron and releases the locked ICP tokens.

This method transfers all of the staked ICP tokens held in the specified neuron to the caller's ledger account.
This method requires the dissolve timer to have a value of zero (0) for the withdrawal of staked ICP tokens to be successful.

....
dissolve_neuron: (
neuron_id: NeuronId,
) -> Result<(), String>
....

[width="90%",cols="<15%,<75%",options="header"]
|===
|Parameter |Description
|`+neuron_id+`|Specifies the neuron to dissolve.
|===

The principal who invokes the method is identified as the `+caller+`.

The method succeeds only if:

- `+caller+` is equal the `+controller+` of the neuron.
