= Integrating with the Internet Computer Network Nervous System (NNS)
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

[[nns-intro]]
This _{doctitle}_ guide introduces the Internet Computer Network Nervous System (NNS).
The Internet Computer Network Nervous System (NNS) is a decentralized, algorithmic governance system that manages many aspects of the Internet Computer on behalf of its stakeholders.

The document includes an overview of the NNS and its key operations and provides a summary of the application programming interface (API) methods that support staking operations for ICP token holders.

_{doctitle}_ is intended as a high-level overview for organizations and developers who need to understand the terminology and operational management flow for Internet Computer governance system. 
The document focuses on how participants in the Internet Computer network can create a stake with voting rights by locking up ICP tokens for a given period of time.

NOTE: Currently, _{doctitle}_ only covers the minimal API for neuron custody and staking. 
It does not provide information about how to participate in governance by submitting proposals or voting.

In reviewing this document, keep in mind that additional details about specific operations, components, or interfaces might be available in subsequent documents to supplement the overview provided in this document. For example, information about submitting proposals or voting might be provided in a subsequent document or in a update to this document at a later time.

== Basic terminology to get you started

The Internet Computer is primarily a distributed and decentralized platform for running software. 
When developers write applications that run on the Internet Computer, they deploy their programs in the form of a conceptual computational unit called a **canister**. 
A canister is similar to a “smart contract” in that it consists of both program code and state running, replicated, on a block chain network with security and liveness guarantees.

== NNS overview

As a decentralized platform, all changes to the configuration and behavior of the Internet Computer are controlled by an algorithmic governance system called the Network Nervous System (NNS). 
The NNS controls all aspects of the {IC} network configuration and is responsible for performing many network management operations. For example, the Network Nervous System (NNS) is responsible for:

* Upgrading the protocol and guest operating system software used by the nodes that provide computing capacity to the network.
* Inducting new node operators and machines into the network.
* Creating new subnets to increase network capacity.
* Splitting subnets to balance network load.
* Configuring parameters that control how much must be paid by users for compute capacity.
* Monitoring canister activity and node performance for
malicious behavior and statistical deviations.
* De-activating malicious software or under-performing nodes to protect the network.

The NNS works by accepting proposals, then deciding to adopt or reject those proposals based on voting activity by “neurons” that network participants have created.

The requests for changes and updates to the network are submitted to the NNS in the form of proposals.
The NNS decides to adopt or reject proposals based on voting activity by certain network participants.

=== Neurons

For network participants to be able to vote on proposals, they need to lock up a stake of ICP tokens for a given period of time to create a representative called a **neuron**.

Because neurons represent a stake of ICP tokens, they also represent an identity with a ledger canister account and a principal that controls the ledger account.

Neurons provide the stability required for responsible governance of the {IC} by ensuring the ICP tokens they represent cannot be exchanged for a specific period of time sometimes referred to as the lock-up period.

When a person or organization has ICP tokens locked up in a neuron, the neuron holder can propose and vote on governance issues.
To encourage participation, neuron holders are also paid for voting in proportion to the number of ICP tokens they have locked up and the length of the lock-up period up to a maximum of eight years.

After network participants create a neuron, the locked balance of ICP tokens can only be unlocked by fully dissolving the neuron.

The period of time it takes for a neuron to be fully dissolved is configured with a *dissolve timer* setting. The dissolve timer determines how long it will take to completely dissolve a neuron after it is placed into “dissolve mode”. 
When the dissolve timer reaches zero, the neuron owner—the ICP token holder who created the neuron or an authenticated custodian (?)—can dissolve the neuron and unlock the balance of ICP tokens. 

////
=== Proposals

=== Voting

=== Basic integration workflow

The following steps summarize the basic operational workflow for .... 


=== How to ... 

This section summarizes the steps for how to 

////
=== Requirements and limitations
////

== NNS API reference

This section provides reference information about the NNS interfaces. You can also use this information to help you plan for interacting with the NNS.

The NNS provides the following application programming interface methods.

NOTE: The interfaces described in this document are preliminary and subject to change.

=== create_neuron

Transfers the ICP tokens specified for the ‘+locked_icpt+’ from a ledger account controlled by the caller and creates a new neuron with the `+dissolve_period+` specified.?UNIT? 
The neuron is not dissolving. ?MEANING?
The caller is authenticated with the “cold” key. ?MEANING?

....
create_neuron(locked_icpt, ledger_account, dissolve_period)
....

=== add_hotkey

Adds a hot key to the list of authorized keys of the neuron.
The caller is authenticated with the “cold” key. ?MEANING?

....
add_hotkey(neuron_id)
....

=== remove_hotkey

Removes a hot key from the list of authorized keys for the specified neuron. ?MEANING of "hot" key?
The caller is authenticated with the “cold” key. ?MEANING?
....
remove_hotkey(neuron_id)
....

=== get_neuron_info

Returns information about the neuron.
The caller is authenticated with the cold key or any of the neuron holder's hot keys.

....
get_neuron_info(neuron_id)
....

=== start_dissolving

Starts the dissolve timer.
The caller is authenticated with the “cold” key.

....
start_dissolving(neuron_id)
....

=== stop_dissolving

Stops the dissolve timer.
The caller is authenticated with the “cold” key.

....
stop_dissolving(neuron_id)
....

=== dissolve_neuron

Transfers all of the staked ICP tokens held in the specified neuron to the caller's ledger account.
This method requires the dissolve timer to have a value of zero (0) for the withdrawal of staked ICP tokens to be successful.
The caller is authenticated with the “cold” key.

....
dissolve_neuron(neuron_id)
....
