= Sample Code
:description: Quick links to example code for common use-cases for your dapp
:keywords: Internet Computer,blockchain,cryptocurrency,ICP tokens,smart contracts,cycles,wallet,software canister,developer onboarding,dapp,example,code,rust,Motoko
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

[[example-code-intro]]
Take a look at some sample dapps below and see the possibilities of building on the IC. All samples and further projects can be found in the https://github.com/dfinity/examples[Samples Repo]. Additional resources can be found in the https://github.com/dfinity/awesome-dfinity[Awesome Dfinity] (a curated set of open-source projects and examples from our community) or link:./hackathon-projects.html[Hackathon Projects]!

=== Hello world 
The dapp equivalent of _hello world_, with a separate backend and frontend canister serving a web page. +
https://github.com/dfinity/examples/tree/master/motoko/hello[Motoko] • https://github.com/dfinity/examples/tree/master/rust/hello[Rust] • link:hello{outfilesuffix}[Technical docs]

=== Static website
This tutorial shows how to quickly set up a static website structure, add content and basic styling, and deploy to the IC. + 
link:host-a-website{outfilesuffix}[Technical docs] • https://www.youtube.com/watch?v=JAQ1dkFvfPI[Video guide]

=== Basic DEX
To enable DEFI applications on the IC, canisters need to interact with token canisters and the ledger canister. This example dapp illustrates these interactions by showing how to enable an Exchange to take custody of funds, update an internal balance book as users trade, and give custody back to the user as funds are withdrawn. +
https://github.com/dfinity/examples/tree/master/motoko/defi[Motoko] • https://github.com/dfinity/examples/tree/master/rust/defi[Rust] • https://gzz56-daaaa-aaaal-qai2a-cai.ic0.app/[See running] •link:dex{outfilesuffix}[Technical docs]

=== NFT minting
This NFT minting dapp showcases how easy it can be to create a user generated NFT and share it. This dapp uses the https://github.com/Psychedelic/DIP721[DIP721] NFT standard. +
https://github.com/dfinity/examples/tree/master/rust/dip721-nft-container[Rust] • xref:examples:nft.adoc[Technical docs]

=== Basic DAO
Decentralised governance is higlight of the IC and is illustrated by the basic DAO sample code. It illustrates how to initialize a set of accounts and corresponding tokens, how account owners can sumit proposals for other account owners to vote on, and how a proposal is executed given enough favorable votes.  + 
https://github.com/dfinity/examples/tree/master/motoko/basic_dao[Motoko] • https://github.com/dfinity/examples/tree/master/rust/basic_dao[Rust] • link:dao{outfilesuffix}[Technical docs]

=== Encrypted note-taking
Create/access/modify confidential notes from multiple devices using https://smartcontracts.org/docs/ic-identity-guide/what-is-ic-identity.html[Internet Identity] service and end-to-end encryption. The sample code relies upon the _web-serving_ and _storage capabilities_ of the IC, and highlights two key functionalities: (1) client-side, end-to-end encryption and (2) multi-user and multi-device support. + 
https://github.com/dfinity/examples/tree/master/motoko/encrypted-notes-dapp/src/encrypted_notes_motoko[Motoko] •
https://github.com/dfinity/examples/tree/master/motoko/encrypted-notes-dapp/src/encrypted_notes_rust[Rust] • https://cvhrw-2yaaa-aaaaj-aaiqa-cai.ic0.app/[See running] • link:encrypted-notes{outfilesuffix}[Technical docs]

=== Token transfer
This sample code demonstrates how a dapp can transfer tokens to its most active users. + 
https://github.com/dfinity/examples/tree/master/motoko/ledger-transfer[Motoko] • https://github.com/dfinity/examples/tree/master/rust/tokens_transfer[Rust] • link:tokentransfer{outfilesuffix}[Technical docs]


== Explore further Samples in Motoko

This is a collection of repo-links to additional code samples written in Motoko. Most are also available in the https://m7sm4-2iaaa-aaaab-qabra-cai.raw.ic0.app/[Motoko playground]. The playground provides the simplest enviromnent for trying out pure Motoko samples without having to download and learn to use the SDK, but does not support dapps with frontends.


=== Basic

This is collection of basic getting-started Motoko samples, which demonstrate basic concepts of the IC and the Motoko language. 

- https://github.com/dfinity/examples/tree/master/motoko/actor_reference[actor_reference] -- IC management canister as an actor (reference).
- https://github.com/dfinity/examples/tree/master/motoko/counter[counter] -- basic (stable) variable demo.
- https://github.com/dfinity/examples/tree/master/motoko/echo[echo] -- basic query function demo.
- https://github.com/dfinity/examples/tree/master/motoko/factorial[factorial] -- basic factorial demo.
- https://github.com/dfinity/examples/tree/master/motoko/hello_cycles[hello_cycles] -- Receive and transfer cycles and check your balance.
- https://github.com/dfinity/examples/tree/master/motoko/whoami[whoami] -- a simple canister that reports the Principal of its caller.

=== Intermediate

The intermediate samples demonstrate how to use some of the basic concepts in common use cases. The samples show how to build simple backend functionalities in Motoko.

- https://github.com/dfinity/examples/tree/master/motoko/classes[classes] -- dynamic actor (class) instantiation.
- https://github.com/dfinity/examples/tree/master/motoko/pub-sub[pub-sub]-- multiple canisters, with publisher-subscriber inter-canister calls.
- https://github.com/dfinity/examples/tree/master/motoko/quicksort[quicksort] -- sorting an array, via Quick Sort, in Motoko.
- https://github.com/dfinity/examples/tree/master/motoko/simple-to-do[simple-to-do] -- CRUD-like demo service, sans a front end; see also: phone-book and superheroes.
- https://github.com/dfinity/examples/tree/master/motoko/calc[calc] -- more advanced version of counter demo.
// - https://github.com/dfinity/examples/tree/master/motoko/ledger-transfer[Ledger Transfer] -- a canister that transfers ICP to its users.

=== Minimal front end

These two samples show how to create simple frontends in JavaScript. Where the previous samples did not provide a frontend, these two samples provide both a frontend and a backend.

- https://github.com/dfinity/examples/tree/master/motoko/random_maze[random_maze] -- random maze generation, with IC-based randomness.
- https://github.com/dfinity/examples/tree/master/motoko/cert-var[cert_var] -- simple certified variable (a single 32-bit number), with client-side certificate validation.

=== Full stack

These samples demonstrate how to build dapps on the IC, with frontends based on React and TypeScript.  

- https://github.com/dfinity/examples/tree/master/motoko/life[life] -- Conway's https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life[Game of Life], running in a Motoko Canister. Demonstrates upgrades among three versions and state migration using stable variables. 
- https://github.com/dfinity/examples/tree/master/motoko/phone-book[phone-book] -- CRUD-like demo service.
- https://github.com/dfinity/examples/tree/master/motoko/superheroes[superheroes] -- a simple CRUD dapp. 
- https://github.com/krpeacock/auth-client-demo[Auth Client Demo] - simple authentication with Internet Identity.
- https://github.com/krpeacock/ic-avatar[IC-Avatar] - full-stack Motoko + React with more advanced authentication, image uploads, and optimistic updates.

[[motoko-advanced]]
=== Advanced

Large samples contributed by the community and not necessarily up-to-date:

- Reversi game, in https://github.com/ninegua/reversi[Motoko] accompanying https://ninegua.github.io/reversi[Blog post].

- QR code generator in https://github.com/enzoh/motoko-qr[Motoko] accompanying
  https://medium.com/@ehaussecker/my-first-microservice-on-dfinity-3ac5c142865b[Medium article].

- https://github.com/timohanke/icvault[IC Vault] - end-to-end Encryption.

- Certified asset canister in
  https://github.com/nomeata/motoko-certified-http[Motoko]
  https://forum.dfinity.org/t/certified-assets-from-motoko-poc-tutorial/7263[forum post] - demonstrating a larger application of {IC} certified variables.


// - xref:examples:encrypted-notes.adoc[Encrypted Notes dapp] -- create/access/modify confidential notes from multiple devices using https://smartcontracts.org/docs/ic-identity-guide/what-is-ic-identity.html[Internet Identity] service and end-to-end encryption.

// [[rust]]
// == Rust Examples

// [[rust-beginner]]
// === Beginner

// Simple examples written in Rust

// - https://github.com/dfinity/examples/tree/master/rust/pub-sub[Pub Sub] -- This example is similar to the intermediate Motoko pub-sub example.
// - https://github.com/dfinity/examples/tree/master/rust/tokens_transfer[Tokens Transfer] -- demonstrates how to make ledger transfers and query account balance from a Rust canister.
// - https://github.com/dfinity/examples/tree/master/rust/basic_dao[Basic DAO] -- demonstrates a basic Decentralized Autonomous Organization 

[[rust-videos]]
== Video Guides for Building Dapps

These videos from the https://www.youtube.com/playlist?list=PLuhDt1vhGcrez-f3I0_hvbwGZHZzkZ7Ng[community conversations] series cover an introduction to building dapps in Rust, and best practices for building dapps in Rust. 

- https://www.youtube.com/watch?v=6wyIhzsFbKw[Community conversations | overview of building a dapp in Rust]
- https://www.youtube.com/watch?v=36L33S_DYHY&ab_channel=DFINITY[Community conversations | best practices for canisters in Rust]

Additional video series https://www.youtube.com/watch?v=M2XnywvwxFM&list=PLuhDt1vhGcrfQGLWqhUo9-DFD5JaHqCh1[Coding with Kyle].

// More Rust examples coming soon!

// [[rust-advanced]]
// === Advanced Examples

// - xref:examples:encrypted-notes.adoc[Encrypted Notes dapp] -- create/access/modify confidential notes from multiple devices using https://smartcontracts.org/docs/ic-identity-guide/what-is-ic-identity.html[Internet Identity] service and end-to-end encryption.

// == C

// For examples of projects written in the C programming language for the {IC}, see link:https://github.com/dfinity/examples/tree/master/c[C++ sample projects].

// WARNING: these examples are likely to bit-rot and may need updating and are provided for illustration only.

// * link:https://github.com/dfinity/examples/tree/master/c/adventure[Adventure game]
// * link:https://github.com/dfinity/examples/tree/master/c/qr[QR code generator]
// * link:https://github.com/dfinity/examples/tree/master/c/reverse[Reverse game]

// == Wat (Wasm textual format)

// Just for fun, we also have a simple example written in pure Wasm textual format:

// * link:https://github.com/dfinity/examples/tree/master/wasm/counter[counter]

