= Using the {proglang} standard library
:proglang: Motoko
:company-id: DFINITY

For various practical language engineering reasons, the design of {proglang} strives to minimize built-in types and operations.

Instead, whenever possible, the {proglang} standard library provides the types and operations that make the language feel complete.
__**However**, this standard library is still currently under development,
and is still incomplete__.

This section describes a _selected subset_ of modules from the {proglang} standard library, with an emphasis on the modules that support core features and the libraries that are referenced in the examples.
The libraries documented in this section are the most stable and least likely to change.
However, all of the standard library APIs are subject to change over time to varying degrees.
You should note, in particular, that the size and number of modules and functions included in the standard library may increase dramatically as {proglang} evolves.

== Importing from the standard library

To import from the standard library, use the `import` keyword.
Give a local module name to introduce, in this example `P` for
"`**P**relude`", and a URL where the `import` declaration may locate
the imported module:

....
import P "mo:stdlib/prelude";
P.printLn("hello world");
....

In this case, we import {proglang} code (not some other module form)
with the `mo:` prefix.  We specify the `stdlib/` path, followed by the
module name `prelude`.

=== Accommodating incomplete code

Sometimes, in the midst of writing a program, we want to run an
incomplete version, or a version where one or more execution paths are
either missing or simply invalid.

To accommodate these situations, we use the `xxx`, `nyi` and
`unreachable` functions from the standard library, explained below.
Each wraps a <<overview-traps,general trap mechanism>>,
explained further below.

=== Use short-term holes

Short-term holes are never committed to a source repository, and only
ever exist in a single development session, for a developer that is
still writing the program.

Assuming that earlier, one has imported the prelude as follows:

....
import P "mo:stdlib/prelude";
....

The developer can fill _any missing expression_ with the following one:

....
P.xxx()
....

The result will _always_ type check at compile time, and _will always_
trap at run time, if and when this expression ever executes.

=== Document longer-term holes

By convention, longer-term holes can be considered "yet not
implemented" (`nyi`) features, and marked as such with a similar
function from the prelude:

....
P.nyi()
....

=== Document `unreachable` code paths

In contrast to the situations above, sometimes code will _never_ be
filled, since it will _never_ be evaluated, assuming the coherence of
the internal logic of the programs' invariants.

To document a code path as logically impossible, or _unreachable_, use
the standard library function `unreachable`:

....
P.unreachable()
....

As in the situations above, this function type-checks in all contexts,
and when evaluated, traps in all contexts.

[[overview-traps]]
=== Execution traps stop the program

Each form above is a simple wrapper around the always-fail use of the
<<exp-assert, `assert` primitive>>:

....
assert false
....

Dynamically, we call this program-halting behavior a
_program(-generated) trap_, and we say that the program _traps_ when
it executes this code.  It will cease to progress further.

=== The `Array` module

The {proglang} standard library provides <<stdlib-array, additional array operations>>.

Many common operations for arrays reside in the standard library,
since the the {proglang} language intentionally places features that
can be written in {proglang} into this library, and not the set of
compiler and language builtin features.

 - discuss use of <<stdlib-result,`Result` module>>, with examples
 - discuss use of <<stdlib-option,`Option` module>>, with examples
 - discuss use of <<error-type, `Error` type>>; exceptions versus traps (is there a difference?)


== Using the {proglang} standard library

This section covers the following topics:

- <<compiler-prelude,Definitions that are *built into the compiler*>>
- <<stdlib-prelude,module `Prelude`>> defines additional helpers
- <<stdlib-option,module `Option`>> defines values that may be "missing"
- <<stdlib-result,module `Result`>> defines results that may contain errors
- <<stdlib-hash,module `Hash`>> defines types and functions for hashing
- <<stdlib-list,module `Array`>> defines supplemental functions for arrays
- <<stdlib-list,module `List`>> defines the linked list type and functions
- <<stdlib-list,module `AssocList`>> defines association lists and functions

[[compiler-prelude]]
== Compiler prelude

The compiler itself contains a prelude in every program,
effectively extending the language definition with a
set of types and declarations that are always available.

In addition to these in-built compiler definitions, the prelude of the standard
library contributes some additional functions in a <<stdlib-prelude, supplemental `Prelude` module>>.

In contrast to those definitions, the compiler prelude definitions here
are always present, and do _not_ require any `import` declaration to bring them into the current scope.

include::compiler-prelude.adoc[]

[[stdlib-prelude]]
== module `Prelude`

This standard library prelude module supplements the
<<compiler-prelude, compiler prelude>> with additional features that
do not require (additional) special compiler support.

include::prelude.adoc[]

[[stdlib-result]]
== module `Result`

include::libresults.adoc[]

[[stdlib-option]]
== module `Option`

include::option.adoc[]

[[stdlib-hash]]
== module `Hash`

include::hash.adoc[]

[[stdlib-array]]
== module `Array`

The design of {proglang} strives to minimize builtin operations, and
whenever possible, to instead implement array operations as
{proglang} functions in a standard library module dedicated to
extending that type's suite of supported operations.

include::array.adoc[]

[[stdlib-list]]
== module `List`

include::list.adoc[]

[[stdlib-assoclist]]
== module `AssocList`

include::assocList.adoc[]
