= Highlights of what's new in {release}
:description: DFINITY Canister Software Development Kit Release Notes
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
:release: 0.6.20
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

The {release} release has both user-facing and internal enhancements, including fixes and updates to {proglang}, the {proglang} base library, and Candid. 

== New features and capabilities

The most significant new features and capabilities include updates in the following functional areas:

* <<DFX,DFX>>
* <<Candid,Candid>>
* <<Motoko,Motoko>>

=== DFX

* The `+dfx+` commands that support the `+--network+` option have been updated to support URLs when specifying the network value.
+
Previously, the `+--network+` option required you to specify a network name that matched a network aliases configured in the project's `+dfx.json+` file.

=== Candid

The Candid web interface has been updated to provide easier navigation and a better user experience.
The updates to the Candid web interface include the following new features and improvements:

* A new Console drawer provides quick access to method output and a list of all available methods as links for fast navigation.
* Canister methods and their related form elements are more clearly separated and annotated.
* Method output is selectable and easier to toggle between text, UI, and JSON formats.
* The layout is now responsive to provide an optimized display when viewing service using mobile devices or other media. 

=== Motoko

* The {proglang} base documentation examples are now executable in the browser.

* The {proglang} compiler supports specifying command-line arguments using `+--args <file>+` and `+--args0 <file>+`.
+
The new options enable the compiler to read newline and NUL terminated arguments from a specified file name.

== Issues fixed in this release

This section covers any reported issues that have been fixed in this release.

== Known issues and limitations

This section covers any known issues or limitations that might affect how you work with the {sdk-short-name} in specific environments or scenarios.
