= Highlights of what's new in {release}
:description: DFINITY Canister Software Development Kit Release Notes
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
:release: 0.6.21
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

The {release} release primarily consists of changes to support new features that are not yet complete, including fixes and updates to DFX commands, {proglang}, the {proglang} base library, and Candid.

== New features and capabilities

The most significant new features and capabilities include updates in the following functional areas:

* <<DFX,DFX>>
* <<Candid,Candid>>
* <<Motoko,Motoko>>

=== DFX

* Two new subcommands—`+get-wallet+` and `+set-wallet+`—have been added to the `+dfx identity+` command to support working with wallet canisters.
+
In a future release, you will be able to use these commands locally for testing purposes. However, the commands are not currently supported on any version of the {IC} network available for you to run locally or on the public {IC} network.

=== Candid

* link:https://github.com/dfinity/candid/blob/master/Changelog.md[Candid changelog]

=== Motoko

* The Motoko compiler now reports errors and warnings with an additional error code.
+
You can use the error code to look up a more detailed description for a given error by passing the `+--explain+` flag with a code to the compiler. 
+
Note that detailed descriptions are not yet available for most error codes and will be added incrementally in upcoming releases.


== Issues fixed in this release

This section covers any reported issues that have been fixed in this release.

== Known issues and limitations

This section covers any known issues or limitations that might affect how you work with the {sdk-short-name} in specific environments or scenarios.
