= Highlights of what's new in {release}
:description: DFINITY Canister Software Development Kit Release Notes
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:release: 0.6.26
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

The {release} release primarily consists of changes to support new features that are not yet complete, including fixes and updates to DFX commands, {proglang}, the {proglang} base library, and Candid.

== New features and capabilities

The most significant new feature included in this release is the publication of the link:../interface-spec/index{outfilesuffix}[_{IC} Interface Specification_].

The _{IC} Interface Specification_ details many technical properties that describe the lower-level interfaces for interacting with the {IC}. 
For example, the _{IC} Interface Specification_ describes the HTTPS endpoints that are exposed to handle incoming requests and how low-level bindings enable canisters to interact with system components. 

If you use existing tools—like the DFINITY Canister SDK or Canister Development Kit for Rust—to work with canisters, these tools interact with  lower-level interfaces described in the _{IC} Interface Specification_ on your behalf. 
If you want to create your own tooling for working with canisters, however, the _{IC} Interface Specification_ includes the technical details you need to understand how the {IC} external interfaces work.

If you are interested in expanding the {IC} ecosystem, you'll find information in the _{IC} Interface Specification_ to support the following kinds of development activity:

* Building front-end *agents* for user-facing interaction in any programming language, including popular languages such as Python, Golang, or C.
* Building *back-end Canister Development Kits* (CDKs) in any language that can compile down to WebAssembly bytecode.
* Building *local development tools* such as command line interfaces or Internet Computer emulators and debuggers.
* Implementing features and enhancements to improve the developer experience for deploying and managing canisters running remotely on the network.

== Issues fixed in this release

This section covers any reported issues that have been fixed in this release.

This release fixes an issue with memory allocation in the default cycles wallet that caused an error after creating and deploying canisters.
If you encountered this issue, you might have seen an error message similar to the following:

....
The Replica returned an error: code 5, message: "Canister 6dtaa-vaaaa-aaaab-aaipa-cai exceeded its allowed memory allocation"
....

This release updates the default cycles wallet to provide better handling of unused memory and how memory is allocated when creating and deploying canisters. 

== Known issues and limitations

This section covers any known issues or limitations that might affect how you work with the {sdk-short-name} in specific environments or scenarios.

The introduction of the cycles wallet canister changes the default principal used to perform key canister management tasks, such as registering a new canister identifier and deploying a new canister on the {IC}. 
This change introduces some inconsistencies in the identity used to perform certain tasks and can result in potential access control issues.

You should note that none of the tutorials have been updated to reflect this specific change in behavior yet and the current version of the link:../developers-guide/tutorials/access-control{outfilesuffix}[Add access control with identities] tutorial is known to be invalid for this release.
If you want to experiment with access control using the link:../developers-guide/tutorials/access-control{outfilesuffix}[Add access control with identities] tutorial, you should install the {sdk-short-name} version 0.6.23 (or older). 