= Highlights of what's new in {release}
:description: DFINITY Canister Software Development Kit Release Notes
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
:release: 0.8.2
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

An overview of the {release} release:

- Breaking change in how to specify a controller to `dfx canister create`

== Changes to DFX

=== Breaking change: controller parameter for dfx canister create

Breaking change: The controller parameter for `dfx canister create` is now passed as a named parameter,
rather than optionally following the canister name.

Old: dfx canister create [canister name] [controller]
New: dfx canister create --controller <controller> [canister name]

=== New feature: dfx canister create now accepts multiple instances of --controller argument

It is now possible to create canisters with more than one controller by
passing multiple instances of the `--controller parameter to `dfx canister create`.

You will need to upgrade your wallet with `dfx wallet upgrade`, or `dfx wallet --network ic upgrade`

=== New feature: dfx canister update-settings now accepts multiple instance of --controller argument

It is now possible to configure a canister to have more than one controller by
passing multiple instances of the `--controller parameter to `dfx canister update-settings`.

=== New feature: dfx canister info and dfx canister status now display all controllers

== Cycles Wallet

- Module hash: 9183a38dd2eb1a4295f360990f87e67aa006f225910ab14880748e091248e086
- https://github.com/dfinity/cycles-wallet/commit/9ef38bb7cd0fe17cda749bf8e9bbec5723da0e95

=== Added support for multiple controllers
