= Highlights of what's new in {release}
:description: DFINITY Canister Software Development Kit Release Notes
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
:release: 0.9.1
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

An overview of the {release} release:

Be sure to see the link:0.9.1-rn.adoc[0.9.1 Release Notes] and follow the instructions due to breaking changes since dfx 0.8.4.

== Changes to DFX

=== New Feature: Support for local ledger calls

If you have an installation of the ICP Ledger (see https://github.com/dfinity/ic/tree/master/rs/rosetta-api/ledger_canister#deploying-locally[Ledger Installation Guide]), `dfx ledger balance` and `dfx ledger transfer` now support
`--ledger-canister-id` parameter.

Some examples:
```
$ dfx ledger \
  --network local \
  balance \
  --ledger-canister-id  rrkah-fqaaa-aaaaa-aaaaq-cai
1000.00000000 ICP

$ dfx ledger \
  --network local \
  transfer --amount 0.1 --memo 0 \
  --ledger-canister-id  rrkah-fqaaa-aaaaa-aaaaq-cai 8af54f1fa09faeca18d294e0787346264f9f1d6189ed20ff14f029a160b787e8
Transfer sent at block height: 1
```

=== New Feature: `dfx ledger account-id` can now compute canister addresses

The `dfx ledger account-id` can now compute addresses of principals and canisters.
The command also supports ledger subaccounts now.

[source, bash]
----
dfx ledger account-id --of-principal 53zcu-tiaaa-aaaaa-qaaba-cai
dfx ledger --network small02 account-id --of-canister ledger_demo
dfx ledger account-id --of-principal 53zcu-tiaaa-aaaaa-qaaba-cai --subaccount 0000000000000000000000000000000000000000000000000000000000000001
----

=== New Feature: Print the full error chain in case of a failure

All `dfx` commands will now print the full stack of errors that led to the problem, not just the most recent error.
Example:

[source]
----
Error: Subaccount '00000000000000000000000000000000000000000000000000000000000000000' is not a valid hex string
Caused by:
  Odd number of digits
----

=== Fixed: dfx import will now import pem files created by `quill generate`

`quill generate` currently outputs .pem files without an `EC PARAMETERS` section.
`dfx identity import` will now correctly identify these as EC keys, rather than Ed25519.

=== Fixed: retry on failure for ledger create-canister, top-up, transfer

dfx now calls `transfer` rather than `send_dfx`, and sets the created_at_time field in order to retry the following commands:

* dfx ledger create-canister
* dfx ledger top-up
* dfx ledger transfer

== Motoko

Updated Motoko from 0.6.20 to 0.6.21.

== Replica

Updated replica to blessed commit 936bf9ccaabd566c68232e5cb3f3ce7d5ae89328.
This incorporates the following executed proposals:

* https://dashboard.internetcomputer.org/proposal/38541[38541]

== ic-ref

Upgraded from a432156f24faa16d387c9d36815f7ddc5d50e09f to ab8e3f5a04f0f061b8157c2889f8f5de05f952bb

* Support 128-bit system api for cycles
* Include canister_ranges in the state tree
* Removed limit on cycles in a canister
