= Highlights of what's new in {release}
:description: DFINITY Canister Software Development Kit Release Notes
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
:release: 0.9.2
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

An overview of the {release} release:

Be sure to see the link:0.9.0-rn[0.9.0 Release Notes] and follow the instructions due to breaking changes since dfx 0.8.4.

== Changes to DFX

=== New Feature: Verify Candid and Motoko stable variable type safety of canister upgrades

Newly deployed Motoko canisters now embed the Candid interface and Motoko stable signatures in the Wasm module.
`dfx deploy` and `dfx canister install` will automatically check

	1) the backward compatible of Candid interface in both upgrade and reinstall mode;
	2) the type safety of Motoko stable variable type in upgrade mode to avoid accidentally lossing data;

See https://smartcontracts.org/docs/language-guide/compatibility.html[Upgrade compatibility] for more details.

=== New Feature: Unified environment variables across build commands

The three canister types that use a custom build tool - `assets`, `rust`, and `custom` - now all support the same set of environment variables during the build task:

* `DFX_VERSION` - The version of DFX that was used to build the canister.
* `DFX_NETWORK` - The network name being built for. Usually `ic` or `local`.
* `CANISTER_ID_{canister}` - The canister principal ID of the canister `{canister}` registered in `dfx.json`.
* `CANISTER_CANDID_PATH_{canister}` - The path to the Candid interface file for the canister `{canister}` among your canister's dependencies.
* `CANISTER_CANDID_{canister}` (deprecated) - the same as `CANISTER_CANDID_PATH_{canister}`.  This is provided for backwards compatibility with `rust` and `custom` canisters, and will be removed in dfx 0.10.0.
* `CANISTER_ID` - Same as `CANISTER_ID_{self}`, where `{self}` is the name of _this_ canister.
* `CANISTER_CANDID_PATH` - Same as `CANISTER_CANDID_PATH_{self}`, where `{self}` is the name of _this_ canister.


=== New Feature: Support for local ledger calls

If you have an installation of the ICP Ledger (see https://github.com/dfinity/ic/tree/master/rs/rosetta-api/ledger_canister#deploying-locally[Ledger Installation Guide]), `dfx ledger balance` and `dfx ledger transfer` now support
`--ledger-canister-id` parameter.

Some examples:
[source, base]
----
$ dfx ledger \
  --network local \
  balance \
  --ledger-canister-id  rrkah-fqaaa-aaaaa-aaaaq-cai
1000.00000000 ICP

$ dfx ledger \
  --network local \
  transfer --amount 0.1 --memo 0 \
  --ledger-canister-id  rrkah-fqaaa-aaaaa-aaaaq-cai 8af54f1fa09faeca18d294e0787346264f9f1d6189ed20ff14f029a160b787e8
Transfer sent at block height: 1
----

=== New Feature: `dfx ledger account-id` can now compute canister addresses

The `dfx ledger account-id` can now compute addresses of principals and canisters.
The command also supports ledger subaccounts now.

[source, bash]
----
dfx ledger account-id --of-principal 53zcu-tiaaa-aaaaa-qaaba-cai
dfx ledger --network small02 account-id --of-canister ledger_demo
dfx ledger account-id --of-principal 53zcu-tiaaa-aaaaa-qaaba-cai --subaccount 0000000000000000000000000000000000000000000000000000000000000001
----

=== New Feature: Print the full error chain in case of a failure

All `dfx` commands will now print the full stack of errors that led to the problem, not just the most recent error.
Example:

[source]
----
Error: Subaccount '00000000000000000000000000000000000000000000000000000000000000000' is not a valid hex string
Caused by:
  Odd number of digits
----

=== Fixed: dfx import will now import pem files created by `quill generate`

`quill generate` currently outputs .pem files without an `EC PARAMETERS` section.
`dfx identity import` will now correctly identify these as EC keys, rather than Ed25519.

=== Fixed: retry on failure for ledger create-canister, top-up, transfer

dfx now calls `transfer` rather than `send_dfx`, and sets the created_at_time field in order to retry the following commands:

* dfx ledger create-canister
* dfx ledger top-up
* dfx ledger transfer

== Motoko

Updated Motoko from 0.6.20 to 0.6.21.

== Replica

Updated replica to blessed commit 04fe8b0a1262f07c0cec1fdfa838a37607370a61.
This incorporates the following executed proposals:

* https://dashboard.internetcomputer.org/proposal/45091[45091]
* https://dashboard.internetcomputer.org/proposal/43635[43635]
* https://dashboard.internetcomputer.org/proposal/43633[43633]
* https://dashboard.internetcomputer.org/proposal/42783[42783]
* https://dashboard.internetcomputer.org/proposal/42410[42410]
* https://dashboard.internetcomputer.org/proposal/40908[40908]
* https://dashboard.internetcomputer.org/proposal/40647[40647]
* https://dashboard.internetcomputer.org/proposal/40328[40328]
* https://dashboard.internetcomputer.org/proposal/39791[39791]
* https://dashboard.internetcomputer.org/proposal/38541[38541]

== ic-ref

Upgraded from a432156f24faa16d387c9d36815f7ddc5d50e09f to ab8e3f5a04f0f061b8157c2889f8f5de05f952bb

* Support 128-bit system api for cycles
* Include canister_ranges in the state tree
* Removed limit on cycles in a canister
