= Developer Release Notes
:toc:
:toc: right
:toc-title: QUICK LINKS
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:page-layout: releasenotes
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:release: 0.6.2
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

The {sdk-long-name} enables developers to develop applications for the {IC} using the {proglang} programing language.
{proglang} is a new programming language optimized for creating tamper-proof software and open internet services that will be hosted on the Internet Computer.

The {sdk-short-name} provides everything you need to perform the following key tasks:

- Author canisters in {proglang} and compile them to WebAssembly.
- Run {IC} replica processes locally on your development computer.
- Deploy compiled programs as standalone canisters and interact with the canisters using a command-line interface.

This {release} version of the {sdk-long-name} is an interim update of the Alpha release recently shared with the development community and made available to the public for preliminary testing, demonstration, and exploration.
As part of our commitment to continuous improvement and iterative development focused on addressing developer feedback, this version includes numerous fixes and enhancements.

[IMPORTANT]
=====================================================================
Note that {sdk-long-name} and {proglang} programming language are Alpha-quality releases intended to give you an early look at the potential for building applications that run on the {IC}.
This {release} version of the software and programming language should not be used for developing production applications at this time.
=====================================================================

== Highlights of what's new in {release}

The {release} release only includes the following user-facing change which is also a breaking change:

- In this release, all canister identifiers are generated using a text-based representation.
+
To work with this release, you should delete any existing canisters, then regenerate new canister identifiers using the `+dfx canister create+` command and redeploy the updated canisters with the `+dfx canister install+` command to begin using the new text-based identifiers.

The 0.6.1 release only included the following user-facing changes:

- An update to the `+dfx ping+` command enables you to specify a network name to check the status of a network connection.
- An update to the user authentication method enables `+dfx+` to use the browser's `+localStorage+` for the user's public and private keys if cookies are not enabled.
- Motoko programming guidelines are now available as part of the programming language guide on the link:../language-guide/style{outfilesuffix}[SDK website].

All other new features and enhancements described below were included in the 0.6.0 release.

=== SDK

- You can now look up a canister identifier using the command `dfx canister id <canister_name>`
- The `--check` flag can be used with the `dfx build` command to check whether a canister will build before creating or building the canister
- Both canister name and identifiers are printed upon canister creation
- The `dfx.json` configuration file has a new field—`+defaults/build/packtool+`—to support the Vessel package manager.
- The `dfx.json` file supports canister new types—`motoko`, `assets`, and `custom`—to allow different build tools to be used for building canisters:
+
** The `motoko` canister type uses the `motoko` compiler to build a canister.
+
** The  `assets` canister type uses `npm run build` (optionally) to build files and uploads them to an asset canister
+
** The `custom` canister type uses a custom builder that should output WASM and DID files.
- The `dfx.json` file includes network mapping for `local` and `Tungsten` networks. The local network defaults to `127.0.0.1:8000`.

=== Tungsten (Developer Network)

- HTTP authorization and credentials management for onboarded Tungsten users
- `Tungsten` added as a provider in `dfx.json
- You can use the `dfx ping` command to ping an Internet Computer and request its status
- The `--network <network>` flag can be used to build and install canisters to the specified provider
- Canister ID formatting for accessing Tungsten-deployed apps in the browser

=== Motoko

- The `motoko-base` repository is now open. We encourage developers to use Vessel package manager to download the latest `base` from `master`.
- Stable variable support
- Released `mo-doc` for generating documentation from Motoko comments
- Better support for `Char` and `Text` module
- `Error` module for rejecting messages
- `Buf` module renamed to `Buffer`

== Breaking changes
The {release} release includes the following changes that might require updates to existing programs:

- Major breaking changes and updates to Motoko as detailed here: https://github.com/dfinity/motoko-base/issues/37
- The command `dfx new` now creates a separate assets canister. Programs built with earlier versions of the SDK may need to be converted to this new format.
- You must now create empty canisters before building and installing using the subcommand `dfx canister create`.
- `dfx canister call` will consult the Candid file for method types. You no longer need to use `--type string/number`. The arguments are therefore deprecated.

== Issues fixed in this release

This section covers the issues fixed in this release.
The {release} release includes internal fixes and improvements to the Candid user interface, the interface description library, and some refactoring of `dfx` commands.

- Certification validation error fixed on Linux and NixOS
- `dfx stop` now finds and kills all `dfx start` and `dfx replica` processes
- Allow lowercase hex in Canister ID
- Allow installation without sudo when possible
- Install script issues resolved for Ubuntu and Mac
- Check added to forbid starting webserver with a forwarded port
- Cache directory management and error messages
- Improved error messages for HTTP server error

== Known issues and limitations

This section covers any known issues or limitations that might affect how you work with the {sdk-short-name} in specific environments or scenarios.
If there are workarounds to any of the issues described in this section, you can find them in the link:../developers-guide/troubleshooting{outfilesuffix}[Troubleshooting] section.

== Additional questions and feedback

Check out link:../developers-guide/troubleshooting{outfilesuffix}[Troubleshooting] for additional technical support.
