= Developer Release Notes
:description: DFINITY Canister Software Development Kit Release Notes
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
:release: 0.7.2
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

The {sdk-long-name} enables developers to develop applications to run on the {IC}.
The {proglang} new programming language is bundled with the {sdk-long-name} to provide native support for creating tamper-proof software and open internet services.

The {sdk-short-name} provides everything you need to perform the following key tasks:

- Author canisters in {proglang} and compile them to WebAssembly.
- Simulate the {IC} network running locally on your development computer.
- Deploy compiled programs as link:../developers-guide/glossary{outfilesuffix}#g-canister[canisters].
- Interact with your application service using a command-line interface or through a web browser.

[NOTE]
=====================================================================
The current release of the {sdk-long-name} is intended to introduce you to building applications that run on the {IC} and to provide access to the {IC} network for application testing, demonstration, and exploration..
The {sdk-long-name} should not be used for developing _production applications_ at this time.
=====================================================================

== Known issues and limitations

This section covers any known issues or limitations that might affect how you work with the {sdk-short-name} in specific environments or scenarios.

* Creating a new project displays errors or warnings.
+
By default, creating a new project installs node dependencies to support building a front-end for your project. 
+
Depending on your environment, the installation of node dependencies might display errors or warnings generated by the `+npm+` package manager. 
+
The errors and warnings issued by the `+npm+` package manager do not prevent you from successfully creating a new project and, in most cases, can be safely ignored.

== Additional questions and feedback

Joining the link:https://forum.dfinity.org/[DFINITY Developer Forum] is an effective way to learn from community members, ask questions, solicit help from other developers, and provide insight and feedback about your experiences.

If you have questions that aren't answered by the community, you might also want to check out link:../developers-guide/troubleshooting{outfilesuffix}[Troubleshooting] topics for information about common issues, workarounds for known issues, or help troubleshooting warnings or errors.

For technical support, send email to mailto:support@dfinity.org[DFINITY Support].

A self-service Help Center of Knowledge Base articles will also be coming soon.
