= Developer Release Notes
:toc:
:toc: right
:toc-title: QUICK LINKS
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:ext: .mo
:company-id: DFINITY
:page-layout: releasenotes
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:release: 0.5.6
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

The {sdk-long-name} enables developers to develop applications for the {IC} using the {proglang} programing language.
{proglang} is a new programming language optimized for creating tamper-proof software and open internet services that will be hosted on the Internet Computer.

The {sdk-short-name} provides everything you need to perform the following key tasks:

- Author canisters in {proglang} and compile them to WebAssembly.
- Run {IC} client processes locally on your development computer.
- Deploy compiled programs as standalone canisters and interact with the canisters using a command-line interface.

This {release} version of the {sdk-long-name} is an interim update of the Alpha release recently shared with the development community and made available to the public for preliminary testing, demonstration, and exploration.
As part of our commitment to continuous improvement and iterative development focused on addressing developer feedback, this version includes numerous fixes and enhancements.

[IMPORTANT]
=====================================================================
Note that {sdk-long-name} and {proglang} programming language are Alpha-quality releases intended to give you an early look at the potential for building applications that run on the {IC}.
This {release} version of the software and programming language should not be used for developing production applications at this time.
=====================================================================

== Highlights of what's new in {release}

The {release} release includes the following new features and capabilities:

- {proglang}, the Candid interface description language, and the Candid UI now support floating point numbers (float64).
- When using the Candid UI, you can view return values in the following formats:
+
    - using the interface description language syntax
    - as values displayed in fields using a browser
    - as JSON fields.
+
You can switch between the formats for representing values by clicking the results bar.
- Internal updates that are not yet user-visible to support future features.

== Breaking change
The {release} release includes the following changes that might require updates to existing programs:

- The name of the library recognized by the {proglang} compiler has changed from `stdlib` to `base`.
+
If you have programs that rely on modules `base` library, you must change the `import` statement to use the new library name.
For example, you might have previously imported the Array module using the following statement:
+
[source,motoko]
----
import Array "mo:stdlib/Array";
----
+
With this release, you would change the statement like this:
+
[source,motoko]
----
import Array "mo:base/Array";
----
- The modules in the Motoko base library are case-sensitive.
With this release, all of the module names have been modified to start with an uppercase letter.
If you have programs that refer to modules in the `base` library using lowercase names, you must change the program to use the new naming convention.
+
For example, if you previously referred to the `array` module, you would change the program to ref to the `Array` modules.

== Issues fixed in this release

This section covers the issues fixed in this release.
The {release} release includes internal fixes and improvements to the Candid user interface, the interface description library, and some refactoring of `dfx` commands.

== Known issues and limitations

This section covers any known issues or limitations that might affect how you work with the {sdk-short-name} in specific environments or scenarios.
If there are workarounds to any of the issues described in this section, you can find them in the link:../developers-guide/troubleshooting{outfilesuffix}[Troubleshooting] section.

The {release} release includes the following known issues and limitations:

- Float support in the {proglang} programming language that is compiled to WebAssembly.
+
Although {proglang} recognizes floating point numbers, there are some limitations related to the deterministic requirements of the {IC} that can create issues when compiling {proglang} source code that includes floating point data types into WebAssembly for deployment.
To simplify the development of test and demonstration programs that run on the current {release} release, you should avoid using Float data types for now.

- Using fixed-length Word data type arguments when running `+dfx+` commands.
+
Fixed-length Word32 data types are not yet supported in the `+dfx+` command-line interface.
As an alternative, you can convert integers to Word32 using the standard library function `+int32ToWord32(intToInt32(value))+`` until the support for fixed-length Word32 and Nat32 data types is added.

== Additional questions and feedback

Check out link:../developers-guide/troubleshooting{outfilesuffix}[Troubleshooting] for additional technical support.
