= Developer Release Notes
:toc:
:toc: right
:toc-title: QUICK LINKS
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:ext: .mo
:company-id: DFINITY
:page-layout: releasenotes
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:release: 0.6.0
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

The {sdk-long-name} enables developers to develop applications for the {IC} using the {proglang} programing language.
{proglang} is a new programming language optimized for creating tamper-proof software and open internet services that will be hosted on the Internet Computer.

The {sdk-short-name} provides everything you need to perform the following key tasks:

- Author canisters in {proglang} and compile them to WebAssembly.
- Run {IC} replica processes locally on your development computer.
- Deploy compiled programs as standalone canisters and interact with the canisters using a command-line interface.

This {release} version of the {sdk-long-name} is an interim update of the Alpha release recently shared with the development community and made available to the public for preliminary testing, demonstration, and exploration.
As part of our commitment to continuous improvement and iterative development focused on addressing developer feedback, this version includes numerous fixes and enhancements.

[IMPORTANT]
=====================================================================
Note that {sdk-long-name} and {proglang} programming language are Alpha-quality releases intended to give you an early look at the potential for building applications that run on the {IC}.
This {release} version of the software and programming language should not be used for developing production applications at this time.
=====================================================================

== Highlights of what's new in {release}

The {release} release includes the following new features and capabilities:

=== SDK

- You can now look up a canister identifier using the command `dfx canister id <canister_name>`.
- The `--check` flag can be used with the `dfx build` command to check whether a canister will build before creating or building the canister.
- Both canister name and identifiers are printed upon canister creation.
- Canister manifest now stores multiple canister IDs associated with local and remote networks as well as network mapping.

=== Tungsten (Developer Network)

- HTTP authorization and credentials management for onboarded Tungsten users.
- `Tungsten` added as a provider in `dfx.json`
- You can use the `dfx ping` command to access and toggle between local and Tungsten networks.
- The `--network <network>` flag can be used to build and install canisters to the specified provider.
- Canister ID formatting for accessing Tungsten-deployed apps in the browser.

=== Motoko

- Stable variable support
- Improved type checking of literals as payload for variant tags. The following will now type-check:
`func () : { #tag : Nat8 } = #tag 42;`
- Warning when the read file has a different name from the requested file.
- `debug_show` implemented for `Principal`
- Type hash implementation

== Breaking changes
The {release} release includes the following changes that might require updates to existing programs:

- The command `dfx new` now creates a separate assets canister. Programs built with earlier versions of the SDK may need to be converted to this new format. 
- You must now create empty canisters before building and installing using the subcommand `dfx canister create`.
- `string` and `number` are no longer supported as arguments to the `--type` flag for `dfx canister call` commands.
- Methods starting with `__` will break, as those are not implemented anymore.
- When creating an actor, you need to pass in the canister ID.

== Issues fixed in this release

This section covers the issues fixed in this release.
The {release} release includes internal fixes and improvements to the Candid user interface, the interface description library, and some refactoring of `dfx` commands.

- `dfx stop` now finds and kills all `dfx start` and `dfx replica` processes.
- Various references changed from `client` to `replica`.
- Allow lowercase hex in Canister ID.
- Canister name now used for WASM and DID output.
- Allow installation without sudo when possible.
- Install script issue resolved for Ubuntu.
- Check added to forbid starting webserver with a forwarded port.

== Known issues and limitations

This section covers any known issues or limitations that might affect how you work with the {sdk-short-name} in specific environments or scenarios.
If there are workarounds to any of the issues described in this section, you can find them in the link:../developers-guide/troubleshooting{outfilesuffix}[Troubleshooting] section.

The {release} release includes the following known issues and limitations:

== Additional questions and feedback

Check out link:../developers-guide/troubleshooting{outfilesuffix}[Troubleshooting] for additional technical support.
