= Developer Release Notes
:toc:
:toc: right
:toc-title: QUICK LINKS
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:page-layout: releasenotes
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:release: 0.6.9
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

The {sdk-long-name} enables developers to develop applications for the {IC} using the {proglang} programing language.
{proglang} is a new programming language optimized for creating tamper-proof software and open internet services that will be hosted on the Internet Computer.

The {sdk-short-name} provides everything you need to perform the following key tasks:

- Author canisters in {proglang} and compile them to WebAssembly.
- Run {IC} replica processes locally on your development computer.
- Deploy compiled programs as standalone canisters and interact with the canisters using a command-line interface.

This {release} version of the {sdk-long-name} is an interim update of the Alpha release recently shared with the development community and made available to the public for preliminary testing, demonstration, and exploration.
As part of our commitment to continuous improvement and iterative development focused on addressing developer feedback, this version includes numerous fixes and enhancements.

[IMPORTANT]
=====================================================================
Note that {sdk-long-name} and {proglang} programming language are Alpha-quality releases intended to give you an early look at the potential for building applications that run on the {IC}.
This {release} version of the software and programming language should not be used for developing production applications at this time.
=====================================================================

[[highlights]]
== Highlights of what's new in {release}

The {release} release includes both user-visible new features and internal enhancements and fixes. The most significant new features and capabilities include the following:

* You can now register, build, and deploy applications with a single command.
+
This release introduces a simplified developer workflow using the the `+dfx deploy+` command.
You can use this command to replace running the following commands as separate steps:
+
....
dfx canister create --all
dfx build
dfx canister install -all
....
+
For a preview of how to use the simplified developer workflow, see https://sdk.dfinity.org/docs/quickstart/dfx-deploy-quickstart.html[Developer Workflow Preview].

* You can now specify arguments on the command-line when you deploy a **single** canister using the `+dfx canister install+` command.
+
For example, you might use the following command to add the `+self+` Text argument when deploying the canister named `+profile_map+` locally.
+
....
dfx canister install profile_map '("self")'
....
+
Note that you specify the argument you want to pass using the Candid interface description format.

* A new `+--memory allocation+` command-line option enables you to specify a memory allocation when deploying a canister.

* The `+dfx identity new+` command has been enhanced to display a confirmation message when adding a new identify is successful.

* Key updates for {proglang} (0.4.4) include backend support for the following features:

** Preliminary support for importing and exporting actor classes and for dynamic canister installation.
** Unit installation arguments for actors.
** Improved error handling for actor classes and input/output exceptions.
** Improved garbage collection.

This release also includes the following BREAKING CHANGE: 

* The Motoko compiler no longer supports variable or type declarations before defining an actor or an actor class. 
Only import declarations can be used as leading declarations for programs that define an actor or an actor class.

=== Highlights of what's new in 0.6.7

The 0.6.7 release includes the following new features and capabilities:

* The `+dfx build+` command now supports building a specific canister, in addition to building all canisters.
+
For example, you can compile the code for a back-end canister without building the canister used for your project's front-end assets.
+
Because of this change to the `+dfx build+` command, the `+--skip-frontend+` option is no longer needed and has been removed.
* There are several new `+dfx identity+` commands that enable you to create, manage, and switch between different user identities when communicating with the {IC} network.
+
You can also use a new `+--identity+` command-line option to set a specific user context when running `+dfx+` commands. 
+
This new support for multiple identities enables you to test role-based access control for your programs.
* Updates to the Candid argument parser in `+dfx canister call+` include the following user-facing features:
+
** Support type annotations when parsing Candid values. For example, you can use the following syntax to specify types:
+
....
(42: nat8, vec {1;-3;5} : vec int8)
....
** Support for pretty-print decoded Candid values:
+
`+--output pp+` is the default and prints the value in multiple lines.
+
`+--output idl+` prints the value in a single line.
** Support for `+float e+` notation.
** Support for Rust-like parsing errors.
* Key updates for {proglang} include the following:
+
** Support for polymorphic equality that enables the `==` and `!=` operators to work on all shareable types.
** Improvements to catch clashing function and class declarations.
** Language support to enable canisters to take installation arguments.
** Optimized backend handling for `Bool` data types.

=== Highlights of what's new in 0.6.6

The 0.6.6 release features several new commands for managing canisters.
The release include the following new commands for managing canister operations and the canister lifecycle:

- The `+dfx canister status+` command enables you to check whether all canisters or a specific canister in a project are currently running.
- The `+dfx canister stop+` command enables you to stop all canisters or a specific canister in a project to prevent canisters from receiving new requests.
- The `+dfx canister start+` command enables you to restart all canisters or a specific canister in a project so they can resume receiving new requests.
- The `+dfx canister delete+` command enables you to delete all canisters or a specific canister in a project.

=== Highlights of what's new in 0.6.4

The 0.6.4 release primarily included internal improvements that are not user-facing.
The only user-facing features and fixes in the 0.6.4 release are the following:

- A new Reserved type has been added to the JavaScript agent library.
- Fixed the timer that is used in the Candid UI when issuing function calls.

For information about breaking changes that were introduced in the previous releases, see <<Breaking changes>>.

For information about known issues that were introduced in the previous releases, see <<Known issues and limitations>>.

=== Highlights of what's new in 0.6.3

The 0.6.3 release only included minor fixes and enhancements including the following:

- The `+dfx start --clean+` command has been improved to no longer crash if you run the command in a project that is already in a clean state.
+
Without this fix, manually removing the directories the command is intended to delete would result in `+dfx+` exiting without restarting the {IC}.
- The parsing logic for the `+dfx canister call+` command has been improved to more consistently recognize arguments in Candid format and to return better error messages  when argument formats are not recognized.
- The Welcome page displayed when you create a new project has been updated to reflect the current location of SDK and Motoko documentation.

=== Highlights of what's new in 0.6.2

The 0.6.3 release only included one important user-facing change which was also a breaking change that required you to update all existing projects.

Starting with the 0.6.3 release, all canister identifiers are generated using a text-based representation.
To work with the {release} release, therefore, you must update your projects to use the new canister identifier format.

If you are connected to the {IC} running locally, do the following in **each project directory**:

. Stop the {IC} by running the following command:
+
[source,bash]
----
dfx stop
----
. Restart the {IC} in a clean state by running the following command:
+
[source,bash]
----
dfx start --clean
----
+
This command removes all existing canister state and build output.
. Generate new textual canister identifiers by running the following command:
+
[source,bash]
----
dfx canister create --all
----
. Redeploy the updated canisters to use the new text-based identifiers by running the following command:
+
[source,bash]
----
dfx canister install --all
----

=== Highlights of what's new in 0.6.1

The 0.6.1 release only included the following user-facing changes:

- An update to the `+dfx ping+` command enables you to specify a network name to check the status of a network connection.
- An update to the user authentication method enables `+dfx+` to use the browser's `+localStorage+` for the user's public and private keys if cookies are not enabled.
- Motoko programming guidelines are now available as part of the programming language guide on the link:../language-guide/style{outfilesuffix}[SDK website].

=== Highlights of what's new in 0.6.0

The 0.6.0 release included many new features and enhancements.
The following sections describe the key features and enhancements that were introduced in the 0.6.0 release. 

==== SDK

- You can now look up a canister identifier using the command `dfx canister id <canister_name>`
- The `--check` flag can be used with the `dfx build` command to check whether a canister will build before creating or building the canister
- Both canister name and identifiers are printed upon canister creation
- The `dfx.json` configuration file has a new field—`+defaults/build/packtool+`—to support the Vessel package manager.
- The `dfx.json` file supports canister new types—`motoko`, `assets`, and `custom`—to allow different build tools to be used for building canisters:
+
** The `motoko` canister type uses the `motoko` compiler to build a canister.
+
** The  `assets` canister type uses `npm run build` (optionally) to build files and uploads them to an asset canister
+
** The `custom` canister type uses a custom builder that should output WASM and DID files.
- The `dfx.json` file includes network mapping for `local` and `Tungsten` networks. The local network defaults to `127.0.0.1:8000`.

==== Tungsten (Developer Network)

- HTTP authorization and credentials management for onboarded Tungsten users
- `Tungsten` added as a provider in `dfx.json
- You can use the `dfx ping` command to ping an Internet Computer and request its status
- The `--network <network>` flag can be used to build and install canisters to the specified provider
- Canister ID formatting for accessing Tungsten-deployed apps in the browser

==== Motoko

- The `motoko-base` repository is now open. We encourage developers to use Vessel package manager to download the latest `base` from `master`.
- Stable variable support
- Released `mo-doc` for generating documentation from Motoko comments
- Better support for `Char` and `Text` module
- `Error` module for rejecting messages
- `Buf` module renamed to `Buffer`

== Breaking changes

In addition to the change described in xref:highlights[Highlights of what's new], the {release} release includes the following changes that might require updates to existing programs:

- Major breaking changes and updates to Motoko as detailed here: https://github.com/dfinity/motoko-base/issues/37
- The command `dfx new` now creates a separate assets canister. Programs built with earlier versions of the SDK may need to be converted to this new format.
- You must now create empty canisters before building and installing using the subcommand `dfx canister create`.
- `dfx canister call` will consult the Candid file for method types. You no longer need to use `--type string/number`. The arguments are therefore deprecated.

== Issues fixed in this release

This section covers the issues fixed in this release.
The {release} release includes internal fixes and improvements to the Candid user interface, the interface description library, and some refactoring of `dfx` commands.

- Certification validation error fixed on Linux and NixOS
- `dfx stop` now finds and kills all `dfx start` and `dfx replica` processes
- Allow lowercase hex in Canister ID
- Allow installation without sudo when possible
- Install script issues resolved for Ubuntu and Mac
- Check added to forbid starting webserver with a forwarded port
- Cache directory management and error messages
- Improved error messages for HTTP server error

== Known issues and limitations

This section covers any known issues or limitations that might affect how you work with the {sdk-short-name} in specific environments or scenarios.
If there are workarounds to any of the issues described in this section, you can find them in the link:../developers-guide/troubleshooting{outfilesuffix}[Troubleshooting] section.

- Creating a new project displays errors or warnings
+
By default, creating a new project installs node dependencies to support building a front-end for your project. 
+
Depending on your environment, the installation of node dependencies might display errors or warnings generated by the `+npm+` package manager. 
For example, you might see errors or warnings similar to the following on macOS:
+
....
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/13.7.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pubs/hello/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v13.7.0
gyp ERR! node-gyp -v v5.0.5
⠴ Installing node dependencies...
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"13.7.0","npm":"6.13.6"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN hello_assets@0.1.0 No repository field.
npm WARN hello_assets@0.1.0 No license field.
....
+
The errors and warnings issued by the `+npm+` package manager do not prevent you from successfully creating a new project and, in most cases, can be safely ignored.

== Additional questions and feedback

Check out link:../developers-guide/troubleshooting{outfilesuffix}[Troubleshooting] for additional technical support.
