= Glossary
:sdk-short-name: DFINITY Canister SDK
:stem: latexmath :stem: latexmath
:icons: font

This section provides definitions for terms used to describe the {IC} and the internal workings of the {IC} protocol in technical documentation and specifications.

include::developers-guide:page$glossary.adoc[leveloffset=2,tag=g-app-canister]

[[application-state]]
application state::
 Compiled WebAssembly (wasm) module implementing the <<g-canister,canister’s>> functionality and its dependent modules, together with an instance of each of the modules.

[[batch]]
batch::
 An ordered set of <<g-message,messages>> that have been agreed-upon order by a sufficient number of <<g-replica, replicas>>, and finalized by <<g-consensus,consensus>>.
 Once assembled into a batch, the messages are available for the <<message-routing,message routing>> layer to add to the <<induction-pool,induction pool>>.

[[bounded-time--eventual-delivery]]
bounded-time / eventual delivery::
 The <<g-node,nodes>> (IC replicas) of a <<sub-network,subnet>> form a dedicated <<peer-to-peer,peer-to-peer>> broadcast network that facilitates the secure “bounded-time/eventual delivery” broadcast of artifacts (such as <<ingress-message,ingress messages>>, control messages and their signature shares). 
 More precisely, up to a certain maximum volume of valid artifacts that are not dropped by any honest <<g-node,node>> reaches all honest nodes in bounded time/eventually, despite attacks (under certain network assumptions). 
 The <<g-consensus,consensus>> layer builds upon this functionality.

include::developers-guide:page$glossary.adoc[leveloffset=2,tag=g-canister]

[[canister-pool]]
canister pool::
 The collection of all <<g-canister,canisters>> on any given <<sub-network,subnet>>.

[[canister-messages]]
canister messages::
 A message sent from one <<g-canister,canister>> to another. Note that a <<g-canister,canister>> message can be an application-generated <<g-message,message>> sent from one <<g-canister,canister>> to another or a system-generated <<g-message,message>> sent from one <<g-canister,canister>> to another and that the <<g-canister,canisters>> can be on the same or different <<sub-network,subnets>>. This type of message is also referred to as a *canister-to-canister* message or an <<inter-canister-message,inter-canister call>>.

[[canister-migration]]
canister migration::
 The system services and components that interact with the replica and NetOS to enable <<g-canister,canisters>> to be moved from one <<sub-network,subnet>> to another.
 CanisterMigration is a sub-component of NetOS (and part of the <<g-replica,replica>>) involved in migrating <<application-canister,application canisters>> from one <<sub-network,subnet>> to another.

[[canister-state]]
canister state::
 The entire current state of a <<g-canister,canister>>, consisting of the <<application-state,application state>> and the <<system-state, system state>>, and the <<g-canister,canister’s>> code (excluding the Input and OutputQueues).

[[catch-up-package-CUP]]
catch-up package (CUP)::
Contains all necessary data to bootstrap a <<sub-network,subnet>> participant.

[[certified-non-mutating-query]]
certified non-mutating query::
A query call that reads data from a <<g-node,node>> that has been
cryptographically certified by a quorum of <<g-node,nodes>>.

[[certified-variables]]
certified variables::
Global variables that are signed by the hosting <<sub-network,subnet>> after each round, such that it can be exposed to users much faster than the rest of the <<canister-state,canister state>>.

[[g-consensus]]
consensus::
In distributed computing, *consensus* is a fault tolerant mechanism by which a sufficient number of processes in a group can reach agreement about a value or state.
+
For the <<internet-computer, Internet Computer>>, *consensus* is a core component of the <<g-replica,replica>> software. The consensus layer selects <<g-message, messages>> from the peer-to-peer artifact pool and pulls <<g-message,messages>> from the cross-network streams of other <<sub-network,subnets>> and organizes them into a <<batch>> with a sequence that sufficiently many <<g-replica,replicas>> agree upon before the batch is delivered to the <<message-routing, message routing>> layer.

include::developers-guide:page$glossary.adoc[leveloffset=2,tag=g-controller]

[[Cryptographic-Service-Provider-CSP]]
Cryptographic Service Provider (CSP)::
*Cryptographic Service Provider (CSP)* sub-component that performs all cryptographic operations, such as randomness generation and public and secret key operations. The CSP interface allows one to reference algorithms and secret keys by their identifiers. The secret key values are then picked up from the key store, while the public key values are passed directly to the CSP interface. This component is unaware of the specifics of the https://internetcomputer.org<<internet-computer, Internet Computer>> platform, such as message types, identities and algorithms mapping, and so on. The CSP contains the stateless implementation of all cryptographic algorithms (together with the low-level group operations) that are used within the https://internetcomputer.org
<<internet-computer, Internet Computer>>.

[[CSP]]
CSP::
See <<Cryptographic-Service-Provider-CSP,Cryptographic Service Provider (CSP)>>.

[[CUP]]
CUP::
See <<catch-up-package-CUP, catch-up package (CUP)>>.

include::developers-guide:page$glossary.adoc[leveloffset=2,tag=g-cycles]

[[data-center-provider]]
__((Data Center Provider__::

[[default-canister]]
__((default canister__::

[[DFN-tokens]]
DFN tokens::
__**Deprecated** terminology for the <<internet-computer,Internet Computer>> native currency. The native currency was previously referred to as https://internetcomputer.org[Internet Computer] network tokens or as DFN. 
The native currency is now referred to as ICP tokens.
__

[[distributed-key-generation-DKG]]
__((distributed key generation (DKG)__::

[[epoch]]
epoch::
Represents the number of consecutive <<g-consensus,consensus>> rounds during which the <<subnet-protocol-replica,subnet>> membership stays the same and <<g-consensus,consensus>> can reach finalization with a very high degree of probability guarantee.

[[eventual-delivery-bounded-time]]
eventual delivery / bounded-time::
See <<bounded-time--eventual-delivery, Bounded-time / eventual delivery>>.

[[execution-cycle]]
execution cycle::
An event invoked by the <<message-routing, message routing>> scheduler upon receipt of a new InputBlock during which it executes as much of the induction pool as possible

[[execution-environment]]
execution environment::
For the <<<internet-computer, Internet Computer>>>, the <<execution-environment,execution environment>> is a core component of the <<g-replica,replica>> software. The <<execution-environment, execution environment>> provides a runtime environment for executing <<WebAssembly>> modules. After the <<message-routing, message routing>> layer identifies the <<g-canister,canister>> that will handle processing for an <<ingress-message,ingress message>>, the <<execution-environment,execution environment>> processes the <<g-message,message>> in the order in which it receives it.

[[funding-partners-FP]]
__((funding partners (FP)__::

[[gas]]
gas::
**Deprecated** terminology that represents the unit of measurement for resources consumed in the form of processing time, memory an application requires for storage, and network bandwidth. The gas used
to pay for resources consumed by a <<g-canister,canister>> is held in an account on behalf of a user or an application.

[[genesis-token-canister-GTC]]
genesis token canister (GTC)::
A genesis token <<g-canister,canister>> is a special <<g-canister,canister>> for funding partners and seed-round investors that contains ICP tokens issued at the launch of the Internet Computer public network (the genesis event).

[[gossip-protocol]]
gossip protocol::
A *gossip protocol* is a common approach to communication for distributed systems that is analogous to how information spreads from person to person in a social network. With a *gossip protocol*, information spreads from computer to computer in the form of broadcast <<g-message,messages>> with each computer only disseminating the information to its network neighbors.
For the Internet Computer, gossip is used in the peer-to-peer layer of the <<g-replica,replica>> to advertise the artifacts the <<g-replica,replica>> has received to the neighboring peers it has been assigned.

[[GTC]]
GTC::
See <<genesis-token-canister-GTC, genesis token canister (GTC)>>.

[[ICA]]
ICA::
See <<Internet-Computer-Association-ICA, Internet Computer Association (ICA)>>.

[[ICNS]]
ICNS::
*Deprecated*. See <<g-nns,network nervous system (NNS)>>

[[ICP]]
ICP::
See <<Internet-Compute-Provider-ICP, Internet Compute Provider (ICP)>>.

[[ICPId]]
ICPId::
*Deprecated*. See <<Internet-Compute-Provider-Identity-ICPId, Internet Compute Provider Identity (ICPId)>>.

[[induction-pool]]
induction pool::
Collection of input queues of all <<g-canister, canisters>> on a <<sub-network,subnet>>.

[[ingress-message]]
ingress message::
A <<g-message,message>> sent by an end-user to an <<application-canister, application canister>> that is routed through consensus.

[[ingress-message-history]]
ingress message history::
Records every processed <<ingress-message,ingress message>> with a boolean flag to indicate whether it was successfully included in the <<induction-pool, induction pool>> or not and, potentially, the response.

[[input-batch-queue]]
input batch queue::
Ordered sequence of blocks produced by the <<g-consensus, consensus>> component

[[input-pool]]
input pool::
Collection of <<ingress-messages, ingress messages>>.

[[Input-queue]]
Input queue::
Contains <<g-canister,canister>> to <<g-canister,canister>> <<g-message,messages>>. Held by the receiving <<g-canister,canister>>.

include::developers-guide:page$glossary.adoc[leveloffset=2,tag=g-intercanister-call]

[[internet-computer]]
Internet Computer::
The **Internet Computer** is a decentralized platform that enables a global network of connected computers to provide scalable computing capacity for running application software.

[[Internet-Computer-Association-ICA]]
Internet Computer Association (ICA)::
The **Internet Computer Association** is a legally-recognized entity (under Swiss law) for member organizations that participate in the development and deployment of the <<internet-computer,Internet Computer>> as a computing platform. The association includes the https://dfinity.org[DFINITY Foundation], independent data centers, universities, and developer partners that have registered and been accepted as members.

[[Internet-Computer-nervous-system-ICNS]]
Internet Computer nervous system (ICNS)::
**Deprecated** terminology for the <<internet-computer,Internet Computer>> governance system. See *network nervous system (NNS)*.

[[Internet-Compute-Provider-ICP]]
Internet Compute Provider (ICP)::
**Deprecated** terminology for <<data-center-provider,data center provider>>.

[[Internet-Compute-Provider-Identity-ICPId]]
Internet Compute Provider Identity (ICPId)::
**Deprecated** terminology for the identifier associated with each <<data-center-provider,data center provider>>.

[[mainnet]]
mainnet::
*Deprecated* terminology for the platform management network. See <<g-nns, network nervous system (NNS)>> and *registry*.

[[g-message]]
message::
Data sent from one <<g-canister,canister>> to another, from a user to a <<g-canister,canister>>, or between system components.

[[message-routing]]
message routing::
For the <<Internet-Computer, Internet Computer>>, <<message-routing,message routing>> is a core component of the <<g-replica,replica>> software. The <<message-routing,message routing>> layer receives the <<g-message,message>> batches from the <<g-consensus,consensus>> layer, extracts the <<g-message,messages>> in order, and schedules the <<g-message,messages>> for execution.
+
After <<g-message,messages>> are executed, the <<message-routing,message routing>> layer takes any <<g-message,messages>> produced in the execution cycle from the application output queues and puts those <<g-message,messages>> into the outgoing streams to be consumed by <<g-canister,canisters>> on other <<sub-network,subnets>>.

[[mutating-call]]
mutating call::
A “write” call that changes the state of the queried <<g-canister,canister>>.

[[neighboring-peers]]
neighboring peers::
The <<g-replica,replicas>> that exchange gossip with each other based on their network overlay topology.

include::developers-guide:page$glossary.adoc[leveloffset=2,tag=g-nns]

include::developers-guide:page$glossary.adoc[leveloffset=2,tag=g-neuron]

[[NID]]
NID::
See <<node-identifier-NID, node identifier (NID)>>.

[[NNS]]
NNS::
See <<g-nns, network nervous system (NNS)>>.

include::developers-guide:page$glossary.adoc[leveloffset=2,tag=g-node]

[[node-identifier-NID]]
node identifier (NID)::
The unique identifier of a <<g-node,node>>. This identifier is a 29-byte selfauthenticating SHA-224 hash of its private key with the byte 0x02 appended as defined in the link:../interface-spec/index{outfilesuffix}[_Interface Specification_].

[[node-operator]]
node provider::
A *node provider* is an entity that provides and operates a <<g-node,node>>. The *node provider* is remunerated periodically for providing <<g-node,nodes>> in the form of newly minted ICP tokens.

[[node-operator-identifier-NOID]]
node operator identifier (NOID)::
The unique identifier of a <<node-operator,node provider>>. This identifier is a 29-byte self-authenticating SHA-224 hash of the public key stored on its https://en.wikipedia.org/wiki/Hardware_security_module[HSM] with the byte 0x02 appended as defined in the link:../interface-spec/index{outfilesuffix}[_Interface Specification_].

[[NOID]]
NOID::
See <<node-operator-identifier-NOID, node operator identifier (NOID)>>.

node identifier (NID)::

[[non-mutating-query]]
non-mutating query::
A “read” operation call that does not change the state of the queried <<g-canister,canister>>.
More commonly, this type of operation is simply referred to as a *query*.

__((orthogonal persistence__::

[[output-pool]]
output pool::
Collection of output queues of all <<g-canister,canisters>> on a <<sub-network,subnet>>.

[[output-queue]]
output queue::
Contains <<g-canister,canister>> to <<g-canister,canister>> messages. Held by the sending <<g-canister,canister>>.

[[output stream]]
output-stream::
A sequence of output <<g-message,messages>> from the different <<g-canister,canister>>
output queues.

__((overlay network__::

[[P2P]]
P2P::
See <<peer-to-peer-P2P,peer-to-peer (P2P)>>.

[[peer-to-peer-P2P]]
peer-to-peer (P2P)::
In common usage, *peer-to-peer (P2P)* computing or networking is a distributed application architecture that partitions workload across a network of equally-privileged computer <<g-node,nodes>> so that participants can contribute resources such as processing power, disk storage, or network bandwidth to handle application workload.
+
For the <<internet-computer,Internet Computer>>, *peer-to-peer* is a core component of the *replica* software. 
The *peer-to-peer layer* collects and advertises <<g-message,messages>> and artifacts from users and from other <<g-node,nodes>> in its <<sub-network,sub-network>>.
+
The primary purpose of the peer-to-peer layer is to make the artifact pool consistent across all of the <<g-replica,replicas>> in a given <<sub-network,subnet>> before sequencing by <<g-consensus,consensus>>.

[[pre-processing]]
pre-processing::
Phase triggered by a new InputBlock during which the <<message-routing, message routing>> component puts the <<ingress-message,Ingress messages>> and <<canister-messages,canister messages>> from the <<sub-network,subnet>> streams into the Induction Pool as appropriate, updates the IngressMsgHistory, manages the OutputQueue and creates SignalingMessages as a reaction to XNet <<canister-message,canister messages>>.

include::developers-guide:page$glossary.adoc[leveloffset=2,tag=g-principal]

[[post-processing]]
post-processing::
Once execution is finished, the <<message-routing,message routing>> layer produces a new set of output streams from the <<output-pool,output pool>>.

include::developers-guide:page$glossary.adoc[leveloffset=2,tag=g-query]

include::developers-guide:page$glossary.adoc[leveloffset=2,tag=g-replica]

[[registry]]
registry::
The *Registry* manages the system meta-data (that will eventually) be maintained on the <<g-nns, network nervous system (NNS)>>.
+
The GlobalRegistry is a read-only versioned per value structured data store which support `get(key, version)`. Each call to `get(key, version)` returns the implied struct of the key, where each field is last written at `version` or earlier.
+
The RegistryManager is a <<system-canister,system canister>> replicated by the <<g-nns, network nervous system (NNS)>> which enforces schema on update.

[[retransmission-request]]
retransmission request::
In the <<peer-to-peer-P2P,P2P>> layer, a peer sends a so-called *retransmission request* to update the other peers about the current status of its artifact pool after a disruption (due to network issues or peer reboot). 
The receiving peers use this information to determine which adverts and artifact requests to send. As such, the <<g-message,message>> could also be called an artifact pool status <<g-message,message>>.

[[rotating-log]]
rotating log::
*Deprecated terminology* for where information about user-generated update call is recorded. See <<ingress-message-history,ingress message history>>.

[[signal-messages]]
signal messages::
Signal messages acknowledge the receipt of <<g-message,messages>> sent on behalf of a <<g-canister,canister>> as follows:

- ERROR: Indicates that a Xnet <<canister-message,canister message>> has been rejected.
- ACK: Indicates that a Xnet <<canister-message,canister message>> has been processed.

[[state-change]]
state change::
A *state change* is the result of any transaction, function call, or operation that changes the information stored for an application. For example, if a function makes an update call that adds two numbers together or removes a name from a list, the result is a change to the application state.

[[state-manager]]
state manager::
The *state manager* is responsible for

* maintaining (multiple versions of) the replicated state the deterministic state machine implemented by <<message-routing,message routing>> and the <<execution-environment,execution environment>> operates on,
* converting back and forth between the replicated state and its canonical version (latter can be understood independent of the concrete implementation),
* obtaining certifications of parts of the canonical state, which allow other stakeholders such as other <<sub-network,subnets>> and/or users, to verify that some piece of state indeed originates from a valid sub-network, and
* providing capabilities to sync the canonical state with other <<g-replica,replicas>> in the same <<sub-network,subnet>> so that <<g-replica, replicas>> that have fallen behind can catch up.

[[sub-network]]
__((sub-network / subnet::

[[subnet-protocol-replica]]
subnet protocol replica::
The set of Internet Computer protocol components that are necessary for a <<g-node,node>> to participate in a <<sub-network,subnet>>.

[[system-canister]]
system canister::
A pre-installed <<g-canister,canister>> that performs certain management tasks needed to maintain the <<internet-computer, Internet Computer>> network.

[[system-state]]
system state::
Auxiliary state of a <<g-canister,canister>> that is maintained by the system on behalf of the <<g-canister,canister>>, including DFN balance, its allocations, meta-data.

[[THID]]
THID::
See <<token-holder-identifier-THID, token holder identifier (THID)>>.

[[token-holder-identifier-THID]]
token holder identifier (THID)::
The *token holder identifier* is defined as the SHA-256 hash of the token holder's https://en.bitcoin.it/wiki/BIP_0032#Extended_keys[extended public key].

[[TsDemuxTxDemux]]
TsDemuxTxDemux::
Demultiplexes different types of input messages and routes them to the right destination

[[uncertified-non-mutating-query]]
uncertified non-mutating query::
Asks one or multiple <<g-node,nodes>> about uncertified data and takes the <<g-node,node>>’s word.

[[user]]
user::
Depending on context, any entity that interacts with the <<internet-computer, Internet Computer>> platform but is not a direct participant
in network operations might be referred to a user. For example, while participants might include <<g-node,nodes>> <<data-centerproviders, data center providers>>, and <<g-neuron,neuron>> stakeholders, users might include end users, third party developers, and server operators.

[[valid-set-rule]]
valid set rule::
The set of checks that every <<ingress-message,ingress-message>> and <<canister-message,canister message>> from a finalized batch must pass before it can be added to the appropriate application input queue in the induction pool.

include::developers-guide:page$glossary.adoc[leveloffset=2,tag=g-wasm]