= Using an actor in the Hello, World! program
December 2019 (Alpha)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:linkedcss:
:toc:
:toc: right
:toc-title: TUTORIAL - HELLO, WORLD
:toclevels: 3
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:ext: .mo
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)

In the link:../../quickstart/quickstart{outfilesuffix}[Quick start], you had your first look at a simple program for the {platform} involving an actor object and asynchronous messaging. 
As the next step in learning to write programs that take advantage of actor-based messaging, this tutorial illustrates how to modify a traditional `+Hello, World!+` program to define an actor, then deploy and test your program on a local network.

== Before you begin

Before starting the tutorial, verify the following:

* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart{outfilesuffix}#download-and-install[Download and install].
* You have stopped any {IC} network processes running on the local
computer.

This tutorial takes approximately 20 minutes to complete.

== Create a new project

To create a new project for this tutorial:

[arabic]
. Open a terminal shell on your local computer, if you don’t already
have one open.
. Change to the folder you are using for your {IC} sample projects.
. Create a new project by running the following command:
+
[source,bash]
----
dfx new actor_hello
----
. Change to your project directory by running the following command:
+
[source,bash]
----
cd actor_hello
----

== Verify the default configuration

You have already seen that creating a new project adds a default `dfx.json` configuration file to your project directory.
In this tutorial, you only need to verify that the default settings reflect your new project name.

To check the default `+dfx.json+` configuration file:

. Open the `+dfx.json+` configuration file in a text editor.
. Check the default settings for the `+actor_hello+` project.
+
For example:
+
[source,bash,subs="quotes"]
----
  "canisters": {
    "*actor_hello*": {
      "frontend": {
        "entrypoint": "src/*actor_hello*/public/index.js"
      },
      "main": "src/*actor_hello*/main.mo"
----
+
You can rename any of the files or directories specified in the `+dfx.json+` configuration file. 
If you make any changes, however, be sure that the names you use for your files and directories match the names specified in the `+dfx.json+` configuration file.
+
If you plan to use the default directory and file names, no changes are necessary. 
. Close the file to continue.

== Modify the default template program

You have already seen that creating a new project creates a default `+src+` directory with a template `+main.mo+` file.
In this tutorial, you modify the template code to create a simple "Hello, World!" program.

To modify the default template source code:

. Change to the source code directory for your project by running the following command:
+
[source,bash]
----
cd src/actor_hello
----
. Open the template `+main.mo+` file in a text editor and delete the existing content.
+
The next step is to write a program that prints a statement like the traditional "Hello, World!" sample program. 
If you were writing this program to run on a platform other than the {IC}, the {proglang} code might look similar to the following:
+
[source,bash]
----
func main() {
   print "Hello, World! from DFINITY\n"
   };
main()
----
+
You could also write the program in {proglang} without the `main` function at all, like this:
+
[source,bash]
----
print "Hello, World! from DFINITY\n"
----
+
To compile the program for the {IC}, however, your program must include an `+actor+` object with a `+public+` function.
. Copy and paste the following sample code into the `+main.mo+` file:
+
[source,motoko]
----
include::example$actor_hello.mo[]
----
+
This code sample imports a `+Debug+` module to provide the `+print+` functionality.
The program uses the `+public query func+` to define a query method because, in this case, the `+actor_hello+` program doesn't make any changes to the state of the canister or perform any operations that would update the data you are accessing.
+
For more information about using a query call, see link:../introduction-key-concepts{outfilesuffix}#query-calls[query calls] in link:../introduction-key-concepts{outfilesuffix}#canister-state[Canisters include both program and state].

== Build and deploy the program

You now have a program that you can compile into an executable WebAssembly module that you can deploy—using the canister model—on your local replica network.

To build the program executable:

. Build the WebAssembly executable by running the following command:
+
[source,bash]
----
dfx build --skip-frontend
----
. Start the {IC} network on your local computer by running the following command:
+
[source,bash]
----
dfx start
----
. Open a new terminal and navigate to your project directory.
. Deploy your `+actor_hello+` project on the local network by running the following command:
+
[source,bash]
----
dfx canister install actor_hello
----

== Query the canister

You now have a program deployed as a *canister* on your local replica network and can test your program by using the `+dfx canister call+` commands.

To test the program you have deployed on the local network:

. Use `+dfx canister call+` to call the `+hello+` function by running the following command:
+
[source,bash]
----
dfx canister call --query actor_hello hello
----
. Verify that the command returns the text specified for the `+hello+` function along with a checkpoint message in the terminal running the local network process.
+
For example, the program displays "Hello, World! from DFINITY" in output similar to the following:
+
[source,bash]
----
Jun 08 20:45:45.284 INFO Created checkpoint @611 in 5.143003ms, StateManager: 1
debug.print: Hello, World from DFINITY 
----
. Stop the {IC} processes running on your local computer by running the following command:
+
[source,bash]
----
dfx stop
----
