= Defining an actor
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:toc:
:toc: right
:toc-title: TUTORIAL - HELLO, WORLD
:toclevels: 3
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:ext: .mo
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)

In the link:../../quickstart/quickstart{outfilesuffix}[Quick start], you had your first look at a simple program for the {IC} involving an actor object and asynchronous messaging. 
As the next step in learning to write programs that take advantage of actor-based messaging, this tutorial illustrates how to modify a traditional `+Hello, World!+` program to define an actor, then deploy and test your program on a local network.

== Before you begin

Before starting the tutorial, verify the following:

* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart{outfilesuffix}#download-and-install[Download and install].
* You have stopped any {IC} network processes running on the local computer.

This tutorial takes approximately 20 minutes to complete.

== Create a new project

To create a new project for this tutorial:

[arabic]
. Open a terminal shell on your local computer, if you don’t already
have one open.
. Change to the folder you are using for your {IC} sample projects.
. Create a new project by running the following command:
+
[source,bash]
----
dfx new actor_hello
----
. Change to your project directory by running the following command:
+
[source,bash]
----
cd actor_hello
----

== Modify the default configuration

In the link:explore-templates{outfilesuffix}[Exploring the default project] tutorial, you saw that creating a new project adds a default `dfx.json` configuration file to your project directory.
In this tutorial, you need to modify a few of the default settings to reflect your project.

To modify the `+dfx.json+` configuration file:

. Open the `+dfx.json+` configuration file in a text editor.
. Check the default settings for the `+actor_hello+` project.
. Notice that the names and paths to source and output files all use the `+actor_hello+` project name.
+
For example, the default canister name is `+actor_hello+` and the default path to the main program file is `+src/actor_hello/main.mo+`.
+
You can rename any of these files or directories. 
If you make any changes, however, be sure that the names you use for your files and directories match the names you specify in the `+dfx.json+` configuration file.
If you plan to use the default directory and file names, no changes are necessary.
. Remove all of the `+actor_hello_assets+` configuration settings from the file.
+
The sample program for this tutorial doesn't use any front-end assets, so you need to remove those settings from the configuration file.
+
For example, the configuration file looks like this after you remove the `+actor_hello_assets+` section:
+
[source,json]
----
{
  "canisters": {
    "actor_hello": {
      "main": "src/actor_hello/main.mo",
      "type": "motoko"
    }
  },
  "defaults": {
    "build": {
      "output": "canisters/",
      "packtool": ""
    },
    "start": {
      "address": "127.0.0.1",
      "port": 8000,
      "serve_root": "canisters/actor_hello_assets/assets"
    }
  },
  "dfx": "0.5.8",
  "version": 1
}
----
. Save your changes and close the file to continue.

== Modify the default program

In the link:explore-templates{outfilesuffix}[Exploring the default project] tutorial, you saw that creating a new project creates a default `+src+` directory with a template `+main.mo+` file.
In this tutorial, you modify the template code to create a simple "Hello, World!" program that uses an actor.

To modify the default template source code:

. Change to the source code directory for your project by running the following command:
+
[source,bash]
----
cd src/actor_hello
----
. Open the template `+main.mo+` file in a text editor and delete the existing content.
+
The next step is to write a program that prints a statement like the traditional "Hello, World!" sample program. 
If you were writing this program to run on a platform other than the {IC}, you could write the program in {proglang} without an actor or a `main` function like this:
+
[source,bash]
----
print "Hello, World! from DFINITY\n"
----
+
To compile the program for the {IC}, however, your program must include an `+actor+` object with a `+public+` function.
. Copy and paste the following sample code into the `+main.mo+` file:
+
[source,motoko]
----
include::example$actor_hello.mo[]
----
+
Let's take a closer look at this simple program:
+
--
* The program imports a `+Debug+` module to provide the `+print+` functionality.
* The program uses the `+public query func+` to define a query method because, in this case, the `+actor_hello+` program doesn't make any changes to the state of the canister or perform any operations that would update the data you are accessing.
+
For more information about using a query call, see link:../introduction-key-concepts{outfilesuffix}#query-calls[query calls] in link:../introduction-key-concepts{outfilesuffix}#canister-state[Canisters include both program and state].
--
. Save your changes and close the `+main.mo+` file.

== Build the program with a local identifier

You are probably only going to use this simple program for some locally testing.
Therefore, there's no need to reserve a unique canister identifier on the {IC} network to hold the compiled output for the program. 

In this scenario, you can compile the program without connecting to an {IC} network at all.
Instead, the `+dfx build+` command creates a local, hard-coded canister identifier for you to use.

You can use this local identifier while you are testing your program or any time you want to compile your program without starting the {IC} replica process locally or connecting to a replica on a remote sub-network.

To build the program executable:

. Open a new terminal and navigate to your project directory.
. Build the program with a locally-defined identifier by running the following command:
+
[source,bash]
----
dfx build --skip-manifest
----
+
You should see output similar to the following:
+
[source,bash]
----
Skipping the build manifest. Canister IDs might be hard coded.
Building canisters...
----

== Deploy the project

Before you can deploy this project, you need to connect to the {IC} network either running locally in your development environment or running remotely on a sub-network that you can access.
You must also generate a unique canister identifier to replace your locally-defined identifier.

To deploy this project locally:

. Open a new terminal window or tab on your local computer and navigate to your project directory.
+
For example, click *Shell*, select *New Window*, then run the following command in the new terminal:
+
[source,bash]
----
cd ~/ic-projects/actor_hello
----
. Start the {IC} network on your local computer by running the following command:
+
[source,bash]
----
dfx start --background
----
+
You can use the `+--background+` option to start the Internet Computer network processes then run them in the background. 
+
With this option, you can continue to the next step without opening another terminal shell on your local computer.
. Generate a new canister identifier for your project on the local {IC} network by running the following command:
+
[source,bash]
----
dfx canister create actor_hello
----
+
You should see output similar to the following:
+
[source,bash]
----
Jun 12 22:24:18.254 INFO s:0/n:100/ic_execution_environment/canister_manager Successfully created canister, canister_id: ic:0100000000000000000000000000000000012D, subnet_id: 0
----
+
The `+dfx canister create+` command also creates a `+canister_manifest.json+` file in the `+canisters+` directory.
+
For example:
+
[source,json]
----
{
  "canisters": {
    "actor_hello": {
      "candid_path": "/Users/pubs/ic-projects/actor_hello/canisters/actor_hello/actor_hello.did",
      "canister_id": "ic:03000000000000000000000000000000000179",
      "timestamp": "Fri, 12 Jun 2020 21:39:17 +0000",
      "wasm_path": "/Users/pubs/ic-projects/actor_hello/canisters/actor_hello/actor_hello.wasm"
    }
  }
}
----
. Deploy your `+actor_hello+` project on the local network by running the following command:
+
[source,bash]
----
dfx canister install actor_hello
----
+
The command displays output similar to the following:
+
[source,bash]
----
Installing code for canister actor_hello, with canister_id ic:03000000000000000000000000000000000179
----

== Query the canister

You now have a program deployed as a *canister* on your local replica network and can test your program by using the `+dfx canister call+` commands.

To test the program you have deployed on the local network:

. Use `+dfx canister call+` to call the `+hello+` function by running the following command:
+
[source,bash]
----
dfx canister call --query actor_hello hello
----
. Verify that the command returns the text specified for the `+hello+` function along with a checkpoint message in the terminal running the local network process.
+
For example, the program displays "Hello, World! from DFINITY" in output similar to the following:
+
[source,bash]
----
debug.print: Hello, World from DFINITY 
----

== Stop the local network

After you finish experimenting with your program, you can stop the local Internet Computer network so that it doesn’t continue running in the background.

To stop the local network:

. In the terminal that displays network operations, press Control-C to interrupt the local network process.

. Stop the {IC} network by running the following command:
+
[source,bash]
----
dfx stop
----
