= At a glance
:IC: Internet Computer
:company-id: DFINITY

The link:../../quickstart/quickstart-intro{outfilesuffix}[Quick start] provides a fast path to deploying a simple default application without stopping to admire the scenery along the way. 
Individual link:../tutorials-intro{outfilesuffix}[tutorials] walk through specific scenarios, pointing out details about what you're doing in each step. 

If the quick start and tutorials aren’t quite your style, this at-a-glance cheat sheet summarizes the steps to follow for quick reference.  

After you install the {sdk-short-name}, here's all you need to know:

. Create a new project and change to the project directory.
+
....
dfx new <project_name> && cd <project_name>>
....
. Edit the back-end that defines your service or application.
. Edit the HTML, JavaScript, and CSS that provides the front-end for your service or application.
. Start the {IC} for local development or check your connection to the {IC} for network deployment.
. Register, build, and deploy locally or on the network.
+
....
dfx deploy --network <network>
....
. View your service or application in a browser.