= Calling shared functions
March 2020 (Alpha)
:source-highlighter: coderay
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:toc:
:toc: right
:toc-title: TUTORIAL - INTER-CANISTER
:toclevels: 3
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)

One of the most important features of the {IC} for developers is the ability to build, deploy, and call shared functions in one canister from a program in another canister. 
This capability to make calls between canisters—also sometimes referred to as **inter-canister calls**—enables you to reuse and share functionality in multiple applications.

For example, you might want to create an application for professional networking, organizing community events, or hosting fundraising activities.
Each of these applications might have a social component that enables users to identify social relationships based on some criteria or shared interest, such as friends and family or current and former colleagues.

To address this social component, you might want to create a single canister for storing user relationships then write your professional networking, community organizing, or fundraising application to import and call functions that are defined in the canister for social connections.
You could then build additional applications to use the social connections canister or extend the features provided by the social connections canister to make it useful to an even broader community of other developers.

The Motoko-based LinkedUp sample application provides a simple implementation of an open professional network that demonstrates how to use inter-canister calls.

In the LinkedUp sample application, there are two canisters:

* The `linkedup` canister stores basic profile information for a user.
* The `connectd` canister stores connections that a user has a established.

== Download the demo

To experiment with inter-canister calls using the LinkedUp sample application:

1. Clone the `linkedup` repository.

1. Change to the local working directory for the `linkedup` repository.

1. Install node modules by running the following commands:
+
[source,bash]
----
npm install
npm audit fix
----

. Build the canisters by running the following command:
+
[source,bash]
----
dfx build
----
. Start the {IC} network by running the following command:
+
[source,bash]
----
dfx start
----
. Deploy the project on the local network by running the following command:
+
[source,bash]
----
dfx canister install --all
----

== Review the configuration file

== Explore the source code

