= Using multiple actors
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:toc:
:toc: right
:toc-title: TUTORIAL - MULTIPLE ACTORS
:toclevels: 3
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)

In this tutorial, you are going to create a project with multiple actors. 
Currently, you can only define one actor in a {proglang} file and a single actor is always compiled to a single canister.
In addition, you cannot yet define an actor class to support multiple actor instances in your {proglang} programs.
You can, however, create **projects** that have multiple actors and can build multiple canisters from the same `+dfx.json+` configuration file.

For this tutorial, you are going to create separate program files for three actors in the same project. 
This project defines the following unrelated actors:

* The `+assistant+` actor provides functions to add and show tasks in a to-do list.
+
For simplicity, the code sample for this tutorial only includes the functions to add to-do items and to show the current list of to-do items that have been added. A more complete version of this program-with additional functions for marking items as complete and removing items from the list—is available in the link:https://github.com/dfinity/examples/[examples] repository as link:https://github.com/dfinity/examples/tree/master/motoko/simple_to_do[Simple to-do checklist].

* The `+rock_paper_scissors+` actor provides a function for determining a winner in a hard-coded rock-paper-scissors contest.
+
This code sample illustrates the basic use of `+switch+` and `+case+` in a {proglang} program with hard-coded players and choices.

* The `+daemon+` actor provides mock functions for starting and stopping a daemon.
+
This code sample simply assigns a variable and prints messages for demonstration purposes.

== Before you begin

Before starting the tutorial, verify the following:

* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart{outfilesuffix}#download-and-install[Download and install].
* You have stopped any {IC} network processes running on the local
computer.

This tutorial takes approximately 20 minutes to complete.

== Create a new project

To create a new project for this tutorial:

[arabic]
. Open a terminal shell on your local computer, if you don’t already have one open.
. Change to the folder you are using for your {IC} sample projects.
. Create a new project by running the following command:
+
[source,bash]
----
dfx new multiple_actors
----
. Change to your project directory by running the following command:
+
[source,bash]
----
cd multiple_actors
----

== Modify the default configuration

You have already seen that creating a new project adds a default `+dfx.json+` configuration file to your project directory.
For this tutorial, you need to add sections to this file to specify the location of each program that defines an actor you want to build.

To modify the default `+dfx.json+` configuration file:

. Open the `+dfx.json+` configuration file in a text editor, then change the default `+multiple_actors+` canister name and source directory to `+assistant+`.
+
For example, under the `canisters` key:
+
[source,json]
----
    "assistant": {
      "main": "src/assistant/main.mo",
      "type": "motoko"
    },
----
+
Because you are going to add settings to this `+canisters+` section of the configuration file, you must also add a **comma** after the curly brace that encloses the location of the `+assistant+` main source code file and the canister type.
. Remove the `+multiple_actors_assets+` section from the file.
. Add a new canister name, source code location, and canister type for the `+rock_paper_scissors+` program and a new canister name, source code location, and canister type for the `+daemon+` program files below the `+assistant+` canister definition.
+
After making the changes, the `+canisters+` section of the `+dfx.json+` file should look similar to this:
+
[source,json]
----
include::example$multiple-actors/dfx.json[]
----
+
You can leave the other sections as-is. 
. Change the name of the default source file directory to match the name specified in the `+dfx.json+` configuration file by running the following command:
+
[source,bash]
----
cp -r src/multiple_actors/ src/assistant/
----
. Copy the `+assistant+` source file directory to create the main program file for the `+rock_paper_scissors+` actor by running the following command:
+
[source,bash]
----
cp -r src/assistant/ src/rock_paper_scissors/
----
. Copy the `+assistant+` source file directory to create the main program file for the `+daemon+` actor by running the following command:
+
[source,bash]
----
cp -r src/assistant/ src/daemon/
----

== Modify the default programs

You now have three separate directories in the `+src+` directory, each with a template `+main.mo+` file.
For this tutorial, you will replace the content in each template `+main.mo+` file with a different actor.

To modify the default source code:

. Open the `+src/assistant/main.mo+` file in a text editor and delete the existing content.
. Copy and paste the following sample code into the file:
+
[source,motoko]
----
include::example$multiple-actors/assistant/main.mo[]
----
. Open the `+src/rock_paper_scissors/main.mo+` file in a text editor and delete the existing content.
. Copy and paste the following sample code into the file:
+
[source,motoko]
----
include::example$multiple-actors/rock_paper_scissors/main.mo[]
----
. Open the `+src/daemon/main.mo+` file in a text editor and delete the existing content.
. Copy and paste the following sample code into the file:
+
[source,motoko]
----
include::example$multiple-actors/daemon/main.mo[]
----

== Start the local network

Before you can build the `+multiple_actors+` project, you need to connect to the {IC} network either running locally in your development environment or running remotely on a sub-network that you can access.

To start the network locally:

[arabic]
. Open a new terminal window or tab on your local computer and navigate to your project directory.
+
For example, you can do either of the following if running Terminal on macOS:
+
--
* Click *Shell*, then select *New Tab* to open a new terminal in your current working directory.

* Click *Shell* and select *New Window*, then run `+cd ~/ic-projects/multiple_actors+` in the new terminal if your project is in the `+ic-projects+` working folder.
--
+
You should now have two terminals open with your project directory as your current working directory.
. Start the {IC} network on your local computer by running the following command:
+
[source,bash]
----
dfx start
----
+
After you start the local network, this terminal displays messages about network operations.
. Leave the terminal that displays network operations open and switch your focus to your original terminal where you created your new project.

== Register canister identifiers

After you connect to the {IC} network running locally in your development environment, you can register with the network to generate unique canister identifiers for your project.

To register canister identifiers for the local network:

. Check that you are still in your project directory, if needed.
. Register unique canister identifiers for all of the canisters in the project by running the following command:
+
[source,bash]
----
dfx canister create --all
----
+
The command displays the network-specific canister identifiers for the three canisters defined in the `+dfx.json+` configuration file.
+
....
"assistant" canister created with canister id: "ic:040000000000000000000000000000000001AF"
"daemon" canister created with canister id: "ic:05000000000000000000000000000000000185"
"rock_paper_scissors" canister created with canister id: "ic:060000000000000000000000000000000001FB"
....

== Build and deploy multiple canisters

Now that you have registered with the network, you are ready to compile your program into an executable WebAssembly module that you can then deploy on your local {IC} network.

To build and deploy the programs for each actor in the project:

. Check that you are still in your project directory by running the `+pwd+` command, if necessary.
. Build the WebAssembly executable for each program by running the following command:
+
[source,bash]
----
dfx build
----
+
If the command is successful, it builds all of the canisters you have specified in the `+dfx.json+` file.
+
....
Building canisters...
....
. Deploy your canisters on the local network by running the following command:
+
[source,bash]
----
dfx canister install --all
----
+
The command displays output similar to the following:
+
....
Installing code for canister assistant, with canister_id ic:040000000000000000000000000000000001AF
Installing code for canister daemon, with canister_id ic:05000000000000000000000000000000000185
Installing code for canister rock_paper_scissors, with canister_id ic:060000000000000000000000000000000001FB
....

== Verify deployment by calling functions

You now have three programs deployed as a *canisters* on your local replica network and can test each program by using `+dfx canister call+` commands.

To test the programs you have deployed:

. Use the `+dfx canister call+` command to call the canister `+assistant+` using the `+addTodo+` function and pass it the task you want to add by running the following command:
+
[source,bash]
----
dfx canister call assistant addTodo '("Schedule monthly demos")'
----
. Verify that the command returns the to-do list item using the `+showTodos+` function by running the following command:
+
[source,bash]
----
dfx canister call assistant showTodos
----
+
The command returns output similar to the following:
+
....
("
___TO-DOs___
(1) Schedule monthly demos")
....
. Use the `+dfx canister call+` command to call the canister `+rock_paper_scissors+` using the `+contest+` function by running the following command:
+
[source,bash]
----
dfx canister call rock_paper_scissors contest
----
+
The command returns the result of the hard-coded contest similar to the following:
+
....
("Bob won")
....
. Use the `+dfx canister call+` command to call the canister `+daemon+` using the `+launch+` function by running the following command:
+
[source,bash]
----
dfx canister call daemon launch
----
. Verify the mock `+launch+` function returns "The daemon process is running" message":
+
....
(""The daemon process is running"")
....

== Stop the local network

After you finish experimenting with your program, you can stop the local Internet Computer network so that it doesn’t continue running in the background.

To stop the local network:

. In the terminal that displays network operations, press Control-C to interrupt the local network process.

. Stop the {IC} network by running the following command:
+
[source,bash]
----
dfx stop
----

////
== Import an actor

To extend what you have learned in this tutorial, you might want to try modifying the source code to return different results.
 
As features are added, the tutorial can be modified to illustrate other functionality such as:
- How to import an actor
- How to call a function in another actor
- How to include multiple actors in a single program
- How and when to add an actor class

////
