= Reproducible Canister Builds

The {IC} always ensures that the code of a canister executes correctly.
But how do you verify whether it's executing the _intended_ code for a canister?
This document shows a common way of verifing that.

There are two parts to this question:

1. Which code is being executed for a canister? 
   The {IC} executes WebAssembly (WASM) code, and provides information about the code.
2. The canisters are rearely written in WASM directly, but normally in a higher-level language, such as Motoko or Rust.
   The question is then: does the purported source code of the canister really result in the WASM that's running? 
   To be able to answer this, canister authors should ensure https://reproducible-builds.org/docs/definition/[reproducible builds] of the WASM code. 
   Such builds allows anyone to follow the same steps as the canister authors and yield the exact same WASM code,
   which can then be compared to the code executing on the {IC}.
   Moreover, the build process has to be trusted by the user.

The rest of the document explains both how to retrieve information about code being executed, and instructs authors how to ensure reproducibility of their builds.
The impatient reader who is familiar with the topic of reproducible builds can skip to the <<repro-build-summary>>.

== Finding out which code the {IC} is executing

{IC} does not allow you to access the WASM code of an arbitrary canister.
This is a design decision, as developers might want to keep some code private.
However, the {IC} does allow you to access the _cryptographic hash_ of the WASM code of a canister, or more concretely, the SHA-256 hash.

To obtain this hash, you must first note the ID of the {IC} canister whose code you want to check.
For example, assume we're interested in the code of the Internet Identity canister, whose ID is `rdmx6-jaaaa-aaaaa-aaadq-cai`.
Then, the easiest way to access this service is using the `dfx` tool from the terminal.
Open your terminal, and run:

----
$ dfx canister --no-wallet --network ic info rdmx6-jaaaa-aaaaa-aaadq-cai
Controller: r7inp-6aaaa-aaaaa-aaabq-cai
Module hash: 0xda8d1bdd93fbf1edddeb2a423fa3c528c2e4877d39beed2277a12e60227e44d4
----

NOTE: If you are running an old version of `dfx`, you will need to run this command from a directory that contains a valid `dfx.json` file.
If you don't have such a directory, you can create it using `dfx new`.

Here, the {IC} tells us that the hash of the code of the `rdmx6-jaaaa-aaaaa-aaadq-cai` canister (which happens to be the internet identity canister) is `0xda8d1bdd93fbf1edddeb2a423fa3c528c2e4877d39beed2277a12e60227e44d4`.

CAUTION: The check above provides you the _current_ hash of the canister, but the _controllers_ of an {IC} canister may change the code at any time (e.g., to upgrade a canister). Currently, there is only way to ensure that the canister hasn't changed its code since you last checked it: the canister's controllers must be empty.

Armed with this hash, you can next check whether it corresponds to some given source code.
This only works if the build process for the code is reproducible.

== Reproducible builds

As a canister author, there are a few things you have to provide to your users to allow them to reproduce your build:

* The same source code that you used to create the WASM for canister.
* Instructions on how to recreate your build environment.
* Instructions on how to repeat the process of building the WASM from the source code.
  Crucially, the process must be deterministic, to ensure that it results in the exact same WASM.

We next look at each of these points in more detail.

=== Providing source code

Typically, you will version your code in `git` or some other version control system.
In this case, you should note the particular commit that you use when producing the code to be deployed to the {IC}, and communicate it to the users who are trying to verify your canister.
Alternatively, you can also provide a package (e.g., a zip file or a tarball) containing the source code you used to build your canister.

=== Reproducing build environments

Before building your code, you should note down the exact versions of your system and the build tools, as well as the environment variables you are using.
In particular, for the languages supported by the {IC} SDK:

* Note down the operating system and the version you are using to build your canister.
* If you are using `dfx`, note the version used, as specified in `dfx.json`. You can install arbitrary versions
  of `dfx` using `dfx toolchain install <version>`, or by running the installation script with the `DFX_VERSION`
  set to the desired version.
* If you are building Motoko code in a way other than `dfx build`, note the version of `moc` you are using.
* If you are building Rust, note the version of `cargo` you are using.
* If you are using Node.js, `npm` and/or `webpack`, note their versions.
* If your build process depends on any environment variables (such as time zone or local), note them down.

You should communicate all of these to your user in the instructions.
Ideally, do so by providing an executable recipe to recreate the build environment, using tools such as Docker or Nix.
We recommend using Docker, as this allows you to also fix the platform used for building the software.

=== Build environments using Docker

https://docs.docker.com/[Docker containers] are a popular solution to providing build environments.
You can use a `Dockerfile` such as the following to provide the user with a particular version of the operating system,
as well as `dfx`, `Nodejs` and the Rust toolchain.

----
FROM ubuntu:20.10

# Install a basic environment needed for our build tools
RUN \
    apt -yq update && \
    apt -yqq install --no-install-recommends curl ca-certificates \
        build-essential pkg-config libssl-dev llvm-dev liblmdb-dev clang cmake reprotest

# Install Node.js using nvm
# Specify the Node version
ENV NODE_VERSION=14.17.1
RUN curl --fail -sSf https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"P

# Install Rust and Cargo in /opt
# Specify the Rust toolchain version
ARG rust_version=1.51.0
ENV RUSTUP_HOME=/opt/rustup \
    CARGO_HOME=/opt/cargo \
    PATH=/opt/cargo/bin:$PATH
RUN curl --fail https://sh.rustup.rs -sSf \
        | sh -s -- -y --default-toolchain ${rust_version}-x86_64-unknown-linux-gnu --no-modify-path && \
    rustup default ${rust_version}-x86_64-unknown-linux-gnu && \
    rustup target add wasm32-unknown-unknown
ENV CARGO_HOME=/cargo \
    CARGO_TARGET_DIR=/cargo_target \
    PATH=/cargo/bin:$PATH

# Install dfx; the version is picked up the DFX_VERSION environment variable
# Specify the dfx version to download
ENV DFX_VERSION=0.8.1
RUN sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"

COPY . /canister
WORKDIR /canister
----

There are a couple of things worth noting about this `Dockerfile`:
* It starts from an official Docker image. Furthermore, all the installed tools are standard, and come from standard sources. 
  This provides the user with confidence that the build environment hasn't been tampered with, and thus that the build process 
  using Docker can be trusted.
* To ensure that specific versions of the build tools are installed, it installs them directly, rather than through 
  the package manager of the Linux distribution running inside of the container.
  Such package managers usually don't provide a way of pinning the build tools to a specific versions.

To use this `Dockerfile`, get Docker up and running, place the `Dockerfile` in the directory containing the source of your canister,
and create the Docker container by running:
----
$ docker build -t mycanister .
----

This creates a Docker container called `mycanister`, with npm, Rust and `dfx` installed in it, and your canister source code
copied to `/canister`.
You can then enter an interactive shell inside of your container by running:
----
docker run -it --rm mycanister
----

From here, you can experiment with the steps needed to build your canister.
Once you are confident that the steps are deterministic, you can also put them in the `Dockerfile`, 
to allow the user to automatically reproduce your build when creating the canister.
You can see an example in the https://github.com/dfinity/internet-identity/blob/397d0087a29855564c47f0fd3323f60b5b67a8fa/Dockerfile[Dockerfile of the internet identity canister].
Next, we will investigate what is necessary to make the build deterministic.

=== Ensuring the determinism of the build process

For the build process to be deterministic:

.  You will need to ensure that any dependencies of your canister are always resolved in the same way.
   Most build tools now support a way of "freezing" dependencies to a particular version.

   * For `npm`, running `npm install` will create a `package-lock.json` file with some fixed versions of all 
     transitive dependencies of your project that satisfy the requirements specified in your `package.json`.
     However, `npm install` does not honor the `package-lock.json` file by default.
     Thus, once you create the final version of your canister, run `npm install` only once.
     After that, commit `package-lock.json` to your version control system.
     Finally, when checking the build for reproducibility, use `npm ci` instead of `npm install`.

   * For Rust code, Cargo will automatically generate a `Cargo.lock` file with the fixed versions of
     your (transitive) dependencies.
     Like with `package-lock.json`, you should commit this file to your version control system once you
     are ready to produce the final version of your canister.
     Furthermore, Cargo by default ignores the locked versions of dependencies.
     Pass the `--locked` flag to the `cargo` command to ensure that the locked dependencies are used.

   * You have to allocate canister IDs in advance, as canisters refer to each other by their IDs.

.  Your own build scripts must not introduce non-determinism.
   Obvious sources of non-determinism include randomness, timestamps, or code obfuscators.
   Less obvious sources include locales, absolute file paths, and remote URLs whose content can change.
   Furthermore, relying on third-party build plug-ins exposes you to any non-determinism introduced by these.

.  Given the same dependencies and deterministic build scripts, the build tools themselves (`moc` for Motoko, `cargo` for Rust, `webpack` 
   by default for front-end development) must also be deterministic.
   The good news is that all of these tools aim to be deterministic.
   However, they are complicated pieces of software, and ensuring determinism is non-trivial.
   Thus, non-determinism bugs can and do occur.
   For example, see the https://github.com/rust-lang/rust/labels/A-reproducibility[list of current potential non-determinism issues in Rust].
   For webpack, determinism is important to ensure caching, and webpack has since version 5 introduced deterministic naming.
   The Motoko compiler aims to be deterministic, but there are currently known issues.
   Absolute file paths might be included in the binary, and the Motoko runtime bundled in the canisters may differ between platforms (such as Linux and MacOS).
   You can work around these issues by performing your build in a Docker container, as this will fix both the platform and the file paths.
   
=== Testing reproducibility

While the above guidelines should help you achieve reproducible builds, they are by no means perfect.
If reproducibility is vital for your code, you should test your builds to increase your confidence in their reproducibility.
This is non-trivial: we have seen real-world examples where non-determinism in a canister build took a month to show up!
Fortunately, a tool called https://salsa.debian.org/reproducible-builds/reprotest[reprotest] can help you automate reproducibility tests.
It tests your build by running it in two different environments, which differ in characteristics such as paths, times, file order, and others.
To use it, you can put the following `Dockerfile` in the root directory of your canister project.

----
FROM ubuntu:20.10

# Install a basic environment needed for our build tools
RUN \
    apt -yq update && \
    apt -yqq install --no-install-recommends curl ca-certificates \
        build-essential pkg-config libssl-dev llvm-dev liblmdb-dev clang cmake

# Install Node.js using nvm
ENV NODE_VERSION=14.17.1
RUN curl --fail -sSf https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"P

# Install Rust and Cargo in /opt
ARG rust_version=1.51.0
ENV RUSTUP_HOME=/opt/rustup \
    CARGO_HOME=/opt/cargo \
    PATH=/opt/cargo/bin:$PATH
RUN curl --fail https://sh.rustup.rs -sSf \
        | sh -s -- -y --default-toolchain ${rust_version}-x86_64-unknown-linux-gnu --no-modify-path && \
    rustup default ${rust_version}-x86_64-unknown-linux-gnu && \
    rustup target add wasm32-unknown-unknown
ENV CARGO_HOME=/cargo \
    CARGO_TARGET_DIR=/cargo_target \
    PATH=/cargo/bin:$PATH

# Install dfx; the version is picked up the DFX_VERSION environment variable
ENV DFX_VERSION=0.8.1
RUN sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"

# Install reprotest and useful tools it relies on
RUN apt -yqq install --no-install-recommends reprotest disorderfs faketime sudo wabt

COPY . /canister
WORKDIR /canister
----

Next, create a `canister_ids.json` file containing the IDs of your canisters on the {IC}, and put it in the `.dfx/local/ic` file.
Now, from the root directory of your canister project, you can test the reproducibility of your `dfx` builds as follows:
----
$ docker build -t mycanister .
...
$ docker run --rm --privileged -it mycanister
root@6fe19d89f8f5:/canister# reprotest -vv "dfx build --network ic" '.dfx/ic/canisters/*/*.wasm'
----

The first command builds the Docker canister using the above `Dockerfile`.
The second one opens an interactive shell (hence the `--it` flags) in the canister.
We run this in privileged mode, as `reprotest` installs some kernel modules to modify environments.
You can also run it in non-privileged mode by excluding some of the variations; see the https://manpages.debian.org/stretch/reprotest/reprotest.1.en.html[reprotest manual].
Finally, once inside of the canister, we launch `reprotest` in verbose mode (the `-vv` flags).
You need to give it the build command you want to run as the first argument; here, we assume that it's just `dfx build`.
It will then run the build in two different environments.
Finally, you need to tell `reprotest` which paths to compare at the end of the two build.
Here, we compare the wasm code for all canisters, which is found in the `.dfx/ic` directory.

If the comparison finds any differences between the wasm code produced in two builds, it will output a diff.
You will then likely want to use the `--store-dir` flag of `reprotest` to store the outputs and the diff somewhere where you can analyze them.

If the comparison doesn't find any differences, you will see output similar to this one:

----
No differences in ./.dfx/local/canisters/*/*.wasm
27ff185372dbf51a860d6ddbe6fc9cbdd47cb41fba8c1b702bed9767cc34d66f  ./.dfx/local/canisters/Map/Map.wasm
6af1076f70407854cd6f62f23429d81f58398729f9ee5d4247ae4f93eb12770c  ./.dfx/local/canisters/Test/Test.wasm
----

Congratulations - this is a good indicator that your build is reproducible!
However, there are still other things to consider for the long term.

=== Long-term considerations

As you have seen, ensuring reproducibile builds for your canisters isn't a trivial task.
It's even more demanding if you expect your canister canister code to stay around for years, and stay reproducible.
The biggest challenges are to ensure that your:
. Build toolchain is still available in the future.
. Dependencies are avaiable.
. Toolchain still runs and still correctly builds your dependencies.

Distributions and package archives may drop old versions of packages, including both your toolchain and their dependencies.
Web sites may go offline and URLs might stop working.
Thus, it's thus prudent to back up all of your toolchain and dependencies.
You should consider getting involved in projects such as https://www.softwareheritage.org/[Software Heritage], which do this on a large scale.
At some later point in time, you might have to adjust your build process later (e.g., by changing URLs) to ensure that your canister still builds.
Nevertheless, if the build still yields the same result, you can still convince the user that your canister is running the correct code.
This may be easier if you source your dependencies from a trustworthy source, such as the Software Heritage project.

== Summary
[[repro-build-summary]]

Summarizing our recommendations for canister authors:

* Ideally, use Docker to conveniently set up the operating system and the build tools, and fix their versions for the user.
  If the build tools you are using don't guarantee fully reproducible builds, Docker can also help by minimizing the differences in paths, environment variables etc.
* The build tools and the base Docker image should be sourced from somewhere that user can trust.
* Rust and Motoko compilers aim to be deterministic, and thus support reproducible builds. If you notice non-determinism, file bug reports.
* When using NPM, ensure that you specify the exact versions of all your dependencies (commit `package_lock.json` to your git repo!).
  Invoke NPM using the `ci` command rather than `install`. Similarly, for Rust packages commit `Cargo.lock` to your repository, and then
  use `cargo build --locked` when building the package.
* Webpack builds should be deterministic, but obfuscators and similar tools may compromise reproducibility.
  Make sure you use deterministic chunk and module IDs.
* Build tools aren't perfect, and may fail to ensure reproducible builds. 
  If reproducibility is critical for your canister (e.g., it holds a large amount of funds), test it.
  Reprotest is a useful tool for this purpose.
* Ideally, you want to minimize the number of dependencies, as, in order to do a full audit, the user should (reproducibly) rebuild all 
  of your dependencies too. 
  This is especially important if you plan to run the same canister code for a long time, while ensuring
  reproducible builds.

Finally, if your build is reproducible, you can compare the hash of the resulting WASM code to the hash of the code that is running in a canister as follows:
----
$ dfx canister --no-wallet --network ic info <canister-id>
----

Beware that this hash might change if the controllers upgrade the canister code.

== Remaining questions

* How does the Wasm stay they same when I changed the canister IDs in the different versions of dfinihack?
  How are the calls to a different canister routed? Or perhaps the frontend canister wasn't actually doing anything?
