[[candid-ui]]
== Test functions in a browser

The canister interface description language—often referred to as Candid or more generally as the IDL—provides a common language for specifying the signature of a canister service.
The language provides a unified way of interacting with canisters in various languages and tools, such as the `+dfx+` command-line interface, JavaScript, and {proglang}.

Based on the type signature of the actor, Candid also provides a web interface that allows you to call canister functions for testing and debugging.

NOTE: If you have upgraded to a `0.7.0-beta` version of the {sdk-short-name}, you cannot yet use the Candid web interface to test functions in a browser. To use the Candid web interface, you can install a previous version of the {sdk-short-name} for your project. 

After you have deployed your project locally using the `+dfx deploy+` or `+dfx canister install+` command, you can access the Candid web interface endpoint in a browser. Accessing the Candid web interface endpoint enables you to view and test canister functions without writing any front-end code.

To use the Candid web interface to test canister functions:

. Copy the canister identifier associated with the *main actor* for your application.
. Open a browser and navigate to the address and port number specified in the `+dfx.json+` configuration file.
+
By default, the `+local+` network binds to the `+127.0.0.1:8000+` address and port number.
. Add the `+candid+` endpoint to access the Candid web interface followed by the required `canisterId` parameter and canister identifier.
+
For example, the full URL should look similar to the following but with the `+canister_identifier+` that was returned by the `+dfx canister install+` command:
+
....
http://127.0.0.1:8000/candid?canisterId=<YOUR-CANISTER-IDENTIFIER>
....
. Review the list of function calls and types defined in the program.
. Type a value of the appropriate type for a function or click *Random* to generate a value, then click *Call* or *Query* to see the result.
+
Note that depending on the data type, the Candid interface might display additional configuration settings for testing functions. 
For example, if a function takes an array, you might need to specify the number of items in the array before entering values.
