== 5. Deploying On-chain (1 min)

== 5.1 Deploy the Dapp On-chain via dfx (Terminal B)

Now that you have your cycles and your dfx is configured to transfer cycles, you are now ready to deploy your `Hello` dapp on-chain.

[source,bash]
----
$ npm install
----

[source,bash]
----
$ dfx deploy --network ic
----

The `--network` option specifies the network alias or URL for deploying the dapp. This option is required to install on the Internet Computer blockchain mainnet.

If successful, your terminal should look like this: 

[source,bash]
----
Deploying all canisters.
Creating canisters...
Creating canister "hello"...
"hello" canister created on network "ic" with canister id: "5o6tz-saaaa-aaaaa-qaacq-cai"
Creating canister "hello_assets"...
"hello_assets" canister created on network "ic" with canister id: "5h5yf-eiaaa-aaaaa-qaada-cai"
Building canisters...
Building frontend...
Installing canisters...
Installing code for canister hello, with canister_id 5o6tz-saaaa-aaaaa-qaacq-cai
Installing code for canister hello_assets, with canister_id 5h5yf-eiaaa-aaaaa-qaada-cai
Authorizing our identity (default) to the asset canister...
Uploading assets to asset canister...
  /index.html 1/1 (472 bytes)
  /index.html (gzip) 1/1 (314 bytes)
  /index.js 1/1 (260215 bytes)
  /index.js (gzip) 1/1 (87776 bytes)
  /main.css 1/1 (484 bytes)
  /main.css (gzip) 1/1 (263 bytes)
  /sample-asset.txt 1/1 (24 bytes)
  /logo.png 1/1 (25397 bytes)
  /index.js.map 1/1 (842511 bytes)
  /index.js.map (gzip) 1/1 (228404 bytes)
  /index.js.LICENSE.txt 1/1 (499 bytes)
  /index.js.LICENSE.txt (gzip) 1/1 (285 bytes)
Deployed canisters.
----

In the example above, we created a `Hello` dapp that is composed of two canisters: 

a. `hello` canister `5o6tz-saaaa-aaaaa-qaacq-cai` which contains the backend logic.

b. `hello_assets` canister `5h5yf-eiaaa-aaaaa-qaada-cai` which contains the frontend assets (e.g. HTML, JS, CSS).

Note: you will notice that the canister ids of for the same project are different between the local (section 3 of this tutorial) and the on-chain environments.

== 5.2 Testing the On-chain Dapp via Command Line (Terminal B)

Now that the canister is deployed on-chain, you can send it a message. Since the canister has a method called `greet` (which accepts a string as a parameter), we will send it a message.

[source,bash]
----
$ dfx canister --network ic call hello greet '("everyone": text)'
----

Note the way the message is constructed:

* `dfx canister --network ic call` is setup for calling a canister on the IC

* `hello greet` means we are sending a message to a canister named `hello` and evoking its `greet` method

* `'("everyone": text)'` is the parameter we are sending to `greet` (which accepts `Text` as its only input).

== 5.3 See your Dapp live On-chain via a Browser

Find your new canister's ID:

[source,bash]
----
$ dfx canister --network ic id hello
----

Take that canister id and visit +https://<canister-id>.ic0.app+, inserting the `hello_assets` canister id as the subdomain in the URL. In this tutorial, it is `5h5yf-eiaaa-aaaaa-qaada-cai` so it would be https://5h5yf-eiaaa-aaaaa-qaada-cai.ic0.app+.

== Conclusion

You have now deployed the dapp on-chain! You can read the conclusion of the tutorial.

Continue with the main tutorial: link:how-to-deploy-hello-world-smart-contract{outfilesuffix}[How to deploy a "hello world" smart contract/dapp in 20 minutes].