= Introduction to Internet Computer Protocol (ICP) token management
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:title: Introduction to Internet Computer Protocol (ICP) token management
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

[[ledger-intro]]
This draft of _Introduction to Internet Computer Protocol (ICP) token management_ is based on the current design of the Internet Computer Protocol (ICP) components for token distribution, transaction management, token-based staking, and payments for services. 
The document includes preliminary details about the design implementation, security guarantees, system requirements, and the application programming interface (API) that support token management for the Internet Computer Protocol.

The _Introduction to Internet Computer Protocol (ICP) token management_ is intended as a high-level overview for organizations and system integrators who need to understand the terminology and overall transaction management flow for Internet Computer Protocol (ICP) tokens.

In reviewing this document, keep in mind that additional details about specific components or interfaces might be available in subsequent documents intended to supplement the overview provided in this document.

== Basic terminology to get you started

The Internet Computer is primarily a distributed and decentralized platform for running software. 
When developers write applications that run on the Internet Computer, they deploy their programs in the form of a conceptual computational unit called a **canister**. 
A canister is similar to a “smart contract” in that it consists of both program code and state running on a blockchain network with security and liveness guarantees.

Each canister has a **controller**, a unique identifier, and the code and assets it needs for an application or service. 
End-users—or other canisters—can send messages to canister functions to perform specific operations. 
The messages can be either **query calls** that retrieve information without preserving state or **update calls** that change and preserve state. 
State changes that result from update calls are arranged into an agreed upon order by consensus and written to blocks.

== Ledger canister overview

This core functionality of code that runs inside of a canister with state maintained on the blockchain provides the foundation for Internet Computer Protocol (ICP) token management in the form of a specialized canister, called the **ledger canister**.
Conceptually, the ledger canister maintains two key pieces of information related to Internet Computer Protocol (ICP) token: **accounts** and **transactions**.

=== Accounts

The ledger canister provides a set of accounts that have access to ICP tokens.
Each account on the ledger canister is identified and controlled by a unique security identifier called a **principal**. 
Principals are generated using the hash of a public key and are similar to addresses in Bitcoin or Ethereum. The principal is then used to sign messages to authenticate the operations that are passed to the canister.

Initially, the ledger canister only includes the set of accounts associated with early investors and those who have a stake that can be converted to tokens. 
The specific set of accounts that the ledger canister contains at genesis are the following: 

* The account for the **Genesis token canister (GTC)** that holds all of the tokens that need to be distributed to initial investors. 

* The account for the **Neurons canister** that holds all of the tokens staked and locked at any given point in time.

* The account for the **Foundation** that holds the ICP tokens reserved for the DFINITY Foundation.

* The account for the **Proposal canister** that holds a reserve of virtual ICP tokens that can be converted to ICP tokens for future events such as voting rewards or data center payments.

After the initial set of accounts are instantiated with the appropriate token balances, new accounts are created by sending tokens to a specified principal.

NOTE: Details about the accounts held in the genesis token canister (GTC) and the neuron canister and about how tokens for these accounts are instantiated and recorded in the ledger canister are outside the scope of this document.

=== Transactions

There are two types of operations that can mutate the internal state of the ledger canister: 

* Minting ICP tokens.
* Sending ICP tokens between accounts. 

Both of these operations are recorded as transactions in the ledger canister. 

The transactions in the ledger are maintained as a hashed block chain. 
As state changes are recorded, each new transaction is authenticated using a signature on the tip of the chain, placed in a block, and assigned a unique index. 
Queries can use the index to retrieve transaction details. 
The signature used to authenticate a transaction can be verified by any third party who has access to the root public key of the internet Computer.

== Integration with Rosetta


To download and install:

[arabic]
. Open a terminal shell on your local computer, if you don’t already have one open.
+
For example, open Applications, Utilities, then double-click *Terminal* or press kbd:[{commandkey} + spacebar] to open Search, then type `terminal`.

