=  初めての人のための予備知識
:experimental:
:commandkey: &#8984;

初めて開発ツールをインストールする際には、環境を整えるためのいくつかの手順を踏む必要があります。

ただし、これらの作業には何通りかの方法があります。
ここに記載されていない情報については、使用しているオペレーティングシステムのマニュアルを参照してください。

NOTE: ここでの説明は、あなたが macOS コンピュータを使用していることを想定しています。
Linux の開発環境をお持ちの方は、お使いの Linux ディストリビューションやバージョンによって、以下の手順が異なります。

以下は {sdk-short-name} をインストールする前に、知っておくべきことです。

* ターミナルでコマンドを開き、実行する方法
* パッケージと依存関係を確認し、インストールする方法
* 新しいディレクトリを作成し、そこに移動する方法
* 使用しているプラットフォームの PATH を確認して更新する方法

このセクションでは、基本的な開発環境を準備する方法について説明します。

[[open-terminal]]
== ターミナルを開く

link:../developers-guide/tutorials-intro{outfilesuffix}[チュートリアル] を試す際には、ターミナルを開いてディレクトリに移動し、{sdk-short-name} をインストールしたり、ローカルで動作している {IC} を起動・停止する方法を知っておく必要があります。

macOS でターミナルアプリケーションを開くには

. Finder を開きます。
. 「*アプリケーション*」をクリックし、「*ユーティリティ*」を開いて、「*ターミナル*」をダブルクリックします。
+
または、kbd:[{commandkey} + spacebar] を押して「検索」を開き、「 `terminal` 」と入力します。
+
ターミナルは、コマンドを入力し実行する場所です。
コマンドを実行するには、命令を入力するか、コピー＆ペーストしてから、kbd:[Return] を押します。
. `pwd` コマンドを実行し、kbd:[Return] を押して、現在の PATH を確認します。
+
[source,bash]
----
pwd
----
+
このコマンドは、 `/Users/<ユーザー名>` のように、現在いるディレクトリの PATH を表示します。
+
ターミナルを開いた後、 *Shell* をクリックし、*New Window* または *New Tab* を選択することで、いつでも新しいターミナルを開くことができます。
+
デフォルトでは、新しいターミナルは常にホームディレクトリで開かれ、 PATH は  `/Users/<ユーザー名>` のようになります。
+
+

[[check-pkgs]]
== パッケージの確認

Homebrew アプリケーションは、macOS 用のパッケージマネージャで、ローカルの開発環境に必要なパッケージ（外部プログラム）のインストールやアップデートを簡単に行うことができます。

`node.js` パッケージは、フロントエンドユーザーインターフェース開発のための JavaScript ランタイム環境とモジュールを提供します。
`node.js` パッケージは、プログラムをビルドする際には必要ありませんが、グラフィカル・ユーザー・インターフェースを使用する場合には、おそらく必要になるでしょう。

NOTE: 開発環境がLinuxの場合、パッケージのインストールや依存関係の管理に、Homebrew ではなく任意のパッケージマネージャーを使用することができます。

パッケージの確認とインストール: 

. Homebrew パッケージマネージャーがインストールされているかどうか、以下のコマンドで確認してください。
+
[source,bash]
----
brew --version
----
+
バージョン情報が返ってきた場合は、次のステップに進みます。
Homebrewが インストールされていない場合は、以下のコマンドをコピーしてターミナルに貼り付けます。
+
[source,bash]
----
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
----
. 以下のコマンドを実行して、`node.js` パッケージマネージャがインストールされているかどうかを確認します。
+
[source,bash]
----
node --version
----
+
サポートされている node.js の最低バージョンは 12 です。バージョン情報が返ってきて、node のバージョンが 12 以上であれば、そのまま <<working-folder, 作業フォルダの作成>> に進みます。
もし `node.js` がインストールされていないか、バージョンが 12 より古い場合には、以下のコマンドをコピーしてターミナルに貼り付けます。
+
[source,bash]
----
brew install node
----

[[working-folder]]
== 作業フォルダの作成

通常、ターミナルはホームディレクトリである、`/Users/<ユーザー名>` のような PATH で開きます。
ワークスペースを整頓するために、{IC} プロジェクト用に別のフォルダを作成してもよいでしょう。

{IC} プロジェクト用作業フォルダの作成は任意ですが、作成するとプロジェクト間の検索や移動が容易になります。
link:../developers-guide/tutorials-intro{outfilesuffix}[チュートリアル] のうち、link:quickstart-intro{outfilesuffix}[クイックスタート] 以外のものを試す場合に特に便利です。

新しい作業フォルダを作成するには:

. ローカルコンピュータでターミナルを開きます（まだ開いていない場合）。
. 以下のコマンドを実行して、ホームディレクトリに  `+ic-projects+`  という名前の新しいフォルダを作成します。
+
[source,bash]
----
mkdir ic-projects
----
. 以下のコマンドを実行して、新しい作業フォルダに移動します。
+
[source,bash]
----
cd ic-projects
----

[[check-path]]
== PATH 内のディレクトリの表示

環境変数 `+PATH+` は、オペレーティングシステムが、実行可能なプログラムの場所を特定するために使用される重要な設定です。
すべてのオペレーティングシステムはプログラムを探すための独自のディレクトリリストを持っており、 {sdk-short-name} コマンドラインの実行ファイル - `+dfx+` - がリストのいずれかにあることを確認するため、PATH 環境変数の表示および変更の方法を知っておく必要があります。

macOS コンピュータでは、 `+dfx+` 実行ファイルのデフォルトの場所は `+/usr/local/bin+` で、このディレクトリは通常、デフォルトのリストに含まれています。
そのため、macOSを使用しているコンピュータでは、通常、`+PATH+` 変数の更新は必要ありません。
ただし、Linux ディストリビューションを使用している場合は、以下の方法を知っておきましょう。

* `+dfx+` の実行ファイルの場所を確認する。
* 現在の `+PATH+` に含まれるディレクトリのセットを確認する。
* 必要に応じて、環境変数 `+PATH+` を変更する。

ほとんどのオペレーティング・システムでは、以下のようなコマンドを実行して、現在の `+PATH+` に含まれるディレクトリのセットを確認することができます。
....
export $PATH
....

{sdk-short-name} をインストールした後に、 `+dfx+` の実行ファイルの場所を確認するには、以下のコマンドを実行してください。

....
which dfx
....

現在の `+$PATH+` にリストされているディレクトリのいずれにも `+dfx+` の実行ファイルがない場合は、実行ファイルを移動するか、`+PATH+` の設定を変更する必要があります。
`+PATH+` を更新するための具体的な手順はお使いのオペレーティングシステムによって異なりますが、多くの場合、以下のようなコマンドを実行して、 `+~/bin+` などの適切なディレクトリを指定します。

....
export PATH="<dfx コマンドが配置されているディレクトリ>:$PATH"
....

これで、{sdk-short-name} の link:local-quickstart{outfilesuffix}#download-and-install[インストール] とコーディングを始める準備ができました!


////
= Preliminary steps for newcomers
:experimental:
:commandkey: &#8984;

If this is the first time you are installing developer tools on your computer, you might need to take a few extra steps to prepare your environment.

However, there are often multiple ways to perform each of these tasks.
If you need more help than provided here, see the documentation for the operating system you are using.

NOTE: The instructions here assume that you are using a macOS computer.
If you have a Linux development environment, the steps to follow depend on the specific Linux distribution and version you use.

Before you install the {sdk-short-name}, you need to know:

* How to open and run commands in a terminal
* How to check for and install packages and dependencies
* How to create and navigate to new directories
* How to view and update your PATH on the platform you use

The steps in this section describe how to prepare a basic development environment.

[[open-terminal]]
== Open a terminal

You need to know how to open a terminal and navigate to directories to install the {sdk-short-name} and to start and stop the {IC} running locally when trying any of the link:../developers-guide/tutorials-intro{outfilesuffix}[tutorials].

To open the Terminal application on macOS:

. Open the Finder. 
. Click *Applications*, open *Utilities*, then double-click *Terminal*.
+
Alternatively, you can press the kbd:[{commandkey} + spacebar] keyboard keys to open Search, then type `terminal`.
+
The terminal is where you are going to execute command-line instructions. 
To execute a command, you type or copy and paste an instruction, then press kbd:[Return].
. Check your current path by running the print working directory–`pwd`—command, then pressing kbd:[Return].
+
[source,bash]
----
pwd
----
+
This command displays your current directory with a path like `/Users/<your-user-name>`.
+
After you open the Terminal application, you can open new terminal shell at any time by clicking *Shell*, then selecting *New Window* or *New Tab*.
+
By default, a new terminal shell always opens in your home directory with a path like `/Users/<your-user-name>`.

[[check-pkgs]]
== Check for packages

The Homebrew application is a package manager for macOS that makes it easy to install and update packages—that is, external programs—that you need to have available in a local development environment.

The `node.js` package provides a JavaScript runtime environment and modules for front-end user interface development. 
The `node.js` package is not required to build programs, but you'll probably need it if you want to add a graphical user interface to your program.

NOTE: If your development environment is Linux, you can use a package manager of your choice instead of Homebrew to install packages and manage dependencies. 

To check and install packages:

. Check whether you have the Homebrew package manager installed by running the following command:
+
[source,bash]
----
brew --version
----
+
If the command returns version information, continue to the next step.
If Homebrew isn't installed, copy and paste the following command in your terminal:
+
[source,bash]
----
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
----
. Check whether you have the `node.js` package manager installed by running the following command:
+
[source,bash]
----
node --version
----
+
The minumum version of node.js we support is 12. If the command returns version information and your node version is at least 12, continue to <<Create a working folder>>.
If `node.js` isn't installed, or if your installation is out of date, copy and paste the following command in your terminal:
+
[source,bash]
----
brew install node
----

[[working-folder]]
== Create a working folder

By default, a new terminal shell always opens in your home directory with a path like `/Users/<your-user-name>`.
To keep your workspace tidy, you can create a separate folder for your {IC} projects.

Creating a working folder for {IC} projects is optional, but can make it easier to find and navigate between projects.
A separate folder is especially useful if you plan to experiment with any of the link:../developers-guide/tutorials-intro{outfilesuffix}[tutorials] beyond the link:quickstart-intro{outfilesuffix}[Quick start].

To create a new working folder:

. Open a terminal shell on your local computer, if you don’t already have one open.
. Create a new folder called `+ic-projects+` in your home directory by running the following command:
+
[source,bash]
----
mkdir ic-projects
----
. Change to the new working folder by running the following command:
+
[source,bash]
----
cd ic-projects
----

[[check-path]]
== View directories in your PATH

The `+PATH+` environment variable is an important setting that your operating system uses to locate
the set of directories where executable programs are located. 
Because every operating system has its own set of directories where it expects to find programs, you need to know how to view and update the PATH environment variable so that you can verify that the {sdk-short-name} command-line executable—`+dfx+`—is in one of the directories listed.

On macOS computers, the default location for the `+dfx+` executable is `+/usr/local/bin+` and this directory is typically included in the default set of paths. 
Therefore, updating the `+PATH+` variable is usually not necessary for computers running macOS.
If you are using a Linux distribution, however, you should know how to do the following:

* Verify the location of the `+dfx+` executable.
* View the set of directories in your current `+PATH+`.
* Update the `+PATH+` environment variable, if necessary.

On most operating systems, you can run a command similar to the following to view the set of directories in your current `+PATH+`:

....
export $PATH
....

To check the location of the `+dfx+` executable after you install the {sdk-short-name}, you might run a command similar to the following:

....
which dfx
....

If the `+dfx+` executable is not in one of the directories listed in your current `+$PATH+`, you need to move the executable or update the `+PATH+` setting.
The specific steps for updating the `+PATH+` depend on your operating system, but, in many cases, you can run a command similar to the following and specifying the appropriate directory, such as `+~/bin+`:

....
export PATH="<path-to-directory-for-dfx>:$PATH"
....

Now you're ready to link:local-quickstart{outfilesuffix}#download-and-install[install] the {sdk-short-name} and get coding!

////