= Quick start
:description: Download the DFINITY Canister SDK and learn how to deploy your first application.
:keywords: Internet Computer,blockchain,cryptocurrency,ICP tokens,smart contracts,cycles,wallet,software canister,developer onboarding
:proglang: Motoko
:IC: Internet Computer
:company-id: DFINITY
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

[[quick-start-intro]]
This {sdk-long-name} provides tools, sample code, and documentation to help you create programs to run on the {IC}.
The _Quick Start_ tutorial assumes that you are installing the {sdk-short-name} for the first time and illustrates how to create, build, and deploy your first application. 

To keep the instructions simple and focused on the task at hand, the _Quick start_ is split into two scenarios:

* In the link:local-quickstart{outfilesuffix}[Local development] scenario, you create and deploy the sample application with {IC} processes that run _locally to simulate connecting to the network_.

* In the link:network-quickstart{outfilesuffix}[Network deployment] scenario, you create the sample application locally but _connect to the {IC} running remotely_ on computers in an external data center.

If you need some help setting up your development environment—for example, if you aren’t sure how to open a new terminal, install packages, or create folders and navigate between directories—you might want to start with the link:newcomers{outfilesuffix}[Preliminary steps for newcomers].

[[default-app]]
== Default application

Both scenarios build and deploy a simple Hello application that has just one function—called `+greet+`. The `+greet+` function accepts one text argument and returns the result with a greeting similar to **Hello,{nbsp}everyone!** in a terminal if you run the application using the command-line or in an alert pop-up window if you access the application in a browser.

The default application consists of back-end code written in  {proglang}, a programming language specifically designed for interacting with the {IC}, and a simple webpack-based front-end.

== Getting ICP tokens and cycles

As discussed in link:../developers-guide/concepts/tokens-cycles{outfilesuffix}[Tokens and cycles], *cycles* are required to power canister operations for applications running on the {IC}. 
As a developer, you have a few different options for acquiring and managing cycles for your applications:

* Purchase or claim ICP tokens through an exchange that lists ICP tokens available for trade, then convert your tokens to cycles using the link:network-quickstart{outfilesuffix}#convert-tokens[{sdk-short-name} command-line interface] or the link:https://nns.ic0.app/#/auth[Network Nervous System application].
* Register for cycles by signing up for an account or link:../developers-guide/default-wallet{outfilesuffix}#wallet-create-wallets[cycles wallet] through a provider offering those services.
* Coordinate with other developers to link:../developers-guide/default-wallet{outfilesuffix}#wallet-send[send] and link:../developers-guide/default-wallet{outfilesuffix}#wallet-receive[receive] cycles directly to and from canisters through a cycles wallet or another application.

Because only canisters require and consume cycles—to perform operations and to pay for the resources they use—cycles are always transferred between canisters and not to users or developers. You can manage the distribution of cycles, however, through a cycles wallet created for you or using a similar application. 

== Want to learn more?

If you are looking for more information before getting started or want to view a demonstration of how to deploy before you try it for yourself, check out the following related resources:

* link:../developers-guide/concepts/tokens-cycles{outfilesuffix}#using-tokens[How you can use ICP tokens (overview)]
* link:https://www.youtube.com/watch?v=jduSMHxdYD8[Building on the Internet Computer: Fundamentals (video)]
* link:https://www.youtube.com/watch?v=60uHQfoA8Dk[What is the DFINITY Canister SDK (video)]
* link:https://www.youtube.com/watch?v=yqIoiyuGYNA[Deploying your first application (video)]