= Seed round investors token distribution
:experimental:
// Define unicode for Apple Command key.
:commandkey: &#8984;
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

If you participated in the DFINITY Foundation seed round by making a contribution in February 2017, now is the time to prepare for your token distribution.

To receive your tokens, you need to complete the following steps:

* Add an identity for your Ethereum-based address to the {IC}.
* Create the neuron stake for your account.
* Dissolve the neuron stake to view and access ICP tokens.
* Complete the Know Your Customer (KYC) verification process.

== Add an identity for your address to the {IC}

As a participant in the seed round, you received a 12-word mnemonic seed phrase that was created with a DFINITY Chrome extension. 
To receive your tokens, you need to use this 12-word mnemonic seed phrase to generate a public/private key pair for your identity that can be recognized by the {IC}.
The output from your seed phrase is a security certificate in the form of a PEM file. 
You can then import the PEM file using the {sdk-short-name} command-line interface, `dfx` to create an {IC} *principal* for your identity. 
A principal similar to a Bitcoin or Ethereum address and can be used to securely identify your account for making transactions and creating neurons.

=== Access a secure device 

To get start, you should first verify that you have access to a hardware wallet or an air-gapped computer that is secure and not connected to the internet.
Depending on the hardware you have available, you might need to physically remove network cards, disable software, or be prepared to completely wipe the machine before connecting it to the internet again. 
As an example, before entering your seed phrase, you can start a air-gapped computer from a bootable image that provides a minimal operating system, perform the steps to create a public/private key pair for your 12-word mnemonic seed phrase, then remove any artifacts and reboot the computer normally after completing your registration for token distribution. 

NOTE: It is not clear if we will provide access to an image for this purpose. The PoC image has a minimal OS, `keysmith`, and `dfx` for a self-contained solution.

After you start the computer, you can either install the DFINITY Chrome extension or a software program like `keysmith` to convert your 12-word mnemonic seed phrase into a hashed address.

=== Install and use keysmith

If you want to use the `keysmith` program to convert your 12-word mnemonic seed phrase into a hashed address, you can install the `keysmith` program then run `keysmith` commands.

NOTE: The keysmith program is written in the Go programming language. You can download a binary for your operating system from the link:https://golang.org/dl/[Download Go] page if you don't already have Go installed on your air-gapped computer.
Follow the appropriate instructions for your operating environment to download, install, and verify Go is in your PATH. 

To install and use `keysmith`:

. Open a terminal shell on the air-gapped computer.
+
For example, on macOS, open Applications, Utilities, then double-click *Terminal* or press kbd:[{commandkey} + spacebar] to open Search, then type `terminal`.
. Install the `keysmith` program by running the following command:
+
[source,bash]
----
go get github.com/enzoh/keysmith
----
. Change to the directory that contains the keysmith binary by running the following command:
+
[source,bash]
----
cd go/bin
----
. Run an appropriate command—such as an `echo` or `printf` command—to write your 12-word mnemonic seed phrase to a text file. 
+
For example, you might use `echo` followed by your 12-word mnemonic seed phrase and redirect the output to a file named `my-seed-phrase.txt` by running a command similar to the following:
+
[source,bash]
----
 echo 'verb bottom twelve symptom plastic believe beach cargo inherit viable dice loop' > my-seed-phrase.txt
----
. Generate a PEM certificate file from the file containing your 12-word mnemonic seed phrase by running a command similar to the following:
+
[source,bash]
----
./keysmith private-key -f my-seed-phrase.txt -o identity.pem
----
. (Optional) Review the contents of the PEM file you just created to verify they match what you would expect by running the following command:
+
[source,bash]
----
cat identity.pem
----
+
The command should display results similar to the following:
+
....
-----BEGIN EC PARAMETERS-----
BgUrgQQACg==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHQCAQEEIAgy7nZEcVHkQ4Z1Kdqby8SwyAiyKDQmtbEHTIM+WNeBoAcGBSuBBAAK
oUQDQgAEgO87rJ1ozzdMvJyZQ+GABDqUxGLvgnAnTlcInV3NuhuPv4O3VGzMGzeB
N3d26cRxD99TPtm8uo2OuzKhSiq6EQ==
-----END EC PRIVATE KEY-----
....

[[import-pem]]
=== Import your PEM file using DFX

After using your 12-word mnemonic seed phrase to create a PEM file, you can import your certificate to create a secure identity and a hashed identifier called a principal.
A principal identifier is a textual representation of your identity that is similar to an address in Bitcoin or Ethereum. The principal identifier enables the secret key associated with your public key to be used to sign messages and therefore authenticate actions on your behalf. 

If you don't already have the {sdk-short-name} installed, you can download the latest version directly from within a terminal shell on your local computer. For information about downloading and installing the {sdk-short-name}, see link:../download{outfilesuffix}[Download and install].

To create an identity from your PEM file:

. Open a terminal shell on the computer where you have {sdk-short-name} installed.
. Store a name for your {IC} identity in a `NAME` environment variable by running a command similar to the following:
+
....
NAME="Jane Doe"
....
. Create an identity associated with the `NAME` environment variable from your PEM file by running a command similar to the following:
+
....
dfx identity import "$NAME" identity.pem
....
. Store the address associated with your 12-word seed phrase in an `ADDRESS` environment variable by running a command similar to the following:
+
....
ADDRESS="$(./keysmith address -f my-seed-phrase.txt)"
....
. Store the public key associated with your 12-word seed phrase in a `PUBLIC_KEY` environment variable by running a command similar to the following:
+
....
PUBLIC_KEY="$(./keysmith public-key -f my-seed-phrase.txt)"
....
. Use the principal associated with the identity you created from the PEM file by running the following command:
+
[source,bash]
----
dfx --identity="$NAME" canister call <canister-name> <method-name> "(\"$PUBLIC_KEY\")"
----

== Create neurons

. Sign a message using the principal associated with the identity you created from the PEM file by running the following command:
+
[source,bash]
----
dfx --identity="$NAME" canister sign "(\"$PUBLIC_KEY\")" ????
----
. Send the signed message to the genesis token canister (GTC) to create a neuron on your behalf by running the following command:
+
[source,bash]
----
dfx --identity="$NAME" canister send ????
----
. Open a web browser and navigate to the link:xxx[Foundation Registry] website.
. Paste the public key stored in the `PUBLIC_KEY` environment variable in the XX field.
+
If the principal is valid, the Foundation website generates a token-holder identifier (THID) for you to use in the KYC process and you can continue to the next step.
+
If your principal is not validated, submit a link:xx[support request].

== Dissolve neurons

TBD

== Submit documents for the KYC process

TBD

== View funds

TBD

