= Seed Round Token Distribution
:experimental:
// Define unicode for Apple Command key.
:commandkey: &#8984;
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

If you participated in the Seed Round by making a donation in February 2017, then now is the time to prepare for your token distribution.

To receive your tokens, you need to complete the following steps:

* Create an identity.
* Claim your neurons (stake deposits).
* Complete the KYC/AML verification process.
* Dissolve your neurons.
* View your balance of ICP tokens.

== Create an identity

As a Seed Round participant, you wrote down a 12-word mnemonic seed phrase that was generated by the DFINITY Chrome extension. To create an identity, you must derive a private key from your seed phrase and import that private key into the DFINITY Canister SDK. Only then can you claim your neurons.

=== Secure your environment

The safety and security of your private key is your responsibility and there is no substitute for planning ahead, bringing the right equipment, having the right skills, and using good judgment. We strongly recommend you proceed using an air-gapped computer to reduce the risk of having your private key compromised. Depending on the hardware available, you might want to physically remove your network controller, microphone, speakers, and other components, or disable them in your BIOS. Covert channels can be established through a variety of different mediums, including sound, light, radio-frequency, and physical media. Be sure to evaluate the capabilities of your system before settling on a configuration that makes sense for you. If you don't know what you are doing, then consult an expert who you trust. Do not contact the DFINITY Foundation. We cannot help you with this.

=== Install Keysmith

The DFINITY Canister SDK does not yet provide HD wallet capabilities, so you must rely on 3rd-party software to derive your private key. We strongly recommend using link:https://github.com/enzoh/keysmith[Keysmith] for this task. You can install Keysmith by fetching the `v1.0.0` release binary from link:https://github.com/enzoh/keysmith/releases/tag/v1.0.0[GitHub] or by building it from source. Note that Keysmith is written in link:https://golang.org[Go], so if you choose to build it from source, then you must first link:https://golang.org/dl[download] and install Go, verify that `go` is in your `PATH`, and configure your `GOPATH` and `GOBIN` environment variables.

==== Fetch the release binary

Fetch the `v1.0.0` release binary from link:https://github.com/enzoh/keysmith/releases/tag/v1.0.0[GitHub].

Note that this can only be done from a networked computer. How you copy the release binary from your networked computer to your air-gapped computer will depend on your configuration. Below are SHA256 checksums for supported architectures.

....
SHA256(keysmith-darwin-amd64)= b153196c14d847aea5d33c20e3ad48509f48146cbcbf13cbc342689e220f55e8
SHA256(keysmith-linux-amd64)= 54a937fafc55edc745ec02a45fec6c18defcb30126b0a67a758fa5e337fb7279
....

==== Build from source

Run the following command to build Keysmith from source.

[source,bash]
----
go get github.com/enzoh/keysmith
----

Note that this can only be done from a networked computer. How you copy the target binary from your networked computer to your air-gapped computer will depend on your configuration.

=== Install the DFINITY Canister SDK

You can install the DFINITY Canister SDK by fetching the `v0.7.0-beta.0` release binary. It is not yet possible to build DFINITY Canister SDK from source.

Run the following command to install the DFINITY Canister SDK.

[source,bash]
----
DFX_VERSION=v0.7.0-beta.0 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

Note that this can only be done from a networked computer. How you copy the release binary from your networked computer to your air-gapped computer will depend on your configuration. Below are SHA256 checksums for supported architectures.

....
SHA256(dfx-darwin-amd64)= 2f410a34eaf26b276988716fbbe4e15b1c5e89bced2c111b4d28832f9b468fa6
SHA256(dfx-linux-amd64)= ced2f3440cbd5b5795d4270e92d7ba0482cba0ccf2b6629d90306bdabd9aa3a7
....

=== Derive and import your private key

Once you have installed Keysmith and the DFINITY Canister SDK, and you are confident that your environment is secure, then you are ready to derive and import your private key.

Write your seed phrase to a text file.

[source,bash]
----
touch my-seed-phrase.txt
chmod 600 my-seed-phrase.txt
env -i bash -c 'echo "Enter your seed phrase: "; read -s password; echo "$password" > my-seed-phrase.txt'
----

Derive your private key from your seed phrase.

[source,bash]
----
keysmith private-key -f my-seed-phrase.txt -o identity.pem
----

Import your private key into the DFINITY Canister SDK.

[source,bash]
----
dfx identity import <name> identity.pem
----

The command displays output similar to the following:

....
Creating identity: "Jane Doe".
Created identity: "Jane Doe".
....

Make this identity your currently-active identity.

[source,bash]
----
dfx identity use <name>
----

The command displays output similar to the following:

....
Using identity: "Jane Doe".
....

== Claim your neurons

The next step is to sign and send a message to the Genesis Token Canister (GTC) to claim your neurons. You can accomplish this in one step using `dfx canister call`, or, for added security, as two separate steps, `dfx canister sign` and `dfx canister send`, that your complete at different times or using different devices.



For example, you might want to create and sign the message to create neurons on one computer, then copy the message to a different computer or convert the message to a QR code before sending it.

Note the you must have a `dfx.json` file available in the directory from which you are running `dfx` commands that connect to the {IC}. 
You can create an empty `dfx.json` file in your current directory by running the following command:

....
touch dfx.json
....

After creating the `dfx.json` file, you can continue to either the <<Single call>> or <<Separate sign and send steps>> instructions.

=== Single call (not recommended)

To create your neuron stake using a single call:

. Verify that you can access the {IC} by running the following command:
+
....
dfx ping ic
....
. Call the genesis token canister *canister identifier* and the `create_neurons` method by running a command similar to the following:
+
....
PUBLIC_KEY="$(keysmith public-key -f my-seed-phrase.txt)"
dfx canister --network=ic --no-wallet call rno2w-sqaaa-aaaaa-aaacq-cai create_neurons '(\"$PUBLIC_KEY\")'
....

=== Separate sign and send steps

In some cases, however, you might want to separate the request for creating neurons in separate signing and sending tasks.
For example, you might want to sign the request but delay sending it for some period of time.

To create your neuron stake using separate sign and send commands:

. Verify that you can access the {IC} by running the following command:
+
....
dfx ping ic
....
. Create a signed `message.json` file using the principal associated with the identity you created from the PEM file by running a command similar to the following:
+
....
dfx canister --network=ic --no-wallet sign --expire-after=1h rno2w-sqaaa-aaaaa-aaacq-cai create_neurons ‘(“PUBLIC_KEY”)’
....
+
This command illustrates how to creates a `message.json` to create neurons that is signed using your principal identifier as the message sender and with an expiration window that ends in one hour.
+
Note that the time alloted to send a signed message is a fixed *5-minute window*. The `--expire-after` option enables you to specify the point in time when the 5-minute window for sending the signed message should end. For example, if you set the `--expire-after` option to one hour (`1h`), you must wait at least 55 minutes before you send the generated message and the signature for the message is only valid during the 5-minute window ending in the 60th minute.
+
In this example, therefore, you would need to send the message after 55 minutes and before 60 minutes for the message to be recognized as valid.
+
If you don't specify the `--expire-after` option, the default expiration is five minutes.
. Send the signed message to the genesis token canister (GTC) to create a neuron on your behalf by running the following command:
+
....
dfx canister --no-wallet send message.json
....

== Dissolve neurons

TBD

== Submit documents for the KYC process

TBD

== View funds

TBD

