= Seed round investors token distribution
:experimental:
// Define unicode for Apple Command key.
:commandkey: &#8984;
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

If you participated in the DFINITY Foundation seed round by making a contribution in February 2017, now is the time to prepare for your token distribution.

To receive your tokens, you need to complete the following steps:

* Add an identity for your Ethereum-based address to the {IC}.
* Create the neuron stake for your account.
* Dissolve the neuron stake to view and access ICP tokens.
* Complete the Know Your Customer (KYC) verification process.

== Add an identity for your address to the {IC}

As a participant in the seed round, you received a 12-word mnemonic seed phrase that was created with a DFINITY Chrome extension. 
To receive your tokens, you need to use this 12-word mnemonic seed phrase to generate a public/private key pair for your identity that can be recognized by the {IC}.
The output from your seed phrase is a security certificate in the form of a PEM file. 
You can then import the PEM file using the {sdk-short-name} command-line interface, `dfx`, to create an {IC} *principal* for your identity. 
A principal similar to a Bitcoin or Ethereum address and can be used to securely identify your account for making transactions and creating neurons.

=== Access a secure device 

To get start, you should first verify that you have access to an *air-gapped computer* that is secure and not connected to the internet.
Although you can complete the steps for token distribution without using an air-gapped computer, we strongly recommend you use a secure device to safeguard your secret keys and reduce the risk of having your information compromised.

Depending on the hardware you have available, you might need to physically remove network cards, disable software, or be prepared to completely wipe the machine before connecting it to the internet again. 
As an example, before entering your seed phrase, you can start a air-gapped computer from a bootable image that provides a minimal operating system, perform the steps to create a public/private key pair for your 12-word mnemonic seed phrase, then remove any artifacts and reboot the computer normally after completing your registration for token distribution. 

// NOTE: It is not clear if we will provide access to an image for this purpose. The PoC image has a minimal OS, `keysmith`, and `dfx` for a self-contained solution.

After you start the computer, you can either install the DFINITY Chrome extension or a software program like `keysmith` to convert your 12-word mnemonic seed phrase into a hashed address.

=== Install and use keysmith

If you want to use the `keysmith` program to convert your 12-word mnemonic seed phrase into a hashed address, you can install the `keysmith` program then run `keysmith` commands.
Alternatively, you can build the `keysmith` program binary yourself by cloning the link:https://github.com/enzoh/keysmith[keysmith] repository.

NOTE: The keysmith program is written in the Go programming language. You can download a binary for your operating system from the link:https://golang.org/dl/[Download Go] page if you don't already have Go installed on your air-gapped computer.
Follow the appropriate instructions for your operating environment to download, install, and verify Go is in your PATH. 

To install and use `keysmith`:

. Open a terminal shell on the air-gapped computer.
+
For example, on macOS, open Applications, Utilities, then double-click *Terminal* or press kbd:[{commandkey} + spacebar] to open Search, then type `terminal`.
. Install the `keysmith` program by running the following command:
+
[source,bash]
----
go get github.com/enzoh/keysmith
----
. Change to the directory that contains the `keysmith` binary by running the following command:
+
[source,bash]
----
cd go/bin
----
+
Optionally, you might want to copy the `keysmith` binary to another location so that it is available in your PATH and you can perform the remaining steps in a temporary directory. For example, you might want to move the `keysmith` binary to the `/usr/local/bin` directory by running the following command:
+
....
cp keysmith /usr/local/bin/
....
. Run an appropriate command—such as an `echo` or `printf` command—to write your 12-word mnemonic seed phrase to a text file. 
+
For example, you might use `echo` followed by your 12-word mnemonic seed phrase and redirect the output to a file named `my-seed-phrase.txt` by running a command similar to the following:
+
[source,bash]
----
echo 'twelve tide pepper woman sustain please divorce firm order hurry share story' > my-seed-phrase.txt
----
. Generate a PEM certificate file from the file containing your 12-word mnemonic seed phrase by running a command similar to the following:
+
[source,bash]
----
keysmith private-key -f my-seed-phrase.txt -o identity.pem
----
. (Optional) Review the contents of the PEM file you just created to verify they match what you would expect by running the following command:
+
[source,bash]
----
cat identity.pem
----
+
The command should display results similar to the following:
+
....
-----BEGIN EC PARAMETERS-----
BgUrgQQACg==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHQCAQEEIKZ+lAq3M5D5nSx4m1YJSSMm6UI7DbQhK9KqNlxEbVFOoAcGBSuBBAAK
oUQDQgAE2VP17I4jXnMl4pRIjIxAkRDIu7fm4GXUWxZZlj9sRM2FDCSXHH7UjIGj
92+7gBvrL/iiM55hoDTUi7kxuu/GuA==
-----END EC PRIVATE KEY-----
....

[[import-pem]]
=== Import your PEM file using DFX

After using your 12-word mnemonic seed phrase to create a PEM file, you can import your certificate to create a secure identity and a hashed identifier called a principal.
A principal identifier is a textual representation of your identity that is similar to an address in Bitcoin or Ethereum. The principal identifier enables the secret key associated with your public key to be used to sign messages and  authenticate actions on your behalf.

If you don't already have the {sdk-short-name} installed, you can download the latest version directly from within a terminal shell on your local computer. For information about downloading and installing the {sdk-short-name}, see the link:../download{outfilesuffix}[download] instructions.

To create an identity from your PEM file:

. In a terminal shell on your local computer, import your PEM file to create an identity by running a command similar to the following:
+
....
dfx identity import <your-identity-name> identity.pem
....
+
For example, if you wanted to import the PEM file to create an identity named `Jane Doe`, you would run the following command:
+
....
dfx identity import "Jane Doe" identity.pem
....
+
The command displays output similar to the following:
+
....
Creating identity: "Jane Doe".
Created identity: "Jane Doe".
....
. Make the identity created from the imported PEM file your currently-active identity by running a command similar to the following and substituting "Jane Doe" with your identity name:
+
....
dfx identity use "Jane Doe"
....
+
The command displays output similar to the following:
+
....
Using identity: "Jane Doe".
....
+
You can verify the currently-active identity at any point by running the `dfx identity whoami` command.
. Get the principal for you currently-active identity by running the following command:
+
....
dfx identity get-principal
....
+
This command displays the textual representation of your principal as plain text that you can copy and paste. For example:
+
....
g3jww-sbmtm-gxsag-4mecu-72yc4-kef5v-euixq-og2kd-sav2v-p2sb3-pae
....
+
This principal represents the beneficiary for which you will create neurons and is used to call the genesis token canister (GTC) on the {IC}.
. Generate and store the public key for your principal and 12-word seed phrase in a `PUBLIC_KEY` environment variable by running a command similar to the following:
+
....
PUBLIC_KEY="$(keysmith public-key -f my-seed-phrase.txt)"
....

== Create neurons

The next step is to sign and send a message to the genesis token canister (GTC) to create your neuron stake.
You can do this in one step using a single `dfx canister call` command, or, for added security, as two separate steps that your complete at different times or using different devices.
For example, you might want to create and sign the message to create neurons on one computer, then copy the message to a different computer or convert the message to a QR code before sending it.

Note the you must have a `dfx.json` file available in the directory from which you are running `dfx` commands that connect to the {IC}. 
You can create an empty `dfx.json` file in your current directory by running the following command:

....
touch dfx.json
....

After creating the `dfx.json` file, you can continue to either the <<Single call>> or <<Separate sign and send steps>> instructions.

=== Single call

To create your neuron stake using a single call:

. Verify that you can access the {IC} by running the following command:
+
....
dfx ping ic
....
. Call the genesis token canister *canister identifier* and the `create_neurons` method by running a command similar to the following:
+
....
dfx canister --network=ic --no-wallet call rno2w-sqaaa-aaaaa-aaacq-cai create_neurons '(\"$PUBLIC_KEY\")'
....

=== Separate sign and send steps

In some cases, however, you might want to separate the request for creating neurons in separate signing and sending tasks.
For example, you might want to sign the request but delay sending it for some period of time.

To create your neuron stake using separate sign and send commands:

. Verify that you can access the {IC} by running the following command:
+
....
dfx ping ic
....
. Create a signed `message.json` file using the principal associated with the identity you created from the PEM file by running a command similar to the following:
+
....
dfx canister --network=ic --no-wallet sign --expire-after=1h rno2w-sqaaa-aaaaa-aaacq-cai create_neurons ‘(“PUBLIC_KEY”)’
....
+
This command illustrates how to creates a `message.json` to create neurons that is signed using your principal identifier as the message sender and with an expiration window that ends in one hour.
+
Note that the time alloted to send a signed message is a fixed *5-minute window*. The `--expire-after` option enables you to specify the point in time when the 5-minute window for sending the signed message should end. For example, if you set the `--expire-after` option to one hour (`1h`), you must wait at least 55 minutes before you send the generated message and the signature for the message is only valid during the 5-minute window ending in the 60th minute.
+
In this example, therefore, you would need to send the message after 55 minutes and before 60 minutes for the message to be recognized as valid.
+
If you don't specify the `--expire-after` option, the default expiration is five minutes.
. Send the signed message to the genesis token canister (GTC) to create a neuron on your behalf by running the following command:
+
....
dfx canister --no-wallet send message.json
....

== Dissolve neurons

TBD

== Submit documents for the KYC process

TBD

== View funds

TBD

