= Self-custody quick start
:description: How you can use your ICP tokens.
:keywords: Internet Computer,blockchain,cryptocurrency,ICP tokens,smart contracts,cycles,wallet,software canister,developer onboarding
:experimental:
// Define unicode for Apple Command key.
:commandkey: &#8984;
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

Within the Internet Computer ecosystem, Internet Computer Protocol tokens (ICP tokens) are a native utility token.
ICP tokens play a key role in both the governance and economics of the {IC}. 

This _Self-Custody Quick Start_ scenario assumes:

* You are a new ICP token holder.
* You want to understand what you can do with your ICP tokens.
* You want to know how to convert, transfer, or lock your ICP tokens using the {sdk-short-name} command-line interface DFX.

If you are using another application—such as the Network Nervous System (NNS) or the user interface provided by a hardware wallet—to interact with your ICP tokens, you should refer to the documentation for that application.

This _Self-Custody Quick Start_ focuses solely on interacting with ICP tokens using the {sdk-short-name} command-line interface DFX.

== How you can use ICP tokens

The following diagram provides a simplified overview the three most common ways you can use tokens.

image:developers-guide:icp-tokens-how-to-use.svg[]

As this diagram suggests, how you use ICP tokens depends primarily on your goals in acquiring them.

If you are a **developer** or **entrepreneur**, ICP tokens can be converted to **cycles**. Cycles can then be used to build and deploy applications to deliver products and services to the market.

If you are a member of the community interested in **participating in governance** and influencing the direction of the {IC}, you can lock up ICP tokens in a stake—called a neuron—so that you can submit and vote on proposals.

[[self-before]]
== Before you begin

To get started, verify the following:

* You have an internet connection and access to a shell terminal on your local **Intel-based macOS** or **Linux** computer.

* You know how to open a new terminal shell on your local computer and how to run basic command-line programs in the terminal.

* You hold ICP tokens in a self-custody wallet.

* You have downloaded and installed the {sdk-long-name} by running the following command in a terminal on your local computer:
+
[source,bash]
----
DFX_VERSION=0.7.0-beta.7 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
----

== Connect to the ledger and get your account identifier

All ICP token transactions are recorded in a ledger canister running on the Internet Computer.
These instructions assume that you are using the `+default+` developer identity that `+dfx+` has created for you.

This identity is represented by a *principal* data type and a textual representation of the principal often referred to as your *principal identifier*.
This representation of your identity is similar to a Bitcoin or Ethereum address.

However, the principal associated with your developer identity is typically not the same as your *account identifier* in the ledger. The principal identifier and the account identifier are related—both provide a textual representation of your identity—but they use different formats.

To connect to the ledger and get account information:

. Create an empty `+dfx.json+` file in your current directory by running the following command:
+
[source,bash]
----
echo '{}' > dfx.json
----
. Check the current status of the {IC} network and your ability to connect to it by running the following command
+
[source,bash]
----
dfx ping https://ic0.app
----
+
You should see output similar to the following:
+
....
{
  "ic_api_version": "0.17.0"  "impl_hash": "029b46fa3385c17f9a33f1616156f5be956701ea7109fe94d22b6ff828514461"  "impl_version": "8a560f9510b0df9e747ffaede3b731f2ade9c0b7"  "root_key": [48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 129, 76, 14, 110, 199, 31, 171, 88, 59, 8, 189, 129, 55, 60, 37, 92, 60, 55, 27, 46, 132, 134, 60, 152, 164, 241, 224, 139, 116, 35, 93, 20, 251, 93, 156, 12, 213, 70, 217, 104, 95, 145, 58, 12, 11, 44, 197, 52, 21, 131, 191, 75, 67, 146, 228, 103, 219, 150, 214, 91, 155, 180, 203, 113, 113, 18, 248, 71, 46, 13, 90, 77, 20, 80, 95, 253, 116, 132, 176, 18, 145, 9, 28, 95, 135, 185, 136, 131, 70, 63, 152, 9, 26, 11, 170, 174]
}
....
. (Optional) Confirm the developer identity you are currently using by running the following command:
+
[source,bash]
----
dfx identity whoami
----
+
In most cases, you should see that you are currently using +default+` developer identity.
For example:
+
....
default
....
. (Optional) View the textual representation of the principal for your current identity by running the following command:
+
[source,bash]
----
dfx identity get-principal
----
+
This command displays output similar to the following:
+
....
tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe
....
. Get the account identifier for your developer identity by running the following command:
+
[source,bash]
----
dfx ledger account-id
----
+
This command displays the ledger account identifier associated with your developer identity.
For example, you should see output similar to the following:
+
....
03e3d86f29a069c6f2c5c48e01bc084e4ea18ad02b0eec8fccadf4487183c223
....
. Check your account balance by running the following command:
+
[source,bash]
----
dfx ledger --network https://ic0.app balance
----
This command displays the ICP token balance from the ledger account.
For example, you should see output similar to the following:
+
....
100.00000000 ICP
....

[[convert-icp]]
== Convert ICP tokens to cycles

If you want to use your ICP tokens in your ledger account to power application development, you first must convert them to cycles and transfer the cycles to a canister that will be your cycles wallet.

To convert ICP tokens to cycles:

. Create a new canister with cycles by transferring ICP tokens from your ledger account by running a command similar to the following:
+
[source,bash]
----
dfx ledger --network https://ic0.app create-canister --amount <icp-tokens> --controller <principal-identifier>
----
+
This command converts the number of ICP tokens you specify for the `+--amount+` argument into cycles, and associates the cycles with a new canister identifier controlled by the principal you specify using the `+--controller+` argument.
+
For example, the following command converts 1.25 ICP tokens into cycles and specifies the principal identifier for the default identity as the controller of the new canister:
+
....
dfx ledger --network https://ic0.app create-canister --amount 1.25 --controller tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe
....
+
If the transaction is successful, the ledger records the event and you should see output similar to the following:
+
....
Transfer sent at BlockHeight: 20
Canister created with id: "53zcu-tiaaa-aaaaa-qaaba-cai"
....
. Install the cycles wallet code in the newly-created canister placeholder by running a command similar to the following:
+
[source,bash]
----
dfx identity --network https://ic0.app deploy-wallet <canister-identifer>
----
+
For example:
+
....
dfx identity --network https://ic0.app deploy-wallet 53zcu-tiaaa-aaaaa-qaaba-cai
....
+
This command displays output similar to the following:
+
....
Creating a wallet canister on the https://ic0.app network.
The wallet canister on the "https://ic0.app" network for user "default" is "53zcu-tiaaa-aaaaa-qaaba-cai"
....

== Transfer ICP tokens to another account

If you want to transfer ICP tokens to another account in the ledger, you need to know the account identifier for the destination account.

To transfer ICP tokens to another account:

. Transfer ICP tokens to another account by running a command similar to the following:
+
[source,bash]
----
dfx ledger --network https://ic0.app transfer --amount <ICP amount> --to <destination ledger account-id> --memo <numeric memo>
----
+
For example: 
....
dfx ledger --network https://ic0.app transfer --amount 20 --to ae6e1a76da5725bbbf0c5c035aaf0525b791e0f0f7cce27d8e27826389871406 --memo 12345
....

== Lock ICP tokens by staking them in a neuron

If you want to lock up ICP tokens to participate in governance and earn rewards, you must use the Network Nervous System (NNS) application or `+dfx canister call+` commands.

Because locking up ICP tokens to create staked neurons is a slightly more complex process when using the {sdk-short-name} command-line interface, the steps aren't included in this guide.

//// Uncomment the DRAFT section temporarily ////

To create a neuron from ICP tokens:

. Determine the target account by running a command similar to the following:
+
[source,bash]
----
dfx canister --network https://ic0.app call governance build_stake_transfer_targets "(<unique_memo> : Nat64)"
----
+
For example:
+
....
dfx canister --network https://ic0.app call governance build_stake_transfer_targets "(0001 : Nat64)"
....
+
This command uses the principal associated with your current identity and the value you specify for the _<unique_memo>_ field to return an account identifier and a sub-account for the transfer.
+
In the command output, you should see an account identifier that looks similar to the following:
+
....
ae6e1a76da5725bbbf0c5c035aaf0525b791e0f0f7cce27d8e27826389871406
....
You should also see a sub-account similar to the following:
+
....

....
. Transfer ICP tokens from the ledger account to the target account identifier returned in the previous step by running a command similar to the following:
+
[source,bash]
----
dfx ledger --network https://ic0.app transfer --amount <ICP amount> --to <destination-account-id> --memo <unique_memo>
----
+
For example:
+
....
dfx ledger --network https://ic0.app transfer --amount 20 --to  --memo 0001
....
+
If the transfer is successful, the command returns the block height for the transaction.
For example:
+
....
Transfer sent at BlockHeight: 20
....

=== Configuring neuron properties

After the neuron is created, there are several properties that need to be configured to lock the stake, set the dissolve delay, and begin submitting proposals and earning rewards.
You can set these properties for a neuron from the command line by calling the `+governance+` canister and the `+manage_neuron+` method or by using the Network Nervous System application (nns-ui.ic0.app).

For example, if you continue using the `+dfx+` command-line interface, you might configure a neuron to have a hot key by running a command similar to the following:

....
dfx canister --network https://ic0.app governance manage_neuron \
"( record {id = opt record { id = <neuron_id>; \
command = opt variant { Configure = record { operation \
= opt variant {AddHotKey = record { new_hot_key = \
principal <new_hot_key_principal_id> }}}}}}"
....

=== Learning more about the Network Nervous System

For additional details about the Network Nervous System, see link:https://medium.com/dfinity/understanding-the-internet-computers-network-nervous-system-neurons-and-icp-utility-tokens-730dab65cae8[Understanding the {IC}'s Network Nervous System, Neurons, and ICP Utility Tokens].

For additional details about setting the locked period and dissolve delay for a neuron, see link:xxx[Getting Started | The {IC} Network Nervous System Application & Wallet]

