= dfx wallet
:sdk-short-name: DFINITY Canister SDK

Use the `+dfx wallet+` command with subcommands and flags to manage the wallets of your identities and to send cycles to the wallets of other account wallet canisters.

The basic syntax for running the `+dfx wallet+` commands is:

[source,bash]
----
dfx wallet [option] <subcommand> [flag]
----

Depending on the `+dfx wallet+` subcommand you specify, additional arguments, options, and flags might apply or be required.
To view usage information for a specific `+dfx wallet+` subcommand, specify the subcommand and the `+--help+` flag.
For example, to see usage information for `+dfx wallet send+`, you can run the following command:

[source,bash]
----
dfx wallet send --help
----

For reference information and examples that illustrate using `+dfx wallet+` commands, select an appropriate command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description

|<<dfx wallet add-controller,`+add-controller+`>> | Add a controller using the selected identity's principal. 

|<<dfx wallet addresses,`+addresses+`>> |Displays the address book of the wallet.

|<<dfx wallet authorize,`+authorize+`>> |Authorize a custodian by principal for the selected identity's wallet

|<<dfx wallet balance,`+balance+`>> |Displays the cycles balance of the selected identity.

|<<dfx wallet controllers,`+controllers+`>> |Displays a list of the selected identity's wallet controllers. 

|<<dfx wallet custodians,`+custodians+`>> |Displays a list of the selected identity's wallet custodians.

|<<dfx wallet deauthorize,`+deauthorize+`>> | Deauthorize a wallet custodian using the custodian's principal.

|`+help+` |Displays a usage message and the help of the given subcommand(s).

|<<dfx wallet name,`+name+`>> |Returns the name of the wallet if you've used the `+dfx wallet set-name+` command.

|<<dfx wallet remove-controller,`+remove-controller+`>> |Removes a specified controller from the selected identity's wallet. 

|<<dfx wallet send,`+send+`>> |Sends a specified amount of cyles from the selected identity's wallet to another cycles wallet using the destination wallet canister ID. 

|<<dfx wallet set-name,`+set-name+`>> |Specify a name for your wallet. 

|<<dfx wallet upgrade,`+upgrade+`>> |Upgrade the wallet's Wasm module to the current Wasm bundled with DFX.
|===

== Using your wallet

After you have used the `+dfx identity deploy-wallet+` command to create a wallet canister tied to an identity, you can use `+dfx wallet+` commands to modify your wallet settings, send cycles to other wallets, and add or remove controllers and custodians. 

== dfx wallet add-controller

Use the `+dfx wallet add-controller+` command to add controllers using their principals. 

=== Basic usage

[source,bash]
----
dfx wallet add-controller [flag]
----

=== Flags

You can use the following optional flags with the `+dfx wallet add-controller+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

Use the following necessary argument with the `+dfx wallet add-controller+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description
|`+<controller>+` | Specify the principal of the identity you would like to add as a controller.
|===

=== Example

For example, to add alice_auth as a controller, specify her principal in the following command

[source,bash]
----
dfx wallet add-controller dheus-mqf6t-xafkj-d3tuo-gh4ng-7t2kn-7ikxy-vvwad-dfpgu-em25m-2ae
----

== dfx wallet addresses

This command returns the information of identities that are associated with the selected identity's wallet. When you use the command, the information returned is the following:

* An identity's principal (`+Id+`).
* `+Kind+` which can be one of `+User+`,`+Canister+`, or `+Unknown+`. 
* `+Role+` which can be one of `+Contact+`,`+Controller+`, or `+Custodian+`. 
* `+Name+` if the wallet's name is set. 

=== Basic usage

[source,bash]
----
dfx wallet addresses [flag]
----

=== Flags

You can use the following optional flags with the `+dfx wallet get-wallet+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Example

Running the following command:

[source,bash]
----
dfx wallet addresses
----

Will return information similar to the following:

....
Id: dheus-mqf6t-xafkj-d3tuo-gh4ng-7t2kn-7ikxy-vvwad-dfpgu-em25m-2ae, Kind: Unknown, Role: Controller, Name: No name set.
Id: hpnmi-qgxsv-tgecj-hmjyn-gmfft-vbego-lpcax-ou4ld-oh7kr-l3nu2-yae, Kind: Unknown, Role: Controller, Name: No name set.
....

== dfx wallet authorize 

Use the `+dfx wallet authorize+` command to authorize a wallet custodian.

=== Basic usage

[source,bash]
----
dfx wallet authorize <custodian> [flag]
----

=== Flags

You can use the following optional flags with the `+dfx wallet authorize+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

Use the following necessary argument with the `+dfx wallet authorize+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description
|`+<custodian>+` | Specify the principal of the identity you would like to add as a custodian.
|===

=== Example

For example, to add alice_auth as a custodian, specify her principal in the following command:

[source,bash]
----
dfx wallet authorize dheus-mqf6t-xafkj-d3tuo-gh4ng-7t2kn-7ikxy-vvwad-dfpgu-em25m-2ae
----

== dfx wallet balance

Use the `+dfx wallet balance+` command to display the balance of the cycles wallet of the selected identity. 

=== Basic usage

[source,bash]
----
dfx wallet balance
----

=== Flags

You can use the following optional flags with the `+dfx wallet balance+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Examples

Check your wallet balance

[source,bash]
----
dfx wallet balance
----

This command displays the number of cycles in your cycles wallet. For example: 

....
89000000000000 cycles.
....

== dfx wallet controllers

Use the `+dfx wallet controllers+` command to list the principals of the identities that are controllers of the selected identity's wallet. 

=== Basic usage

[source,bash]
----
dfx wallet controllers
----

=== Flags

You can use the following optional flags with the `+dfx wallet controllers+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Examples

List the controllers of your identity's wallet. 

[source,bash]
----
dfx wallet controllers
----

The information returned should look similar to the following if there are two controllers:

....
dheus-mqf6t-xafkj-d3tuo-gh4ng-7t2kn-7ikxy-vvwad-dfpgu-em25m-2ae
hpnmi-qgxsv-tgecj-hmjyn-gmfft-vbego-lpcax-ou4ld-oh7kr-l3nu2-yae
....

== dfx wallet custodians

Use the `+dfx wallet custodians+` command to list the principals of the identities that are custodians of the selected identity's wallet. Identities that are added as controllers are also listed as custodians

=== Basic usage

[source,bash]
----
dfx wallet custodians
----

=== Flags

You can use the following optional flags with the `+dfx wallet custodians+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Examples

List the custodians of your identity's wallet. 

[source,bash]
----
dfx wallet custodians
----

The information returned should look similar to the following if there are two custodians:

....
dheus-mqf6t-xafkj-d3tuo-gh4ng-7t2kn-7ikxy-vvwad-dfpgu-em25m-2ae
hpnmi-qgxsv-tgecj-hmjyn-gmfft-vbego-lpcax-ou4ld-oh7kr-l3nu2-yae
....


== dfx wallet deauthorize

Use the `+dfx wallet deauthorize+` command to remove a wallet custodian.

=== Basic usage

[source,bash]
----
dfx wallet deauthorize <custodian> [flag]
----

=== Flags

You can use the following optional flags with the `+dfx wallet deauthorize+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

Use the following necessary argument with the `+dfx wallet deauthorize+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description
|`+<custodian>+` | Specify the principal of the custodian you want to remove.
|===

=== Example

For example, to remove "alice_auth" as a custodian, specify her principal in the following command:

[source,bash]
----
dfx wallet deauthorize dheus-mqf6t-xafkj-d3tuo-gh4ng-7t2kn-7ikxy-vvwad-dfpgu-em25m-2ae
----

== dfx wallet name

Use the `+dfx wallet name+` command to display the name of the selected identity's wallet if it has ben set using the `+dfx wallet set-name+` command. 

=== Basic usage

[source,bash]
----
dfx wallet name [flag] 
----

=== Flags

You can use the following optional flags with the `+dfx wallet name+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Example

If the name of your wallet is "Terrances_wallet", then the command would return the following:

....
Terrances_wallet
....

== dfx wallet remove-controller

Use the `+dfx wallet remove-controller+` command to remove a wallet controller.

=== Basic usage

[source,bash]
----
dfx wallet remove-controller <controller> [flag]
----

=== Flags

You can use the following optional flags with the `+dfx wallet remove-controller+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

Use the following necessary argument with the `+dfx wallet remove-controller+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description
|`+<controller>+` | Specify the principal of the controller you want to remove.
|===

=== Example

For example, to remove alice_auth as a controller, specify her principal in the following command:

[source,bash]
----
dfx wallet remove-controller dheus-mqf6t-xafkj-d3tuo-gh4ng-7t2kn-7ikxy-vvwad-dfpgu-em25m-2ae
----

== dfx wallet send

Use the `+dfx wallet send+` command to send cycles from the selected identity's wallet to another cycles wallet using the destination wallet's Canister ID. 

=== Basic usage

[source,bash]
----
dfx wallet [network] send [flag] <destination> <amount> 
----

=== Flags

You can use the following optional flags with the `+dfx wallet send+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Options

You can use the following option with the `+dfx wallet send+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Option |Description
|`+--network+` |Override the compute network to connect to. By default, the local network is used. A valid URL (starting with `http:` or `https:`) can be specified here, and a special ephemeral network will be created specifically for this request. E.g. "http://localhost:12345/" is a valid network name.
|===

=== Arguments

You must specify the following arguments for the `+dfx wallet send+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description

|`+<destination>+` |Specify the destination wallet's Canister ID.
|`+<amount>+` |Specify the number of cycles to send.
|===

=== Examples

Send cycles from the selected identity's wallet to another cycles wallet.
For example, to send 2,000,000,000 cycles from the wallet of the selected identity, `+<ic_admin>+`, to the wallet of the destination identity, `+<buffy_standard>+` with a wallet address `+r7inp-6aaaa-aaaaa-aaabq-cai+`, run the following command:

[source,bash]
----
dfx wallet send r7inp-6aaaa-aaaaa-aaabq-cai 2000000000
----

== dfx wallet set-name

Use the `+dfx wallet set-name+` command to assign a name to the selected identity's wallet.

=== Basic usage

[source,bash]
----
    dfx wallet set-name [flag] <name> 
----

=== Arguments

You must specify the following arguments for the `+dfx wallet set-name+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Argument |Description
|`+<name>+` |Specify a name for the wallet.
|===

=== Flags

You can use the following optional flags with the `+dfx wallet set-name+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Example

If you want to set the name of the current wallet to "Terrances_wallet" you can run the following command:

[source,bash]
----
dfx wallet set-name Terrances_wallet
----

== dfx wallet upgrade

Use the `+dfx wallet upgrade+` command to upgrade the wallet's Wasm module to the current Wasm bundled with DFX.

=== Basic usage

[source,bash]
----
    dfx wallet upgrade [flag] 
----

=== Flags

You can use the following optional flags with the `+dfx wallet upgrade+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Example
To upgrade the Wasm module to the latest version, run the following command:

[source,bash]
----
dfx wallet upgrade
----