= dfx replica

Use the `+dfx replica+` command to start a {IC} replica process (without a web server) locally.
This command enables you to deploy canisters locally to simulate network deployment and to test your programs during development.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

== Basic usage

[source,bash]
----
dfx replica [option] [flag]
----

== Flags

You can use the following optional flags with the `+dfx replica+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

== Options

You can use the following option with the `+dfx replica+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Option |Description
|`+--port port+` |Specifies the port the local replica should listen to.
|===

////
|`+--message-gas-limit maximum-gas-limit+` |Specifies the maximum resources that a single message can consume. Computational resources such as CPU, memory, and storage are measured in tokens that are converted in "gas" available to be consumed by applications.
|`+--round-gas-limit round-gas-limit+` |Specifies the maximum resources that a single round of messages can consume in the "gas" available to be consumed by applications.
////

== Examples

You can start the {IC} replica by running the following command:

[source,bash]
----
dfx replica
----
////
If you want to set an upper limit on the resources a single message can consume, you might run a command similar to the following:

[source,bash]
----
dfx replica --maximum-gas-limit 1000
----
////
