= dfx stop

Use the `+dfx stop+` command to stop the {IC} processes that you currently have running on your local computer.
In most cases, you run the {IC} locally so that you can deploy canisters and test your programs during development.
To simulate an external {IC} connection, these processes run continuously either in a terminal shell where you started them or the in the background until you stop or kill them.

Note that you can only run this command from within the project directory structure.
For example, if your project name is `+hello_world+`, your current working directory must be the `+hello_world+` top-level project directory or one of its subdirectories.

== Basic usage

[source,bash]
----
dfx stop [flag]
----

== Flags

You can use the following optional flags with the `+dfx stop+` command.

[width="100%",cols="<32%,<68%",options="header",]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.

|`+-V+`, `+--version+` |Displays version information.
|===

== Examples

You can stop the {IC} network processes that are running in the background by changing to a project directory then running the following command:

[source,bash]
----
dfx stop
----

If the local {IC} network is running in a current shell rather than in the background, open a new terminal shell, change to a project directory, then run the `+dfx stop+` command.

The current process identifier (`+pid+`) for the {IC} process started by `+dfx+` is recorded in the `+.dfx/pid+` file.
You can view the process identifier before running the `+dfx stop+` command by running the following command:

[source,bash]
----
more .dfx/pid
----

This command displays a process identifier similar to the following:

[source,bash]
----
1896
----
