= dfx ledger
:sdk-short-name: DFINITY Canister SDK

Use the `+dfx ledger+` command to interact with the ledger canister.

This command can be used to make ICP utlity token transactions from one AccountIdentifier to another, or top up canisters with cycles from ICP.

The basic syntax for running `+dfx ledger+` commands is:

[source,bash]
----
dfx ledger [options] [subcommand]
----

Depending on the `+dfx ledger+` subcommand you specify, additional arguments, options, and flags might apply. For reference information and examples that illustrate using `+dfx ledger+` commands, select an appropriate command.

== Commands

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description
|`+account-id+` |Prints the selected identity's Account Identifier.
|<<dfx ledger balance,`+balance+`>> |Prints the account balance of the user.
|<<dfx ledger create-canister,`+create-canister+`>> |Creates a canister from ICP.
|`+help+` |Displays usage information message for a specified subcommand.
|<<dfx ledger notify,`+notify+`>> |Notifies the ledger when there is a send transaction to the cycles minting canister.
|<<dfx ledger top-up,`+top-up+`>> |Tops up a canister with cycles minted from ICP.
|<<dfx ledger transfer,`+transfer+`>> |Transfers ICP from the user to the destination Account Identifier.

To view usage information for a specific subcommand, specify the subcommand and the `+--help+` flag.
For example, to see usage information for `+dfx ledger transfer+`, you can run the following command:


`+dfx ledger transfer --help+`

|===

[[balance]]
== dfx ledger balance

Use the `+dfx ledger balance+` command to print your account balance or that of another user.

=== Basic usage

[source,bash]
----
dfx ledger --network ic balance [of] [flag]
----

=== Flags

You can use the following optional flags with the `+dfx ledger balance+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx ledger balance+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description
|`+of+` |Specifies an AccountIdentifier to get the balance of.
|===

=== Examples

You can use the `+dfx ledger balance+` command to check the balance of another user.
For example, you can run the following command to see the ICP utlity tokens associated with a known AccountIdentifier:

[source,bash]
----
dfx ledger --network ic balance 03e3d86f29a069c6f2c5c48e01bc084e4ea18ad02b0eec8fccadf4487183c223
----
This command displays an ICP amount similar to the following:

[source,bash]
----
2.49798000 ICP
----

[[create-canister]]
== dfx ledger create-canister

Use the `+dfx ledger create-canister+` command to create a canister from ICP utility tokens.

=== Basic usage

[source,bash]
----
dfx ledger create-canister --network ic [options] <controller> [flag]
----

=== Flags

You can use the following optional flags with the `+dfx ledger balance+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx ledger balance+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description
|`+controller+` |Specifies the controller of the new canister as a principal identifier.
|===

=== Options

You can specify the following argument for the `+dfx ledger balance+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description
|`+--amount <amount>+` |ICP to mint into cycles and deposit into destination canister.
Can be specified as a Decimal with the fractional portion up to 8 decimal places.
|`+--e8s <e8s>+` |Specify e8s as a whole number, helpful for use in conjunction with `+--icp+`.
|`+--fee <fee>+` |Transaction fee, default is 10000 e8s.
|`+--icp <icp>+` |Specify ICP as a whole number, helpful for use in conjunction with `+--e8s+`.
|`+--max-fee <max-fee>+` |Maximum transaction fee, default is 10000 e8s.
|===

=== Examples

Create a new canister with cycles by transferring ICP tokens from your ledger account by running a command similar to the following:

[source,bash]
----
dfx ledger --network ic create-canister <controller-principal-identifier> --amount <icp-tokens>
----

This command converts the number of ICP tokens you specify for the --amount argument into cycles, and associates the cycles with a new canister identifier controlled by the principal you specify.

For example, the following command converts 1.25 ICP tokens into cycles and specifies the principal identifier for the default identity as the controller of the new canister:

[source,bash]
----
dfx ledger --network ic create-canister tsqwz-udeik-5migd-ehrev-pvoqv-szx2g-akh5s-fkyqc-zy6q7-snav6-uqe --amount 1.25
----

If the transaction is successful, the ledger records the event and you should see output similar to the following:

[source,bash]
----
Transfer sent at BlockHeight: 20
Canister created with id: "53zcu-tiaaa-aaaaa-qaaba-cai"
----

[[notify]]
== dfx ledger notify

Use the `+dfx ledger notify+` command to notify the ledger about a send transaction to the cycles minting canister.
This command should only be used if `+dfx ledger create-canister+` or `+dfx ledger top-up+` successfully sent a message to the ledger, and a transaction was recorded at some block height, but for some reason the subsequent notify failed.

=== Basic usage

[source,bash]
----
dfx ledger notify [options] <block-height> <destination-principal>
----

=== Flags

You can use the following optional flags with the `+dfx ledger notify+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx ledger balance+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description
|`+<block-height+` |BlockHeight at which the send transation was recorded.
|`+<destination-principal+` |Specify the principal of the destination, either a canister id or a user principal.
If the send transaction was for `+create-canister+`, specify the `+controller+` here.
If the send transacction was for `+top-up+`, specify the `+canister ID+` here.
|===

=== Examples

[[top-up]]
== dfx ledger top-up

Use the `+dfx ledger top-up+` command to top up a canister with cycles minted from ICP.

=== Basic usage

[source,bash]
----
dfx ledger --network ic top-up [options] <canister> [flag]
----

=== Flags

You can use the following optional flags with the `+dfx ledger balance+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx ledger balance+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description
|`+canister+` |Specifies the canister identifier that you would like to top up.
|===

=== Options

You can specify the following argument for the `+dfx ledger top-up+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description
|`+--amount <amount>+` |ICP to mint into cycles and deposit into destination canister.
Can be specified as a Decimal with the fractional portion up to 8 decimal places.
|`+--e8s <e8s>+` |Specify e8s as a whole number, helpful for use in conjunction with `+--icp+`.
|`+--fee <fee>+` |Transaction fee, default is 10000 e8s.
|`+--icp <icp>+` |Specify ICP as a whole number, helpful for use in conjunction with `+--e8s+`.
|`+--max-fee <max-fee>+` |Maximum transaction fee, default is 10000 e8s.
|===

=== Examples

You can use the `+dfx ledger top-up+` command to top up the cycles of a specific canister from ICP.
The canister ID must be associated with a cycles wallet canister that is able to receive cycles. Alternatively, a non-cycles wallet canister may implement a method to receive cycles using system APIs from the Internet Computer Interface Specification.

For example, you can run the following command to top-up a cycles wallet canister deployed on the Internet Computer with 1 ICP worth of cycles:

[source,bash]
----
dfx ledger --network ic top-up --icp 1 5a46r-jqaaa-aaaaa-qaadq-cai
----
This command displays an output similar to the following:

[source,bash]
----
Transfer sent at BlockHeight: 59482
Canister was topped up!
----

[[transfer]]
== dfx ledger transfer

Use the `+dfx ledger transfer+` command to transfer ICP from your AccountIdentifier on the ledger canister to a destination AccountIdentifier.

=== Basic usage

[source,bash]
----
dfx ledger transfer [options] <to> --memo <memo>
----

=== Flags

You can use the following optional flags with the `+dfx ledger notify+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Flag |Description
|`+-h+`, `+--help+` |Displays usage information.
|`+-V+`, `+--version+` |Displays version information.
|===

=== Arguments

You can specify the following argument for the `+dfx ledger balance+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description
|`+<to>+` |AccountIdentifier of transfer destination.
|===

=== Options

You can specify the following argument for the `+dfx ledger top-up+` command.

[width="100%",cols="<32%,<68%",options="header"]
|===
|Command |Description
|`+--amount <amount>+` |ICP to mint into cycles and deposit into destination canister.
Can be specified as a Decimal with the fractional portion up to 8 decimal places.
|`+--e8s <e8s>+` |Specify e8s as a whole number, helpful for use in conjunction with `+--icp+`.
|`+--fee <fee>+` |Transaction fee, default is 10000 e8s.
|`+--icp <icp>+` |Specify ICP as a whole number, helpful for use in conjunction with `+--e8s+`.
|`+--memo <memo>+` |Specify a numeric memo for this transaction.

=== Examples

You can use the `+dfx ledger transfer+` command to send ICP from one AccountIdentifier to another.

For example, you can run the following command to check the AccountIdentifier associated with the principal you are currently using:

[source,bash]
----
dfx ledger account-id
----
This command displays an output similar to the following:

[source,bash]
----
30e596fd6c5ff5ad7b7d70bbbda1187c833e646c6251464da7f82bc217bba397
----

You can check the balance of this account by running the following command:

[source,bash]
----
dfx ledger --network ic balance
----

This command displays an output similar to the following:

[source,bash]
----
64.89580000 ICP
----

Use the `+dfx ledger balance`+ command to send some of your ICP balance to another known AccountIdentifier using the following command:

[source,bash]
----
dfx ledger --network ic transfer 03e3d86f29a069c6f2c5c48e01bc084e4ea18ad02b0eec8fccadf4487183c223 --memo 12345 --icp 1
----
This command displays an output similar to the following:

[source,bash]
----
Transfer sent at BlockHeight: 59513
----

You can check your balance again to ensure the transaction went through using `+dfx ledger --network ic balance+`.

